module.exports = {
  hostid: "285", // GN Config
  channelid: "696089404",
  mediawireslot: "13",
  wapsitename: "Samayam Tamil",
  wapsiteregionalname: "சமயம் தமிழ்",
  siteName: "tamil.samayam.com",
  staticSiteName: "static.tml.indiatimes.com",
  fbIAcontentId: "1026676867365335",
  languagemeta: "ta",
  language: "Tamil",
  channelCode: "tml",
  wapCode: "tamil",
  gdprID: "TAMIL",
  languagefullName: "Samayam Tamil",
  iospackageid: "1426269205",
  androidpackage: "com.til.tamilsamayam",
  deeplinkappid: "tamilsamayamactivities",
  deeplinkpubid: "pub=8:Samayam Tamil",
  iosapp_name: "Samayam Tamil App",
  weburl: "https://tamil.samayam.com",
  mweburl: "https://tamil.samayam.com",
  ccaudId: "13539:214",
  ccaudAmp: "13539",
  ccaudIdAmp: "13539:1217",
  indexExchangeUrl: "//js-sec.indexww.com/ht/p/191952-52237125690122.js",
  pwtUrl: "//ads.pubmatic.com/AdServer/js/pwt/23105/2923",
  footerDesktopLink: "https://tamil.samayam.com?mobile=no",
  langnetstorageBasePath: "https://langnetstorage.indiatimes.com/langappfeeds",
  cookieLessDomain: "https://static.tml.indiatimes.com",
  video: {
    rootId: "47344128",
    newsId: "97579824",
  },
  fbLive: "92082182",
  videoiconurl: "/news-video/videolist/47344128.cms",
  editTrendingMSID: "72180247",
  coronaId: "74471153",
  domain: "samayam.com",
  webdomain: "tamil.samayam.com",
  mwebdomain: "tamil.samayam.com",
  gadgetdomain: "https://tamil.gadgetsnow.com",
  etdomain: "https://tamil.economictimes.com",
  photogallerydomain: "photogallery.tamil.samayam.com",
  google_site_verification: "6j2LiIEnVIeQivS9Z22g50jOqP1AnqnW9qx247OwWwc",
  twitterHdandler: "@SamayamTamil",
  logo: "nbt-logo.jpg",
  logo_id: "https://static.langimg.com/thumb/78038855/tamil-samayam.jpg?width=176&resizemode=4",
  logogn_id: "https://static.langimg.com/thumb/78038855/tamil-samayam.jpg?width=176&resizemode=4",
  logoPathGadget: "https://static.langimg.com/thumb/82999048,width=232&resizemode=4/tamil-samayam.jpg",
  googleNews: "https://news.google.com/publications/CAAqBwgKMPOGqQsw5ZHBAw?hl=ta&gl=IN&ceid=IN%3Ata",
  fb: "https://www.facebook.com/SamayamTamil",
  twitter: "https://twitter.com/SamayamTamil",
  gplus: "https://plus.google.com/116030764148407709961/about",
  youtubeUrl: "https://www.youtube.com/channel/UCi-MPuZaplEjdCTwquSMETQ",
  linkedInUrl: "",
  shoppingBag: "https://tamil.samayam.com/best-deals-online?category=clothes?utm_source=social_panel",
  izooto: "",
  fullutm: "&utm_campaign=tamilmobile&utm_medium=referral",
  slikeshareutm: "utm_source=slikevideo&utm_medium=referral",
  telegramFollowLink: "https://telegram.me/SamayamTamil_News",
  shortutm: "ma3", // Using for micron
  icon: "https://tamil.samayam.com/favicon.ico",
  breakingNewsFeedUrl: "https://langnetstorage.indiatimes.com/LANGBNews/tamilbnews.htm",
  fbsdkurl: "https://connect.facebook.net/en_IN/sdk.js#xfbml=1&version=v3.0",
  fbpage: "https://www.facebook.com/SamayamTamil",
  livebloghpfeed: "",
  livebloghostname: "tamil", // Using to getch liveblog callback feed
  navfeedurl: "https://langnetstorage.indiatimes.com/langappfeeds/tamil_navjson.htm",
  liveblogbnbewsurl: "",
  moreNews: "More News",
  moreNewsUrl: "https://tamil.samayam.com/headlines.cms",
  glossaryLanding: "https://langnetstorage.indiatimes.com/langappfeeds/tml_glossarylist_business.htm",
  marketindices: "https://m.economictimes.com/mcoverage_langwidget.cms?language=TAM&type=indices&nofollow=true",
  marketcommodities: "https://m.economictimes.com/mcoverage_langwidget.cms?language=TAM&type=commodities&nofollow=true",
  // logo_schema dimension should be 600*60
  logo_schema: "https://static.langimg.com/thumb/66631504/navbharat-times.jpg?width=600&resizemode=4",
  logo_alt: "Samayam Tamil - Tamil News",
  viralBrandingLink: "/viral-corner/articlelist/67088635.cms",
  siteid: "696089404",
  fbpixelid: "",
  fbappid: "980029552049573",
  googleClientId: "981468711104-ogbi31m4kaqpnvslenmovvmuh33c161j.apps.googleusercontent.com",
  astrowidgetId: "49629606",
  bennett: "https://timesofindia.indiatimes.com/bennettjul2020_form_nbt_mweb.cms",

  css:
    "$body-bgcolor:#fff;	$navbar-top-bgcolor:#fff;	$navbar-bg-color:#F5CC10;	$navbar-border-top:#c8cccb;	$navbar-border-shadow:#D8B40D;	$navbar-active-border-bottom-color:#000;	$navbar-link-color:#000;	$hamburger-bg-color:#747474;	$sidenav-bg-color:#fff;	$sidenav-color:#000;	$sidenav-border-bottom:#F5F5F5;	$sidenav-arrow-color:#D1D1D1;	$layer-bg:rgba(0,0,0,0.5);	$breadcrumb-home-color:#DA4848;	$card-border-bottom:#F5F5F5;	$card-bg-color:#8e8e93;	$card-text-color:#191919;	$card-date-color:#bababa;	$home-section-border-bottom:#f5f5f5;	$home-section-heading-border-bottom:#F5CC10;	$home-section-arrow-color:#000000;	$home-section-more-color:#858585;	$home-section-more-border:#CCCCCC;	$footer-background:#585858;	$footer-border-top:#333;	$footer-border-bottom:#7b7b7b;	$footer-heading-color:#e6e6e6;	$footer-text-color:#fff;	$footer-link-color:#d0d0d0;	$footer-trending-color:#95989a;	$footer-copyright-color:#d0d0d0;",
  fontContent:
    "@font-face {font-family: Noto Sans;src: url('https://static.tml.indiatimes.com/fonts/NotoSansTamil-Regular.eot');src: url('https://static.tml.indiatimes.com/fonts/NotoSansTamil-Regular.eot?#iefix') format('embedded-opentype'),url('https://static.tml.indiatimes.com/fonts/NotoSansTamil-Regular.woff2') format('woff2'),url('https://static.tml.indiatimes.com/fonts/NotoSansTamil-Regular.ttf') format('truetype');font-weight: normal;font-style: normal;font-display: optional;}",
  fontUrl: "https://static.tml.indiatimes.com/fonts/NotoSansTamil-Regular.woff2",
  cricket_SIAPI: {
    minischedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_liupre_ta.json",
    schedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_ta.json",
    points_table: "https://toicri.timesofindia.indiatimes.com/jsons/stats/Standings/standing_%seriesid%.json",
    scoreboard: "https://toicri.timesofindia.indiatimes.com/jsons/%matchid%_ta.json",
    topPlayer: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/feed_topplayer.cms?feedtype=sjson",
  },

  techsectionID: {
    // GN Config
    latestGadgets: "81813044",
    trendingGadgets: "81813038",
    video: "70501705",
    photo: "60825524",
  },

  locale: {
    comment: {}, // don't remove this
    appIconText: "ஆப்",
    live_blog: "லைவ் பிளாக்",
    commentary: "Commentary",
    whatsapp_share: "Hey, you might find this interesting: ",
    latest: "லேட்டஸ்ட்",
    most_read: "அதிகம் வாசித்தவை",
    latest_video: "லேட்டஸ்ட் வீடியோ",
    latest_photo: "லேட்டஸ்ட் போட்டோஸ்",
    see_in_app: "Appல் பார்க்க",
    see_in_app_details: "மேலும் ஃபோட்டோஸ்க்கு App-ல் பார்க்கவும்",
    scorecard: "Scorecard",
    releaseDate: "ரிலீஸ் தேதி",
    readmore: "மேலும் படிக்க",
    watchmore: "மேலும் பார்க்க",
    recommendednews: "உங்களுக்கானவை",
    photo_maza: "போட்டோ மஜா",
    key_words: "இந்த தலைப்புகளில் செய்திகளை தேடவும்",
    more_from_topics: "இந்த தலைப்பில் படிக்கவும்",
    brief: {
      tooltip: "இதே முறையில் சிறுதுளி செய்திகளை படிக்க ஆப் டவுண்லோட் செய்யுங்கள்",
      limitation_txt: "சிறுதுளி செய்திகளை மேலும் படிக்க ",
    },
    newsLetter: {
      LS: "5230",
      thankyou: "நன்றி",
      headerText: "முக்கிய செய்திகளை உங்கள் மெயிலில் பெற்றிடுங்கள்..",
      joinIn: "இணையவும் ",
      footerText: "மேலே உங்களது மெயில் ஐடியை பதிவு செய்து, செய்திகளின் அடுத்தடுத்த நிகழ்வுகளை பெற்றிடுங்கள்!",
      verification: "Verification Email Sent to your Email Address",
      already: "நீங்கள் ஏற்கனவே சந்தாதாரர் ஆக இருக்கிறீர்கள் ",
      Subscribed: "You are subscribed now",
      errorNetwork: "There is some network error ! Please try again !",
      notverified: "Already an email has been sent to you ! Please verify !",
      verified: "Your are already Verified",
      unchecked: "Please check the check box",
      validemail: "Please enter a valid email address (example@domain.com)",
      blankemail: "Email Address cannot be left blank",
      login: "Please login to subscribe",
      error: "Error occured!! kindly make sure that you are not unsubscrbing from any older mailer",
    },
    popup: {
      related_videos: "தொடர்புடைய வீடியோக்கள்",
    },
    social_download: {
      title: "'சமயம் தமிழ்' செய்திகளுடன் தொடர்ந்திருங்கள்",
      fblike: "ஃபேஸ் புக் பக்கத்தை லைக் செய்க",
      appdownload: "ஆப் டவுண்லோட் செய்க",
      extrasharetxt: "\n\nஆப் டவுன்லோட் செய்து படிக்க இங்கே கிளிக் செய்க : ",
      fblikeURL:
        "https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FSamayamTamil%2F%3Ffref%3Dts&width=90&layout=button_count&action=like&size=small&show_faces=false&share=false&height=21&appId=117787264903013",
    },
    share_popup_header: "ஷேர் செய்யுங்கள்",
    read_more: "Read More...",
    read_less: "Read Less...",
    view_gallery_from_start: "கேலரியை முதலிலிருந்து பார்க்க",
    next_gallery: "அடுத்த கேலரி",
    next_article: {
      moviereview: "அடுத்த விமர்சனம்",
      articleshow: "அடுத்த செய்தி",
      default: "அடுத்த செய்தி",
      photoshow: "Next Gallery",
      movieshow: "Next Movie",
    },
    next_topic: {
      more_all: "மேலும்",
      more_news: "மேலும் செய்திகள்",
      more_photos: "மேலும் புகைப்படங்கள்",
      more_videos: "மேலும் வீடியோக்கள்",
    },
    search_placeholder: "தேடுக",
    highlight: "ஹைலைட்ஸ்:",
    popularVideos: "பிரபலமான வீடியோக்கள்",
    orientation_heading: "மீண்டும் முயற்சிக்க",
    orientation_text: "லாண்ட்ஸ்கேம் முறையில் பார்க்க இயலாது. போர்ட்ரெய்ட் முறையில் பார்க்க।",
    videos: "வீடியோ",
    photo: "புகைப்படம்",
    related_videos: "தொடர்பான வீடியோக்கள்",
    default_horizontal_tile_width: 200, // These widths are used for slider
    default_slideshow_tile_width: 120,
    related_articles_horizontal_tile_width: 230,
    relatedarticle: "தொடர்பான செய்திகள்",
    wHeadingExitPoll: "எக்ஸிட் போல்",
    read_more_listing: "மேலும்",
    photomasti: "போட்டோ மஸ்தி",
    critics_review: "க்ரிட்டிக் விமர்சனம்",
    twitte_reaction: "டுவிட்டர் விமர்சனம்",
    critics_rating: "Critic's Rating",
    user_rating: "Avg User Rating",
    movie_review: "திரைவிமர்சனம்",
    film_review: "திரைப்பட விமர்சனம்",
    review_movie: "Review Movie",
    review_device: "டிவைஸ் ரிவியூ",
    rate_movie: "Rate this Movie",
    rate: "Rate",
    rate_recipe: "Rate Recipe",
    slide_to_rate: "Slide to Rate",
    slide_to_rate_movie: "Rate This Movie",
    reader_rating: "Avg User Rating",
    movie_review_tile_bg: "https://static.langimg.com/moviereview_list_bg/photo/65022261.cms",
    movie_review_detail_bg: "https://static.langimg.com/moviereview_list_bg/photo/65594589.cms",
    breaking_news: "முக்கியச் செய்திகள்",
    trending: "டிரெண்டிங்",
    highlightText: "ஹைலைட்ஸ் படிக்க - டவுண்லோட் ஆப்",
    live_video: "லைவ் வீடியோ", // Using for minitv widget
    view_text: "பார்க்க",
    aur_jaane: "மேலும் தெரிந்துகொள்ள",
    oops: "ஓ... ",
    offlineText: "நீங்கள் ஆஃப்லைனில் இருப்பதாக தெரிகிறது",
    onlineText: "நீங்கள் ஆன்லைனில் இருக்கிறீர்கள்",
    openinapp: "ஓபன் ஆப்",
    superhit: " மேலும் சில முக்கிய செய்திகளை படிக்க",
    live_updates: "லைவ் அப்டேட்",
    fblikecardtext: "சமயம் தமிழ் <br/> ஃபேஸ்புக் பக்கம் <br/> லைக் செய்க", // Using in Service Drawer
    appdownloadcardtext: "'சமயம் தமிழ்' உடன் எப்போதும்  <br /> தொடர்ந்திருக்க...", // Using in Service Drawer
    installapp: "சமயம் தமிழ் App!",
    login: "லாக் -இன்",
    logout: "லாக்-அவுட்",
    amazonDeals: "இன்றைய டீல்",
    seemoreimages: "மேலும் படங்கள்!", // Using in Photomazzashow
    read_more_liveblog: " மேலும் படிக்க",
    footerheading: "சமயம் தமிழ் விரிவுகள்",
    comment_text: "உங்கள் கருத்தை பதிவு செய்க",
    download_text: "டவுண்லோட்",
    write_comment: "கருத்து எழுதுக",
    wp_broadcast: {
      description: "செய்திகளை வாட்ஸ்ஆப்-ல் பெற்றிடுங்கள்",
      btnText: "சப்ஸ்கிரைப்",
      url: "https://widget.whatsbroadcast.com/widget_more/8531f3a382edfe5c49a332a5fb08a2aa/?show=walink&text=",
    },
    crossbrand: "இந்த செய்தி -hyperlink- ல் -dl- முதலில் வெளியிட்டது",
    appexclusive: "App Exclusive",
    votesuccessfully: "உங்கள் வாக்கு பதிவுசெய்யப்பட்டது",
    votealready: "நீங்கள் ஏற்கனவே வாக்களித்து விட்டீர்கள்.",
    thanks: "நன்றி",
    submit_vote: "வாக்கு",
    photoshow_app_install: {
      read_more: "மீதமுள்ள புகைப்படங்களைக் காண பயன்பாட்டைப் பதிவிறக்கவும்",
      download: "Download App",
    },
    disclaimer: "மறுப்பு",
    live_tv: "LIVE TV",
    data_hub: "டேட்டா ஹப்",
    fantasy_game: "கேம்",
    topics_no_result: "தொடர்புடைய முடிவுகள்",
    players: "வீரர்கள்",
    utility: "பயன்பாடு",
    appDownload: "Tamil Samayam App",
    tech: {
      inIndia: "இந்திய விலை",
      loadmore: "மேலும்",
      rating: "மதிப்பீடு",
      sortby: "வரிசைப்படுத்துக",
      clearall: "நீக்கு",
      buyhere: "வாங்குங்கள்",
      indiaLaunchDates: "இந்தியாவில் அறிமுகம்",
      indiaPrice: "இந்திய விலை",
      compCriteria: "ஒப்பீடு",
      showDiff: "வேறுபாடுகளை காண்பி",
      alreadyAdded: "ஏற்கெனவே சேர்க்கப்பட்டது",
      buyFrom: "அமேசானில் வாங்க",
      addDevice: "டிவைஸ் சேர்க்க",
      compare: "ஒப்பிடுங்கள்",
      englishtype: "ஆங்கிலத்தில் டைப் செய்க",
      change: "बदला",
      suggestedDevice: "பரிந்துரைக்கப்பட்ட டிவைஸ்",
      pe: "पर",
      gadgets: "கேஜட்ஸ்",
      filtertxt: "ஃபில்டர்ஸ்",
      purchasehere: "ஸ்பான்சர்",
      popular: "பாப்புலர்",
      allbrands: "அனைத்து பிராண்டுகள்",
      brands: "பிராண்ட்ஸ்",
      othervariants: "மற்ற வேரியன்ட்ஸ்",
      criticsrating: "க்ரிட்டிக் மதிப்பீடு",
      launchdate: "அறிவிக்கப்பட்ட தேதி",
      review: "ரிவியூ",
      overview: "ஓவர்வியூ",
      userrating: "பயனர் மதிப்பீடு",
      comparedotxt: "ஒப்பீடு",
      submitrating: "மதிப்பிடுக",
      addtocompare: "ஒப்பிடுங்கள்",
      purchase: "வாங்குங்கள்",
      suggested: "பரிந்துரை",
      comparetxt: "ஒப்பீடு",
      latest: "லேட்டஸ்ட்",
      price: "விலை",
      rumoured: "வதந்தி",
      upcoming: "விரைவில்",
      ki: "ची",
      relatedgadgets: "தொடர்புடைய கேஜட்ஸ்",
      seemore: "மேலும்",
      topfeature: "சிறப்பு அம்சங்கள்",
      fullspecification: "முழு அம்சங்கள்",
      selectatleast2: "இரண்டை தேர்வு செய்யவும்",
      devicealreadyinlist: "ஒப்பீடுக்கு ஏற்கனவே தேர்வுசெய்யப்பட்டது",
      same_gadget: "ஒரே கேஜட்டுகள்",
      user_review: "பயனர் ரிவியூ",
      read_fullreview: "முழு ரிவியூ",
      similar_gadget: "ஒரே கேஜட்டுகள்",
      see_diff: "வேறுபாடுகள்",
      latest_comparisons: "லேட்டஸ்ட் ஒப்பீடு",
      popular_comparisons: "பாப்புலர் ஒப்பீடு",
      techNewsH1: "டெக்னாலஜி நியூஸ்",
      minimumComparisonError: "இரண்டை தேர்வு செய்யவும் ",
      // gadgets show
      buyAtAmazon: "அமேசானில் வாங்குங்கள்",
      priceList: "விலை பட்டியல்",
      priceInIndia: "இந்திய விலை",
      criticReview: "க்ரிட்டிக் ரிவியூ",
      userReview: "பயனர் ரிவியூ",
      specifications: "விவரங்கள்",
      moreLikeThis: "மேலும்",
      criticRating: "க்ரிடிக் மதிப்பீடு",
      userRating: "பயனர் மதிப்பீடு",
      user: "பயனர்",
      others: "மற்றவை",
      nextGadget: "அடுத்த கேஜட்ஸ்",
      similarGadgets: "ஒரே கேஜட்ஸ்",

      readCompleteReview: "முழு விமர்சனம்",
      readLess: "சுருக்க",

      recentlyCompared: "சமீபத்தில் ஒப்பிட்டவை",
      weak: "மோசமான",
      belowAverage: "சராசரிக்கும் குறைவான",
      worthpurchase: "வாங்க சிறந்தது",
      good: "சிறப்பு",
      excellent: "மிகச்சிறப்பு",
      thanksforreview: "உங்கள் ரிவியூக்கு நன்றி",
      befirsttoreview: "ரிவியூ எழுதுக",
      userreviewandrating: "பயனர் ரிவியூ & மதிப்பீடு",
      ratedevice: "டிவைசை மதிப்பிடு",
      postRating: "உங்கள் மதிப்பீடு",
      readMoreReview: "மேலும் ரிவியூஸ்",
      varients: "மற்ற வேரியன்ட்",
      text_write_reviews: "ரிவியூ எழுதுக",
      text_view_comment: "View Comments",
      text_write_comment: "Write Comments",
      critic: "Critic",
      language: "Tech",
      category: [
        { keylabel: "மொபைல்", keyword: "mobile" },
        { keylabel: "லேப்டாப்", keyword: "laptop" },
        { keylabel: "ஸ்மார்ட்வாட்ச்", keyword: "smartwatch", keylabelEng: "smart watch" },
        { keylabel: "டெலிவிஷன்", keyword: "tv" },
        { keylabel: "ஏர் கன்டிஷ்னர்", keyword: "ac" },
        { keylabel: "டேப்லட்", keyword: "tablet" },
        { keylabel: "கேமரா", keyword: "camera" },
        { keylabel: "ஃபிட்னஸ்பேண்ட்", keyword: "fitnessband", keylabelEng: "fitness band" },
        { keylabel: "வாஷிங்மெஷின்", keyword: "washingmachine", keylabelEng: "washing machine" },
        { keylabel: "ரெஃப்ரிஜிரேட்டர்", keyword: "refrigerator", keylabelEng: "fridge" },
        { keylabel: "பவர்பேங்க்", keyword: "powerbank", keylabelEng: "power bank" },
      ],
      gadgetSliderConfig: {
        mobile: "மொபைல்",
        laptop: "லேப்டாப்",
        tablet: "டேப்லட்",
        camera: "கேமரா",
        smartwatch: "ஸ்மார்ட்வாட்ச்",
        fitnessband: "ஃபிட்னஸ்பேண்ட்",
        tv: "டெலிவிஷன்",
        ac: "ஏர் கன்டிஷ்னர்",
        washingmachine: "வாஷிங்மெஷின்",
        refrigerator: "ரெஃப்ரிஜிரேட்டர்",
        powerbank: "பவர்பேங்க்",
      },
      affiliateTags: {
        homePage: "tml_wap_home_latesttrendingwidget",
      },
    },
    user_review: "User Review",
    listenAlbum: "Listen to this album",
    castncrew: "Cast & Crew",
    filmSongs: "Film Songs",
    read_movie_review: "read movie review",
    news: "செய்திகள்",
    photos: "Photos",
    market: "சந்தை",
    choseStateCity: { dropDownText: "நகரத்தை தேர்வு செய்யுங்கள்", extraCityContent: "உங்கள் நகர செய்திகளை படிக்க" },
    cityPopUp: {
      selectStateCity: "மாநிலம் மற்றும் நகரம்",
      selectCity: "நகரத்தைத் தேர்ந்தெடுக்கவும்",
      save: "சேமிக்கவும்",
      state: "மாநிலத்தைத்",
      city: "நகரம்",
    },
    cityHeading: "அருகிலுள்ள நகரங்களின் செய்திகள்",
    cityHeadingVideo: "மற்ற நகர வீடியோக்கள்",
    openInApp: {
      stayHere: "இப்படியே தொடரவும்",
      openApp: "ஆப்-ஐத் திற",
      mainText: "ஆப்-ல் கட்டுரையைத் தொடர்ந்து படிக்க?",
      mainTextForVSnPS: "தொடர்ந்து ஆப்-ல் காண...",
    },
    authoraritcle: "எழுதிய கட்டுரைகள்",
    authorwebstories: " இன் வெப் ஸ்டோரி",
    authorsharetext: "ஆன்லைனில் இணைய",
    authorabout: "கட்டுரையாளரை பற்றி",
    articles: "செய்திகள்",
    webstories: "வெப் ஸ்டோரிஸ்",
    dailyNewsUpdate: "தினசரி அப்டேட்டுகளுக்கு லாக்இன்",
    downloadAppForNews: "தினசரி அப்டேட்டுகளுக்கு ஆப் டவுன்லோடு செய்க",
    notificationTopNewsAlert: "செய்திகளை மிஸ் பண்ணாதீங்க. அலோ கிளிக் செய்து சப்ஸ்கிரைப் பண்ணுங்க",
    notification: "அறிவிப்பு",
    others: "மற்றவை",
  },
  imageconfig: {
    thumbid: "67415803",
    liveblogthumb: "56295200",
    // Thumbid reference can change dynamically, this is default thumbid
    defaultthumb: "67415803",
    imagedomain: "https://static.langimg.com/thumb/",
    webimagedomain: "https://tamil.samayam.com/thumb/",

    bigimage: "width=540&resizemode=3", // Article Inline Images, will maintain aspect ratio of original image
    big2ximage: "width=1080&resizemode=3", // Article Inline Images, will maintain aspect ratio of spotlight/paid article image
    smallthumb: "width=280&height=210&resizemode=75", // Listing small thumbs, Aspect Ratio 4:3
    smallslideshowthumb: "width=320&height=240&resizemode=1", // Used for external photogallery strip on top news, Aspect Ratio 4:3
    midthumb: "width=320&height=240&resizemode=75", // Photo Listing widget thumb, etc Aspect Ratio 4:3
    largethumb: "width=380&height=285&resizemode=75", // Lead Images Aspect Ratio 4:3
    amplargethumb: "width=1600&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only videoshow
    amplargethumbarticle: "width=1200&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only for article
    smallwidethumb: "width=200&height=111&resizemode=75", // For video listing widgets Aspect Ratio 16:9
    largewidethumb: "width=380&height=214&resizemode=75", // For videowidget lead image and videoshow Aspect Ratio 16:9
    posterthumb: "width=210&height=281&resizemode=4", // Moview Posters
    squarethumb: "width=200&height=200&resizemode=75", // for two colum layout
    rectanglethumb: "width=160&height=103&resizemode=75", // for rectangle flags
    gnthumb: "width=200&resizemode=4", // for Gadget now
    gnthumbWithHeight: "height=150&resizemode=4", // for GN PDP, need height
    webstoriesthumb: "width=300&height=500&resizemode=4", // web stories Photo Listing widget thumb
    webstoriesthumbLarge: "width=364&height=607&resizemode=4", // web stories Photo Listing widget thumb
    widecardthumb: "width=600&height=315&resizemode=6", // End Article Card thumb 16: 9",
  },
  sso: {
    BASE_URL: "https://tamil.samayam.com",
    SSO_CHANNEL: "tm-wap",
    GADGET_CHANNEL: "tamil-gadgetsnow-wap",
    stg: {
      BASE_URL: "https://jstgtamil.samayam.com",
      MYTIMES_URL_USER: "https://mytest.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
      MYTIMES_URL_SETTINGS: "https://jssostg.indiatimes.com/sso/identity/profile/edit?channel=tm",
      SSO_URL_LOGIN: "https://jssostg.indiatimes.com/sso/identity/login",
      SSO_URL_LOGOUT: "https://jssostg.indiatimes.com/sso/identity/profile/logout/external",
      SSO_URL_GETTICKET: "https://jssostg.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
      SOCIAL_API_INTEGRATOR: "https://testsocialappsintegrator.indiatimes.com/socialsite/",
      SSO_BASE_URL: "https://jssostg.indiatimes.com/sso/crossdomain",
      SSO_CROSSWALK: "https://jssocdnstg.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
      SSO_WIDGET_URL: "https://jssocdnstg.indiatimes.com/crosswalk/133/widget/main.bundle.js",
    },
    SSO_BASE_URL: "https://jsso.indiatimes.com/sso/crossdomain",
    SSO_CROSSWALK: "https://jssocdn.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
    SSO_WIDGET_URL: "https://jssocdn.indiatimes.com/crosswalk/34/widget/main.bundle.min.js",
    MYTIMES_URL_USER: "https://myt.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
    MYTIMES_URL_SETTINGS: "https://jsso.indiatimes.com/sso/identity/profile/edit?channel=tm",
    SSO_URL_LOGIN: "https://jsso.indiatimes.com/sso/identity/login",
    SSO_URL_LOGOUT: "https://jsso.indiatimes.com/sso/identity/profile/logout/external",
    SSO_URL_GETTICKET: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
    SOCIAL_API_INTEGRATOR: "https://socialappsintegrator.indiatimes.com/socialsite",
    MYTIMES_ALREADY_RATED: "https://myt.indiatimes.com/mytimes/alreadyRated?appKey=TAMIL&",
    MYTIMES_ADD_ACTIVITY: "https://myt.indiatimes.com/mytimes/addActivity?appKey=TAMIL&",
    SSO_TRUECALLER_visibility: 4,
    PROFILE_URL: "https://mytimes.indiatimes.com/profile",
    SSO_URL_NewsTicket: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1",
    SSO_URL_SubStatus: "https://webapi.sendpal.in/api/v1/get/user/tm/status?dataformat=json",
    SSO_URL_unsubscribe: "https://webapi.sendpal.in/api/v1/multiple/unsubscribe/tm?dataformat=json",
    SSO_URL_subscribe:
      "https://webapi.sendpal.in/api/v1/add/subscription/tm?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=41",
    SSO_URL_confirm: "https://webapi.sendpal.in/api/v1/confirm/subscription/tm?dataformat=json",
  },
  MYTIMES_PROFILE: "https://mytimes.indiatimes.com/?channel=tml",
  TimesPoint: {
    jsDev: "https://test.timespoint.com/tpwidgets-test/static/dist/js/main.js",
    jsProd: "https://image.timespoints.iimg.in/tpwidgets/static/dist/js/main.js",
    channels: ["tml", "nbt", "eisamay", "tlg"],
    // status: true,
    pcode: "channel8951747",
    scode: "channel8951747",
    activities: {
      DAILY_CHECKINS: "act3432947",
      DAILY_CHECKINS_MOBILE: "act3682055",
      READ_ARTICLE: "act4757750",
      WATCH_VIDEOS: "watch_video",
      SH_FB: "sh_fb",
      SH_TW: "sh_tw",
      LOGIN: "act3460671",
      MOVIE_RATE: "act2995299",
      MOVIE_REVIEW: "act2927403",
      VIEW_PHOTO: "view_photo",
      LIVE_BLOG: "act3503227",
      SUB_NL: "act3528954",
      REGISTER: "act3559146",
      COMMENT: "cmnt",
      SUB_NOTIFICATION: "act7176795",
      CHECKIN_BONUS_DESKTOP: "act3921411",
      CHECKIN_BONUS_MOBILE: "act3944615",
      WHATSAPP_SHARE: "act5434425",
    },
    campaingHistoryName: {
      desktop: "campaign4654430",
      mobile: "campaign4848729",
    },
    campaignDays: 5,
    stg: {
      pcode: "channel1130049",
      scode: "channel1130049",
      campaingHistoryName: {
        desktop: "campaign1650529",
        mobile: "campaign1741855",
      },
      activities: {
        DAILY_CHECKINS: "act1000165",
        DAILY_CHECKINS_MOBILE: "act1448351",
        READ_ARTICLE: "read",
        WATCH_VIDEOS: "watch_video",
        SH_FB: "sh_fb",
        SH_TW: "sh_tw",
        LOGIN: "act1341701",
        MOVIE_RATE: "act1594658",
        MOVIE_REVIEW: "act1643595",
        VIEW_PHOTO: "view_photo",
        LIVE_BLOG: "act1798195",
        SUB_NL: "act1849353",
        REGISTER: "act3473944",
        COMMENT: "cmnt",
        SUB_NOTIFICATION: "act3529439",
        CHECKIN_BONUS_DESKTOP: "act3921411",
        CHECKIN_BONUS_MOBILE: "act3944615",
        WHATSAPP_SHARE: "act3814272",
      },
    },

    TP_FAQ_MSID: "76003641",
    NP_DOMAIN: {
      production: "https://npcoins.indiatimes.com",

      development: "https://nprelease.indiatimes.com",
      stg1: "https://nprelease.indiatimes.com",
      stg2: "https://nprelease.indiatimes.com",
    },

    TP_DOMAIN: {
      production: "https://tpapi.timespoints.com",

      development: "https://test.timespoints.com/tpapi",
      stg1: "https://test.timespoints.com/tpapi",
      stg2: "https://test.timespoints.com/tpapi",
    },

    SDK_DOMAIN: {
      production: "https://image.timespoints.iimg.in",

      development: "https://test-img.timespoints.com",
      stg1: "https://test-img.timespoints.com",
      stg2: "https://test-img.timespoints.com",
    },

    tpwidgetJS: {
      production: "/tpwidgets/dist/js/tpwidget.js",

      development: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg1: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg2: "/static/tpwidgets/static/dist/js/tpwidget.js",
    },

    //* * Moved to common config */
    tpPage: "/timespoints.cms",
    tpRedeemLink: "https://www.timespoints.com/products",
  },
  Comments: {
    appkey: "TAMIL",
    topComments: {
      appkey: "TAMIL",
      sortcriteria: "AgreeCount",
      order: "desc",
      size: "1",
      lastdeenid: "0",
      after: "true",
      withReward: "false",
      pagenum: "1",
    },
    allComments: {
      appkey: "TAMIL",
      sortcriteria: "CreationDate",
      order: "asc",
      size: "6",
      lastdeenid: 0,
      after: true,
      withReward: false,
      pagenum: 1,
    },
  },
  // GN config
  pages: {
    elections: "51601233",
    mktwdt: "88010209",
    business: "56197390",
    iplHomePage: "63299420",
    commonwealth: "63477968",
    fifa: "64425104",
    wcHomePage: "86753325",
    stateSection: "73081152,48237907",
    tech: "70501579",
    techreview: "70501742",
    gadgethome: "83349784",
    gadgetsnow: {
      video: "83709395",
    },
    budget: "62458756",
    budget_you: "97255082",
    apanabazaar: "84552421",
  },

  iplpages: {
    venues: "63299476",
    teams: "63299516",
    pointsTable: "63299555",
    miniSchedule: "63299532",
  },
  t20wcpages: {
    venues: "86757058",
    teams: "86756689",
    pointsTable: "86756662",
    miniSchedule: "86756593",
  },
  redis: {
    host: "192.168.24.51",
    port: "6379",
    db: "1",
  },
  // To print label in listing node at bottom right corner [templatename, label]
  listNodeLabels: {
    articlelist: ["articlelist"],
    news: ["articleshow"],
    photo: ["photoshow"],
    slideshow: ["photoshow"],
    video: ["videoshow"],
    videolist: ["videolist"],
    photolist: ["photolist"],
    lb: ["liveblog", "லைவ் அப்டேட்"],
    moviereview: ["moviereview", "விமர்சனம்"],
    movieshow: ["movieshow", "விமர்சனம்"],
    poll: ["pollsurvey", "வாக்கு"],
  },
  photoListView: "47882310",
  miniTvMoreVideos: "47344128",
  // Used In AnchorLinkCard
  routes: [
    "/exitpolls/",
    "/results/",
    "/electionlist/",
    "/articlelist/",
    "/photoarticlelist/",
    "/photomazza/",
    "/photolist/",
    "/photoshow/",
    "/photogallery/",
    "/articleshow/",
    "/moviereview/",
    "/movieshow/",
    "/liveblog/",
    "/videolist/",
    "/videoshow/",
    "/topics/",
    "/teams/",
    "/venues/",
    "/pointstable/",
    "/iplt20.cms",
    "/schedule/",
    "/sportsresult/",
    "elections.cms",
    "/topics/",
    "/timespoints",
  ],

  staticPagesDir: "/var/www/html/testpages/",

  slike: {
    apikey: "tamilmweb60lang",
    snapchatapikey: "",
    ampapikey: "tamilampweb60lang",
    default_slikeid_minitv: "1x13qpaggu", // Times-Now
    nextvideo_domain: "https://mtpwafeeds.indiatimes.com",
    default_pl_videolist: "/feeds/videpostroll_v5_slike/47344128.cms?feedtype=json&callback=cached",
  },

  slikeAdCodes: {
    others: "other",
  },

  gRecaptchaKey: "6LcxSGUUAAAAAPsGPKVpEkLKxnuluuqDKa1AivEN",

  ga: {
    gtm: "GTM-WJQSHS7",
    gtm4: "G-E9Y6SFCC6X",
    ampgtm: "GTM-NKJT2VF",
    gverifyCode: "zU5qA2HPdN2PFPyZd70q25_5NHXI8AE8AbqWNwXsoFA",
    gatrackid: "UA-29031733-11",
    ga4trackid: "G-E9Y6SFCC6X",
    gaprofile: "[]",
  },

  growthrx: {
    stg: {
      id: "g717ee3fc",
    },
    prod: {
      id: "g728bdb82",
    },
    gn: {
      stg: {
        id: "g1affb2b8",
      },
      prod: {
        id: "g5ac60ca0",
      },
    },
  },

  appexclusive_ga: {
    category: "Wap to App install",
    action: "click",
    label: "articlelist_topsection",
  },
  poll: {
    link: "pollslist.cms",
  },
  poll_ga: {
    poll_submit: {
      category: "pollSurvey",
      action: "submit",
      label: "pollsubmit",
      event: "tvc_pollSurvey_submit",
    },
    poll_result_loggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "loggedin",
      event: "tvc_pollSurvey_submit",
    },
    poll_result_nonloggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "non-loggedin",
      event: "tvc_pollSurvey_submit",
    },
  },

  photoshow_app_install: {
    ga_object: {
      category: "Wap to App install",
      action: "click",
      label: "photo show",
    },
  },
  // sso_ga: {
  //   truecaller_requestscreen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen Request",
  //   },
  //   truecaller_screen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen View",
  //     event: "tvc_truecaller_screenview",
  //   },
  //   truecaller_screencontinue: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Continue",
  //   },
  //   truecaller_skip: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Skip",
  //   },
  //   truecaller_loginsuccess: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Login Successful",
  //     event: "tvc_truecaller_login_success",
  //   },
  // },
  comscore: { c1: "2", c2: "6036484", c9: "https://tamil.samayam.com" },

  applinks: {
    android: {
      hrnav: "https://tamilsamayam.onelink.me/V28U/9a985aa6",
      asshow: "https://tamilsamayam.onelink.me/V28U/b43da2a8",
      photoshow: "https://tamilsamayam.onelink.me/V28U/504ccc9a",
      serviceDrawer: "https://tamilsamayam.onelink.me/V28U/58e98b7f",
      // social: "http://smym.in/tmlsharing",
      social: "https://tamilsamayam.onelink.me/V28U/741ac984",
      oip_appexclusive: "https://navbharattimes.indiatimes.com/off-url-forward/tm_openinapp.cms?msid=",
      // https://tamilsamayam.onelink.me/cMxT/b256ac1
    },
  },
  appdeeplink: {
    domain: "https://tamilsamayam.onelink.me",
    shortcode: "V28U",
    c: "Internal_Campaign",
    pid: {
      hrnav: "WAP_HRNAV_New",
      serviceDrawer: "WAP_BOTTOM_New",
      news: "WAP_MWEB_New",
      article_end: "WAP_AS_New",
      photo: "WAP_PG_New",
      toparticle: "WAP_Top%20Articles_New",
      extphoto: "WAP_Home_Photostrip_New",
      photoshow: "WAP_Photoshow_New",
      campaign: "WAP_Election",
      campaignHome: "WAP_Election_Home",
      openinapp_as: "TML_AS_Brandwire",
      openinapp_al: "TML_AL_Brandwire",
      photofeature: "WAP_MWEB_New",
      photoFeature: "WAP_MWEB_New",
      recipe: "WAP_MWEB_New",
      videoshow: "WAP_VideoShow",
      topStrip: "WAP_Top_Strip",
      articlelist: "WAP_ArticleList",
      topStripAS: "New_Top",
      videolist: "WAP_VideoList",
      photolist: "WAP_PhotoList",
      continueInApp: "Continue_App",
      sharing: "WAP_Sitesharing_New",
    },
    listdefaultUrl: " https://tmlpwafeeds.indiatimes.com/feeds/app_listing/<MSID>.cms?feedtype=json",
    openapp: "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil",
    opennews:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dnews-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openphoto:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openextphoto:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dp-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openhtmlview:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BURL%7D",
    opensection:
      "tamilsamayamactivities://open-%24%7C%24-pub%3D8:Samayam Tamil-%24%7C%24-type%3Dsection-%24%7C%24-sectionID%3D%7BsectionID%7D-%24%7C%24-sectionName%3D%7BsectionName%7D-%24%7C%24-id%3D%7BMSID%7D",
    openphotofeature:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3DphotoFeature-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openrecipe:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Drecipe-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openvideoshow:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dvideo-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openarticlelist:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dnews-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openphotolist:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dphoto-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openvideolist:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dvideo-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openContinueInApp:
      "tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D&af_web_dp=https%3A%2F%2Ftamil.samayam.com&is_retargeting=true&deep_link_value=tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
  },
  pushNotification: {
    cookieName: "notifypopup_tml",
    defaultThumb: "https://static.langimg.com/thumb/59423128/pic.jpg?width=100&height=100",
    heading: "லேட்டஸ்ட் & பிரேக்கிங் செய்திகளுக்கான நோட்டிஃபிகேஷன் பெற சப்ஸ்கிரைப் செய்யவும்",
  },

  weather: {
    geoLocationApi: "https://geoapi.indiatimes.com/?cb=1",
    defaultCity: "Chennai",
    citiesJson: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_geocities.cms",
    weatherFeed: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_weathertoday.cms?lat=",
    heading: "இன்றைய வெப்பநிலை",
    cityText: "உங்கள் நகரச் செய்திகள்",
  },
  pollution: {
    heading: "प्रदूषण",
    headingV1: "காற்று மாசு அளவு",
    status: {
      good: "நன்று",
      moderate: "மிதமானது",
      unhelathfSG: "குறிப்பிட்ட குழுக்களுக்கு ஆரோக்கியமற்றது",
      unhealthy: "ஆரோக்கியமற்றது",
      veryUnhealthy: "மிகவும் ஆரோக்கியமற்றது",
      hazardous: "அபாயகரமானது",
    },
    url: "https://tamil.samayam.com/latest-news/pollution-tracker",
  },
  fuel: {
    heading: "फ्यूल",
    feedUrl: "https://toibnews.timesofindia.indiatimes.com/fuelprice/latestPrice",
  },

  oneTapSignIn: {
    smartlockurl: "https://smartlock.google.com/client",
    isViewGaTracked: false,
    eventGAObj: {
      hitType: "event",
      category: "Login",
      action: "One_Tap",
      label: "",
    },
    text: {
      oneTapSuccessMsg: "வெற்றிகரமாக உள்நுழைந்தீர்கள்",
      oneTapErrorMsg: "Oops! ஏதோ தவறு உள்ளது. மீண்டும் முயற்சி செய்க",
      oneTapBtnText: "மீண்டும் முயற்சி செய்க",
    },
    constants: {
      onetapIgnoreDays: 15,
      onetapCookie: "oneTapNextShow",
      onetapIframeCheckTimer: 2000,
      smartlockJsLoadTimer: 10000,
      clientId: "981468711104-ogbi31m4kaqpnvslenmovvmuh33c161j.apps.googleusercontent.com",
      channel: "tm-wap",
      jssoAPIGetURL: "https://jsso.indiatimes.com/sso/services/gponetaplogin/verify",
    },
  },

  cricplay_widget: {
    schedulelink: "/sports/cricket/icc-world-cup/schedule/69161420.cms",
    deeplink:
      "https://tamilsamayam.onelink.me/V28U?pid=WAP_CricPlay&c=Internal_Campaign&af_dp=tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3Dhttps%3A%2F%2Fcrpl.app.link%2FZnAyOSBSxW",
    wincashtxt1: "உங்களுக்கு பிடித்த கிரிக்கெட் அணியை உருவாக்குங்கள் மற்றும் ",
    wincashtxt2: "பணம் வென்றிடுங்கள்!",
    appdwntxt: "சமயம் தமிழ் ஆப் டவுண்லோடு செய்க",
  },

  ZodiacSigns: {
    url: "#",
    data: [
      {
        name: "aries",
        regName: "மேஷம்",
        pos: 1,
      },
      {
        name: "taurus",
        regName: "ரிஷபம்",
        pos: 2,
      },
      {
        name: "gemini",
        regName: "மிதுனம்",
        pos: 3,
      },
      {
        name: "cancer",
        regName: "கடகம்",
        pos: 4,
      },
      {
        name: "leo",
        regName: "சிம்மம்",
        pos: 5,
      },
      {
        name: "virgo",
        regName: "கன்னி",
        pos: 6,
      },
      {
        name: "libra",
        regName: "துலாம்",
        pos: 7,
      },
      {
        name: "scorpio",
        regName: "விருச்சிகம்",
        pos: 8,
      },
      {
        name: "sagittarius",
        regName: "தனுசு",
        pos: 9,
      },
      {
        name: "capricorn",
        regName: "மகரம்",
        pos: 10,
      },
      {
        name: "aquarius ",
        regName: "கும்பம்",
        pos: 11,
      },
      {
        name: "pisces",
        regName: "மீனம்",
        pos: 12,
      },
    ],
  },

  ads: {
    ampInuxuAd:
      "https://adgebra.co.in/afpf/IBN_AMP.html?domain=amp-tamil.samayam.com&pubid=3613&slotId=1&templateId=4656&accessMode=1&divId=div_407860734567731&cache=123",
    ampAdAfter: "",
    gptUrl: "https://www.googletagservices.com/tag/js/gpt.js",
    ctnAddress: "https://static.clmbtech.com/ad/commons/js/13539/colombia_v2.js",
    dmpUrl: "https://static.clmbtech.com/ase/13539/205/aa.js",
    isvPreRollUrl:
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/7176/TML_MWEB/TML_MWEB_Videoshow/TML_MWEB_Videoshow_ISV&description_url=https%3A%2F%2Ftamil.samayam.com%2F&tfcd=0&npa=0&sz=300x230%7C300x400&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
    dmpAmpCode: "13539:1217",
    ADS_PRIORITY: "FAN",
    profileid: "2929",
    exchangeId: "692989",
    ctnads: {
      inline: "206013",
      ampinline: "328050",
      ampinlinehome: "328049",
      ampctnhometop: "330647", // For AMP Home Page
      ampctnshowvideo: "334315",

      ctnlist: "206013",
      ctnlistTop: "354483",
      ampctnlist: "328050",
      ctnlist1: "206013",
      // "ctnlist": "320650",
      ctnpgl1: "337260",
      ampctnpgl1: "337262",
      ctnpgl2: "337260",
      ampctnpgl2: "337262",
      ctnvll1: "335032",
      ampctnvll1: "337264",
      ctnvll2: "335033",
      ampctnvll2: "337270",
      ctnbiglist: {
        ctnId: "324209",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_Mweb_Direct_AL_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnsluglist: {
        ctnId: "355640",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_MWEB_AL_INS_NEW_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listdefault: "206013",
      listhorizontalsmall: "206013",
      ctnmgid: "M787958ScriptRootC",
      ctnMmgid: "1277569",
      ctnBmgid: "1277570",
      ctnmgidurl: "https://jsc.mgid.com/t/i/til.tamil.samayam.com",

      ctnshow: "323122",
      ctnmidart: "334315",
      ctnnative: "323121",
      ctnmidart_test: "", // for test page only requested by sales
      ctninlineshow: "208370",
      ctnrecommended: "206013",
      ctnrhsvideo: "335031",
      ctnshowvideo: "334315", // video ad on articleshow
      ctnvs: "335032", // Video Show
      ampctnvs: {
        id: "337264",
        width: "320",
        height: "110",
        minHeights1: "188px",
        minHeights2: "188px",
        minHeights3: "188px",
        minHeights4: "188px",
      }, // Video Show AMP
      // "ctnhome" : "316371",  // caraousal ad code, just for test
      // "ctnhometop" : "206698",
      ctnhome: {
        ctnId: "206012",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefault: {
        ctnId: "206012",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefaultsmall: {
        ctnId: "206012",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontal: {
        ctnId: "206012",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homevertical: {
        ctnId: "206012",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontalsmall: {
        ctnId: "206012",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnhometop: "207572", // updated
      ctnhomevideo: "324708",
      ctnbighome: {
        ctnId: "324208",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_Mweb_Direct_HP_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      homeibeat: {
        ctnId: "206012",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },

      ctnslider: "210640",
      ctnVideoURL: "https://tamil.samayam.com/ads_native_video_dev.cms",

      adspositionsPhoto: "-3-,-5-,-9-,-14-,-20-,-27-,-36-,-45-,-55-",
      ctnbigphoto: {
        ctnId: "324210",
        dfpSlot: "/7176/TML_MWEB/TML_MWEB_Bid_Experiment/TML_Mweb_Direct_PG_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ampctnbigphoto: "337263",

      ctnint: "324741",
      ctnint_test: "337410",
      adspositionsLiveblog: "-5-,-10-,-15-,-20-,-25-,-30-,-35-,-40-",
      ctncookievalue: "ce_tsmap",

      ctntopicsall: "206013",
      ampctntopicsall: "328050",
      ctntopicsnews: "206013",
      ampctntopicsnews: "328050",
      ctntopicsphotos: "335033",
      ampctntopicsphotos: "337262",
      ctntopicsvideos: "335033",
      ampctntopicsvideos: "337270",
      ctnbccl: "340362",
      ctntechlist: "335470", // Gadget Config
      ctnTechGL: "335470", // Gadget Config
      ctnTechPDP: "335474", // Gadget Config
      ctnTechCL: "357059", // Gadget Config
      ctnTechCDP: "335474", // Gadget Config
      ctnTechTC: "357059", // Gadget Config
      ctntechTop: "335476", // GN Config
      ctntechvideo: "335475", // GN Config
      ctntechoth: "357687", // GN Config
      ctnInImage: "518961",
      ctnPreRoll: "518889",
    },
    // For ESI Ads
    ctnslots: {
      atf: "327960",
      ctnshow: "323122",
      ctnbiglist: "",
      ctnbigphoto: "",
      midart: "327959",
      articleshow: "ctnshow,atf,midart",
      liveblog: "",
      photoshow: "",
      videoshow: "",
      videolist: "",
    },

    dfpads: {
      topatf: "/7176/TML_Mweb/TML_Mweb_Others/TML_MWEB_OTH_Fixed",
      cubead1: "/7176/TML_MWEB/TML_MWEB_Others/TML_MWEB_OTH_CUBE_195x85",
      cubead2: "/7176/TML_MWEB/TML_MWEB_Others/TML_MWEB_OTH_CUBE2_195x85",
      cubeheadad1: "/7176/TML_MWEB/TML_MWEB_Others/TML_MWEB_OTH_CUBE_195x30",
      cubeheadad2: "/7176/TML_MWEB/TML_MWEB_Others/TML_MWEB_OTH_CUBE_195x30",
      cubeheadad3: "/7176/TML_MWEB/TML_MWEB_Others/TML_MWEB_OTH_CUBE2_195x30",
      cubeheadad4: "/7176/TML_MWEB/TML_MWEB_Others/TML_MWEB_OTH_CUBE2_195x30",
      andbeyond: "/7176/TML_MWEB/TML_MWEB_ROS/TML_Mweb_ROS_Andbeyond_1x1",
      inimage: "/7176/TML_MWEB/TML_MWEB_ROS/TML_Mweb_ROS_Inimage_1x1",
      multiplex: "/7176/TML_MWEB/TML_MWEB_ROS/TML_MWEB_ROS_Bottomwidget",
      canvasAd: "/7176/TML_MWEB/TML_MWEB_ROS/TML_Mweb_ROS_Mcanvas_1x1",
      interstitial: "ca-pub-1902173858658913",
      dfpint: "/7176/TML_MWEB/TML_MWEB_Home/TML_MWEB_HP_INT",
      trk: "/7176/TML_MWEB/TML_MWEB_ROS/TML_MWEB_ROS_trk_1x1",
      osv: "/7176/TML_MWEB/TML_MWEB_ROS/TML_MWEB_ROS_OUTSTREAM_1x1",
      sitesync: "/7176/TML_MWEB/TML_MWEB_Home/TML_Mweb_HP_SiteSync_1x1",
      nativead: "/7176/Languages/TML_Mweb/TML_Mweb_Native_300x250",
      nativeadamp: "/7176/Languages/TML_AMP/TML_AMP_Native_300x250",
      ampIntAd: "/7176/AMP_TML_Mweb/AMP_TML_Mweb_ROS/AMP_TML_Mweb_ROS_INT",
      budgetSlug: "/7176/Tamil/Budget/TML_BDGT_SLG",
      test1: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_1_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_1_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_1_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_1_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_1_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_1_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      test2: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_2_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_2_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_2_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_2_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_2_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/TML_MWEB/TML_Mweb_Test/TML_MWeb_Test_2_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      others: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/TML_MWEB/TML_MWEB_Others/TML_MWEB_Others_ATF",
          size: [
            [300, 250],
            [320, 100],
            [320, 50],
            [336, 280],
            [250, 250],
            [300, 50],
          ],
        },
        btf: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_BTF",
          size: [
            [300, 250],
            [320, 50],
            [300, 50],
            [300, 75],
            [234, 60],
          ],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-2-fbn",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_FBN",
          size: [
            [320, 50],
            [300, 50],
          ],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-4",
          name: "/7176/TML_MWEB/TML_MWEB_Others/TML_MWEB_Others_Mrec1",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-2",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_Mrec2",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-inf",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_MrecINF",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        slug: {
          id: "div-gpt-ad-9135510865388-slug",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_slug1",
          size: [
            [320, 100],
            [300, 100],
          ],
        },
        parallax: {
          id: "div-gpt-ad-9135510865388-parallax",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_FC",
          size: [[300, 600]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-3",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_Mrec3",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec4: {
          id: "div-gpt-ad-9135510865388-4",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_Mrec4",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec5: {
          id: "div-gpt-ad-9135510865388-5",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_Mrec5",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec6: {
          id: "div-gpt-ad-9135510865388-6",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_Mrec6",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec7: {
          id: "div-gpt-ad-9135510865388-7",
          name: "/7176/TML_MWeb/TML_MWEB_Others/TML_MWEB_Others_Mrec7",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        refreshnews: "/7176/TML_MWEB/TML_MWEB_News/TML_MWEB_News",
      },
    },
  },
  plus: {
    disablePlus: false,
    logo: "https://static.langimg.com/thumb/85000251/tamil-samayam.jpg?height=36&resizemode=4",
    home: "84195947",
    video: "84195995",
    shortName: "TML Plus",
    articleReferrerCd: 8,
    articleTypeCd: 6,
    premiumText: "பிரீமியம்",
    homeText: "Home",
  },
  // dailyMotion: { channel: "samayamtamil", playerId: "x6k8w", meta: "dmskibozi0z18ljhu", syndication: "278259" },
  plusWidgetObj: {
    logo: "https://static.langimg.com/thumb/85000251&/tamil-samayam.jpg?height=36&resizemode=4",
    altText: "tamil-samayam",
    premiumText: "பிரீமியம்",
    thumb: "https://static.langimg.com/thumb/67415803/tamil-samayam.jpg?width=540&height=405&resizemode=4",
  },
  loginWall: {
    heading: "சமயம் பிளஸ் செய்திகளை தொடர்ந்து படிக்க உள் நுழையவும்.",
    subHeading: "சமயம் பிளஸ் நன்மைகள்",
    label1: "விளம்பரமில்லா வாசிப்பு அனுபவம்",
    label2: "பிரத்தியேக கட்டுரைகள் மற்றும் வீடியோக்கள்",
    label3: "ஒவ்வொரு செய்திகள் மற்றும் வீடியோவிலும் டைம்ஸ்பாய்ண்ட்ஸ்களை பெறுங்கள்",
  },
  foryoupage: {
    cid: "13539:214",
    agencyFilters: ["மொழி", "Brandwire", "SPOTLIGHT"],
  },
  authorDetails: {
    agencyName: "Samayam Tamil",
    authorName: "",
    editorLink: "",
    editorLabel: "",
  },
  cityLandingPage: "/city/articlelist/73081152.cms",
  timesXP: {
    hostName: "tml_xp",
    xpUrl: "https://tmlfeed.timesxp.com/langapi",
    appUrl: "https://tamil.timesxp.com",
    wapCode: "tamilTxp",
  },
  vdoAI: {
    isEnabled: true,
    scriptUrl: "//a.vdo.ai/core/v-tamil-samayam-v0/vdo.ai.js",
    containerID: "v-tamil-samayam-v0",
  },
  orgAddress: {
    addressLocality: "Times Internet Limited, Kochar Towers, #19, Venkatnarayana Road, T Nagar",
    addressRegion: "Chennai ",
    postalCode: "600017",
  },
};
