module.exports = {
  hostid: "252", // GN Config
  channelid: "696089404",
  mediawireslot: "13",
  wapsitename: "Eisamay",
  wapsiteregionalname: "এই সময়",
  siteName: "eisamay.com",
  staticSiteName: "static.eis.indiatimes.com",
  fbIAcontentId: "383650978371417",
  languagemeta: "bn",
  language: "Bengali",
  channelCode: "eisamay",
  wapCode: "eis",
  gdprID: "EIS",
  coronaId: "74471263",
  languagefullName: "Eisamay",
  iospackageid: "679530233",
  androidpackage: "com.eisamay.reader",
  deeplinkappid: "eisamayreaderactivities",
  deeplinkpubid: "pub=4:EI Samay",
  iosapp_name: "EI Samay App",
  weburl: "https://eisamay.com",
  mweburl: "https://eisamay.com",
  gadgetdomain: "https://bengali.gadgetsnow.com",
  etdomain: "https://bengali.economictimes.com",
  ccaudId: "7270:134",
  ccaudAmp: "7270",
  ccaudIdAmp: "7270:1216",
  indexExchangeUrl: "//js-sec.indexww.com/ht/p/191952-69829312058988.js",
  pwtUrl: "//ads.pubmatic.com/AdServer/js/pwt/23105/3787",
  liveblogApi: "https://langnetstorage.indiatimes.com/Score/pwa_indiaLiveblog_eis.htm",
  footerDesktopLink: "https://eisamay.com?mobile=no",
  langnetstorageBasePath: "https://langnetstorage.indiatimes.com/langappfeeds",
  cookieLessDomain: "https://static.eis.indiatimes.com",
  video: { rootId: "16683331", newsId: "97366736" },
  fbLive: "92081751",
  videoiconurl: "/videos/videolist/16683331.cms",
  editTrendingMSID: "75174693",
  rss: "/rss.cms",
  domain: "indiatimes.com",
  webdomain: "eisamay.com",
  mwebdomain: "eisamay.com",
  photogallerydomain: "photogallery.eisamay.indiatimes.com",
  google_site_verification: "aazPHkz9wF1xs6eEAk49ugaknkewzNLhvWhr_fyXOIM",
  twitterHdandler: "@Ei_Samay",
  logo: "nbt-logo.jpg",
  logo_id: "https://static.langimg.com/thumb/78038849/eisamay.jpg?height=150&resizemode=4",
  logogn_id: "https://static.langimg.com/thumb/78038849/eisamay.jpg?height=150&resizemode=4",
  logoPathGadget: "https://static.langimg.com/thumb/83990236/eisamay.jpg?height=232&resizemode=4",
  googleNews: "https://news.google.com/publications/CAAqBwgKMIfm3QownsPUAQ?hl=en-IN&gl=IN&ceid=IN%3Aen",
  fb: "https://www.facebook.com/eisamay.com/",
  twitter: "https://twitter.com/Ei_Samay",
  gplus: "https://plus.google.com/+EisamayOfficial",
  youtubeUrl: "https://www.youtube.com/channel/UCPYZ_TMaFSsAGyedFpwyufA",
  linkedInUrl: "",
  shoppingBag: "https://eisamay.com/best-deals-online?category=clothes?utm_source=social_panel",
  izooto: "",
  fullutm: "&utm_campaign=eismobile&utm_medium=referral",
  slikeshareutm: "utm_source=slikevideo&utm_medium=referral",
  telegramFollowLink: "https://telegram.me/EisamayNews",
  shortutm: "mz",
  icon: "https://eisamay.com/favicon.ico",
  breakingNewsFeedUrl: "https://langnetstorage.indiatimes.com/LANGBNews/eisamaybnews.htm",
  fbsdkurl: "https://connect.facebook.net/bn_IN/sdk.js#xfbml=1&version=v3.0",
  fbpage: "https://www.facebook.com/eisamay.com/",
  livebloghpfeed: "https://langnetstorage.indiatimes.com/Score/pwa_eisamayLiveblog_hp.htm",
  livebloghostname: "es",
  moreNews: "আরও পড়ুন",
  moreBangladeshNewsUrl: "https://eisamay.com/bangladesh-news/articlelist/62281110.cms?curpg=3",
  moreNewsUrl: "https://eisamay.com/headlines.cms",
  glossaryLanding: "https://langnetstorage.indiatimes.com/langappfeeds/eis_glossarylist_business.htm",
  marketindices: "https://m.economictimes.com/mcoverage_langwidget.cms?language=BEN&type=indices&nofollow=true",
  marketcommodities: "https://m.economictimes.com/mcoverage_langwidget.cms?language=BEN&type=commodities&nofollow=true",
  // FIXME: DEV URL, REVERT TO NORMAL AFTER DEV DONE.
  // navfeedurl: "https://mdev8358.indiatimes.com/off-url-forward/wdt_navjson_v2.cms",
  navfeedurl: "https://langnetstorage.indiatimes.com/Score/eisamay_navconfig.htm",
  liveblogbnbewsurl: "https://eisamay.com/bangla-news-live/liveblog/62537291.cms",
  logo_schema: "https://static.langimg.com/thumb/60408752/ei-samay.jpg?width=600&resizemode=4",
  logo_alt: "Bengali News",
  viralBrandingLink: "/viral-corner/articlelist/67088635.cms",
  siteid: "2147477985",
  fbpixelid: "",
  fbappid: "223044881622213",
  googleClientId: "879025834833-h6n58fvfovaebhvehtoufi32rcgesd25.apps.googleusercontent.com",
  astrowidgetId: "19127963",
  bennett: "https://timesofindia.indiatimes.com/bennettjul2020_form_nbt_mweb.cms",
  css:
    "$body-bgcolor:#fff;    $navbar-top-bgcolor:#fff;    $navbar-bg-color:#F5CC10;    $navbar-border-top:#c8cccb;    $navbar-border-shadow:#D8B40D;    $navbar-active-border-bottom-color:#000;    $navbar-link-color:#000;    $hamburger-bg-color:#747474;    $sidenav-bg-color:#fff;    $sidenav-color:#000;    $sidenav-border-bottom:#F5F5F5;    $sidenav-arrow-color:#D1D1D1;    $layer-bg:rgba(0,0,0,0.5);    $breadcrumb-home-color:#DA4848;    $card-border-bottom:#F5F5F5;    $card-bg-color:#8e8e93;    $card-text-color:#191919;    $card-date-color:#bababa;    $home-section-border-bottom:#f5f5f5;    $home-section-heading-border-bottom:#F5CC10;    $home-section-arrow-color:#000000;    $home-section-more-color:#858585;    $home-section-more-border:#CCCCCC;    $footer-background:#585858;    $footer-border-top:#333;    $footer-border-bottom:#7b7b7b;    $footer-heading-color:#e6e6e6;    $footer-text-color:#fff;    $footer-link-color:#d0d0d0;    $footer-trending-color:#95989a;    $footer-copyright-color:#d0d0d0;",
  fontContent:
    "@font-face {font-family: Noto Sans;src: url('https://static.eis.indiatimes.com/fonts/NotoSansBengali-Regular.eot');src: url('https://static.eis.indiatimes.com/fonts/NotoSansBengali-Regular.eot?#iefix') format('embedded-opentype'),url('https://static.eis.indiatimes.com/fonts/NotoSansBengali-Regular.woff2') format('woff2'),url('https://static.eis.indiatimes.com/fonts/NotoSansBengali-Regular.ttf') format('truetype');font-weight: normal;font-style: normal;font-display: optional;}",
  fontUrl: "https://static.eis.indiatimes.com/fonts/NotoSansBengali-Regular.woff2",
  cricket_SIAPI: {
    minischedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_liupre_bn.json",
    schedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_bn.json",
    points_table: "https://toicri.timesofindia.indiatimes.com/jsons/stats/Standings/standing_%seriesid%.json",
    scoreboard: "https://toicri.timesofindia.indiatimes.com/jsons/%matchid%_bn.json",
    topPlayer: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/feed_topplayer.cms?feedtype=sjson",
  },

  techsectionID: {
    // GN Config
    latestGadgets: "82059762",
    trendingGadgets: "82059767", // or popular
    video: "75077268",
    photo: "",
  },

  locale: {
    comment: {}, // don't remove this
    appIconText: "অ্যাপ",
    live_blog: "লাইভ ব্লগ",
    commentary: "Commentary",
    whatsapp_share: "Hey, you might find this interesting: ",
    see_in_app: "অ্যাপে দেখুন",
    see_in_app_details: "ফিচার্ড ছবিগুলি দেখতে অ্যাপে চেক করুন",
    scorecard: "Scorecard",
    releaseDate: "রিলিজের তারিখ",
    recommendednews: "সুপারিশযোগ্য খবর",
    photo_maza: "ফটো গ্যালারি",
    key_words: "এই বিষয়ে আরও পড়ুন",
    latest: "টাটকা",
    most_read: "সবাই যা পড়ছেন",
    latest_video: "টাটকা ভিডিয়ো",
    latest_photo: "টাটকা ফটো",
    more_from_topics: "এই বিষয়ে আরও পড়ুন",
    readmore: "আরও পড়ুন",
    watchmore: "আরও দেখুন",
    brief: { tooltip: "এই ফরম্যাটে খবর পড়তে হলে অ্যাপ ডাউনলোড করুন", limitation_txt: "ব্রিফের বাকি খবর পড়তে হলে" },
    newsLetter: {
      LS: "3290",
      thankyou: "ধন্যবাদ",
      headerText: "দৈনিক গুরুত্বপূর্ণ খবরের আপডেট পেতে চান?",
      joinIn: "যোগ দিন",
      footerText: "উপরের বক্সে ইমেল আইডি উল্লেখ করুন। খবর আপনার ইনবক্সে পৌঁছে যাবে!",
      verification: "আপনার ইমেল অ্যাডড্রেসে ভেরিফিকেশন ইমেল পাঠানো হয়েছে",
      already: "আপনি ইতোমধ্যেই নিউজলেটার সাবস্ক্রাইব করেছেন ",
      Subscribed: "আপনি এখন সাবস্ক্রাইবড",
      errorNetwork: "নেটওয়ার্কে কোনও সমস্যা হয়েছে! ফের চেষ্টা করুন!",
      notverified: "আপনার কাছে ইমেল পাঠানো হয়েছে! প্লিজ ভেরিফাই করুন!",
      verified: "আপনি ইতোমধ্যেই ভেরিফায়েড",
      unchecked: "চেকবক্সে ক্লিক করুন",
      validemail: "সঠিক ইমেল উল্লেখ করুন",
      blankemail: "ইমেল অ্যাডড্রেস খালি রাখবেন না",
      login: "সাবস্ক্রাইব করতে লগ ইন করুন",
      error: "সমস্যা নথিভুক্ত হয়েছে! আপনাকে আনসাবস্ক্রাইব না করতে অনুরোধ করা হচ্ছেడి",
    },
    popup: { related_videos: "সম্পর্কিত ভিডিয়ো" },
    social_download: {
      title: "এই সময় পড়ুন ও সব খবরের আপডেট পান",
      fblike: "ফেসবুক পেজ লাইক করুন।",
      appdownload: "অ্যাপ ডাউনলোড করুন",
      extrasharetxt: "\n\nঅ্যাপ ডাউনলোড করতে ক্লিক করুন: ",
      fblikeURL:
        "https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Feisamay.com%2Fdocs%2Fplugins%2F&width=87&layout=button_count&action=like&show_faces=false&share=false&height=21&appId=223044881622213",
    },
    share_popup_header: "শেয়ার করুন",
    read_more: "Read More...",
    read_less: "Read Less...",
    view_gallery_from_start: "শুরু থেকে গ্যালারি দেখুন",
    next_gallery: "পরবর্তী ফটো গ্যালারি",
    next_article: { moviereview: "পরের রিভিউ", articleshow: "পরের খবর", default: "পরের খবর", movieshow: "Next Movie" },
    next_topic: {
      more_all: "மேலும்",
      more_news: "மேலும் செய்திகள்",
      more_photos: "மேலும் புகைப்படங்கள்",
      more_videos: "மேலும் வீடியோக்கள்",
    },
    search_placeholder: "সার্চ করুন",
    highlight: "হাইলাইটস",
    orientation_heading: "ডিভাইসটি ঘুরিয়ে নিন",
    orientation_text: "আমরা এখনই ল্যান্ডস্কেপ মোডকে সাপোর্ট করছি না। আপনাকে পোর্ট্রেট মোডে ফিরে যেতে অনুরোধ করা হচ্ছে।",
    videos: "ভিডিয়ো",
    photo: "লেন্সবন্দি",
    related_videos: "সম্পর্কিত ভিডিয়ো",
    default_horizontal_tile_width: 133,
    default_slideshow_tile_width: 120,
    related_articles_horizontal_tile_width: 230,
    relatedarticle: "এই বিষয়ে আরও জানুন",
    wHeadingExitPoll: "எக்ஸிட் போல்",
    read_more_listing: " থেকে আরও",
    critics_review: "সমালোচকের রিভিউ",
    photomasti: "ফটো গ্যালারি",
    twitte_reaction: "ট্যুইটারে চর্চা",
    critics_rating: "সমালোচকের রেটিং",
    user_rating: "পাঠকের রেটিং",
    movie_review: "মুভি রিভিউ",
    film_review: "মুভি রিভিউ",
    review_movie: "রিভিউ লিখুন",
    review_device: "রিভিউ ডিভাইস",
    rate_movie: "রেটিং দিন",
    rate: "Rate",
    rate_recipe: "Rate Recipe",
    slide_to_rate: "Slide to Rate",
    slide_to_rate_movie: "রেটিং দিতে স্কেল স্লাইড করুন",
    reader_rating: "পাঠকের রেটিং",
    movie_review_tile_bg: "https://static.langimg.com/moviereview_list_bg/photo/65022261.cms",
    movie_review_detail_bg: "https://static.langimg.com/moviereview_list_bg/photo/65594589.cms",
    breaking_news: "ব্রেকিং নিউজ",
    trending: "ট্রেন্ডিং",
    highlightText: "সময় কম? ঝটিতি খবর পড়তে ডাউনলোড অ্যাপ",
    live_video: "লাইভ ভিডিয়ো",
    view_text: "দেখুন",
    aur_jaane: "আরও পড়ুন",
    oops: "দুঃখিত. ",
    thanks: "ধন্যবাদ",
    offlineText: "আপনি অফলাইন হয়েছেন।",
    onlineText: "এবার আপনি অনলাইন।",
    openinapp: "অ্যাপে দেখুন",
    superhit: " এই সেকশনের সুপারহিট",
    live_updates: "লাইভ আপডেট",
    fblikecardtext: "এই সময় ফেসবুক পেজ <br /> লাইক করুন ",
    appdownloadcardtext: "এই সময় অ্যাপের সঙ্গে <br/> যুক্ত হন",
    installapp: "ইনস্টল করুন",
    login: "লগ ইন",
    logout: "লগ আউট",
    amazonDeals: "দিনের সেরা ডিল",
    seemoreimages: "এমন আরও ফটো দেখুন",
    read_more_liveblog: "আরও পড়ুন",
    cast: "অভিনেতা: ",
    footerheading: "খবর এক ঝলকে",
    comment_text: "মন্তব্য করুন",
    download_text: "ডাউনলোড",
    write_comment: "মন্তব্য লিখুন",
    wp_broadcast: {
      description: "দিনের সেরা খবর এবার হোয়াটসঅ্যাপে",
      btnText: "সাবসক্রাইব",
      url: "https://widget.whatsbroadcast.com/widget_more/8531f3a382edfe5c49a332a5fb08a2aa/?show=walink&text=",
    },
    crossbrand: "এই খবরটি আগে hyperlink- এ- dl- তারিখে পাবলিশ হয়েছিল",
    appexclusive: "অ্যাপ এক্সক্লুসিভ",
    votesuccessfully: "আপনার ভোট গ্রহণ করা হয়েছে",
    votealready: "আপনি আগেই ভোট দিয়েছেন",
    submit_vote: "ভোট দিন",
    photoshow_app_install: { read_more: "আরও ফটো দেখতে অ্যাপ ইনস্টল করুন", download: "অ্যাপ ডাউনলোড করুন" },
    disclaimer: "ডিসক্লেইমার ",
    live_tv: "LIVE TV",
    data_hub: "ডেটা হাব",
    fantasy_game: "আপনি যখন অর্থমন্ত্রী",
    topics_no_result: "সার্চ সম্পর্কিত কোনও তথ্য মেলেনি",
    popularVideos: "সবচেয়ে আলোচিত ভিডিয়ো",
    players: "প্লেয়ার্স",
    utility: "ইউটিলিটি",
    appDownload: "EI Samay App",
    tech: {
      inIndia: "ভারতে দাম",
      loadmore: "আরও লোড ",
      rating: "রেটিং",
      sortby: "সর্ট বাই",
      clearall: "ক্লিয়ার অল",
      buyhere: "এখানে কিনুন",
      indiaLaunchDates: "ভারতে লঞ্চ",
      indiaPrice: "ভারতে দাম",
      compCriteria: "তুলনা শর্ত",
      showDiff: "পার্থক্য দেখান",
      alreadyAdded: "ইতিমধ্যেই গ্যাজেটটি সিলেক্ট করেছেন",
      buyFrom: "থেকে কিনুন",
      addDevice: "ডিভাইস অ্য়াড করুন",
      compare: "এর তুলনা",
      englishtype: "ইংরেজিতে টাইপ করুন",
      change: "পরিবর্তন",
      suggestedDevice: "প্রস্তাবিত ডিভাইস",
      pe: "এর",
      gadgets: "গ্যাজেটস",
      filtertxt: "ফিলটার্স",
      purchasehere: "স্পনসরড: ইন স্টোর",
      popular: "জনপ্রিয়",
      allbrands: "সব ব্র্যান্ড",
      brands: "ব্র্যান্ড",
      othervariants: "অন্য ভেরিয়ান্টস",
      criticsrating: "ক্রিটিক রেটিং",
      launchdate: "লঞ্চ জল্পনা",
      review: "রিভিউ",
      overview: "ওভারভিউ",
      userrating: "ইউজার রেটিং",
      comparedotxt: " তুলনা",
      submitrating: "সাবমিট রেটিং",
      addtocompare: "তুলনার জন্য যোগ করুন",
      purchase: "কিনুন",
      suggested: "প্রস্তাবিত",
      comparetxt: " তুলনা",
      latest: "লেটেস্ট",
      price: "দাম",
      rumoured: "জল্পনা",
      upcoming: "আসন্ন",
      ki: "অফ",
      relatedgadgets: "সম্পর্কিত গ্যাজেট",
      seemore: "আরও দেখুন",
      topfeature: "টপ ফিচার",
      fullspecification: "পুরো স্পেশিফিকেশনস",
      selectatleast2: "কমপক্ষে 2টো আইটেম বেছে নিন",
      devicealreadyinlist: "তুলনার জন্য ইতিমধ্যেই বাছাই করা",
      same_gadget: "একই ধরনের গ্যাজেট",
      user_review: "ইউজার রিভিউ",
      read_fullreview: "পুরো রিভিউ পড়ুন",
      similar_gadget: "একই ধরনের গ্যাজেটস",
      see_diff: "পার্থক্য দেখুন",
      latest_comparisons: "লেটেস্ট তুলনা",
      popular_comparisons: "জনপ্রিয় তুলনা",
      techNewsH1: "টেক নিউজ",
      minimumComparisonError: "তুুলনা করতে কমপক্ষে দুটো গ্যাজেটের প্রয়োজন",
      // gadgets show
      buyAtAmazon: "কিনুন",
      priceList: "দামের তালিকা",
      priceInIndia: "ভারতে দাম",
      criticReview: "ক্রিটিক রিভিউ",
      userReview: "ইউজার রিভিউ",
      specifications: "স্পেশিফিকেশনস",
      moreLikeThis: "এই ধরনের আরও",
      criticRating: "ক্রিটিকের রেটিং",
      userRating: "ইউজার রেটিং",
      user: "ইউজার",
      others: "অন্য",
      nextGadget: "পরবর্তী গ্যাজেট",
      similarGadgets: "একই ধরনের গ্যাজেট",

      readCompleteReview: "পুরো রিভিউ পড়ুন",
      readLess: "কম পড়ুন",

      recentlyCompared: "সাম্প্রতিক তুলনা",
      weak: "দুর্বল",
      belowAverage: "অ্যাভারেজের নীচে",
      worthpurchase: "ক্রয় যোগ্য",
      good: "ভালো",
      excellent: "দারুণ",
      thanksforreview: "রিভিউয়ের জন্য ধন্যবাদ",
      befirsttoreview: "প্রথম রিভিউ করুন",
      userreviewandrating: "ইউজার রিভিউ ও রেটিং",
      ratedevice: "রেড ডিভাইস",
      postRating: "পোস্ট রেটিং",
      readMoreReview: "আরও রিভিউ পড়ুন",
      varients: "অন্য ভেরিয়ান্টস",
      text_write_reviews: "রিভিউ লিখুন",
      text_view_comment: "View Comments",
      text_write_comment: "Write Comments",
      critic: "Critic",
      language: "Tech",
      category: [
        { keylabel: "মোবাইল ফোন", keyword: "mobile" },
        { keylabel: "ল্যাপটপ", keyword: "laptop" },
        { keylabel: "স্মার্টওয়াচ", keyword: "smartwatch", keylabelEng: "smart watch" },
        { keylabel: "টেলিভিশন", keyword: "tv" },
        { keylabel: "এয়ার কন্ডিশনার", keyword: "ac" },
        { keylabel: "ট্যাবলেট", keyword: "tablet" },
        { keylabel: "ক্যামেরা", keyword: "camera" },
        { keylabel: "ফিটনেস ব্যান্ড", keyword: "fitnessband", keylabelEng: "fitness band" },
        { keylabel: "ওয়াশিং মেশিন", keyword: "washingmachine", keylabelEng: "washing machine" },
        { keylabel: "রেফ্রিজেরেটর", keyword: "refrigerator", keylabelEng: "fridge" },
        { keylabel: "পাওয়ার ব্যাংক", keyword: "powerbank", keylabelEng: "power bank" },
      ],
      gadgetSliderConfig: {
        mobile: "মোবাইল ফোন",
        laptop: "ল্যাপটপ",
        tablet: "ট্যাবলেট",
        camera: "ক্যামেরা",
        smartwatch: "স্মার্টওয়াচ",
        fitnessband: "ফিটনেস ব্যান্ড",
        tv: "টেলিভিশন",
        ac: "এয়ার কন্ডিশনার",
        washingmachine: "ওয়াশিং মেশিন",
        refrigerator: "রেফ্রিজেরেটর",
        powerbank: "পাওয়ার ব্যাংক",
      },
      affiliateTags: {
        homePage: "eis_wap_home_latesttrendingwidget",
      },
    },
    top_headlines: "সেরা হেডলাইন",
    user_review: "User Review",
    listenAlbum: "Listen to this album",
    castncrew: "Cast & Crew",
    filmSongs: "Film Songs",
    read_movie_review: "read movie review",
    news: "খবর",
    photos: "ফটো",
    market: "বাজার",
    choseStateCity: { dropDownText: "শহর বেছে নিন", extraCityContent: "আপনার শহরের খবর পড়ুন" },
    cityPopUp: {
      selectStateCity: "রাজ্য ও শহর",
      selectCity: "শহর নির্বাচন করুন",
      save: "সাবমিট",
      state: "রাষ্ট্র",
      city: "শহর",
      readersCount: "এই সময়ে এর পাঠক সংখ্যা {{total}} লাখ (প্রায়)",
    },
    cityHeading: "আশপাশের শহরের খবর",
    cityHeadingVideo: "আশপাশের শহরের ভিডিয়ো",
    openInApp: {
      stayHere: "এখানেই থাকুন",
      openApp: "অ্যাপে খুলুন",
      mainText: "খবরটি অ্যাপেই পড়ুন",
      mainTextForVSnPS: "অ্যাপে দেখতে চান?",
    },
    authoraritcle: "এর আর্টিকেল",
    authorsharetext: "এর সঙ্গে অনলাইনে যোগাযোগ করুন",
    authorwebstories: " এর ওয়েব স্টোরিজ",
    authorabout: "এর বিষয়ে",
    articles: "আর্টিকেল",
    webstories: "ওয়েব স্টোরি",
    dailyNewsUpdate: "দৈনিক আপডেট পেতে লগ ইন করুন",
    downloadAppForNews: "রোজ খবরের আপডেট পেতে আমাদের অ্যাপ ডাউনলোড করুন",
    notificationTopNewsAlert: "খবর মিস করবেন না। নোটিফিকেশন পেতে অ্যালাও করুন",
    notification: "নোটিফিকেশন",
    others: "অন্য",
    authoraritcle: "এর আর্টিকেল",
    authorsharetext: "অনলাইনে যোগাযোগ করুন",
    authorwebstories: " এর ওয়েব স্টোরিজ",
    authorabout: "এর বিষয়ে",
    articles: "আর্টিকেল",
    webstories: "ওয়েব স্টোরি",
  },
  imageconfig: {
    thumbid: "67091961",
    liveblogthumb: "56295200",
    defaultthumb: "67091961",
    imagedomain: "https://static.langimg.com/thumb/",
    webimagedomain: "https://eisamay.com/thumb/",
    bigimage: "width=540&resizemode=3", // Article Inline Images, will maintain aspect ratio of original image
    big2ximage: "width=1080&resizemode=3", // Article Inline Images, will maintain aspect ratio of spotlight/paid article image
    smallthumb: "width=280&height=210&resizemode=75", // Listing small thumbs, Aspect Ratio 4:3
    smallslideshowthumb: "width=320&height=240&resizemode=1", // Used for external photogallery strip on top news, Aspect Ratio 4:3
    midthumb: "width=320&height=240&resizemode=75", // Photo Listing widget thumb, etc Aspect Ratio 4:3
    largethumb: "width=380&height=285&resizemode=75", // Lead Images Aspect Ratio 4:3
    amplargethumb: "width=1600&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only videoshow
    amplargethumbarticle: "width=1200&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only for article
    smallwidethumb: "width=200&height=111&resizemode=75", // For video listing widgets Aspect Ratio 16:9
    largewidethumb: "width=380&height=214&resizemode=75", // For videowidget lead image and videoshow Aspect Ratio 16:9
    posterthumb: "width=210&height=281&resizemode=4", // Moview Posters
    squarethumb: "width=200&height=200&resizemode=75", // for two colum layout
    rectanglethumb: "width=160&height=103&resizemode=75", // for rectangle flags
    gnthumb: "width=200&resizemode=4", // for Gadget now
    gnthumbWithHeight: "height=150&resizemode=4", // for GN PDP, need height
    webstoriesthumb: "width=300&height=500&resizemode=4", // web stories Photo Listing widget thumb
    webstoriesthumbLarge: "width=364&height=607&resizemode=4", // web stories Photo Listing widget thumb
    widecardthumb: "width=600&height=315&resizemode=6", // End Article Card thumb 16: 9",
  },
  sso: {
    BASE_URL: "https://eisamay.com",
    SSO_CHANNEL: "eisamaynew",
    GADGET_CHANNEL: "bengali-gadgetsnow-wap",
    stg: {
      BASE_URL: "https://langdev8358.indiatimes.com",
      MYTIMES_URL_USER: "https://mytest.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
      MYTIMES_URL_SETTINGS: "https://jssostg.indiatimes.com/sso/identity/profile/edit?channel=tm",
      SSO_URL_LOGIN: "https://jssostg.indiatimes.com/sso/identity/login",
      SSO_URL_LOGOUT: "https://jssostg.indiatimes.com/sso/identity/profile/logout/external",
      SSO_URL_GETTICKET: "https://jssostg.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
      SOCIAL_API_INTEGRATOR: "https://testsocialappsintegrator.indiatimes.com/socialsite/",
      SSO_BASE_URL: "https://jssostg.indiatimes.com/sso/crossdomain",
      SSO_CROSSWALK: "https://jssocdnstg.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
      SSO_WIDGET_URL: "https://jssocdnstg.indiatimes.com/crosswalk/133/widget/main.bundle.js",
    },

    SSO_BASE_URL: "https://jsso.indiatimes.com/sso/crossdomain",
    SSO_CROSSWALK: "https://jssocdn.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
    SSO_WIDGET_URL: "https://jssocdn.indiatimes.com/crosswalk/34/widget/main.bundle.min.js",
    MYTIMES_URL_USER: "https://myt.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
    MYTIMES_URL_SETTINGS: "https://jsso.indiatimes.com/sso/identity/profile/edit?channel=eisamay",
    SSO_URL_LOGIN: "https://jsso.indiatimes.com/sso/identity/login",
    SSO_URL_LOGOUT: "https://jsso.indiatimes.com/sso/identity/profile/logout/external",
    SSO_URL_GETTICKET: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
    MYTIMES_ALREADY_RATED: "https://myt.indiatimes.com/mytimes/alreadyRated?appKey=EIS&",
    MYTIMES_ADD_ACTIVITY: "https://myt.indiatimes.com/mytimes/addActivity?appKey=EIS&",
    SOCIAL_API_INTEGRATOR: "https://socialappsintegrator.indiatimes.com/socialsite/",
    SSO_TRUECALLER_visibility: 4,

    SSO_URL_NewsTicket: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1",
    SSO_URL_SubStatus: "https://webapi.sendpal.in/api/v1/get/user/es/status?dataformat=json",
    SSO_URL_unsubscribe: "https://webapi.sendpal.in/api/v1/multiple/unsubscribe/es?dataformat=json",
    SSO_URL_subscribe:
      "https://webapi.sendpal.in/api/v1/add/subscription/es?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=36",
    SSO_URL_confirm: "https://webapi.sendpal.in/api/v1/confirm/subscription/es?dataformat=json",
  },
  TimesPoint: {
    jsDev: "https://test.timespoint.com/tpwidgets-test/static/dist/js/main.js",
    jsProd: "https://image.timespoints.iimg.in/tpwidgets/static/dist/js/main.js",
    channels: ["tml", "nbt", "eisamay", "tlg"],
    // status: true,
    pcode: "ES",
    scode: "ES",
    activities: {
      DAILY_CHECKINS: "act8233833",
      DAILY_CHECKINS_MOBILE: "act8249918",
      READ_ARTICLE: "act9260204",
      WATCH_VIDEOS: "act1228232",
      SH_FB: "act3632033",
      SH_TW: "act3719642",
      LOGIN: "login",
      MOVIE_RATE: "act6485581",
      // Fired by MyProfile team
      MOVIE_REVIEW: "act6388443",
      VIEW_PHOTO: "act4262158",
      LIVE_BLOG: "act8382075",
      SUB_NL: "sub_nltr",
      REGISTER: "act8838785",
      // Fired by MyProfile team
      COMMENT: "act9400286",
      SUB_NOTIFICATION: "act8440462",
      // Not found for staging
      CHECKIN_BONUS_DESKTOP: "act8270932",
      // Not found for staging
      CHECKIN_BONUS_MOBILE: "act8288492",
      WHATSAPP_SHARE: "act8534378",
    },
    campaingHistoryName: {
      desktop: "campaign8159022",
      mobile: "campaign8244936",
    },
    campaignDays: 5,

    stg: {
      pcode: "ES",
      scode: "ES",
      campaingHistoryName: {
        desktop: "campaign8318878",
        mobile: "campaign9248175",
      },
      activities: {
        DAILY_CHECKINS: "act8039161",
        DAILY_CHECKINS_MOBILE: "act8075712",
        READ_ARTICLE: "read",
        WATCH_VIDEOS: "watch_video",
        SH_FB: "sh_fb",
        SH_TW: "sh_tw",
        LOGIN: "login",
        MOVIE_RATE: "act7848838",
        // Fired by MyProfile team
        MOVIE_REVIEW: "rv",
        VIEW_PHOTO: "view_photo",
        LIVE_BLOG: "act7893009",
        SUB_NL: "sub_nltr",
        REGISTER: "register",
        // Fired by MyProfile team
        COMMENT: "cmnt",
        SUB_NOTIFICATION: "act7958259",
        CHECKIN_BONUS_DESKTOP: "act8106907",
        CHECKIN_BONUS_MOBILE: "act8137720",
        WHATSAPP_SHARE: "act7983614",
      },
    },

    TP_FAQ_MSID: "79549078",
    NP_DOMAIN: {
      production: "https://npcoins.indiatimes.com",

      development: "https://nprelease.indiatimes.com",
      stg1: "https://nprelease.indiatimes.com",
      stg2: "https://nprelease.indiatimes.com",
    },

    TP_DOMAIN: {
      production: "https://tpapi.timespoints.com",

      development: "https://test.timespoints.com/tpapi",
      stg1: "https://test.timespoints.com/tpapi",
      stg2: "https://test.timespoints.com/tpapi",
    },

    SDK_DOMAIN: {
      production: "https://image.timespoints.iimg.in",

      development: "https://test-img.timespoints.com",
      stg1: "https://test-img.timespoints.com",
      stg2: "https://test-img.timespoints.com",
    },

    tpwidgetJS: {
      production: "/tpwidgets/dist/js/tpwidget.js",

      development: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg1: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg2: "/static/tpwidgets/static/dist/js/tpwidget.js",
    },

    //* * Moved to common config */
    tpPage: "/timespoints.cms",
    tpRedeemLink: "https://www.timespoints.com/products",
  },
  Comments: {
    appkey: "ES",
    topComments: {
      appkey: "ES",
      sortcriteria: "AgreeCount",
      order: "desc",
      size: "1",
      lastdeenid: "0",
      after: "true",
      withReward: "false",
      pagenum: "1",
    },
    allComments: {
      appkey: "ES",
      sortcriteria: "CreationDate",
      order: "asc",
      size: "6",
      lastdeenid: 0,
      after: true,
      withReward: false,
      pagenum: 1,
    },
  },
  // Gn config
  pages: {
    astro: "17335279",
    sports: "2279790",
    jokes: "12545605",
    business: "56687897",
    mktwdt: "87983731",
    education: "2279784",
    tech: "64760430",
    techreview: "64760842",
    automobile: "2355188",
    citizenreporter: "54234500",
    elections: "56662129",
    iplHomePage: "63298373",
    commonwealth: "63504985",
    fifa: "64415208",
    wcHomePage: "86753986",
    stateSection: "15819609",
    gadgethome: "83548976",
    budget: "67585497",
    budget_you: "97251257", // temp 80233871,97251257
  },
  iplpages: {
    venues: "63298406",
    teams: "63298412",
    pointsTable: "63298438",
    miniSchedule: "63298421",
  },
  t20wcpages: {
    venues: "86756886",
    teams: "86755743",
    pointsTable: "86754909",
    miniSchedule: "86754716",
  },
  redis: { host: "192.168.24.51", port: "6379", db: "1" },
  listNodeLabels: {
    articlelist: ["articlelist"],
    news: ["articleshow"],
    photo: ["photoshow"],
    slideshow: ["photoshow"],
    video: ["videoshow"],
    videolist: ["videolist"],
    photolist: ["photoarticlelist"],
    lb: ["liveblog", "লাইভ আপডেট"],
    moviereview: ["moviereview", "মুভি রিভিউ"],
    movieshow: ["movieshow", "মুভি"],
    poll: ["pollsurvey", "পোল"],
  },
  photoListView: "47882310",
  miniTvMoreVideos: "16683331",
  routes: [
    "/exitpolls/",
    "/results/",
    "/electionlist/",
    "education.cms",
    "business.cms",
    "elections.cms",
    "/articlelist/",
    "/photoarticlelist/",
    "/photoshow/",
    "/photomazaashow/",
    "/photomazaa/",
    "/articleshow/",
    "/moviereview/",
    "/movieshow/",
    "/liveblog/",
    "/videolist/",
    "/videoshow/",
    "/topics/",
    "/teams/",
    "/venues/",
    "/pointstable/",
    "/iplt20.cms",
    "/schedule/",
    "/sportsresult/",
    "/timespoints",
    "/us",
    "/bangladesh",
  ],
  staticPagesDir: "/var/www/html/testpages/",
  slike: {
    apikey: "eisamaymweb205lang",
    snapchatapikey: "lng54mweb5afm96lgz9",
    ampapikey: "lng205googleamp5a5qglkkg9",
    default_slikeid_minitv: "1x13qpaggu",
    nextvideo_domain: "https://mtpwafeeds.indiatimes.com",
    default_pl_videolist: "/feeds/videpostroll_v5_slike/50075780.cms?feedtype=json&callback=cached",
  },
  slikeAdCodes: {
    business: "15819574,50075800",
    cricket: "16570436",
    city: "15819618",
    editorial: "15819584",
    entertainment: "15819570,50075784",
    home: "2147477985",
    international: "15819594",
    lifestyle: "15992436",
    nation: "15819599",
    soccer: "15819590",
    sports: "23000116,50075792",
    state: "15819609",
    world: "15819594",
    rabibaroari: "20742861",
    kolkattewali: "20742872",
    ros: "other",
  },
  gRecaptchaKey: "6LfvEf8eAAAAAL-dR0Yk5Z3czRc7hDHMBphEDy8K",
  ga: {
    gtm: "GTM-MMFVDTG",
    gtm4: "G-8SEJPH2BK1",
    ampgtm: "GTM-MMFVDTG",
    gverifyCode: "aazPHkz9wF1xs6eEAk49ugaknkewzNLhvWhr_fyXOIM",
    gatrackid: "UA-29031733-3",
    ga4trackid: "G-8SEJPH2BK1",
    gaprofile:
      "['superpacer.in', 'atmadeep.com', 'womenbikerally.com','pujoeisamay.com', 'eisamay.com', 'esyoungscholars.com']",
  },
  growthrx: {
    stg: {
      id: "g6f837d7a",
    },
    prod: {
      id: "g88d79f6f",
    },
    gn: {
      stg: {
        id: "g1abf13ca",
      },
      prod: {
        id: "g34601eab",
      },
    },
  },
  appexclusive_ga: { category: "Wap to App install", action: "click", label: "articlelist_topsection" },
  poll: { link: "pollslist.cms" },
  poll_ga: {
    poll_submit: { category: "pollSurvey", action: "submit", label: "pollsubmit" },
    poll_result_loggedIn: { category: "pollSurvey", action: "viewresult", label: "loggedin" },
    poll_result_nonloggedIn: { category: "pollSurvey", action: "viewresult", label: "non-loggedin" },
  },
  photoshow_app_install: { active: true, show_slides: 6 },
  // sso_ga: {
  //   truecaller_requestscreen: { category: "True Caller", action: "Click", label: "Screen Request" },
  //   truecaller_screen: { category: "True Caller", action: "Click", label: "Screen View" },
  //   truecaller_screencontinue: { category: "True Caller", action: "Click", label: "Continue" },
  //   truecaller_skip: { category: "True Caller", action: "Click", label: "Skip" },
  //   truecaller_loginsuccess: { category: "True Caller", action: "Click", label: "Login Successful" },
  // },
  comscore: { c1: "2", c2: "6036484" },
  applinks: {
    android: {
      hrnav: "https://eisamay.onelink.me/kN2v/58c1940",
      asshow: "https://eisamay.onelink.me/kN2v/a585f036",
      photoshow: "https://eisamay.onelink.me/kN2v/f43994f2",
      serviceDrawer: "https://eisamay.onelink.me/kN2v/38a2b578",
      social: "https://eisamay.onelink.me/kN2v/27ab850",
      oip_appexclusive: "https://navbharattimes.indiatimes.com/off-url-forward/eis_openinapp.cms?msid=",
    },
  },
  appdeeplink: {
    domain: "https://eisamay.onelink.me",
    shortcode: "kN2v",
    c: "Internal_Campaign",
    pid: {
      hrnav: "WAP_HRNAV",
      serviceDrawer: "WAP_BOTTOM",
      news: "WAP_MWEB",
      article_end: "WAP_AS",
      photo: "WAP_PG",
      toparticle: "WAP_Top%20Articles",
      extphoto: "WAP_Home_Photostrip",
      photoshow: "WAP_Photoshow",
      campaign: "WAP_Election",
      campaignHome: "WAP_Election_Home",
      openinapp_as: "EIS_AS_Brandwire",
      openinapp_al: "EIS_AL_Brandwire",
      photofeature: "WAP_MWEB",
      recipe: "WAP_MWEB",
      videoshow: "WAP_VideoShow",
      topStrip: "WAP_Top_Strip",
      articlelist: "WAP_ArticleList",
      topStripAS: "New_Top",
      videolist: "WAP_VideoList",
      photolist: "WAP_PhotoList",
      continueInApp: "Continue_App",
      sharing: "WAP_Sitesharing",
    },
    listdefaultUrl: "https://eisamay.com/feeds/app_listing/<MSID>.cms?feedtype=json",
    openapp: "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay",
    opennews:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3Dnews-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openphoto:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openextphoto:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dp-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openhtmlview:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BURL%7D",
    opensection:
      "eisamayreaderactivities://open-%24%7C%24-pub%3D4:EI Samay-%24%7C%24-type%3Dsection-%24%7C%24-sectionID%3D%7BsectionID%7D-%24%7C%24-sectionName%3D%7BsectionName%7D-%24%7C%24-id%3D%7BMSID%7D",
    openphotofeature:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3DphotoFeature-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openrecipe:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3Drecipe-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openvideoshow:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%24%7C%24-type%3Dvideo-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openarticlelist:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dnews-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openphotolist:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dphoto-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openvideolist:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dvideo-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openContinueInApp:
      "eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D&af_web_dp=https%3A%2F%2Feisamay.indiatimes.com%2F&is_retargeting=true&deep_link_value=eisamayreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D4%3AEI%2520Samay-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
  },

  pushNotification: {
    cookieName: "notifypopup_es",
    defaultThumb: "https://static.langimg.com/thumb/55979511/pic.jpg?width=100&height=100",
    heading: " লেটেস্ট ও ব্রেকিং নিউজের নোটিফিকেশনের জন্য সাবস্ক্রাইব করুন। অনুমতি দিতে ক্লিক করুন",
  },
  weather: {
    geoLocationApi: "https://geoapi.indiatimes.com/?cb=1",
    defaultCity: "Kolkata",
    citiesJson: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_geocities.cms",
    weatherFeed: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_weathertoday.cms?lat=",
    heading: "আজকের তাপমাত্রা",
    cityText: "আপনার শহরের খবর",
  },
  pollution: {
    heading: "प्रदूषण",
    headingV1: "আজ শহরে দূষণ কেমন?",
    status: {
      good: "ভালো",
      moderate: "সাধারণ",
      unhelathfSG: "অসুস্থদের জন্য বেশি অস্বাস্থ্যকর",
      unhealthy: "অস্বাস্থ্যকর",
      veryUnhealthy: "অত্যন্ত অস্বাস্থ্যকর",
      hazardous: "বিপজ্জনক",
    },
    url: "https://eisamay.com/west-bengal-news/pollution/67589262.cms",
  },
  fuel: {
    heading: "फ्यूल",
    feedUrl: "https://toibnews.timesofindia.indiatimes.com/fuelprice/latestPrice",
  },
  oneTapSignIn: {
    smartlockurl: "https://smartlock.google.com/client",
    isViewGaTracked: false,
    eventGAObj: { hitType: "event", eventCategory: "Login", eventAction: "One_Tap", eventLabel: "" },
    text: {
      oneTapSuccessMsg: "আপনি সফলভাবে লগ ইন করেছেন",
      oneTapErrorMsg: "Oops! কোনও সমস্যা হয়েছে। দ্বিতীয়বার চেষ্টা করুন।",
      oneTapBtnText: "দ্বিতীয়বার চেষ্টা করুন",
    },
    constants: {
      onetapIgnoreDays: 15,
      onetapCookie: "oneTapNextShow",
      onetapIframeCheckTimer: 2000,
      smartlockJsLoadTimer: 10000,
      clientId: "879025834833-nqo8qbkj4rl86gi5m1q63vj8v5mignl6.apps.googleusercontent.com",
      channel: "eisamay-wap",
      jssoAPIGetURL: "https://jsso.indiatimes.com/sso/services/gponetaplogin/verify",
    },
  },
  cricplay_widget: {
    schedulelink: "/sports/cricket/icc-world-cup/schedule/69161420.cms",
    deeplink:
      "https://tamilsamayam.onelink.me/V28U?pid=WAP_CricPlay&c=Internal_Campaign&af_dp=tamilsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3Dhttps%3A%2F%2Fcrpl.app.link%2FZnAyOSBSxW&af_web_dp=https%3A%2F%2Ftamil.samayam.com",
    wincashtxt1: "আপনার প্রিয় ক্রিকেট দল তৈরি করুন এবং ",
    wincashtxt2: "অর্থ উপার্জন",
    appdwntxt: "ডাউনলোড ES অ্যান্ড্রয়েড অ্যাপ",
  },
  ZodiacSigns: {
    url: "#",
    data: [
      { name: "aries", regName: "মেষ", pos: 1 },
      { name: "taurus", regName: "বৃষ", pos: 2 },
      { name: "gemini", regName: "মিথুন", pos: 3 },
      { name: "cancer", regName: "কর্কট", pos: 4 },
      { name: "leo", regName: "সিংহ", pos: 5 },
      { name: "virgo", regName: "কন্যা", pos: 6 },
      { name: "libra", regName: "তুলা", pos: 7 },
      { name: "scorpio", regName: "বৃশ্চিক", pos: 8 },
      { name: "sagittarius", regName: "ধনু", pos: 9 },
      { name: "capricorn", regName: "মকর", pos: 10 },
      { name: "aquarius ", regName: "কুম্ভ", pos: 11 },
      { name: "pisces", regName: "মীন", pos: 12 },
    ],
  },
  ads: {
    ampInuxuAd:
      "https://adgebra.co.in/afpf/IBN_AMP.html?domain=amp-eisamay.indiatimes.com&pubid=3613&slotId=1&templateId=4654&accessMode=1&divId=div_407860734567731&cache=123",
    ampAdAfter: "",
    gptUrl: "",
    ctnAddress: "https://static.clmbtech.com/ad/commons/js/7270/colombia_v2.js",
    dmpUrl: "https://static.clmbtech.com/ase/7270/20/aa.js",
    isvPreRollUrl:
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/7176/ESMY_Mweb/ESMY_Mweb_Videoshow/ESMY_Mweb_Videoshow_ISV&description_url=https%3A%2F%2Feisamay.com%2F&tfcd=0&npa=0&sz=300x230%7C300x250%7C300x400%7C480x480%7C554x416%7C320x400&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
    dmpAmpCode: "13539:1217",
    ADS_PRIORITY: "FAN",
    profileid: "2930", // used NBT as of now
    exchangeId: "708743",
    ctnads: {
      inline: {
        ctnId: "205999",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },

      ctnlist: {
        ctnId: "205999",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnlistTop: "354475",
      ctnlist1: {
        ctnId: "205999",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      // "ctnlist": "320650",
      ctnpgl1: "339724",
      ctnpgl2: "339724",
      ctnvll1: "339722",
      ctnvll2: {
        ctnId: "339723",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_UPD_New_AL_INS2_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnbiglist: {
        ctnId: "322680",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_Direct_AL_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnsluglist: {
        ctnId: "355635",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_AL_INS_NEW_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listdefault: {
        ctnId: "205999",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listhorizontalsmall: {
        ctnId: "205999",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnmgid: "M787954ScriptRootC",
      ctnMmgid: "1277532",
      ctnBmgid: "1277534",
      ctnmgidurl: "https://jsc.mgid.com/t/i/til.eisamay.com",

      ctnshow: "323128",
      ctnmidart: "334313",
      ctnnative: "323127",
      ctnmidart_test: "", // for test page only requested by sales
      ctninlineshow: "208371",
      ctnrecommended: {
        ctnId: "205999",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnrhsvideo: "339725",
      ctnshowvideo: "334313", // video ad on articleshow
      ctnvs: "339722", // Video Show
      ampctnvs: {
        id: "337264",
        width: "320",
        height: "110",
        minHeights1: "188px",
        minHeights2: "188px",
        minHeights3: "188px",
        minHeights4: "188px",
      }, // Video Show AMP
      // "ctnhome" : "316371",  // caraousal ad code, just for test
      // "ctnhometop" : "206698",
      ctnhome: {
        ctnId: "205998",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefault: {
        ctnId: "205998",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefaultsmall: {
        ctnId: "205998",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontal: {
        ctnId: "205998",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homevertical: {
        ctnId: "205998",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontalsmall: {
        ctnId: "205998",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnhometop: "206705", // updated
      ctnhomevideo: "322378", // video ad , updated
      ctnbighome: {
        ctnId: "322679",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_Direct_HP_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      homeibeat: {
        ctnId: "205998",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },

      ctnslider: "210645",
      ctnVideoURL: "https://eisamay.com/ads_native_video_dev.cms",

      adspositionsPhoto: "-3-,-5-,-9-,-14-,-20-,-27-,-36-,-45-,-55-",
      ctnbigphoto: {
        ctnId: "322681",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_Direct_PG_Bid_Experiment_300",
        dfpSize: [300, 250],
      },

      ctnint: "324739",
      ctnint_test: "337410",
      adspositionsLiveblog: "-5-,-10-,-15-,-20-,-25-,-30-,-35-,-40-",
      ctncookievalue: "ce_aemsp",
      ctnbccl: "340358",

      ctntopicsall: {
        ctnId: "205999",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctntopicsnews: {
        ctnId: "205999",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctntopicsphotos: "339724",
      ctntopicsvideos: {
        ctnId: "339723",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Mweb_UPD_New_AL_INS2_Bid_Experiment_300",
        dfpSize: [300, 250],
      },

      ctntechlist: "335502", // Gadget Config
      ctnTechGL: "335502", // Gadget Config
      ctnTechPDP: "335506", // Gadget Config
      ctnTechCL: {
        ctnId: "357055",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Gadget_Mweb_ROS_PDP_INS_Bid_Experiment_300",
        dfpSize: [300, 250],
      }, // Gadget Config
      ctnTechCDP: "335506", // Gadget Config
      ctnTechTC: {
        ctnId: "357055",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Gadget_Mweb_ROS_PDP_INS_Bid_Experiment_300",
        dfpSize: [300, 250],
      }, // Gadget Config
      ctntechTop: "335508", // GN Config
      ctntechvideo: "335507", // GN Config
      ctntechoth: {
        ctnId: "357689",
        dfpSlot: "/7176/ESMY_Mweb/ESMY_Mweb_Bid_Experiment/ESMY_Gadget_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      }, // GN Config
      ctnInImage: "518953",
      ctnPreRoll: "518879",
    },
    // For ESI Ads
    ctnslots: {
      atf: "327960",
      ctnshow: "323122",
      ctnbiglist: "",
      ctnbigphoto: "",
      midart: "327959",
      articleshow: "ctnshow,atf,midart",
      liveblog: "",
      photoshow: "",
      videoshow: "",
      videolist: "",
    },
    dfpads: {
      adSiteName: "ESMY",
      adSiteShortName: "ESMY",
      topatf: "/7176/ESMY_Mweb/ESMY_MWeb_Others/ESMY_MWeb_ROS_OTH_Fixed",
      cubead1: "/7176/ESMY_Mweb/ESMY_MWeb_Others/ESMY_MWEB_OTH_CUBE_195x85",
      cubead2: "/7176/ESMY_Mweb/ESMY_MWeb_Others/ESMY_MWEB_OTH_CUBE2_195x85",
      cubeheadad1: "/7176/ESMY_Mweb/ESMY_MWeb_Others/ESMY_MWEB_OTH_CUBE_195x30",
      cubeheadad2: "/7176/ESMY_Mweb/ESMY_MWeb_Others/ESMY_MWEB_OTH_CUBE_195x30",
      cubeheadad3: "/7176/ESMY_Mweb/ESMY_MWeb_Others/ESMY_MWEB_OTH_CUBE2_195x30",
      cubeheadad4: "/7176/ESMY_Mweb/ESMY_MWeb_Others/ESMY_MWEB_OTH_CUBE2_195x30",
      andbeyond: "/7176/ESMY_Mweb/ESMY_MWEB_ROS/ES_Mweb_ROS_Andbeyond_1x1",
      inimage: "/7176/ESMY_Mweb/ESMY_MWEB_ROS/ESMY_Mweb_ROS_Inimage_1x1",
      multiplex: "/7176/ESMY_Mweb/ESMY_MWEB_ROS/ES_MWEB_ROS_Bottomwidget",
      canvasAd: "/7176/ESMY_Mweb/ESMY_MWEB_ROS/ESMY_Mweb_ROS_Mcanvas_1x1",
      interstitial: "ca-pub-1902173858658913",
      dfpint: "/7176/ESMY_Mweb/ESMY_Mweb_Home/ESMY_Mweb_HP_INT",
      trk: "/7176/ESMY_Mweb/ESMY_MWEB_ROS/ESMY_MWEB_ROS_trk_1x1",
      osv: "/7176/ESMY_Mweb/ESMY_MWEB_ROS/ESMY_MWEB_ROS_OUTSTREAM_1x1",
      sitesync: "/7176/ESMY_Mweb/ESMY_Mweb_Home/ES_Mweb_HP_SiteSync_1x1",
      nativead: "/7176/Languages/EIS_Mweb/EIS_Mweb_Native_300x250",
      nativeadamp: "/7176/Languages/EIS_AMP/EIS_AMP_Native_300x250",
      ampIntAd: "/7176/AMP_EIS_Mweb/AMP_EIS_Mweb_ROS/AMP_EIS_Mweb_ROS_INT",
      budgetSlug: "/7176/Eisamay/Budget/ES_BDGT_SLG",
      test1: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_1_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_1_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_1_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_1_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_1_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_1_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      test2: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_2_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_2_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_2_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_2_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_2_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Test/ESMY_MWeb_Test_2_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      others: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_ATF",
          size: [
            [300, 250],
            [320, 100],
            [320, 50],
            [336, 280],
            [250, 250],
            [300, 50],
          ],
        },
        btf: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_BTF",
          size: [
            [300, 250],
            [320, 50],
            [300, 50],
            [300, 75],
            [234, 60],
          ],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-2",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_FBN",
          size: [
            [320, 50],
            [300, 50],
          ],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_MREC1",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_Mrec2",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecinf",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_MrecINF",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        slug: {
          id: "div-gpt-ad-9135510865388-slug",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_Slug1",
          size: [
            [320, 100],
            [300, 100],
          ],
        },
        parallax: {
          id: "div-gpt-ad-9135510865388-parallax",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_FC",
          size: [[300, 600]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_Mrec3",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec4: {
          id: "div-gpt-ad-9135510865388-mrec4",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_Mrec4",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec5: {
          id: "div-gpt-ad-9135510865388-mrec5",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_Mrec5",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec7: {
          id: "div-gpt-ad-9135510865388-mrec7",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_Mrec7",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec6: {
          id: "div-gpt-ad-9135510865388-mrec6",
          name: "/7176/ESMY_Mweb/ESMY_Mweb_Others/ESMY_Mweb_Others_Mrec6",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        refreshNews: "/7176/ESMY_Mweb/ESMY_MWeb_News/ESMY_MWEB_News",
      },
    },
  },
  gold: {
    logoClass: "eisgold",
    redirectUrl:
      "https://eisamay.indiatimes.com/eisamaygold?utm_source=gold_navigation&utm_medium=mobile&utm_campaign=eisgold",
    goldNavigationApi: "https://eisamay.indiatimes.com/eisamaygold/esgoldsectiondata.cms?feedtype=sjson",
    homepagePodCastUrl: "https://eisamay.indiatimes.com/eisamaygold/podcastplayer.cms",
    goldTopNewsApi: "https://eisamay.indiatimes.com/eisamaygold/feeds/topnewslist.cms?feedtype=sjson",
  },
  plus: {
    disablePlus: true,
    logo: "https://static.langimg.com/thumb/85000251/tamil-samayam.jpg?height=36&resizemode=4",
    home: "84195947",
    video: "84195995",
    shortName: "EIS Plus",
    articleReferrerCd: 21,
    articleTypeCd: 19,
    homeText: "Home",
  },
  // dailyMotion: { channel: "eisamay", playerId: "x6k8s", syndication: "278257" },
  foryoupage: {
    cid: "7270:134",
    agencyFilters: ["ভাষা", "Brandwire", "SPOTLIGHT"],
  },
  authorDetails: {
    agencyName: "EiSamay.Com",
    authorName: "",
    editorLink: "",
    editorLabel: "",
  },
  cityLandingPage: "/west-bengal-news/articlelist/15819609.cms",
  timesXP: {
    hostName: "eis_xp",
    xpUrl: "https://eisfeed.timesxp.com/langapi",
    appUrl: "https://bengali.timesxp.com",
    wapCode: "bengaliTxp",
  },
  vdoAI: {
    isEnabled: true,
    scriptUrl: "//a.vdo.ai/core/v-eisamay-v0/vdo.ai.js",
    containerID: "v-eisamay-v0",
  },
  orgAddress: {
    addressLocality: "8th Floor, Rudramani, 1720 Lashkarhat, E.M. Bypass, Opposite Fortis Hospital, Kolkata, India",
    addressRegion: "West Bengal",
    postalCode: "700039",
  },
  cleoPlayer: {
    apikey: "lang-n9GgmFF518E5Bknb",
  },
};
