module.exports = {
  hostid: "287", // GN Config
  channelid: "696089404",
  mediawireslot: "13",
  wapsitename: "Samayam Malayalam",
  wapsiteregionalname: "സമയം മലയാളം",
  siteName: "malayalam.samayam.com",
  staticSiteName: "static.mly.indiatimes.com",
  fbIAcontentId: "1618522865080130",
  language: "Malayalam",
  languagemeta: "ml",
  channelCode: "ml",
  wapCode: "malayalam",
  gdprID: "MALAY",
  languagefullName: "Samayam Malayalam",
  iospackageid: "1437610958",
  androidpackage: "com.til.malayalamsamayam",
  deeplinkappid: "malayalamsamayamactivities",
  deeplinkpubid: "pub=7:Samayam Malayalam",
  iosapp_name: "Samayam Malayalam App",
  coronaId: "74459526",
  weburl: "https://malayalam.samayam.com",
  mweburl: "https://malayalam.samayam.com",
  gadgetdomain: "https://malayalam.gadgetsnow.com",
  etdomain: "https://malayalam.economictimes.com",
  mweburlgulf: "https://malayalam.samayam.com/gulf",
  ccaudId: "13542:217",
  ccaudAmp: "13542",
  ccaudIdAmp: "13542:1218",
  indexExchangeUrl: "//js-sec.indexww.com/ht/p/191952-217163869956181.js",
  pwtUrl: "//ads.pubmatic.com/AdServer/js/pwt/23105/3786",
  footerDesktopLink: "https://malayalam.samayam.com?mobile=no",
  cookieLessDomain: "https://static.mly.indiatimes.com",
  domain: "samayam.com",
  webdomain: "malayalam.samayam.com",
  mwebdomain: "malayalam.samayam.com",
  video: { rootId: "47329248", newsId: "97082584" },
  fbLive: "92082451",
  videoiconurl: "/video/videolist/47329248.cms",
  langnetstorageBasePath: "https://langnetstorage.indiatimes.com/langappfeeds",
  editTrendingMSID: "75174893",
  photogallerydomain: "photogallery.malayalam.samayam.com",
  google_site_verification: "6j2LiIEnVIeQivS9Z22g50jOqP1AnqnW9qx247OwWwc",
  twitterHdandler: "@SamayamM",
  logo: "mly-logo.jpg",
  logo_id: "https://static.langimg.com/thumb/78038850/malayalam-samayam.jpg?width=200&resizemode=4",
  logogn_id: "https://static.langimg.com/thumb/78038850/malayalam-samayam.jpg?width=200&resizemode=4",
  logoPathGadget: "https://static.langimg.com/thumb/83978682/malayalam-samayam.jpg?width=232&resizemode=4",
  googleNews: "https://news.google.com/search?for=malayalam+samayam&hl=ml&gl=IN&ceid=IN%3Aml",
  fb: "https://www.facebook.com/samayammalayalam",
  twitter: "https://twitter.com/SamayamM",
  gplus: "https://plus.google.com/112202535427426413527/about",
  youtubeUrl: "https://www.youtube.com/channel/UCozaoypPySB4MKUi19p2HDA",
  linkedInUrl: "",
  shoppingBag: "https://malayalam.samayam.com/best-deals-online?category=clothes?utm_source=social_panel",
  izooto: "",
  fullutm: "&utm_campaign=malayalammobile&utm_medium=referral",
  slikeshareutm: "utm_source=slikevideo&utm_medium=referral",
  telegramFollowLink: "https://telegram.me/samayammalayalam",
  shortutm: "ma2", // Using for micron
  icon: "https://malayalam.samayam.com/icons/malyalam.ico?v=1",
  breakingNewsFeedUrl: "https://langnetstorage.indiatimes.com/LANGBNews/malayalambnews.htm",
  fbsdkurl: "https://connect.facebook.net/ml_IN/sdk.js#xfbml=1&version=v3.0",
  fbpage: "https://www.facebook.com/samayammalayalam",
  livebloghpfeed: "",
  moreNews: "More News",
  moreNewsUrl: "https://malayalam.samayam.com/headlines.cms",
  glossaryLanding: "https://langnetstorage.indiatimes.com/langappfeeds/mly_glossarylist_business.htm",
  marketindices: "https://m.economictimes.com/mcoverage_langwidget.cms?language=MAL&type=indices&nofollow=true",
  marketcommodities: "https://m.economictimes.com/mcoverage_langwidget.cms?language=MAL&type=commodities&nofollow=true",
  livebloghostname: "malayalam", // Using to getch liveblog callback feed
  navfeedurl: "https://langnetstorage.indiatimes.com/langappfeeds/malayalam_navjson.htm",
  liveblogbnbewsurl: "",
  // logo_schema dimensi1on should be 600*60
  logo_schema: "https://static.langimg.com/thumb/66648013/malayalam-samayam.jpg?width=600&resizemode=4",
  logo_alt: "Samayam Malayalam - Malayalam News",
  siteid: "2147478019",
  fbpixelid: "",
  astrowidgetId: "61035114",
  bennett: "https://timesofindia.indiatimes.com/bennettjul2020_form_nbt_mweb.cms",
  fbappid: "1452558595050529",
  googleClientId: "961161019499-83ecofrdm4eg9btinnq5hnkkqj1kvqea.apps.googleusercontent.com",

  css:
    "$body-bgcolor:#fff;	$navbar-top-bgcolor:#fff;	$navbar-bg-color:#F5CC10;	$navbar-border-top:#c8cccb;	$navbar-border-shadow:#D8B40D;	$navbar-active-border-bottom-color:#000;	$navbar-link-color:#000;	$hamburger-bg-color:#747474;	$sidenav-bg-color:#fff;	$sidenav-color:#000;	$sidenav-border-bottom:#F5F5F5;	$sidenav-arrow-color:#D1D1D1;	$layer-bg:rgba(0,0,0,0.5);	$breadcrumb-home-color:#DA4848;	$card-border-bottom:#F5F5F5;	$card-bg-color:#8e8e93;	$card-text-color:#191919;	$card-date-color:#bababa;	$home-section-border-bottom:#f5f5f5;	$home-section-heading-border-bottom:#F5CC10;	$home-section-arrow-color:#000000;	$home-section-more-color:#858585;	$home-section-more-border:#CCCCCC;	$footer-background:#585858;	$footer-border-top:#333;	$footer-border-bottom:#7b7b7b;	$footer-heading-color:#e6e6e6;	$footer-text-color:#fff;	$footer-link-color:#d0d0d0;	$footer-trending-color:#95989a;	$footer-copyright-color:#d0d0d0;",
  fontContent:
    "@font-face {font-family: Noto Sans;src: url('https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.eot');src: url('https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.eot?#iefix') format('embedded-opentype'),url('https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.woff2') format('woff2'),url('https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.ttf') format('truetype');font-weight: normal;font-style: normal;font-display: optional;}",
  fontUrl: "https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.woff2",
  byelection:
    "https://langnetstorage.indiatimes.com/langappfeeds/nbt_section_election_mhfeeds_4.1.4.htm?feedtype=sjson",
  byelectionalt:
    "https://langnetstorage.indiatimes.com/langappfeeds/nbt_section_election_mhfeedssheet2_4.1.4.htm?feedtype=sjson",
  byelectionurl: "/elections/byelectionresult/71652864.cms",

  cricket_SIAPI: {
    minischedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_liupre_ml.json",
    schedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_ml.json",
    points_table: "https://toicri.timesofindia.indiatimes.com/jsons/stats/Standings/standing_%seriesid%.json",
    scoreboard: "https://toicri.timesofindia.indiatimes.com/jsons/%matchid%_ml.json",
    topPlayer: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/feed_topplayer.cms?feedtype=sjson",
  },

  techsectionID: {
    // GN Config
    latestGadgets: "81814336",
    trendingGadgets: "81814275",
    video: "70499318",
    photo: "",
  },

  locale: {
    comment: {}, // don't remove this
    appIconText: "ആപ്പ്",
    by_election: "നിയമസഭാ ഉപതെരഞ്ഞെടുപ്പ്",
    whatsapp_share: "Hey, you might find this interesting: ",
    latest: "ഏറ്റവും പുതിയ ",
    most_read: "Most Read",
    latest_video: "Latest Videos",
    latest_photo: "Latest Photos",
    see_in_app: "App-ൽ നോക്കൂ",
    see_in_app_details: "എല്ലാ ഫീച്ചേർഡ് ഫോട്ടോസും ആപ്പിലൂടെ കാണുക",
    live_blog: "ലൈവ് ബ്ലോഗ്‌",
    commentary: "Commentary",
    recommendednews: "Recommended News",
    appLinkText: "ഏറ്റവും പുതിയ മലയാളം വാര്‍ത്തകള്‍ അറിയാന്‍ ആപ്പ് ഡൗണ്‍ലോഡ് ചെയ്യുക",
    actors: "താരനിര",
    releaseDate: "റിലീസ് തീയതി",
    director: "സംവിധാനം",
    genre: "സിനിമ വിഭാഗം",
    duration: "ദൈര്‍ഘ്യം",
    readmore: "കൂടുതൽ",
    watchmore: "കാണുക",
    scorecard: "Scorecard",
    photo_maza: "ഫോട്ടോ മസ",
    key_words: "കൂടുതൽ വാർത്തകൾ",
    more_from_topics: "ടോപിക്കുകളില്‍ നിന്നും കൂടുതല്‍’",
    brief: {
      tooltip: "കൂടുതല്‍ വാര്‍ത്തകള്‍ ചുരുക്കത്തില്‍ വായിക്കാന്‍ ആപ്പ്  ഡൗണ്‍ലോഡ് ചെയ്യൂ! ",
      limitation_txt: "വാര്‍ത്തകള്‍ ചുരുക്കത്തില്‍ വായിക്കാന്‍",
    },
    newsLetter: {
      LS: "5236",
      thankyou: "നന്ദി",
      headerText: "പ്രധാനപ്പെട്ട ന്യൂസ് അപ്ഡേറ്റുകള്‍ ദിവസവും അറിയണോ?",
      joinIn: "ജോയിൻ ചെയ്യൂ",
      footerText: "മുകളിലുള്ള ബോക്സിൽ ഇമെയിൽ ഐഡി നൽകൂ, വാര്‍ത്തകള്‍ നിങ്ങളുടെ ഇൻബോക്സിലെത്തും",
      verification: "നിങ്ങളുടെ ഇമെയിൽ അഡ്രസിലേക്ക് വേരിഫിക്കേഷന്‍ മെയിൽ അയച്ചിട്ടുണ്ട്.",
      already: "നിങ്ങള്‍ നേരത്തെ തന്നെ ന്യൂസ് ലെറ്റര്‍ സബ്സ്ക്രൈബ് ചെയ്തിട്ടുണ്ട് ",
      Subscribed: "നിങ്ങള്‍ സബ്സ്ക്രൈബ് ചെയ്തിരിക്കുന്നു",
      errorNetwork: "നെറ്റ്‌വർക്കിൽ എന്തോ പ്രശ്നമുണ്ട്! വീണ്ടും ശ്രമിക്കുക!",
      notverified: "നിങ്ങള്‍ ഇമെയിൽ അയച്ചിട്ടുണ്ട്. വേരിഫൈ ചെയ്യൂ!",
      verified: "നിങ്ങള്‍ നേരത്തെ തന്നെ വേരിഫൈ ചെയ്തിട്ടുണ്ട്.",
      unchecked: "ചെക്ക് ബോക്സ് തെരഞ്ഞെടുക്കൂ",
      validemail: "ശരിയായ ഇമെയിൽ അഡ്രസ് നൽകൂ (example@domain.com)",
      blankemail: "ഇമെയിൽ അഡ്രസ് നൽകേണ്ട കോളം ഒഴിവാക്കിയിടാൻ കഴിയുകയില്ല.",
      login: "സബ്സ്ക്രൈബ് ചെയ്യാൻ ലോഗിൻ ചെയ്യൂ",
      players: "താരങ്ങള്‍",
      error: "പ്രശ്നം കണ്ടെത്തി! പഴയ മെയിലറിൽ നിന്ന് നിങ്ങള്‍ അണ്‍ സബ്സ്ക്രൈബ് ചെയ്തിട്ടില്ലെന്ന് ഉറപ്പാക്കൂ!",
    },
    popup: {
      related_videos: "അനുബന്ധ വീഡിയോകൾ",
    },
    social_download: {
      title: "വാര്‍ത്തകള്‍ ഉടനറിയൂ, സമയം മലയാളത്തിനൊപ്പം",
      fblike: "ഫേസ്ബുക്ക് പേജ് ലൈക്ക് ചെയ്യുക",
      appdownload: "ആപ്പ് ഡൌണ്‍ലോഡ് ചെയ്യൂ",
      extrasharetxt: " \n\nഡൗണ്‍ലോഡ് ചെയ്യാനും ആപ്പില്‍ വായിക്കാനുമായി ക്ലിക്ക് ചെയ്യൂ: ",
      fblikeURL:
        "https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fsamayammalayalam%2F&width=79&layout=button_count&action=like&size=small&show_faces=false&share=false&height=21&appId=505830642956378",
    },
    share_popup_header: "ഷെയര്‍ ചെയ്യൂ",
    read_more: "കൂടുതല്‍ വായിക്കൂ",
    read_less: "കുറച്ചു വായിക്കൂ",
    view_gallery_from_start: "ഗ്യാലറി തുടക്കം മുതൽ കാണുക",
    next_gallery: "അടുത്ത ഗാലറി",
    next_article: {
      moviereview: "മൂവി റിവ്യൂ",
      articleshow: "ആര്‍ട്ടിക്കിള്‍ ഷോ",
      default: "ഡിഫോള്‍ട്ട്",
      movieshow: "Next Movie",
    },
    next_topic: {
      more_all: "കൂടുതൽ",
      more_news: "കൂടുതൽ വാര്‍ത്തകള്‍",
      more_photos: "കൂടുതൽ ഫോട്ടോസ്",
      more_videos: "കൂടുതൽ വീഡിയോസ്",
    },
    search_placeholder: "തെരയൂ",
    highlight: "ഹൈലൈറ്റ്:",
    orientation_heading: "ഡിവൈസ് തിരിച്ചു പിടിക്കൂ",
    orientation_text: "ലാന്‍ഡ്‌സ്കേപ്പ് മോഡ് സപ്പോര്‍ട്ട് ചെയ്യുന്നില്ല, ദയവായി പോര്‍ട്രയിറ്റ് മോഡില്‍ ഉപയോഗിക്കൂ",
    videos: "വീഡിയോസ്",
    photo: "ഫോട്ടോസ്",
    related_videos: "അനുബന്ധ വീഡിയോകള്‍",
    most_viewed_videos: "കൂടുതൽ പേര്‍ കണ്ട വീഡിയോസ്",
    cast: "താരനിര: ",
    photomasti: "PHOTO GALLERY",
    user_rating: "വായനക്കാരുടെ റേറ്റിങ്",
    view_comment: "പ്രതികരണങ്ങള്‍",
    text_topcomment: "മികച്ച പ്രതികരണം",
    text_latestcomment: "ഏറ്റവും പുതിയ പ്രതികരണം",
    text_author_comment: "എഴുത്തുകാരന്‍റെ കമന്‍റ്",
    topics_no_result: "ബന്ധപ്പെട്ട വിവരങ്ങളൊന്നും ലഭ്യമല്ല",
    default_horizontal_tile_width: 133, // These widths are used for slider
    default_slideshow_tile_width: 120,
    related_articles_horizonal_tile_width: 230,
    relatedarticle: "അനുബന്ധ ലേഖനങ്ങള്‍",
    read_more_listing: " കൂടുതല്‍",
    critics_review: "ക്രിട്ടിക്സ് റിവ്യൂ",
    twitte_reaction: "ട്വിറ്റര്‍ റിയാക്ഷന്‍",
    critics_rating: "ക്രിട്ടിക്സ് റേറ്റിങ്",
    movie_review: "മൂവി റിവ്യൂ",
    film_review: "ഫിലിം റിവ്യൂ",
    review_movie: "മൂവി റിവ്യൂ ചെയ്യുക",
    review_device: "ഡിവൈസ് റിവ്യൂ ചെയ്യുക",
    rate_movie: "നിങ്ങളുടെ റേറ്റിങ്ങ്",
    rate: "Rate",
    rate_recipe: "Rate Recipe",
    slide_to_rate: "Slide to Rate",
    slide_to_rate_movie: "സിനിമ റേറ്റ് ചെയ്യാനായി സ്ലൈഡ് ചെയ്യൂ",
    reader_rating: "വായനക്കാരുടെ റേറ്റിങ്",
    movie_review_tile_bg: "https://static.langimg.com/moviereview_list_bg/photo/65022261.cms",
    movie_review_detail_bg: "https://static.langimg.com/moviereview_list_bg/photo/65594589.cms",
    breaking_news: "ബ്രേക്കിങ് ന്യൂസ്",
    trending: "ട്രെൻഡിങ്",
    live_video: "ലൈവ് വീഡിയോ", // Using for minitv widget
    view_text: "കാണൂ!",
    aur_jaane: "കൂടുതല്‍ അറിയാന്‍",
    oops: "oops…!!!",
    thanks: "നന്ദി",
    offlineText: "നിങ്ങള്‍ ഓഫ്ലൈന്‍",
    onlineText: "നിങ്ങള്‍ ഓണ്‍ലൈന്‍ ആയിരിക്കുന്നു",
    highlightText: "ഹൈലൈറ്റ്സിനായി ആപ്പ് ഡൗൺലോഡ് ചെയ്യൂ!",
    openinapp: "Open App",
    superhit: " ഏറ്റവും കൂടുതല്‍ പേര്‍ വായിച്ചവ",
    live_updates: "ലൈവ് അപ്ഡേറ്റ്",
    fblikecardtext: "സമയം മലയാളം ഫേസ്ബുക്ക് <br/> പേജ് ലൈക്ക് ചെയ്യുക", // Using in Service Drawer
    appdownloadcardtext: "അപ്ഡേറ്റഡായിരിക്കൂ, സമയം <br /> മലയാളത്തിനൊപ്പം!", // Using in Service Drawer
    installapp: "ഇന്‍സ്റ്റാള്‍ ചെയ്യുക",
    login: "ലോഗിന്‍",
    logout: "ലോഗൗട്ട്",
    amazonDeals: "ഡീൽസ് ഓഫ് ദി ഡേ",
    seemoreimages: "കൂടുതല്‍ ചിത്രങ്ങള്‍", // Using in Photomazzashow
    read_more_liveblog: "കൂടുതല്‍ വായിക്കൂ",
    footerheading: "സമയം മലയാളം",
    comment_text: "കമന്റ് ചെയ്യൂ",
    download_text: "Download App",
    write_comment: "കമന്റ് ചെയ്യൂ",
    wp_broadcast: {
      description: "ഇന്നത്തെ പ്രധാന വാര്‍ത്ത വാട്സാപ്പില്‍ അറിയൂ",
      btnText: "സബ്സ്ക്രൈബ്",
      url: "https://widget.whatsbroadcast.com/widget_more/b1600181418ab41ffc6e0275e17c7d5f/?show=walink&text=",
    },
    crossbrand: "ഈ വാര്‍ത്ത ആദ്യം -hyperlink- ല്‍ -dl- പ്രസിദ്ധീകരിക്കപ്പെട്ടിരിക്കുന്നു",
    appexclusive: "App Exclusive",
    votesuccessfully: "നിങ്ങള്‍ വോട്ടു ചെയ്തിരിക്കുന്നു",
    votealready: "മുന്‍പേ തന്നെ വോട്ടു രേഖപ്പെടുത്തിയിട്ടുണ്ട്",
    submit_vote: "വോട്ട്",
    photoshow_app_install: {
      read_more: "കൂടുതല്‍ വായിക്കൂ",
      download: "Download App",
    },
    disclaimer: "നിരാകരണവ്യവസ്ഥ",
    live_tv: "LIVE TV",
    data_hub: "Budget Data Hub",
    fantasy_game: "Budget Fantasy Game",
    popularVideos: "Popular Videos",
    utility: "Utility",
    appDownload: "Malayalam Samayam App",
    tech: {
      inIndia: "ഇന്ത്യയിലെ വില",
      loadmore: "കൂടൂതൽ ലോഡ് ചെയ്യൂ",
      rating: "റേറ്റിങ്",
      sortby: "ഇപ്രകാരം തരംതിരിക്കൂ",
      clearall: "നീക്കുക",
      buyhere: "ഇവിടെ വാങ്ങാം",
      indiaLaunchDates: "ഇന്ത്യയിലെ ലോഞ്ച് തിയ്യതി",
      indiaPrice: "ഇന്ത്യയിലെ വില",
      compCriteria: "താരതമ്യം ചെയ്യുന്ന മാനദണ്ഡം",
      showDiff: "വ്യത്യാസം മാത്രം കാണിക്കുക",
      alreadyAdded: "ഈ ഗാഡ്ജറ്റ് നേരത്തെ തന്നെ തെരഞ്ഞെടുത്തു",
      buyFrom: "വാങ്ങുക",
      addDevice: "ഉപകരണം ആഡ് ചെയ്യുക",
      compare: "താരതമ്യം ചെയ്യുക",
      englishtype: "ഇംഗ്ലീഷിൽ ടൈപ്പ് ചെയ്യുക",
      change: "മാറ്റുക",
      suggestedDevice: "നിര്‍ദ്ദേശിക്കപ്പെട്ട ഉപകരണങ്ങള്‍",
      pe: "पर",
      gadgets: "ഗാഡ്ജറ്റുകള്‍",
      filtertxt: "ഫിൽറ്ററുകള്‍",
      purchasehere: "സ്പോണ്‍സര്‍ ചെയ്തത് : ഇൻ സ്റ്റോര്‍",
      popular: "പോപ്പുലര്‍",
      allbrands: "എല്ലാ ബ്രാൻഡുകളും",
      brands: "ബ്രാൻഡ്",
      othervariants: "മറ്റു വേരിയന്‍റുകള്‍",
      criticsrating: "ക്രിട്ടിക് റേറ്റിങ്",
      launchdate: "ലോഞ്ച് ഡേറ്റ് അഭ്യൂഹം",
      review: "റിവ്യൂ",
      overview: "ഓവര്‍വ്യൂ",
      userrating: "യൂസര്‍ റേറ്റിങ്",
      comparedotxt: "താരതമ്യം ചെയ്യുക",
      submitrating: "റേറ്റിങ് സമര്‍പ്പിക്കുക",
      addtocompare: "താരതമ്യം ചെയ്യാൻ ചേര്‍ക്കുക",
      purchase: "വാങ്ങുക",
      suggested: "നിര്‍ദ്ദേശിക്കപ്പെട്ടത്",
      comparetxt: "താരതമ്യം",
      latest: "ലേറ്റസ്റ്റ്",
      price: "വില",
      rumoured: "അഭ്യൂഹം",
      upcoming: "ഉടന്‍ വരുന്നത്",
      ki: "ന്‍റെ",
      relatedgadgets: "ബന്ധപ്പെട്ട മറ്റു ഗാ‍ഡ്ജറ്റുകള്‍",
      seemore: "കൂടുതൽ കാണുക",
      topfeature: "ടോപ് ഫീച്ചറുകള്‍",
      fullspecification: "മുഴുവന്‍ സ്പെസിഫിക്കേഷനുകളും കാണുക",
      selectatleast2: "കുറഞ്ഞത് 2 എണ്ണം തെരഞ്ഞെടുക്കുക",
      devicealreadyinlist: "ഇത് നേരത്തെ തന്നെ താരതമ്യം ചെയ്യാനായി തെരഞ്ഞെടുത്തിട്ടുണ്ട്",
      same_gadget: "സമാനമായ ഗാ‍‍ഡ്ജറ്റുകള്‍",
      user_review: "യൂസര്‍ റിവ്യൂ",
      read_fullreview: "മുഴുവന്‍ റിവ്യൂ വായിക്കുക",
      similar_gadget: "സമാനമായ ഗാഡ്ജറ്റുകള്‍",
      see_diff: "വ്യത്യാസം കാണുക",
      latest_comparisons: "അടുത്തിടെ താരതമ്യം ചെയ്തത്",
      popular_comparisons: "പോപുലര്‍ താരതമ്യം",
      techNewsH1: "ടെക്നോളജി വാര്‍ത്ത",
      minimumComparisonError: "താരതമ്യം ചെയ്യാൻ കുറഞ്ഞത് 2 ഗാഡ്ജറ്റുകളെങ്കിലും തെരഞ്ഞെടുക്കുക",
      // gadgets show
      buyAtAmazon: "ആമസോണിൽ നിന്ന് വാങ്ങൂ",
      priceList: "വിലപ്പട്ടിക",
      priceInIndia: "ഇന്ത്യയിലെ വില",
      criticReview: "ക്രിട്ടിക്ക് റിവ്യൂ",
      userReview: "യൂസര്‍ റിവ്യൂ",
      specifications: "സ്പെസിഫിക്കേഷനുകള്‍",
      moreLikeThis: "സമാനമായവ",
      criticRating: "ക്രിട്ടിക്ക് റേറ്റിങ്",
      userRating: "യൂസര്‍ റേറ്റിങ്",
      user: "യൂസര്‍",
      others: "മറ്റുള്ളവ",
      nextGadget: "അടുത്ത ഗാഡ്ജറ്റ്",
      similarGadgets: "സമാനമായ ഗാഡ്ജറ്റുകള്‍",

      readCompleteReview: "മുഴുവന്‍ റിവ്യൂ വായിക്കുക",
      readLess: "കുറച്ച് വായിക്കുക",

      recentlyCompared: "അടുത്തിടെ താരതമ്യം ചെയ്തത്",
      weak: "മോശം",
      belowAverage: "ശരാശരിയിലും താഴെ",
      worthpurchase: "വാങ്ങാവുന്നത്",
      good: "നല്ലത്",
      excellent: "വളരെ മികച്ചത്",
      thanksforreview: "റിവ്യൂ ചെയ്തതിന് നിങ്ങള്‍ക്ക് നന്ദി",
      befirsttoreview: "റിവ്യൂ ചെയ്യുന്ന ആദ്യത്തെ ആളാകം",
      userreviewandrating: "യൂസര്‍ റിവ്യൂകളും റേറ്റിങും",
      ratedevice: "ഡിവൈസിനെ റേറ്റ് ചെയ്യാം",
      postRating: "നിങ്ങളുടെ റേറ്റിങ് പോസ്റ്റ് ചെയ്യുക",
      readMoreReview: "കൂടുതൽ റിവ്യൂ വായിക്കാം",
      varients: "മറ്റു വേരിയന്‍റുകള്‍",
      text_write_reviews: "റിവ്യൂ എഴുതാം",
      text_view_comment: "View Comments",
      text_write_comment: "Write Comments",
      critic: "Critic",
      language: "Tech",
      category: [
        { keylabel: "മൊബൈൽ", keyword: "mobile" },
        { keylabel: "ലാപ്ടോപ്", keyword: "laptop" },
        { keylabel: "സ്മാര്‍ട്ട് വാച്ച്", keyword: "smartwatch", keylabelEng: "smart watch" },
        { keylabel: "ടെലിവിഷന്‍", keyword: "tv" },
        { keylabel: "എയര്‍ കണ്ടീഷണര്‍", keyword: "ac" },
        { keylabel: "ടാബ്ലറ്റ്", keyword: "tablet" },
        { keylabel: "ക്യാമറ", keyword: "camera" },
        { keylabel: "ഫിറ്റ്നസ് ബാന്‍ഡ്", keyword: "fitnessband", keylabelEng: "fitness band" },
        { keylabel: "വാഷിങ് മെഷീന്‍", keyword: "washingmachine", keylabelEng: "washing machine" },
        { keylabel: "റഫ്രിജറേറ്റര്‍", keyword: "refrigerator", keylabelEng: "fridge" },
        { keylabel: "പവര്‍ ബാങ്ക്", keyword: "powerbank", keylabelEng: "power bank" },
      ],
      gadgetSliderConfig: {
        mobile: "മൊബൈൽ",
        laptop: "ലാപ്ടോപ്",
        tablet: "ടാബ്ലറ്റ്",
        camera: "ക്യാമറ",
        smartwatch: "സ്മാര്‍ട്ട് വാച്ച്",
        fitnessband: "ഫിറ്റ്നസ് ബാന്‍ഡ്",
        tv: "ടെലിവിഷന്‍",
        ac: "എയര്‍ കണ്ടീഷണര്‍",
        washingmachine: "വാഷിങ് മെഷീന്‍",
        refrigerator: "റഫ്രിജറേറ്റര്‍",
        powerbank: "പവര്‍ ബാങ്ക്",
      },
      affiliateTags: {
        homePage: "mly_wap_home_latesttrendingwidget",
      },
    },
    top_headlines: "Top Headlines",
    user_review: "User Review",
    listenAlbum: "Listen to this album",
    castncrew: "Cast & Crew",
    filmSongs: "Film Songs",
    read_movie_review: "read movie review",
    news: "വാർത്ത",
    photos: "Photos",
    market: "വിപണി",
    choseStateCity: {
      dropDownText: "ജില്ല തെരഞ്ഞെടുക്കുക",
      extraCityContent: "നിങ്ങളുടെ ജില്ലയിലെ വാര്‍ത്തകള്‍ വായിക്കൂ",
    },
    cityPopUp: {
      selectStateCity: "സംസ്ഥാനവും നഗരവും",
      selectCity: "നഗരം തിരഞ്ഞെടുക്കുക",
      save: "സേവ് ചെയ്യുക",
      state: "സംസ്ഥാനം",
      city: "സിറ്റി",
      readersCount: "സമയം മലയാളത്തിന് {{total}} ലക്ഷം + വായനക്കാരുണ്ട്",
    },
    cityHeading: "സമീപ നഗരങ്ങളിലെ വാര്‍ത്ത",
    cityHeadingVideo: "സമീപ നഗരങ്ങളിലെ വീഡിയോ",
    openInApp: {
      stayHere: "ഇവിടെ തുടരുക",
      openApp: "ആപ്പ് തുറക്കുക",
      mainText: "ആര്‍ട്ടിക്കിള്‍ ആപ്പിൽ തുടര്‍ന്ന് വായിക്കണോ?",
      mainTextForVSnPS: "ആപ്പിൽ തുടര്‍ന്ന് കാണണോ?",
    },
    players: "താരങ്ങള്‍",
    authoraritcle: "ലേഖനങ്ങൾ",
    authorwebstories: " നെ കുറിച്ച് ",
    authorsharetext: "ഓൺലൈനിൽ ബന്ധപ്പെടുക",
    authorabout: "നെ കുറിച്ച് ",
    articles: "ആർട്ടിക്കിൾ",
    webstories: "വെബ് സ്റ്റോറി",
    dailyNewsUpdate: "ദിവസേനയുള്ള വാർത്തകൾക്കായി ലോഗിൻ ചെയ്യുക",
    downloadAppForNews: "ദിവസേനെയുള്ള വാർത്ത അപ്‌ഡേറ്റിനായി നമ്മുടെ ന്യൂസ് ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക",
    notificationTopNewsAlert:
      "ഒരു വാർത്തയും ഇപ്പോൾ നഷ്ടപ്പെടുത്തരുത്. നോട്ടിഫിക്കേഷനുകൾ ലഭിക്കൻ സബ്‌സ്‌ക്രൈബിൽ ക്ലിക്ക് ചെയ്യുക",
    notification: "അറിയിപ്പ്",
    others: "മറ്റുള്ളവ",
  },
  imageconfig: {
    thumbid: "67415762",
    liveblogthumb: "56295200",
    defaultthumb: "67415762",
    imagedomain: "https://static.langimg.com/thumb/",
    webimagedomain: "https://malayalam.samayam.com/thumb/",
    bigimage: "width=540&resizemode=3", // Article Inline Images, will maintain aspect ratio of original image
    big2ximage: "width=1080&resizemode=3", // Article Inline Images, will maintain aspect ratio of spotlight/paid article image
    smallthumb: "width=280&height=210&resizemode=75", // Listing small thumbs, Aspect Ratio 4:3
    smallslideshowthumb: "width=320&height=240&resizemode=1", // Used for external photogallery strip on top news, Aspect Ratio 4:3
    midthumb: "width=320&height=240&resizemode=75", // Photo Listing widget thumb, etc Aspect Ratio 4:3
    largethumb: "width=380&height=285&resizemode=75", // Lead Images Aspect Ratio 4:3
    amplargethumb: "width=1600&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only videoshow
    amplargethumbarticle: "width=1200&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only for article
    smallwidethumb: "width=200&height=111&resizemode=75", // For video listing widgets Aspect Ratio 16:9
    largewidethumb: "width=380&height=214&resizemode=75", // For videowidget lead image and videoshow Aspect Ratio 16:9
    posterthumb: "width=210&height=281&resizemode=4", // Moview Posters
    squarethumb: "width=200&height=200&resizemode=75", // for two colum layout
    rectanglethumb: "width=160&height=103&resizemode=75", // for rectangle flags
    gnthumb: "width=200&resizemode=4", // for Gadget now
    gnthumbWithHeight: "height=150&resizemode=4", // for GN PDP, need height
    webstoriesthumb: "width=300&height=500&resizemode=4", // web stories Photo Listing widget thumb
    webstoriesthumbLarge: "width=364&height=607&resizemode=4", // web stories Photo Listing widget thumb
    widecardthumb: "width=600&height=315&resizemode=6", // End Article Card thumb 16: 9",
  },
  sso: {
    BASE_URL: "https://malayalam.samayam.com",
    SSO_CHANNEL: "ml-wap",
    GADGET_CHANNEL: "malayalam-gadgetsnow-wap",
    stg: {
      BASE_URL: "https://jstgmalayalam.samayam.com",
      MYTIMES_URL_USER: "https://mytest.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
      MYTIMES_URL_SETTINGS: "https://jssostg.indiatimes.com/sso/identity/profile/edit?channel=tm",
      SSO_URL_LOGIN: "https://jssostg.indiatimes.com/sso/identity/login",
      SSO_URL_LOGOUT: "https://jssostg.indiatimes.com/sso/identity/profile/logout/external",
      SSO_URL_GETTICKET: "https://jssostg.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
      SOCIAL_API_INTEGRATOR: "https://testsocialappsintegrator.indiatimes.com/socialsite",
      SSO_BASE_URL: "https://jssostg.indiatimes.com/sso/crossdomain",
      SSO_CROSSWALK: "https://jssocdnstg.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
      SSO_WIDGET_URL: "https://jssocdnstg.indiatimes.com/crosswalk/133/widget/main.bundle.js",
    },

    SSO_BASE_URL: "https://jsso.indiatimes.com/sso/crossdomain",
    SSO_CROSSWALK: "https://jssocdn.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
    SSO_WIDGET_URL: "https://jssocdn.indiatimes.com/crosswalk/34/widget/main.bundle.min.js",
    MYTIMES_URL_USER: "https://myt.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
    MYTIMES_URL_SETTINGS: "https://jsso.indiatimes.com/sso/identity/profile/edit?channel=ml",
    SSO_URL_LOGIN: "https://jsso.indiatimes.com/sso/identity/login",
    SSO_URL_LOGOUT: "https://jsso.indiatimes.com/sso/identity/profile/logout/external",
    SSO_URL_GETTICKET: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
    MYTIMES_ALREADY_RATED: "https://myt.indiatimes.com/mytimes/alreadyRated?appKey=Malayalam&",
    MYTIMES_ADD_ACTIVITY: "https://myt.indiatimes.com/mytimes/addActivity?appKey=Malayalam&",
    SOCIAL_API_INTEGRATOR: "https://socialappsintegrator.indiatimes.com/socialsite",
    SSO_TRUECALLER_visibility: 4,

    SSO_URL_NewsTicket: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1",
    SSO_URL_SubStatus: "https://webapi.sendpal.in/api/v1/get/user/ml/status?dataformat=json",
    SSO_URL_unsubscribe: "https://webapi.sendpal.in/api/v1/multiple/unsubscribe/ml?dataformat=json",
    SSO_URL_subscribe:
      "https://webapi.sendpal.in/api/v1/add/subscription/ml?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=40",
    SSO_URL_confirm: "https://webapi.sendpal.in/api/v1/confirm/subscription/ml?dataformat=json",
  },
  MYTIMES_PROFILE: "https://mytimes.indiatimes.com/?channel=mly",
  TimesPoint: {
    jsDev: "https://test.timespoint.com/tpwidgets-test/static/dist/js/main.js",
    jsProd: "https://image.timespoints.iimg.in/tpwidgets/static/dist/js/main.js",
    channels: ["tml", "nbt", "eisamay", "tlg", "mly", "mt"],
    // status: true,
    pcode: "channel184095",
    scode: "channel184095",
    activities: {
      DAILY_CHECKINS: "act5545856",
      DAILY_CHECKINS_MOBILE: "act5565223",
      READ_ARTICLE: "act3578224",
      WATCH_VIDEOS: "watch_video",
      SH_FB: "sh_fb",
      SH_TW: "sh_tw",
      LOGIN: "login",
      MOVIE_RATE: "act1286216",
      // Fired by MyProfile team
      MOVIE_REVIEW: "act1223982",
      VIEW_PHOTO: "view_photo",
      LIVE_BLOG: "act5636041",
      SUB_NL: "sub_nltr",
      REGISTER: "register",
      // Fired by MyProfile team
      COMMENT: "cmnt",
      SUB_NOTIFICATION: "act3928586",
      // Not found for staging
      CHECKIN_BONUS_DESKTOP: "act5692078",
      // Not found for staging
      CHECKIN_BONUS_MOBILE: "act5712467",
      WHATSAPP_SHARE: "act5666035",
    },
    campaingHistoryName: {
      desktop: "campaign7224262",
      mobile: "campaign7456140",
    },
    campaignDays: 5,

    stg: {
      pcode: "channel9859549",
      scode: "channel9859549",
      campaingHistoryName: {
        desktop: "campaign3944423",
        mobile: "campaign4051778",
      },
      activities: {
        DAILY_CHECKINS: "act3259327",
        DAILY_CHECKINS_MOBILE: "act3281536",
        READ_ARTICLE: "read",
        WATCH_VIDEOS: "watch_video",
        SH_FB: "sh_fb",
        SH_TW: "sh_tw",
        LOGIN: "login",
        MOVIE_RATE: "act3522728",
        // Fired by MyProfile team
        MOVIE_REVIEW: "rv",
        VIEW_PHOTO: "view_photo",
        LIVE_BLOG: "act3548991",
        SUB_NL: "sub_nltr",
        REGISTER: "register",
        // Fired by MyProfile team
        COMMENT: "cmnt",
        SUB_NOTIFICATION: "act3498524",
        CHECKIN_BONUS_DESKTOP: "act3368572",
        CHECKIN_BONUS_MOBILE: "act3327063",
        WHATSAPP_SHARE: "act3394327",
      },
    },

    TP_FAQ_MSID: "79547313",
    NP_DOMAIN: {
      production: "https://npcoins.indiatimes.com",

      development: "https://nprelease.indiatimes.com",
      stg1: "https://nprelease.indiatimes.com",
      stg2: "https://nprelease.indiatimes.com",
    },

    TP_DOMAIN: {
      production: "https://tpapi.timespoints.com",

      development: "https://test.timespoints.com/tpapi",
      stg1: "https://test.timespoints.com/tpapi",
      stg2: "https://test.timespoints.com/tpapi",
    },

    SDK_DOMAIN: {
      production: "https://image.timespoints.iimg.in",

      development: "https://test-img.timespoints.com",
      stg1: "https://test-img.timespoints.com",
      stg2: "https://test-img.timespoints.com",
    },

    tpwidgetJS: {
      production: "/tpwidgets/dist/js/tpwidget.js",

      development: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg1: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg2: "/static/tpwidgets/static/dist/js/tpwidget.js",
    },

    //* * Moved to common config */
    tpPage: "/timespoints.cms",
    tpRedeemLink: "https://www.timespoints.com/products",
  },
  Comments: {
    appkey: "MALAY",
    topComments: {
      appkey: "MALAY",
      sortcriteria: "AgreeCount",
      order: "desc",
      size: "1",
      lastdeenid: "0",
      after: "true",
      withReward: "false",
      pagenum: "1",
    },
    allComments: {
      appkey: "MALAY",
      sortcriteria: "CreationDate",
      order: "asc",
      size: "6",
      lastdeenid: 0,
      after: true,
      withReward: false,
      pagenum: 1,
    },
  },
  pages: {
    elections: "56661604",
    mktwdt: "85295318",
    business: "56197560",
    iplHomePage: "63301790",
    commonwealth: "63477139",
    fifa: "64383342",
    wcHomePage: "86750324",
    tech: "70499011",
    techreview: "70499194",
    stateSection: "74606583",
    gadgethome: "83552323",
    budget: "67585858",
    budget_you: "97254356",
  },
  iplpages: {
    venues: "63301836",
    teams: "63301827",
    pointsTable: "63301823",
    miniSchedule: "63301824",
  },
  t20wcpages: {
    venues: "86750971",
    teams: "86750490",
    pointsTable: "86750469",
    miniSchedule: "86750410",
  },
  redis: {
    host: "127.0.0.1",
    port: "6379",
    db: "1",
    isRedisCachingSupported: true,
  },
  // To print label in listing node at bottom right corner [templatename, label]
  listNodeLabels: {
    articlelist: ["articlelist"],
    news: ["articleshow"],
    photo: ["photoshow"],
    slideshow: ["photoshow"],
    video: ["videoshow"],
    videolist: ["videolist"],
    photolist: ["photolist"],
    lb: ["liveblog", "ലൈവ് ബ്ലോഗ്‌"],
    moviereview: ["moviereview", "मूवी रिव्यू"],
    movieshow: ["movieshow", "मूवी"],
    poll: ["pollsurvey", "പോള്‍"],
  },
  photoListView: "47882310",
  miniTvMoreVideos: "47329248",
  // Used In AnchorLinkCard
  routes: [
    "/exitpolls/",
    "/results/",
    "/electionlist/",
    "/articlelist/",
    "/photoarticlelist/",
    "/photomazza/",
    "/photolist/",
    "/photoshow/",
    "/photogallery/",
    "/articleshow/",
    "/moviereview/",
    "/movieshow/",
    "/liveblog/",
    "/videolist/",
    "/videoshow/",
    "/topics/",
    "/teams/",
    "/venues/",
    "/pointstable/",
    "/iplt20.cms",
    "/schedule/",
    "/sportsresult/",
    "elections.cms",
    "/timespoints",
    "/gulf",
  ],

  staticPagesDir: "/var/www/html/testpages/",

  slike: {
    apikey: "malamweb215lang",
    snapchatapikey: "",
    ampapikey: "malaampweb215lang",
    default_slikeid_minitv: "1x13qpaggu", // Times-Now
    nextvideo_domain: "https://mtpwafeeds.indiatimes.com",
    default_pl_videolist: "/feeds/videpostroll_v5_slike/47329248.cms?feedtype=json&callback=cached",
  },

  slikeAdCodes: {
    others: "ros",
  },

  gRecaptchaKey: "6LcxSGUUAAAAAPsGPKVpEkLKxnuluuqDKa1AivEN",

  ga: {
    gtm: "GTM-KQW3BK6",
    gtm4: "G-6HH2HEJHZT",
    ampgtm: "GTM-KQW3BK6",
    gverifyCode: "zU5qA2HPdN2PFPyZd70q25_5NHXI8AE8AbqWNwXsoFA",
    gatrackid: "UA-29031733-10",
    ga4trackid: "G-6HH2HEJHZT",
    gaprofile: "[]",
  },

  growthrx: {
    stg: {
      id: "ga387f7ef",
    },
    prod: {
      id: "gb5c941ce",
    },
    gn: {
      stg: {
        id: "gf4078923",
      },
      prod: {
        id: "gcf0e7e75",
      },
    },
  },

  appexclusive_ga: {
    category: "Wap to App install",
    action: "click",
    label: "articlelist_topsection",
  },
  poll: {
    link: "pollslist.cms",
  },
  poll_ga: {
    poll_submit: {
      category: "pollSurvey",
      action: "submit",
      label: "pollsubmit",
    },
    poll_result_loggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "loggedin",
    },
    poll_result_nonloggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "non-loggedin",
    },
  },

  photoshow_app_install: {
    ga_object: {
      category: "Wap to App install",
      action: "click",
      label: "photo show",
    },
  },
  // sso_ga: {
  //   truecaller_requestscreen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen Request",
  //   },
  //   truecaller_screen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen View",
  //   },
  //   truecaller_screencontinue: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Continue",
  //   },
  //   truecaller_skip: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Skip",
  //   },
  //   truecaller_loginsuccess: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Login Successful",
  //   },
  // },
  comscore: { c1: "2", c2: "6036484" },

  applinks: {
    android: {
      hrnav: "https://malayalamsamayam.onelink.me/9pRO/c08370a7",
      asshow: "https://malayalamsamayam.onelink.me/9pRO/e19888c3",
      photoshow: "https://malayalamsamayam.onelink.me/9pRO/850cc0d6",
      serviceDrawer: "https://malayalamsamayam.onelink.me/9pRO/7e8cbe8",
      social: "https://malayalamsamayam.onelink.me/9pRO/70b4c17b",
      oip_appexclusive: "https://navbharattimes.indiatimes.com/off-url-forward/ml_openinapp.cms?msid=",
      // https://malayalamsamayam.onelink.me/cMxT/b256ac1
    },
  },
  appdeeplink: {
    domain: "https://malayalamsamayam.onelink.me",
    shortcode: "9pRO",
    c: "Internal_Campaign",
    pid: {
      hrnav: "WAP_HRNAV_New",
      serviceDrawer: "WAP_BOTTOM_New",
      news: "WAP_MWEB_New",
      article_end: "WAP_AS_New",
      photo: "WAP_PG_New",
      toparticle: "WAP_Top%20Articles_New",
      extphoto: "WAP_Home_Photostrip_New",
      photoshow: "WAP_Photoshow_New",
      campaign: "WAP_Election",
      campaignHome: "WAP_Election_Home",
      openinapp_as: "MLY_AS_Brandwire",
      openinapp_al: "MLY_AL_Brandwire",
      photofeature: "WAP_MWEB_New",
      photoFeature: "WAP_MWEB_New",
      recipe: "WAP_MWEB_New",
      videoshow: "WAP_VideoShow",
      topStrip: "WAP_Top_Strip",
      articlelist: "WAP_ArticleList",
      topStripAS: "New_Top",
      videolist: "WAP_VideoList",
      photolist: "WAP_PhotoList",
      continueInApp: "Continue_App",
      sharing: "WAP_Sitesharing_New",
    },
    listdefaultUrl: "https://mlypwafeeds.indiatimes.com/feeds/app_listing/<MSID>.cms?feedtype=json",
    openapp: "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam",
    opennews:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dnews-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openphoto:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openextphoto:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dp-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openhtmlview:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BURL%7D",
    opensection:
      "malayalamsamayamactivities://open-%24%7C%24-pub%3D7:Samayam Malayalam-%24%7C%24-type%3Dsection-%24%7C%24-sectionID%3D%7BsectionID%7D-%24%7C%24-sectionName%3D%7BsectionName%7D-%24%7C%24-id%3D%7BMSID%7D",
    openphotofeature:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3DphotoFeature-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openrecipe:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Drecipe-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openvideoshow:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dvideo-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openarticlelist:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dnews-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openphotolist:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dphoto-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openvideolist:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dvideo-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openContinueInApp:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D&af_web_dp=https%3A%2F%2Fmalayalam.samayam.com%2F&is_retargeting=true&deep_link_value=malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
  },
  pushNotification: {
    cookieName: "notifypopup_mly",
    defaultThumb: "https://static.langimg.com/thumb/58896467/pic.jpg?width=100&height=100",
    heading:
      "വാര്‍ത്തകള്‍ അതിവേഗം അറിയാൻ നോട്ടിഫിക്കേഷന്‍ സബ്സ്ക്രൈബ് ചെയ്യൂ, അനുവദിക്കുക എന്ന ഓപ്ഷനിൽ ക്ലിക്ക് ചെയ്യൂ",
  },

  weather: {
    geoLocationApi: "https://geoapi.indiatimes.com/?cb=1",
    defaultCity: "Thiruvananthapuram",
    citiesJson: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_geocities.cms",
    weatherFeed: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_weathertoday.cms?lat=",
    heading: "ഇന്നത്തെ താപനില",
    cityText: "ജില്ലാ വാർത്ത വായിക്കൂ",
  },

  pollution: {
    heading: "प्रदूषण",
    headingV1: "അന്തരീക്ഷ വായു നിലവാര സൂചിക",
    status: {
      good: "മികച്ചത്",
      moderate: "മിതമായത്",
      unhelathfSG: "സെന്‍സിറ്റീവ് ഗ്രൂപ്പുകാര്‍ക്ക് അനാരോഗ്യകരം",
      unhealthy: "അനാരോഗ്യകരം",
      veryUnhealthy: "വളരെ അനാരോഗ്യകരം",
      hazardous: "അപകടകരം",
    },
    url: "https://malayalam.samayam.com/pollution.cms",
  },
  fuel: {
    heading: "फ्यूल",
    feedUrl: "https://toibnews.timesofindia.indiatimes.com/fuelprice/latestPrice",
  },

  oneTapSignIn: {
    smartlockurl: "https://smartlock.google.com/client",
    isViewGaTracked: false,
    eventGAObj: {
      hitType: "event",
      category: "Login",
      action: "One_Tap",
      label: "",
    },
    text: {
      oneTapSuccessMsg: "നിങ്ങള്‍ വിജയകരമായി ലോഗിന്‍ ചെയ്തിരിക്കുന്നു",
      oneTapErrorMsg: "Oops! രണ്ടാമതും ശ്രമിക്കൂ",
      oneTapBtnText: "വീണ്ടും ശ്രമിക്കൂ",
    },
    constants: {
      onetapIgnoreDays: 15,
      onetapCookie: "oneTapNextShow",
      onetapIframeCheckTimer: 2000,
      smartlockJsLoadTimer: 10000,
      clientId: "961161019499-83ecofrdm4eg9btinnq5hnkkqj1kvqea.apps.googleusercontent.com",
      channel: "ml-wap",
      jssoAPIGetURL: "https://jsso.indiatimes.com/sso/services/gponetaplogin/verify",
    },
  },
  ZodiacSigns: {
    url: "#",
    data: [
      { name: "aries", regName: "മേടം", pos: 1 },
      { name: "taurus", regName: "ഇടവം", pos: 2 },
      { name: "gemini", regName: "മിഥുനം", pos: 3 },
      { name: "cancer", regName: "കർക്കിടകം", pos: 4 },
      { name: "leo", regName: "ചിങ്ങം", pos: 5 },
      { name: "virgo", regName: "കന്നി", pos: 6 },
      { name: "libra", regName: "തുലാം", pos: 7 },
      { name: "scorpio", regName: "വൃശ്ചികം", pos: 8 },
      { name: "sagittarius", regName: "ധനു", pos: 9 },
      { name: "capricorn", regName: "മകരം", pos: 10 },
      { name: "aquarius ", regName: "കുംഭം", pos: 11 },
      { name: "pisces", regName: "മീനം", pos: 12 },
    ],
  },
  ads: {
    ampInuxuAd:
      "https://adgebra.co.in/afpf/IBN_AMP.html?domain=amp-malayalam.samayam.com&pubid=3613&slotId=1&templateId=4658&accessMode=1&divId=div_407860734567731&cache=123",
    ampAdAfter: "",
    gptUrl: "https://www.googletagservices.com/tag/js/gpt.js",
    ctnAddress: "https://static.clmbtech.com/ad/commons/js/13542/colombia_v2.js",
    dmpUrl: "https://static.clmbtech.com/ase/13542/217/aa.js",
    isvPreRollUrl:
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/7176/MS_Mweb/MLY_Mweb_Videoshow/MLY_Mweb_Videoshow_ISV&description_url=https%3A%2F%2Fmalayalam.samayam.com%2F&tfcd=0&npa=0&sz=300x230%7C300x250%7C300x400%7C320x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
    ADS_PRIORITY: "FAN",
    profileid: "2930", // used NBT as of now
    exchangeId: "692984",
    ctnads: {
      inline: {
        ctnId: "206007",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnlist: {
        ctnId: "206007",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnlistTop: "354479",
      ctnlist1: {
        ctnId: "206007",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnsluglist: {
        ctnId: "355637",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_AL_INS_NEW_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listdefault: {
        ctnId: "206007",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listhorizontalsmall: {
        ctnId: "206007",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnmgid: "M787956ScriptRootC",
      ctnMmgid: "1277547",
      ctnBmgid: "1277548",
      ctnmgidurl: "https://jsc.mgid.com/t/i/til.malayalam.samayam.com",

      ctnshow: "323126",
      ctnmidart: "334316",
      ctnnative: "323125",
      ctnmidart_test: "", // for test page only requested by sales
      ctnhome: {
        ctnId: "206006",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefault: {
        ctnId: "206006",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefaultsmall: {
        ctnId: "206006",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontal: {
        ctnId: "206006",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homevertical: {
        ctnId: "206006",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontalsmall: {
        ctnId: "206006",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnrecommended: {
        ctnId: "206007",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnshowvideo: "334316",
      homeibeat: {
        ctnId: "206006",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnphotoshowrhs: "",
      ctnshowphoto: "",
      ctntopicsall: {
        ctnId: "206007",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctntopicsnews: {
        ctnId: "206007",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnhometop: "207573", // updated
      ctnhomevideo: "324710", //  updated
      ctnvll1: "338608",
      ctnvs: "338608", // Video Show
      ctninlineshow: "208369",
      ctnslider: "210642",
      ctnVideoURL: "https://malayalam.samayam.com/ads_native_video_dev.cms",
      ctnbighome: {
        ctnId: "324211",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_Mweb_Direct_HP_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnbiglist: {
        ctnId: "324212",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_Mweb_Direct_AL_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnbigphoto: {
        ctnId: "324213",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_Mweb_Direct_PG_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnint: "324742",
      ctnint_test: "",
      adspositionsPhoto: "-3-,-5-,-9-,-14-,-20-,-27-,-36-,-45-,-55-",
      adspositionsLiveblog: "-5-,-10-,-15-,-20-,-25-,-30-,-35-,-40-",
      ctncookievalue: "ce_mlmap",
      ctnbccl: "340360",
      ctnvll2: {
        ctnId: "338611",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_Mweb_UPD_New_AL_INS2_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctntopicsphotos: "338610",
      ctntopicsvideos: {
        ctnId: "338611",
        dfpSlot: "/7176/MS_Mweb/MS_Mweb_Bid_Experiment/MS_Mweb_UPD_New_AL_INS2_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnpgl1: "338610",
      ctnpgl2: "338610",
      ctnrhsvideo: "338612",
      ctntechlist: "335486", // Gadget Config
      ctnTechGL: "335486", // Gadget Config
      ctnTechPDP: "335490", // Gadget Config
      ctnTechCL: "357067", // Gadget Config
      ctnTechCDP: "335490", // Gadget Config
      ctnTechTC: "357067", // Gadget Config
      ctntechTop: "335492", // GN Config
      ctntechvideo: "335491", // GN Config
      ctntechoth: "357708", // GN Config
      ctnInImage: "518957",
      ctnPreRoll: "518885",
    },
    ctnslots: {
      atf: "327962",
      ctnshow: "323126",
      ctnbiglist: "",
      ctnbigphoto: "",
      midart: "327961",
      articleshow: "ctnshow,atf,midart",
      liveblog: "",
      photoshow: "",
      videoshow: "",
      videolist: "",
    },

    fanads: {
      home: {
        atf: {
          id: "1080596955339043_2483463398385718",
          size: "320x50",
        },
        fbn: {
          id: "1080596955339043_2483463631719028",
          size: "320x50",
        },
      },
      articlelist: {
        atf: {
          id: "1080596955339043_2483463855052339",
          size: "320x50",
        },
        fbn: {
          id: "1080596955339043_2483464135052311",
          size: "320x50",
        },
        mrec: {
          id: "1080596955339043_2483466375052087",
          size: "300x250",
        },
      },
      articleshow: {
        atf: {
          id: "1080596955339043_2483464328385625",
          size: "320x50",
        },
        fbn: {
          id: "1080596955339043_2483464531718938",
          size: "320x50",
        },
        mrec: {
          id: "1080596955339043_2483464785052246",
          size: "300x250",
        },
        mrec2: {
          id: "1080596955339043_2483465055052219",
          size: "300x250",
        },
      },
      others: {
        atf: {
          id: "1080596955339043_2483465578385500",
          size: "320x50",
        },
        fbn: {
          id: "1080596955339043_2483465805052144",
          size: "320x50",
        },
        mrec: {
          id: "1080596955339043_2483466375052087",
          size: "300x250",
        },
      },
    },

    dfpads: {
      topatf: "/7176/MS_Mweb/MS_Mweb_Others/MS_MWEB_OTH_Fixed",
      cubead1: "/7176/MS_Mweb/MS_Mweb_Others/MS_MWEB_OTH_CUBE_195x85",
      cubead2: "/7176/MS_Mweb/MS_Mweb_Others/MS_MWEB_OTH_CUBE2_195x85",
      cubeheadad1: "/7176/MS_Mweb/MS_Mweb_Others/MS_MWEB_OTH_CUBE_195x30",
      cubeheadad2: "/7176/MS_Mweb/MS_Mweb_Others/MS_MWEB_OTH_CUBE_195x30",
      cubeheadad3: "/7176/MS_Mweb/MS_Mweb_Others/MS_MWEB_OTH_CUBE2_195x30",
      cubeheadad4: "/7176/MS_Mweb/MS_Mweb_Others/MS_MWEB_OTH_CUBE2_195x30",
      andbeyond: "/7176/MS_Mweb/MS_Mweb_ROS/MLM_Mweb_ROS_Andbeyond_1x1",
      inimage: "/7176/MS_Mweb/MS_Mweb_ROS/MLY_Mweb_ROS_Inimage_1x1",
      multiplex: "/7176/MS_Mweb/MS_Mweb_ROS/MLM_MWEB_ROS_Bottomwidget",
      canvasAd: "/7176/MS_Mweb/MS_Mweb_ROS/MLM_Mweb_ROS_Mcanvas_1x1",
      interstitial: "ca-pub-1902173858658913",
      dfpint: "/7176/MS_Mweb/MS_Mweb_Home/MS_Mweb_HP_INT",
      trk: "/7176/MS_Mweb/MS_Mweb_ROS/MS_Mweb_ROS_trk_1x1",
      osv: "/7176/MS_Mweb/MS_Mweb_ROS/MS_Mweb_ROS_OUTSTREAM_1x1",
      sitesync: "/7176/MS_Mweb/MS_Mweb_Home/MS_Mweb_HP_SiteSync_1x1",
      nativead: "/7176/Languages/MS_Mweb/MS_Mweb_Native_300x250",
      nativeadamp: "/7176/Languages/MS_AMP/MS_AMP_Native_300x250",
      ampIntAd: "/7176/AMP_MLY_Mweb/AMP_MLY_Mweb_ROS/AMP_MLY_Mweb_ROS_INT",
      budgetSlug: "/7176/Malyalam/Budget/MLM_BDGT_SLG",
      test1: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_1_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_1_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_1_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_1_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_1_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_1_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      test2: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_2_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_2_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_2_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_2_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_2_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/MS_Mweb/MLY_Mweb_Test/MLY_MWeb_Test_2_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      others: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_ATF",
          size: [
            [300, 250],
            [320, 100],
            [320, 50],
            [336, 280],
            [250, 250],
            [300, 50],
          ],
        },
        btf: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_MWeb_OTH_BTF",
          size: [
            [300, 250],
            [320, 50],
            [300, 50],
            [300, 75],
            [234, 60],
          ],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-2",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_FBN",
          size: [
            [320, 50],
            [300, 50],
          ],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_Mrec1",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-2-mrec2",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_Mrec2",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-inf",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_MrecINF",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        slug: {
          id: "div-gpt-ad-9135510865388-slug",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_Slug1",
          size: [
            [320, 100],
            [300, 100],
          ],
        },
        parallax: {
          id: "div-gpt-ad-9135510865388-parallax",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_FC",
          size: [[300, 600]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-3",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_Mrec3",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec4: {
          id: "div-gpt-ad-9135510865388-4",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_Mrec4",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec5: {
          id: "div-gpt-ad-9135510865388-5",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_Mrec5",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec6: {
          id: "div-gpt-ad-9135510865388-6",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_Mrec6",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec7: {
          id: "div-gpt-ad-9135510865388-7",
          name: "/7176/MS_MWeb/MLY_Mweb_Others/MLY_Mweb_Others_Mrec7",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        refreshnews: "/7176/MS_Mweb/MLY_Mweb_News/MLY_Mweb_News",
      },
    },
  },
  plus: {
    disablePlus: false,
    logo: "https://static.langimg.com/thumb/85000255/malayalam-samayam.jpg?height=36&resizemode=4",
    home: "84165781",
    video: "84169892",
    shortName: "MLY Plus",
    articleReferrerCd: 8,
    articleTypeCd: 6,
    premiumText: "പ്രീമിയം",
    homeText: "Home",
  },
  // dailyMotion: { channel: "samayammalayalam", playerId: "x6k8v", meta: "dmnlfxhgtn60p8lmt", syndication: "278261" },
  plusWidgetObj: {
    logo: "https://static.langimg.com/thumb/85000255/malayalam-samayam.jpg?height=36&resizemode=4",
    altText: "malayalam-samayam",
    premiumText: "പ്രീമിയം",
    thumb: "https://static.langimg.com/thumb/67415762/malayalam-samayam.jpg?width=540&height=405&resizemode=4",
  },
  loginWall: {
    heading: "Malayalam Plus തുടർന്നു വായിക്കുന്നത്തിനായി, ദയവായി സൈൻ ഇൻ ചെയ്യുക",
    subHeading: "Malayalam Plus ന്റെ മെച്ചങ്ങള്‍",
    label1: "പരസ്യങ്ങളുണ്ടാകില്ല",
    label2: "എക്‌സ്‌ക്ലുസീവ് ലേഖനങ്ങളും വീഡിയോകളും",
    label3: "ലേഖനങ്ങളിലൂടെയും വീഡിയോകളിലൂടെയും ടൈംസ് പോയിന്റ് നേടാം",
  },
  foryoupage: {
    cid: "13542:217",
    agencyFilters: ["ഭാഷ", "Brandwire", "SPOTLIGHT"],
  },
  authorDetails: {
    agencyName: "Samayam Malayalam",
    authorName: "Samayam Desk",
    editorLink: "",
    editorLabel: "",
  },
  cityLandingPage: "/local-news/articlelist/74606583.cms",
  timesXP: {
    hostName: "mly_xp",
    xpUrl: "https://mlyfeed.timesxp.com/langapi",
    appUrl: "https://malayalam.timesxp.com",
    wapCode: "malayalamTxp",
  },
  vdoAI: {
    isEnabled: true,
    scriptUrl: "//a.vdo.ai/core/v-malayalam-samayam-v0/vdo.ai.js",
    containerID: "v-malayalam-samayam-v0",
  },
  orgAddress: {
    addressLocality:
      "Times Internet Limited,3rd Floor,Monlash Business Centre,Crescens Tower,Changampuzha Nagar PO, South Kalamassery",
    addressRegion: "Kochi, Kerala ",
    postalCode: "682033",
  },
  cleoPlayer: {
    apikey: "lang-n9GgmFF518E5Bknb",
  },
};
