module.exports = {
  hostid: "155", // GN Config
  channelid: "696089404",
  mediawireslot: "13",
  wapsitename: "Maharashtra Times",
  wapsiteregionalname: "महाराष्ट्र टाइम्स",
  siteName: "maharashtratimes.com",
  staticSiteName: "static.mt.indiatimes.com",
  fbIAcontentId: "141173129234898",
  languagemeta: "mr",
  language: "Marathi",
  channelCode: "mt",
  liveblogApi: "https://langnetstorage.indiatimes.com/Score/pwa_indiaLiveblog_mt.htm",
  langnetstorageBasePath: "https://langnetstorage.indiatimes.com/langappfeeds",
  wapCode: "mt",
  gdprID: "MT",
  languagefullName: "Maharashtra Times",
  video: { rootId: "5314584", newsId: "97274318" },
  fbLive: "92081950",
  videoiconurl: "/video/videolist/5314584.cms",
  editTrendingMSID: "75023567",
  rss: "/rss.cms",
  coronaId: "74457128",
  iospackageid: "674365887",
  androidpackage: "com.mt.reader",
  deeplinkappid: "mtreaderactivities",
  deeplinkpubid: "pub=3:Maharashtra Times",
  iosapp_name: "Maharashtra Times App",
  weburl: "https://maharashtratimes.com",
  mweburl: "https://maharashtratimes.com",
  gadgetdomain: "https://marathi.gadgetsnow.com",
  etdomain: "https://marathi.economictimes.com",
  ccaudId: "7268:46",
  ccaudAmp: "7268",
  ccaudIdAmp: "7268:1214",
  indexExchangeUrl: "//js-sec.indexww.com/ht/p/191952-16988016396378.js",
  footerDesktopLink: "https://maharashtratimes.com?mobile=no",
  cookieLessDomain: "https://static.mt.indiatimes.com",
  domain: "indiatimes.com",
  webdomain: "maharashtratimes.com",
  mwebdomain: "maharashtratimes.com",
  photogallerydomain: "photogallery.maharashtratimes.indiatimes.com",
  google_site_verification: "-nsF72j1bIhqlXprbnO9bBQMBjwp-P7m32hGgtRQdqg",
  twitterHdandler: "@mataonline",
  logo: "nbt-logo.jpg",
  logo_id: "https://static.langimg.com/thumb/78038852/maharashtra-times.jpg?width=240&resizemode=4",
  logogn_id: "https://static.langimg.com/thumb/78038852/maharashtra-times.jpg?width=240&resizemode=4",
  logoPathGadget: "https://static.langimg.com/thumb/83981142/maharashtra-times.jpg?width=232&resizemode=4",
  googleNews:
    "https://news.google.com/publications/CAAiEMesfiuIEy6ySDEYZap9JMEqFAgKIhDHrH4riBMuskgxGGWqfSTB?hl=en-IN&gl=IN&ceid=IN%3Aen",
  fb: "https://www.facebook.com/maharashtratimesonline",
  twitter: "https://twitter.com/mataonline",
  gplus: "https://plus.google.com/+maharashtratimes",
  youtubeUrl: "https://www.youtube.com/channel/UCjD_oFXbVfCDhGEsHunI-hg",
  linkedInUrl: "",
  shoppingBag: "https://maharashtratimes.com/best-deals-online?category=clothes?utm_source=social_panel",
  izooto: "",
  fullutm: "&utm_campaign=mtmobile&utm_medium=referral",
  slikeshareutm: "utm_source=slikevideo&utm_medium=referral",
  telegramFollowLink: "https://telegram.me/Maharashtra_Times",
  shortutm: "my",
  icon: "https://maharashtratimes.com/favicon.ico",
  breakingNewsFeedUrl: "https://langnetstorage.indiatimes.com/LANGBNews/mtbnews.htm",
  fbsdkurl: "https://connect.facebook.net/mr_IN/sdk.js#xfbml=1&version=v3.0",
  fbpage: "https://www.facebook.com/maharashtratimesonline",
  livebloghpfeed: "https://langnetstorage.indiatimes.com/Score/pwa_mtLiveblog_hp.htm",
  livebloghostname: "mt",
  navfeedurl: "https://langnetstorage.indiatimes.com/Score/mt_navconfig.htm",
  liveblogbnbewsurl: "https://maharashtratimes.indiatimes.com/marathi-live-news/liveblog/67342968.cms",
  moreNews: "More News",
  moreNewsUrl: "https://maharashtratimes.com/headlines.cms",
  glossaryLanding: "https://langnetstorage.indiatimes.com/langappfeeds/mt_glossarylist_business.htm",
  marketindices: "https://m.economictimes.com/mcoverage_langwidget.cms?language=MAR&type=indices&nofollow=true",
  marketcommodities: "https://m.economictimes.com/mcoverage_langwidget.cms?language=MAR&type=commodities&nofollow=true",
  logo_schema: "https://static.langimg.com/thumb/60408755/maharashtratimes-times.jpg?width=600&resizemode=4",
  logo_alt: "Maharashtra Times - Marathi News",
  siteid: "2147477892",
  viralBrandingLink: "/viral-adda/articlelist/67088530.cms",
  fbpixelid: "",
  fbappid: "531865860340957",
  googleClientId: "311313395240-9vp5b3gv04abro7jue4hcuosc3dpmvr1.apps.googleusercontent.com",
  astrowidgetId: "2428946",
  bennett: "https://timesofindia.indiatimes.com/bennettjul2020_form_nbt_mweb.cms",
  css:
    "$body-bgcolor:#fff; $navbar-top-bgcolor:#fff; $navbar-bg-color:#F5CC10; $navbar-border-top:#c8cccb; $navbar-border-shadow:#D8B40D; $navbar-active-border-bottom-color:#000; $navbar-link-color:#000; $hamburger-bg-color:#747474; $sidenav-bg-color:#fff; $sidenav-color:#000; $sidenav-border-bottom:#F5F5F5; $sidenav-arrow-color:#D1D1D1; $layer-bg:rgba(0,0,0,0.5); $breadcrumb-home-color:#DA4848; $card-border-bottom:#F5F5F5; $card-bg-color:#8e8e93; $card-text-color:#191919; $card-date-color:#bababa; $home-section-border-bottom:#f5f5f5; $home-section-heading-border-bottom:#F5CC10; $home-section-arrow-color:#000000; $home-section-more-color:#858585; $home-section-more-border:#CCCCCC; $footer-background:#585858; $footer-border-top:#333; $footer-border-bottom:#7b7b7b; $footer-heading-color:#e6e6e6; $footer-text-color:#fff; $footer-link-color:#d0d0d0; $footer-trending-color:#95989a; $footer-copyright-color:#d0d0d0;",
  fontContent:
    "@font-face {font-family: Noto Sans; src: url('https://static.mt.indiatimes.com/fonts/NotoSansDevanagari-Regular.woff2') format('woff2'); font-weight: normal;font-style: normal;font-display: optional;}",
  fontUrl: "https://static.mt.indiatimes.com/fonts/NotoSansDevanagari-Regular.woff2",
  cricket_SIAPI: {
    minischedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_liupre_mr.json",
    schedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_mr.json",
    points_table: "https://toicri.timesofindia.indiatimes.com/jsons/stats/Standings/standing_%seriesid%.json",
    scoreboard: "https://toicri.timesofindia.indiatimes.com/jsons/%matchid%_mr.json",
    topPlayer: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/feed_topplayer.cms?feedtype=sjson",
  },
  nativeclick: "https://click.nativclick.com/loading_iframe/?handle=7688&h=6069cecf34adb1d6db60007da39e2ee8",
  // only for nbt and mt test pages
  avdock_av_tagid: "63be5efebc0881fc8c06cb56",
  techsectionID: {
    // GN Config
    latestGadgets: "74433894",
    trendingGadgets: "74433915", // or popular
    video: "61035745",
    photo: "49799682",
  },

  citymsid: "2429066",
  locale: {
    appIconText: "अ‍ॅप",
    live_blog: "लाइव्ह ब्लॉग",
    recommendednews: "हेही वाचा",
    see_in_app: "मध्ये पाहा",
    see_in_app_details: "सर्व फीचर्ड फोटो पाहण्यासाठी अ‍ॅप ओपन करा",
    whatsapp_share: "Hey, you might find this interesting: ",
    appLinkText:
      "तुम्हालाही तुमच्या अवतीभवती होत असलेल्या बदलांमध्ये सहभागी व्हायचं आहे? सिटिझन रिपोर्टर अॅप डाउनलोड करा आणि रिपोर्ट्स पाठवा.",
    actors: "अभिनेता",
    releaseDate: "रिलीज डेट",
    director: "दिग्दर्शक",
    genre: "प्रकार/शैली",
    duration: "कालावधी",
    latest: "लेटेस्ट",
    latest_video: "लेटेस्ट व्हिडीओ",
    most_read: "सर्वाधिक वाचलेले",
    latest_photo: "लेटेस्ट फोटो",
    readmore: "आणखी वाचा",
    watchmore: "आणखी पाहा",
    commentary: "कॉमेंट्री",
    scorecard: "स्कोअरकार्ड",
    photo_maza: "फोटो  धमाल",
    key_words: "या बातम्यांबद्दल अधिक वाचा",
    more_from_topics: "पुढची बातमी",
    brief: { tooltip: "अधिक बातम्यांसाठी अॅप डाउनलोड करा", limitation_txt: "उर्वरित बातम्यांसाठी" },
    newsLetter: {
      LS: "545678",
      thankyou: "धन्यवाद",
      headerText: "नियमित महत्त्वाच्या बातम्या हव्या आहेत..?",
      joinIn: "जॉईन व्हा",
      footerText: "वरील बॉक्समध्ये ई-मेल आयडी टाका. बातमी तुमच्या इनबॉक्समध्ये येईल",
      verification: "पडताळणीसाठी तुम्हाला ई-मेल पाठवला",
      already: "तुम्ही न्यूजलेटरसाठी अगोदरच सबस्क्राईब केले आहे",
      Subscribed: "तुम्ही आता सबस्क्राईबर आहात",
      errorNetwork: "नेटवर्क समस्या येत आहे. कृपया पुन्हा प्रयत्न करा",
      notverified: "तुम्हाला मेल पाठवला आहे. कृपया पडताळणी करा",
      verified: "तुम्ही अगोदरच पडताळणी केली आहे",
      unchecked: "कृपया चेक बॉक्स तपासा",
      validemail: "कृपया योग्य ई-मेल टाका (example@domain.com)",
      blankemail: "ई-मेल रिक्त नसावा",
      login: "सबस्क्राईब करण्यासाठी लॉग इन करा",
      error: "अडथळा येतोय! आपण जुन्या मेलरची सदस्यता रद्द केली नसल्याचे सुनिश्चित करा",
    },
    social_download: {
      title: "महाराष्ट्र टाइम्सवर घ्या बातम्यांचे लेटेस्ट अपडेट्स ",
      fblike: "फेसबुक पेज लाइक करा।",
      appdownload: "Download App",
      extrasharetxt: "\n\nअॅपमध्ये डाऊनलोड आणि वाचण्यासाठी क्लिक करा : ",
      fblikeURL:
        "https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fmaharashtratimesonline&width=90&layout=button_count&action=like&size=small&show_faces=false&share=false&height=21&appId=531865860340957",
    },
    share_popup_header: "शेयर करा",
    read_more: "आणखी वाचा",
    read_less: "कमी वाचा",
    view_gallery_from_start: "सुरुवातीपासून गॅलरी पाहा",
    next_gallery: "पुढची गॅलरी",
    next_article: {
      moviereview: "पुढचा रिव्ह्यू",
      articleshow: "महत्वाचे लेख",
      default: "डिफॉल्ट",
      movieshow: "Next Movie",
    },
    next_topic: {
      more_all: "आणखी",
      more_news: "आणखी बातम्या",
      more_photos: "आणखी फोटो",
      more_videos: "आणखी व्हिडीओ",
    },
    search_placeholder: "सर्च करा",
    highlight: "हायलाइट्स:",
    popularVideos: "लोकप्रिय व्हिडिओ",
    orientation_heading: "कृपया, डिव्हाइस रोटेट करा",
    orientation_text: "आमच्याकडे लॅण्डस्केप मोड नाहीये. कृपया पोर्टेट मोडवर परत जा ।",
    videos: "व्हिडिओ",
    photo: "फोटो",
    popup: {
      related_videos: "संबंधित व्हिडिओ",
    },
    related_videos: "संबंधित व्हिडिओ",
    most_viewed_videos: "सर्वाधिक पाहिलेले व्हिडीओ",
    default_horizontal_tile_width: 133,
    default_slideshow_tile_width: 120,
    related_articles_horizontal_tile_width: 230,
    relatedarticle: "संबंधित बातम्या",
    cast: "कास्ट",
    read_more_listing: " अजून वाचा",
    critics_review: "क्रिटिक रिव्ह्यू",
    photomasti: "फोटोमस्ती",
    twitte_reaction: "ट्विटरवर चर्चा",
    critics_rating: "क्रिटिक रेटिंग",
    user_rating: "युझर रेटिंग",
    movie_review: "सिने रिव्ह्यू",
    film_review: "सिनेरिव्ह्यू",
    review_movie: "रिव्ह्यू लिहा",
    rate_movie: "चित्रपटाला रेट करा",
    rate: "Rate",
    rate_recipe: "Rate Recipe",
    slide_to_rate: "Slide to Rate",
    slide_to_rate_movie: "मूव्ही रेट करण्यासाठी स्लाइड",
    reader_rating: "वाचकांचे रेटिंग",
    movie_review_tile_bg: "https://static.langimg.com/moviereview_list_bg/photo/65022261.cms",
    movie_review_detail_bg: "https://static.langimg.com/moviereview_list_bg/photo/65594589.cms",
    breaking_news: "ब्रेकिंग न्यूज़",
    trending: "ट्रेंडिंग",
    highlightText: "बातमी थोडक्यात वाचण्यासाठी अॅप डाउनलोड करा",
    live_video: "लाइव वीडियो",
    view_text: "पाहा",
    aur_jaane: "अजून जाणून घ्या",
    oops: "ओह... ",
    thanks: "धन्यवाद",
    offlineText: "तुम्ही ऑफलाइन आहात।",
    onlineText: "तुम्ही ऑनलाइन आहात।",
    openinapp: "ओपन ॲप",
    superhit: " सर्वाधिक वाचलेल्या बातम्या",
    live_updates: "लाईव्ह अपडेट ",
    fblikecardtext: "एमटी फेसबुक पेज ला <br/> लाइक करा",
    appdownloadcardtext: "महाराष्ट्र टाइम्सच्या संपर्कात राहा <br /> ",
    installapp: "इंस्टॉल करा",
    login: "लॉग-इन",
    logout: "लॉग-आउट",
    amazonDeals: "टॉप डील्स",
    seemoreimages: "असे आणखी फोटो पाहा",
    read_more_liveblog: "अजून वाचा",
    footerheading: "Explore Maharashtra Times",
    comment_text: "कॉमेंट लिहा",
    download_text: "डाउनलोड अॅप",
    write_comment: "कॉमेंट लिहा",
    view_comment: "कमेंट पाहा",
    text_topcomment: "टॉप कमेंट",
    text_latestcomment: "लेटेस्ट कमेंट",
    text_author_comment: "लेखकाची कमेंट",
    wp_broadcast: {
      description: "दिवसभरातली टॉप न्यूज",
      btnText: "सबस्क्राईब करा",
      url: "https://widget.whatsbroadcast.com/widget_more/cc4419e76f77dae18f383015baf53754/?show=walink&text=",
    },
    crossbrand: "ही बातमी अगोदर -hyperlink- में -dl- पब्लिश झाली होती।",
    appexclusive: "App Exclusive",
    votesuccessfully: "तुमचं मत नोंदवण्यात आलं आहे ।",
    votealready: "तुम्ही आज मतदान केलं आहे  ।",
    submit_vote: "मत",
    photoshow_app_install: { read_more: " इतर फोटोंसाठी App इन्स्टाल करा", download: "Download App" },
    disclaimer: "अस्वीकरण",
    live_tv: "LIVE TV",
    data_hub: "बजेेट डेटा हब ",
    fantasy_game: "हसत खेळत बजेट ",
    topics_no_result: "कोणताही संबंधित परिणाम नव्हता",
    players: "प्लेयर्स",
    utility: "उपयुक्तता",
    comment: {}, // don't remove this
    appDownload: "MT App",
    tech: {
      inIndia: "भारतातील",
      loadmore: "आणखी लोड करा",
      rating: "रेटिंग",
      sortby: "नुसार निवडा",
      clearall: "सर्व पुसून टाका",
      buyhere: "इथून खरेदी करा",
      indiaLaunchDates: "भारतातील लाँचिंग तारीख",
      indiaPrice: "भारतातील किंमत",
      compCriteria: "तुलना निकष",
      showDiff: "फक्त अंतर पाहा",
      alreadyAdded: "हे गॅजेट तुम्ही अगोदरच निवडले आहे",
      buyFrom: "खरेदी करा",
      addDevice: "डिव्हाईज जोडा",
      compare: "ची तुलना करा",
      englishtype: "कृपया इंग्रजीत टाइप करा",
      change: "बदला",
      suggestedDevice: "सुचवलेले",
      pe: "पर",
      gadgets: "गॅजेट्स",
      filtertxt: "फिल्टर्स",
      purchasehere: "स्पॉन्सर्ड : दुकानात",
      popular: "लोकप्रिय",
      allbrands: "सर्व ब्रँड्स",
      brands: "ब्रँड्स",
      othervariants: "आणखी व्हेरिएंट्स",
      criticsrating: "समीक्षक रेटिंग",
      launchdate: "प्रस्तावित लाँच",
      review: "रिव्ह्यू",
      overview: "ओवरव्यू",
      userrating: "युझर रेटिंग",
      comparedotxt: " तुलना करा",
      submitrating: "रेटिंग सबमिट करा",
      addtocompare: "तुलना करण्यासाठी जोडा",
      purchase: "खरेदी करा",
      suggested: "सुचवलेले",
      comparetxt: " तुलना",
      latest: "लेटेस्ट",
      price: "किंमत",
      rumoured: "चर्चित",
      upcoming: "आगामी",
      ki: "ची",
      relatedgadgets: "संबंधित गॅजेट्स",
      seemore: "आणखी पाहा",
      topfeature: "टॉप फीचर्स",
      fullspecification: "सर्व स्पेसिफिकेशन्स पाहा",
      selectatleast2: "किमान २ निवडा",
      devicealreadyinlist: "तुलनेसाठी अगोदरच निवड केलेली आहे",
      same_gadget: "याच प्रकारचे गॅजेट्स",
      user_review: "युझर रिव्ह्यू",
      read_fullreview: "रिव्ह्यू वाचा",
      similar_gadget: "समान गॅजेट",
      see_diff: "अंतर पाहा",
      latest_comparisons: "लेटेस्ट तुलना",
      popular_comparisons: "लोकप्रिय तुलना",
      techNewsH1: "टेक्नोलॉजी न्यूज",
      minimumComparisonError: "तुलनेसाठी किमान २ गॅजेट्स आवश्यक",
      // gadgets show
      buyAtAmazon: "अमेझॉनवरुन खरेदी करा",
      priceList: "किंमतींची यादी",
      priceInIndia: "भारतातील किंंमत",
      criticReview: "समीक्षक रिव्यू",
      userReview: "युझर रिव्यू",
      specifications: "स्पेसिफिकेशन्स",
      moreLikeThis: "याच प्रकारचे",
      criticRating: "समीक्षक रेटिंग‌",
      userRating: "युझर रेटिंग",
      user: "युझर",
      others: "इतर",
      nextGadget: "पुढील गॅजेट",
      similarGadgets: "याच प्रकारचे आणखी गॅजेट्स",
      readCompleteReview: "पूर्ण रिव्यू वाचा",
      readLess: "कमी वाचा",
      recentlyCompared: "नुकतीच केलेली तुलना",
      weak: "कमकुवत",
      belowAverage: "सरासरी रेटिंग",
      worthpurchase: "खरेदीलायक",
      good: "उत्तम",
      excellent: "सर्वोत्कृष्ट",
      thanksforreview: "समीक्षेसाठी धन्यवाद",
      befirsttoreview: "सर्वात अगोदर रिव्यू द्या",
      userreviewandrating: "युझर रिव्यू आणि रेटिंग",
      ratedevice: "डिव्हाईसला रेट द्या",
      postRating: "रेटिंग पोस्ट करा",
      readMoreReview: "आणखी रिव्यू वाचा",
      varients: "आणखी व्हेरिएंट्स",
      text_write_reviews: "पुनरावलोकन लिहा",
      text_view_comment: "View Comments",
      text_write_comment: "Write Comments",
      critic: "Critic",
      language: "Tech",
      category: [
        { keylabel: "मोबाइल", keyword: "mobile" },
        { keylabel: "लॅपटॉप", keyword: "laptop" },
        { keylabel: "स्मार्टवॉच", keyword: "smartwatch", keylabelEng: "smart watch" },
        { keylabel: "टीव्ही", keyword: "tv" },
        { keylabel: "एसी", keyword: "ac" },
        { keylabel: "टॅबलेट", keyword: "tablet" },
        { keylabel: "कॅमेरा", keyword: "camera" },
        { keylabel: "फिटनेस बँड‌", keyword: "fitnessband", keylabelEng: "fitness band" },
        { keylabel: "वॉशिंग मशिन‌", keyword: "washingmachine", keylabelEng: "washing machine" },
        { keylabel: "फ्रीज‌", keyword: "refrigerator", keylabelEng: "fridge" },
        { keylabel: "पॉवर बँक", keyword: "powerbank", keylabelEng: "power bank" },
      ],
      gadgetSliderConfig: {
        mobile: "मोबाइल",
        laptop: "लॅपटॉप",
        tablet: "टॅबलेट",
        camera: "कॅमेरा",
        smartwatch: "स्मार्टवॉच",
        fitnessband: "फिटनेस बँड‌",
        tv: "टीव्ही",
        ac: "एसी",
        washingmachine: "वॉशिंग मशिन‌",
        refrigerator: "फ्रीज‌",
        powerbank: "पॉवर बँक",
      },
      affiliateTags: {
        homePage: "mt_wap_home_latesttrendingwidget",
      },
    },
    top_headlines: "সেরা হেডলাইন",
    user_review: "User Review",
    listenAlbum: "Listen to this album",
    castncrew: "Cast & Crew",
    filmSongs: "Film Songs",
    read_movie_review: "read movie review",
    news: "बातम्या",
    market: "बाजार",
    choseStateCity: { dropDownText: "शहर निवडा", extraCityContent: "तुमच्या शहरातील बातम्या वाचा" },
    cityPopUp: {
      selectStateCity: "राज्य आणि शहर",
      selectCity: "शहर निवडा",
      save: "जतन करा",
      state: "राज्य",
      city: "शहर",
      readersCount: "महाराष्ट्र टाइम्सच्या वाचकांची संख्या {{total}} लाखांहून अधिक आहे.",
    },
    cityHeading: "जवळच्या शहरातील बातम्या",
    cityHeadingVideo: "जवळच्या शहरातील व्हिडिओ",
    openInApp: {
      stayHere: "इथेच थांबा",
      openApp: "अॅप उघडा",
      mainText: "अॅपवर लेख वाचणं चालू ठेवू इच्छिता?",
      mainTextForVSnPS: "अॅपवर पाहणे सुरु ठेवू इच्छिता?",
    },
    authoraritcle: "यांचे लेख",
    authorsharetext: "यांच्याशी ऑनलाईन कनेक्ट करा",
    authorabout: "यांच्याविषयी",
    authorwebstories: " यांनी केलेली वेबस्टोरी",
    articles: "लेख",
    webstories: "वेबस्टोरी",
    dailyNewsUpdate: "रोजच्या अपडेट्ससाठी लॉगइन करा",
    downloadAppForNews: "नियमित बातम्यांच्या अपडेटसाठी अ‍ॅप डाऊनलोड करा",
    notificationTopNewsAlert: "कोणतीही बातमी चुकवू नका. नोटिफिकेशन्स मिळवण्यासाठी परवानगी द्या वर क्लिक करा.",
    notification: "नोटिफिकेशन",
    others: "इतर",
    authoraritcle: "यांचे लेख",
    authorsharetext: "यांच्याशी ऑनलाईन कनेक्ट करा",
    authorabout: "यांच्याविषयी",
    authorwebstories: " यांनी केलेली वेबस्टोरी",
    articles: "लेख",
    webstories: "वेबस्टोरी",
  },
  imageconfig: {
    thumbid: "67144443",
    defaultthumb: "67144443",
    techthumb: "67144443",
    liveblogthumb: "56295200",
    imagedomain: "https://static.langimg.com/thumb/",
    webimagedomain: "https://maharashtratimes.com/thumb/",
    bigimage: "width=540&resizemode=3", // Article Inline Images, will maintain aspect ratio of original image
    big2ximage: "width=1080&resizemode=3", // Article Inline Images, will maintain aspect ratio of spotlight/paid article image
    smallthumb: "width=280&height=210&resizemode=75", // Listing small thumbs, Aspect Ratio 4:3
    smallslideshowthumb: "width=320&height=240&resizemode=1", // Used for external photogallery strip on top news, Aspect Ratio 4:3
    midthumb: "width=320&height=240&resizemode=75", // Photo Listing widget thumb, etc Aspect Ratio 4:3
    largethumb: "width=380&height=285&resizemode=75", // Lead Images Aspect Ratio 4:3
    amplargethumb: "width=1600&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only videoshow
    amplargethumbarticle: "width=1200&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only for article
    smallwidethumb: "width=200&height=111&resizemode=75", // For video listing widgets Aspect Ratio 16:9
    largewidethumb: "width=380&height=214&resizemode=75", // For videowidget lead image and videoshow Aspect Ratio 16:9
    posterthumb: "width=210&height=281&resizemode=4", // Moview Posters
    squarethumb: "width=200&height=200&resizemode=75", // for two colum layout
    rectanglethumb: "width=160&height=103&resizemode=75", // for rectangle flags
    gnthumb: "width=200&resizemode=4", // for Gadget now
    gnthumbWithHeight: "height=150&resizemode=4", // for GN PDP, need height
    webstoriesthumb: "width=300&height=500&resizemode=4", // web stories Photo Listing widget thumb",
    webstoriesthumbLarge: "width=364&height=607&resizemode=4", // web stories Photo Listing widget thumb",
    widecardthumb: "width=600&height=315&resizemode=6", // End Article Card thumb 16: 9",
  },
  sso: {
    BASE_URL: "https://maharashtratimes.com",
    SSO_CHANNEL: "mt-wap",
    GADGET_CHANNEL: "marathi-gadgetsnow-wap",
    stg: {
      BASE_URL: "https://jstg.maharashtratimes.com",
      MYTIMES_URL_USER: "https://mytest.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
      MYTIMES_URL_SETTINGS: "https://jssostg.indiatimes.com/sso/identity/profile/edit?channel=tm",
      SSO_URL_LOGIN: "https://jssostg.indiatimes.com/sso/identity/login",
      SSO_URL_LOGOUT: "https://jssostg.indiatimes.com/sso/identity/profile/logout/external",
      SSO_URL_GETTICKET: "https://jssostg.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
      SOCIAL_API_INTEGRATOR: "https://testsocialappsintegrator.indiatimes.com/socialsite",
      SSO_BASE_URL: "https://jssostg.indiatimes.com/sso/crossdomain",
      SSO_CROSSWALK: "https://jssocdnstg.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
      SSO_WIDGET_URL: "https://jssocdnstg.indiatimes.com/crosswalk/133/widget/main.bundle.js",
    },
    SSO_BASE_URL: "https://jsso.indiatimes.com/sso/crossdomain",
    SSO_CROSSWALK: "https://jssocdn.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
    SSO_WIDGET_URL: "https://jssocdn.indiatimes.com/crosswalk/34/widget/main.bundle.min.js",
    MYTIMES_URL_USER: "https://myt.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
    MYTIMES_URL_SETTINGS: "https://jsso.indiatimes.com/sso/identity/profile/edit?channel=mt",
    SSO_URL_LOGIN: "https://jsso.indiatimes.com/sso/identity/login",
    SSO_URL_LOGOUT: "https://jsso.indiatimes.com/sso/identity/profile/logout/external",
    SSO_URL_GETTICKET: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
    MYTIMES_ALREADY_RATED: "https://myt.indiatimes.com/mytimes/alreadyRated?appKey=MTO&",
    MYTIMES_ADD_ACTIVITY: "https://myt.indiatimes.com/mytimes/addActivity?appKey=MTO&",
    SOCIAL_API_INTEGRATOR: "https://socialappsintegrator.indiatimes.com/socialsite",
    SSO_TRUECALLER_visibility: 4,

    SSO_URL_NewsTicket: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1",
    SSO_URL_SubStatus: "https://webapi.sendpal.in/api/v1/get/user/mt/status?dataformat=json",
    SSO_URL_unsubscribe: "https://webapi.sendpal.in/api/v1/multiple/unsubscribe/mt?dataformat=json",
    SSO_URL_subscribe:
      "https://webapi.sendpal.in/api/v1/add/subscription/mt?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=17",
    SSO_URL_confirm: "https://webapi.sendpal.in/api/v1/confirm/subscription/mt?dataformat=json",
  },
  MYTIMES_PROFILE: "https://mytimes.indiatimes.com/?channel=mt",
  TimesPoint: {
    jsDev: "https://test.timespoint.com/tpwidgets-test/static/dist/js/main.js",
    jsProd: "https://image.timespoints.iimg.in/tpwidgets/static/dist/js/main.js",
    channels: ["tml", "nbt", "eisamay", "tlg", "mly", "mt"],
    // status: true,
    pcode: "MTO",
    scode: "MTO",
    activities: {
      DAILY_CHECKINS: "act3002195",
      DAILY_CHECKINS_MOBILE: "act3018717",
      READ_ARTICLE: "act9633295",
      WATCH_VIDEOS: "act47986",
      SH_FB: "act2947440",
      SH_TW: "act2966619",
      LOGIN: "login",
      MOVIE_RATE: "act1756472",
      // Fired by MyProfile team
      MOVIE_REVIEW: "act1699138",
      VIEW_PHOTO: "view_photo",
      LIVE_BLOG: "act3429020",
      SUB_NL: "sub_nltr",
      REGISTER: "register",
      // Fired by MyProfile team
      COMMENT: "act9892534",
      SUB_NOTIFICATION: "act3132536",
      // Not found for staging
      CHECKIN_BONUS_DESKTOP: "act3037664",
      // Not found for staging
      CHECKIN_BONUS_MOBILE: "act3064295",
      WHATSAPP_SHARE: "act2984416",
    },
    campaingHistoryName: {
      desktop: "campaign7685683",
      mobile: "campaign7818051",
    },
    campaignDays: 5,

    stg: {
      pcode: "MTO",
      scode: "MTO",
      campaingHistoryName: {
        desktop: "campaign3639716",
        mobile: "campaign3758310",
      },
      activities: {
        DAILY_CHECKINS: "act5387031",
        DAILY_CHECKINS_MOBILE: "act5476673",
        READ_ARTICLE: "read",
        WATCH_VIDEOS: "watch_video",
        SH_FB: "sh_fb",
        SH_TW: "sh_tw",
        LOGIN: "act5742527",
        MOVIE_RATE: "act5780676",
        // Fired by MyProfile team
        MOVIE_REVIEW: "rv",
        VIEW_PHOTO: "view_photo",
        LIVE_BLOG: "act5876972",
        SUB_NL: "act5906899",
        REGISTER: "register",
        // Fired by MyProfile team
        COMMENT: "cmnt",
        SUB_NOTIFICATION: "act5959834",
        CHECKIN_BONUS_DESKTOP: "act5506864",
        CHECKIN_BONUS_MOBILE: "act5534332",
        WHATSAPP_SHARE: "act5984566",
      },
    },

    TP_FAQ_MSID: "79549895",
    NP_DOMAIN: {
      production: "https://npcoins.indiatimes.com",

      development: "https://nprelease.indiatimes.com",
      stg1: "https://nprelease.indiatimes.com",
      stg2: "https://nprelease.indiatimes.com",
    },

    TP_DOMAIN: {
      production: "https://tpapi.timespoints.com",

      development: "https://test.timespoints.com/tpapi",
      stg1: "https://test.timespoints.com/tpapi",
      stg2: "https://test.timespoints.com/tpapi",
    },

    SDK_DOMAIN: {
      production: "https://image.timespoints.iimg.in",

      development: "https://test-img.timespoints.com",
      stg1: "https://test-img.timespoints.com",
      stg2: "https://test-img.timespoints.com",
    },

    tpwidgetJS: {
      production: "/tpwidgets/dist/js/tpwidget.js",

      development: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg1: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg2: "/static/tpwidgets/static/dist/js/tpwidget.js",
    },

    //* * Moved to common config */
    tpPage: "/timespoints.cms",
    tpRedeemLink: "https://www.timespoints.com/products",
  },
  Comments: {
    appkey: "MTO",
    topComments: {
      appkey: "MTO",
      sortcriteria: "AgreeCount",
      order: "desc",
      size: "1",
      lastdeenid: "0",
      after: "true",
      withReward: "false",
      pagenum: "1",
    },
    allComments: {
      appkey: "MTO",
      sortcriteria: "CreationDate",
      order: "asc",
      size: "6",
      lastdeenid: 0,
      after: true,
      withReward: false,
      pagenum: 1,
    },
  },
  pages: {
    elections: "64159109",
    mktwdt: "87990409",
    business: "47416711",
    iplHomePage: "63431849",
    commonwealth: "92368537",
    fifa: "64449381",
    wcHomePage: "86777579",
    tech: "2499221",
    techreview: "80476649",
    stateSection: "2429066",
    gadgethome: "83515594",
    budget: "51037966",
    budget_you: "97254398",
    apanabazaar: "85481921",
  },
  iplpages: {
    venues: "63516520",
    teams: "63516480",
    pointsTable: "63516456",
    miniSchedule: "63516464",
  },
  t20wcpages: {
    venues: "86782334",
    teams: "86778084",
    pointsTable: "86777941",
    miniSchedule: "86777724",
  },
  redis: {
    host: "127.0.0.1",
    port: "6379",
    db: "1",
    isRedisCachingSupported: true,
  },
  // redis: { host: "192.168.24.51", port: "6379", db: "1" },
  listNodeLabels: {
    articlelist: ["articlelist"],
    news: ["articleshow"],
    photo: ["photoshow"],
    slideshow: ["photoshow"],
    video: ["videoshow"],
    videolist: ["videolist"],
    photolist: ["photolist"],
    lb: ["liveblog", "लाइव्ह अपडेट"],
    moviereview: ["moviereview", "मूव्ही रिव्ह्यू"],
    movieshow: ["movieshow", "मूव्ही"],
    poll: ["pollsurvey", "पोल"],
  },
  photoListView: "47882310",
  miniTvMoreVideos: "5314584",
  routes: [
    "/exitpolls/",
    "/results/",
    "/electionlist/",
    "/articlelist/",
    "/photoarticlelist/",
    "/photomazza/",
    "/photolist/",
    "/photoshow/",
    "/photogallery/",
    "/articleshow/",
    "/moviereview/",
    "/movieshow/",
    "/liveblog/",
    "/videolist/",
    "/videoshow/",
    "/topics/",
    "/teams/",
    "/venues/",
    "/pointstable/",
    "/iplt20.cms",
    "/schedule/",
    "/sportsresult/",
    "elections.cms",
    "/timespoints",
    "/us",
  ],
  staticPagesDir: "/var/www/html/testpages/",
  slike: {
    apikey: "mtmweb42lang",
    snapchatapikey: "lng54mweb5afm96lgz9",
    ampapikey: "mtampweb42lang",
    default_slikeid_minitv: "1x13qpaggu",
    nextvideo_domain: "https://mtpwafeeds.indiatimes.com",
    default_pl_videolist: "/feeds/videpostroll_v5_slike/5314607.cms?feedtype=json&callback=cached",
  },
  slikeAdCodes: {
    home: "home,4901865",
    auto: "2355188,28471009",
    bharat: "1564454",
    cricket: "3521869",
    duniya: "2279801",
    haryana: "21236773",
    "josh-jawani": "3041664",
    jokes: "12545518,5556078",
    lucknow: "21248218",
    "share-market": "2279786,11873677",
    "movie-masti": "2279793,4901881,11872954",
    mumbai: "5722181",
    "movie-review": "2325387",
    "other-cities": "21236618",
    other: "other",
    photo: "2339144",
    rajya: "33503484",
    rashifal: "17127056,48972527",
    "score-card": "999999",
    sahar: "33503484",
    "super-hit": "999999",
    tech: "19615041,20104392",
    "top-news": "696089404,4901886",
    "uttar-pradesh": "21236867",
    vichar: "2007740431",
  },
  gRecaptchaKey: "6LceKeQUAAAAAK72OwmOvN-lWEfU9z_ezv__lX0P",
  ga: {
    gtm: "GTM-KDKHMSS",
    gtm4: "G-3468TZG00Y",
    ampgtm: "GTM-KDKHMSS",
    gverifyCode: "-nsF72j1bIhqlXprbnO9bBQMBjwp-P7m32hGgtRQdqg",
    gatrackid: "UA-429254-4",
    ga4trackid: "G-3468TZG00Y",
    gaprofile:
      "['maharashtratimes.com', 'superpacer.in', 'mtmobile.in', 'timesofindia.com', 'mtganeshotsav.com', 'mtcultureclub.com']",
  },
  growthrx: {
    stg: {
      id: "g59ddc460",
    },
    prod: {
      id: "g31b18562",
    },
    gn: {
      stg: {
        id: "gfcc17585",
      },
      prod: {
        id: "g10b28ca7",
      },
    },
  },
  appexclusive_ga: { category: "Wap to App install", action: "click", label: "articlelist_topsection" },
  poll: { link: "pollslist.cms" },
  poll_ga: {
    poll_submit: { category: "pollSurvey", action: "submit", label: "pollsubmit" },
    poll_result_loggedIn: { category: "pollSurvey", action: "viewresult", label: "loggedin" },
    poll_result_nonloggedIn: { category: "pollSurvey", action: "viewresult", label: "non-loggedin" },
  },
  photoshow_app_install: { ga_object: { category: "Wap to App install", action: "click", label: "photo show" } },
  // sso_ga: {
  //   truecaller_requestscreen: { category: "True Caller", action: "Click", label: "Screen Request" },
  //   truecaller_screen: { category: "True Caller", action: "Click", label: "Screen View" },
  //   truecaller_screencontinue: { category: "True Caller", action: "Click", label: "Continue" },
  //   truecaller_skip: { category: "True Caller", action: "Click", label: "Skip" },
  //   truecaller_loginsuccess: { category: "True Caller", action: "Click", label: "Login Successful" },
  // },
  comscore: { c1: "2", c2: "6036484" },
  applinks: {
    android: {
      hrnav: "https://maharashtratimes.onelink.me/W6tZ/52dace0c",
      asshow: "https://maharashtratimes.onelink.me/W6tZ/8a95f981",
      photoshow: "https://maharashtratimes.onelink.me/W6tZ/ff6bee6f",
      serviceDrawer: "https://maharashtratimes.onelink.me/W6tZ/9a1d5ba5",
      social: "https://maharashtratimes.onelink.me/W6tZ/dd08d9d7",
      oip_appexclusive: "https://navbharattimes.indiatimes.com/off-url-forward/mt_openinapp.cms?msid=",
    },
  },
  appdeeplink: {
    domain: "https://maharashtratimes.onelink.me",
    shortcode: "W6tZ",
    c: "Internal_Campaign",
    pid: {
      hrnav: "WAP_HRNAV",
      serviceDrawer: "WAP_BOTTOM",
      news: "WAP_MWEB",
      article_end: "WAP_AS",
      photo: "WAP_PG",
      toparticle: "WAP_Top%20Articles",
      extphoto: "WAP_Home_Photostrip",
      photoshow: "WAP_Photoshow",
      campaign: "WAP_Election",
      campaignHome: "WAP_Election_Home",
      openinapp_as: "MT_AS_Brandwire",
      openinapp_al: "MT_AL_Brandwire",
      photofeature: "WAP_MWEB",
      photoFeature: "WAP_MWEB",
      recipe: "WAP_MWEB",
      videoshow: "WAP_VideoShow",
      topStrip: "WAP_Top_Strip",
      articlelist: "WAP_ArticleList",
      topStripAS: "New_Top",
      videolist: "WAP_VideoList",
      photolist: "WAP_PhotoList",
      continueInApp: "Continue_App",
      sharing: "WAP_Sitesharing",
    },
    listdefaultUrl: "https://mtpwafeeds.indiatimes.com/feeds/app_listing/<MSID>.cms?feedtype=json",
    openapp: "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times",
    opennews:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Dnews-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openphoto:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openextphoto:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dp-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openhtmlview:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BURL%7D",
    opensection:
      "mtreaderactivities://open-%24%7C%24-pub%3D3:Maharashtra Times-%24%7C%24-type%3Dsection-%24%7C%24-sectionID%3D%7BsectionID%7D-%24%7C%24-sectionName%3D%7BsectionName%7D-%24%7C%24-id%3D%7BMSID%7D",
    openphotofeature:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3DphotoFeature-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openrecipe:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Drecipe-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openvideoshow:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Dvideo-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openarticlelist:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dnews-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openphotolist:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dphoto-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openvideolist:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dvideo-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openContinueInApp:
      "mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D&af_web_dp=https%3A%2F%2Fmaharashtratimes.com%2F&is_retargeting=true&deep_link_value=mtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D3%3AMaharashtra%2520Times-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
  },
  pushNotification: {
    cookieName: "notifypopup_mt",
    defaultThumb: "https://static.langimg.com/thumb/55869601/pic.jpg?width=100&height=100",
    heading: "लेटेस्ट आणि ब्रेकिंग न्यूजसाठी नोटिफिकेशन सबस्क्राईब करा. 'चालू करा'वर क्लिक करा",
  },
  weather: {
    geoLocationApi: "https://geoapi.indiatimes.com/?cb=1",
    defaultCity: "Mumbai",
    citiesJson: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_geocities.cms",
    weatherFeed: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_weathertoday.cms?lat=",
    heading: "आजचे तापमान",
    cityText: "तुमच्या शहरातील बातम्या",
  },
  pollution: {
    heading: "प्रदूषण",
    headingV1: "आपल्या शहरातील प्रदुषणाची माहिती मिळवा",
    status: {
      good: "चांगले",
      moderate: "मध्यम",
      unhelathfSG: "नाजूक प्रकृतीसाठी धोकादायक",
      unhealthy: "धोकादायक",
      veryUnhealthy: "अधिक धोकादायक",
      hazardous: "घातक",
    },
    url: "https://maharashtratimes.com/maharashtra/pollution/67572545.cms",
  },
  fuel: {
    heading: "फ्यूल",
    feedUrl: "https://toibnews.timesofindia.indiatimes.com/fuelprice/latestPrice",
  },
  oneTapSignIn: {
    smartlockurl: "https://smartlock.google.com/client",
    isViewGaTracked: false,
    eventGAObj: { hitType: "event", eventCategory: "Login", eventAction: "One_Tap", eventLabel: "" },
    text: {
      oneTapSuccessMsg: "तुम्ही यशस्वीपणे लॉगइन केलं आहे",
      oneTapErrorMsg: "Oops! काहीतरी गडबड आहे। कृपया पुन्हा एकदा प्रयत्न करा।",
      oneTapBtnText: "पुन्हा एकदा प्रयत्न करा",
    },
    constants: {
      onetapIgnoreDays: 15,
      onetapCookie: "oneTapNextShow",
      onetapIframeCheckTimer: 2000,
      smartlockJsLoadTimer: 10000,
      clientId: "311313395240-9vp5b3gv04abro7jue4hcuosc3dpmvr1.apps.googleusercontent.com",
      channel: "mt-wap",
      jssoAPIGetURL: "https://jsso.indiatimes.com/sso/services/gponetaplogin/verify",
    },
  },
  cricplay_widget: {
    schedulelink: "/sports/cricket/icc-world-cup/schedule/69161420.cms",
    deeplink:
      "https://telugusamayam.onelink.me/V28U?pid=WAP_CricPlay&c=Internal_Campaign&af_dp=telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3Dhttps%3A%2F%2Fcrpl.app.link%2FZnAyOSBSxW",
    wincashtxt1: "உங்களுக்கு பிடித்த கிரிக்கெட் அணியை உருவாக்குங்கள் மற்றும் ",
    wincashtxt2: "பணம் வென்றிடுங்கள்!",
    appdwntxt: "சமயம் தமிழ் ஆப் டவுண்லோடு செய்க",
  },
  ZodiacSigns: {
    url: "#",
    data: [
      { name: "aries", regName: "मेष", pos: 1 },
      { name: "taurus", regName: "वृषभ", pos: 2 },
      { name: "gemini", regName: "मिथुन ", pos: 3 },
      { name: "cancer", regName: "कर्क", pos: 4 },
      { name: "leo", regName: "सिंह", pos: 5 },
      { name: "virgo", regName: "कन्या", pos: 6 },
      { name: "libra", regName: "तूळ", pos: 7 },
      { name: "scorpio", regName: "वृश्चिक", pos: 8 },
      { name: "sagittarius", regName: "धनु", pos: 9 },
      { name: "capricorn", regName: "मकर", pos: 10 },
      { name: "aquarius ", regName: "कुंभ", pos: 11 },
      { name: "pisces", regName: "मीन", pos: 12 },
    ],
  },
  ads: {
    ampInuxuAd:
      "https://adgebra.co.in/afpf/IBN_AMP.html?domain=amp-maharashtratimes.com&pubid=3613&slotId=1&templateId=4653&accessMode=1&divId=div_407860734567731&cache=123",
    ampAdChannelId: "636b5a0bf7f29d21d941ceb2",
    ampAdAfter:
      "https://player.avplayer.com/amp/ampiframe.html?AV_TAGID=6343f64e103b782b505d2ed5&AV_PUBLISHERID=633e9d23cc55cb310f54cd06",
    gptUrl: "https://www.googletagservices.com/tag/js/gpt.js",
    ctnAddress: "https://static.clmbtech.com/ad/commons/js/7268/colombia_v2.js",
    dmpUrl: "https://static.clmbtech.com/ase/7268/46/aa.js",
    isvPreRollUrl:
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/7176/MT_MWeb/MT_MWeb_Videoshow/MT_MWeb_Videoshow_ISV&description_url=https%3A%2F%2Fmaharashtratimes.com%2F&tfcd=0&npa=0&sz=300x230%7C300x400%7C320x25%7C359x200%7C400x315&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
    ADS_PRIORITY: "FAN",
    profileid: "2930", // used NBT as of now
    exchangeId: "692985",
    ctnads: {
      inline: {
        ctnId: "251737",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_mWeb_ROS_AL_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefault: {
        ctnId: "129188",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Home/MT_MWeb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefaultsmall: {
        ctnId: "129188",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Home/MT_MWeb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontal: {
        ctnId: "129188",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Home/MT_MWeb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homevertical: {
        ctnId: "129188",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Home/MT_MWeb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontalsmall: {
        ctnId: "129188",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Home/MT_MWeb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnlist: {
        ctnId: "251737",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_mWeb_ROS_AL_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnlistTop: "354477",
      ctnlist1: {
        ctnId: "251737",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_mWeb_ROS_AL_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnpgl1: "338547",
      ctnpgl2: "338547",
      ctnvll1: {
        ctnId: "338543",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Mweb_New_AL_INS1_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnvll2: {
        ctnId: "338544",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Mweb_New_AL_INS2_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnbiglist: {
        ctnId: "324200",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Mweb_Direct_AL_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnsluglist: {
        ctnId: "355636",
        dfpSlot: "/7176/MT_MWeb /MT_MWeb_Bid_Experiment/MT_mWeb_ROS_AL_INS_NEW_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listdefault: {
        ctnId: "251737",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_mWeb_ROS_AL_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listhorizontalsmall: {
        ctnId: "251737",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_mWeb_ROS_AL_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnmgid: "M769014ScriptRootC",
      ctnMmgid: "1258797",
      ctnBmgid: "1258798",
      ctnmgidurl: "https://jsc.mgid.com/t/i/til.maharashtratimes.com",
      ctnshow: "323120",
      ctnmidart: "334311",
      ctnnative: "358380",
      ctnmidart_test: "336104",
      ctnrecommended: {
        ctnId: "129176",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_ROS/MT_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnrhsvideo: "338572",
      ctnshowvideo: "334311",
      ctnvs: {
        ctnId: "338543",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Mweb_New_AL_INS1_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnhome: {
        ctnId: "129188",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Home/MT_MWeb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnhometop: "206699",
      ctnhomevideo: "318091",
      ctninlineshow: "208363",
      ctnslider: "210644",
      ctnVideoURL: "https://maharashtratimes.com/ads_native_video_dev.cms",
      ctnbighome: {
        ctnId: "324199",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Mweb_Direct_HP_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnbigphoto: {
        ctnId: "324201",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Mweb_Direct_PG_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      homeibeat: {
        ctnId: "129188",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Home/MT_MWeb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnint: "324737",

      ctnphotoshowrhs: "",
      ctnshowphoto: "338801",

      ctntopicsall: {
        ctnId: "251737",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_mWeb_ROS_AL_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctntopicsnews: {
        ctnId: "251737",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_mWeb_ROS_AL_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctntopicsphotos: "338547",
      ctntopicsvideos: {
        ctnId: "338544",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Mweb_New_AL_INS2_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnint_test: "",
      adspositionsPhoto: "-3-,-5-,-9-,-14-,-20-,-27-,-36-,-45-,-55-",
      adspositionsLiveblog: "-5-,-10-,-15-,-20-,-25-,-30-,-35-,-40-",
      ctncookievalue: "mtm_ce",
      ctnbccl: "340359",
      ctntechlist: "335494", // Gadget Config
      ctnTechGL: "335494", // Gadget Config
      ctnTechPDP: "335498", // Gadget Config
      ctnTechCL: {
        ctnId: "357051",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Gadget_Mweb_ROS_PDP_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      }, // Gadget Config
      ctnTechCDP: "335498", // Gadget Config
      ctnTechTC: {
        ctnId: "357051",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Gadget_Mweb_ROS_PDP_INS_Bid_Experiment_320",
        dfpSize: [320, 100],
      }, // Gadget Config
      ctntechTop: "335500", // GN Config
      ctntechvideo: "335499", // GN Config
      ctntechoth: {
        ctnId: "357685",
        dfpSlot: "/7176/MT_MWeb/MT_MWeb_Bid_Experiment/MT_Gadget_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      }, // GN Config
      ctnInImage: "518955",
      ctnPreRoll: "518883",
    },
    ctnslots: {
      atf: "327958",
      ctnshow: "323120",
      ctnbiglist: "",
      ctnbigphoto: "",
      midart: "327957",
      articleshow: "ctnshow,atf,midart",
      liveblog: "",
      photoshow: "",
      videoshow: "",
      videolist: "",
    },

    fanads: {
      home: {
        atf: { id: "1802497356645104_2634664223428409", size: "320x50" },
        fbn: { id: "1802497356645104_2634664843428347", size: "320x50" },
      },
      articlelist: {
        atf: { id: "1802497356645104_2634664956761669", size: "320x50" },
        fbn: { id: "1802497356645104_2634665026761662", size: "320x50" },
        mrec1: { id: "1802497356645104_2634666736761491", size: "300x250" },
      },
      articleshow: {
        atf: { id: "1802497356645104_2634665170094981", size: "320x50" },
        fbn: { id: "1802497356645104_2634665260094972", size: "320x50" },
        mrec1: { id: "1802497356645104_2634665526761612", size: "300x250" },
        mrec2: { id: "1802497356645104_2634665620094936", size: "300x250" },
      },
      others: {
        atf: { id: "1802497356645104_2634666393428192", size: "320x50" },
        fbn: { id: "1802497356645104_2634666536761511", size: "320x50" },
        mrec1: { id: "1802497356645104_2634666736761491", size: "300x250" },
      },
    },

    dfpads: {
      topatf: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_ROS_Others_Fixed",
      cubead1: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWEB_OTH_CUBE_195x85",
      cubead2: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWEB_OTH_CUBE2_195x85",
      cubeheadad1: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWEB_OTH_CUBE_195x30",
      cubeheadad2: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWEB_OTH_CUBE_195x30",
      cubeheadad3: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWEB_OTH_CUBE2_195x30",
      cubeheadad4: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWEB_OTH_CUBE2_195x30",
      andbeyond: "/7176/MT_MWeb/MT_MWeb_ROS/MT_Mweb_ROS_Andbeyondd_1x1",
      inimage: "/7176/MT_MWeb/MT_MWeb_ROS/MT_Mweb_ROS_Inimage_1x1",
      multiplex: "/7176/MT_MWeb/MT_MWeb_ROS/MT_MWEB_ROS_Bottomwidget",
      canvasAd: "/7176/MT_MWeb/MT_MWeb_ROS/MT_Mweb_ROS_Mcanvas_1x1",
      interstitial: "ca-pub-1902173858658913",
      dfpint: "/7176/MT_MWeb/MT_MWeb_Home/MT_MWeb_HP_PT_INT",
      trk: "/7176/MT_MWeb/MT_MWeb_ROS/MT_MWeb_ROS_Trk_1x1",
      osv: "/7176/MT_MWeb/MT_MWeb_ROS/MT_MWeb_ROS_OUTSTREAM_1x1",
      sitesync: "/7176/MT_MWeb/MT_MWeb_Home/MT_Mweb_HP_SiteSync_1x1",
      nativead: "/7176/Languages/MT_Mweb/MT_Mweb_Native_300x250",
      nativeadamp: "/7176/Languages/MT_AMP/MT_AMP_Native_300x250",
      ampIntAd: "/7176/AMP_MT_Mweb/AMP_MT_Mweb_ROS/AMP_MT_Mweb_ROS_INT",
      budgetSlug: "/7176/Maharashtratimes/MT_Budget/MT_BDGT_SLG",
      test1: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_1_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_1_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_1_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_1_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_1_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_1_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      test2: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_2_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_2_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_2_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_2_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_2_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/MT_MWeb/MT_MWeb_Test/MT_MWeb_Test_2_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      others: {
        atf: {
          id: "div-gpt-ad-9135510865388-atf",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_ATF",
          size: [
            [300, 250],
            [320, 100],
            [320, 50],
            [336, 280],
            [250, 250],
            [300, 50],
          ],
        },
        btf: {
          id: "div-gpt-ad-9135510865388-btf",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_BTF",
          size: [
            [300, 250],
            [320, 50],
            [300, 50],
            [300, 75],
            [234, 60],
          ],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-fbn",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_FBN",
          size: [
            [320, 50],
            [300, 50],
          ],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_MREC1",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_MREC2",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecinf",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_MRECINF",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        slug: {
          id: "div-gpt-ad-9135510865388-SLUG",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_SLUG1",
          size: [
            [320, 100],
            [300, 100],
          ],
        },
        parallax: {
          id: "div-gpt-ad-9135510865388-parallax",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_FC",
          size: [[300, 600]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_MREC3",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec4: {
          id: "div-gpt-ad-9135510865388-mrec4",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_MREC4",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec5: {
          id: "div-gpt-ad-9135510865388-mrec5",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_MREC5",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec6: {
          id: "div-gpt-ad-9135510865388-mrec6",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_MREC6",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec7: {
          id: "div-gpt-ad-9135510865388-mrec7",
          name: "/7176/MT_MWeb/MT_MWeb_Others/MT_MWeb_Others_MREC7",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        refreshnews: "/7176/MT_MWeb/MT_MWeb_News/MT_MWEB_News",
      },
    },
  },
  plus: {
    disablePlus: false,
    logo: "https://static.langimg.com/thumb/85000254/maharashtra-times.jpg?height=36&resizemode=4",
    home: "82406039",
    video: "82406072",
    shortName: "MT Plus",
    articleReferrerCd: 9,
    articleTypeCd: 6,
    premiumText: "प्रीमिअम बातम्या",
    homeText: "होम",
  },
  // dailyMotion: { channel: "maharashtratimes", playerId: "x6k8u", syndication: "028923" },
  plusWidgetObj: {
    logo: "https://static.langimg.com/thumb/85000254/maharashtra-times.jpg?height=36&resizemode=4",
    altText: "maharashtra-times",
    premiumText: "प्रीमियम खबरें",
    thumb: "https://static.langimg.com/thumb/67144443/maharashtra-times.jpg?width=540&height=405&resizemode=4",
  },
  loginWall: {
    heading: "MT Plus लेख वाचत राहण्यासाठी खालील कोणताही पर्याय वापरून साइन इन करा",
    subHeading: "MT Plus चे फायदे",
    label1: "जाहिरातमुक्त अनुभव",
    label2: "विशेष लेख आणि व्हिडिओ",
    label3: "प्रत्येक लेख आणि व्हिडिओवर मिळवा टाइमपॉइंट्स",
  },
  foryoupage: {
    cid: "7268:46",
    agencyFilters: ["भाषा", "Brandwire", "SPOTLIGHT"],
  },
  authorDetails: {
    agencyName: "महाराष्ट्र टाइम्स.कॉम",
    authorName: "",
    editorLink: "",
    editorLabel: "",
  },
  cityLandingPage: "/maharashtra/articlelist/2429066.cms",
  timesXP: {
    hostName: "mt_xp",
    xpUrl: "https://mtfeed.timesxp.com/langapi",
    appUrl: "https://marathi.timesxp.com",
    wapCode: "marathiTxp",
  },
  vdoAI: {
    isEnabled: true,
    scriptUrl: "//a.vdo.ai/core/v-maharashtratimes/vdo.ai.js",
    containerID: "v-maharashtratimes",
  },
  orgAddress: {
    addressLocality: "2nd Floor, Times Of India Building, Dr. D. N. Road",
    addressRegion: "Mumbai ",
    postalCode: "400001",
  },
  cleoPlayer: {
    apikey: "lang-n9GgmFF518E5Bknb",
  },
};
