module.exports = {
  // GN Config
  hostid: "53",
  channelid: "696089404",
  mediawireslot: "13",
  wapsitename: "Navbharat Times",
  wapsiteregionalname: "नवभारत टाइम्स",
  siteName: "navbharattimes.indiatimes.com",
  staticSiteName: "static.nbt.indiatimes.com",
  language: "Hindi",
  languagemeta: "hi",
  channelCode: "nbt",
  gdprID: "NBT",
  wapCode: "nbt",
  languagefullName: "Navbharat Times",

  languagefullNameGN: "टेक",
  appPlayStoreLink: "https://play.google.com/store/apps/details?id=com.nbt.reader",
  langnetstorageBasePath: "https://langnetstorage.indiatimes.com/langappfeeds",
  liveblogApi: "https://langnetstorage.indiatimes.com/Score/pwa_indiaLiveblog_hp.htm",
  video: { rootId: "4901865", newsId: "96546524" },
  fbLive: "92060639",
  editTrendingMSID: "76501746",
  techEditTrendingMSID: "76501746", // "77232358",
  applist: "/appslist.cms",
  rss: "/rss.cms",
  coronaId: "74460387",
  androidpackageid: 656093141,

  videoiconurl: "/video/videolist/4901865.cms",

  gnschecmasitename: "NBT Gadget Now",
  iospackageid: "656093141",

  androidpackage: "com.nbt.reader",
  deeplinkappid: "nbtreaderactivities",
  deeplinkpubid: "pub=2:Navbharat Times",
  iosapp_name: "Navbharat Times App",
  weburl: "https://navbharattimes.indiatimes.com",
  mweburl: "https://navbharattimes.indiatimes.com",
  ccaudId: "2310:49",
  ccaudAmp: "2310",
  ccaudIdAmp: "2310:767",
  indexExchangeUrl: "https://js-sec.indexww.com/ht/p/191952-71956427846521.js",
  footerDesktopLink: "https://navbharattimes.indiatimes.com?mobile=no",
  cookieLessDomain: "https://static.nbt.indiatimes.com",
  domain: "indiatimes.com",
  webdomain: "navbharattimes.indiatimes.com",
  mwebdomain: "navbharattimes.indiatimes.com",
  gadgetdomain: "https://hindi.gadgetsnow.com",
  etdomain: "https://hindi.economictimes.com",
  photogallerydomain: "photogallery.navbharattimes.indiatimes.com",
  google_site_verification: "ZgFICIedNvVZl5pV9EfAUeenwta9vBY0Za_GgmV4zuw",
  twitterHdandler: "@NavbharatTimes",
  logo: "nbt-logo.jpg",
  logo_id: "https://static.langimg.com/thumb/100842088/navbharat-times.jpg?width=128&resizemode=4",
  logogn_id: "https://static.langimg.com/thumb/100842088/navbharat-times.jpg?width=128&resizemode=4",
  businesslogo: "https://static.langimg.com/thumb/82457770/navbharat-times.jpg?width=114&resizemode=4",
  logoPathGadget: "https://static.langimg.com/thumb/83667526/navbharat-times.jpg?width=232&resizemode=4",
  googleNews: "https://news.google.com/publications/CAAqBwgKMKfl3Qowj8LUAQ?hl=en-IN&gl=IN&ceid=IN%3Aen",
  businessLink: "/business/articlelist/2279786.cms",
  fb: "https://www.facebook.com/navbharattimes",
  twitter: "https://twitter.com/navbharattimes",
  gplus: "https://plus.google.com/+navbharattimes",
  youtubeUrl: "https://www.youtube.com/channel/UCl8wUKzoUVzg7U6ky1ZR8hQ",
  // kooUrl: "https://www.kooapp.com/profile/navbharattimes",
  linkedInUrl: "https://www.linkedin.com/company/navbharat-times--hindi/",
  shoppingBag: "https://navbharattimes.indiatimes.com/best-deals-online?category=clothes?utm_source=social_panel",
  izooto: "",
  fullutm: "&utm_campaign=nbtmobile&utm_medium=referral",
  slikeshareutm: "utm_source=slikevideo&utm_medium=referral",
  telegramFollowLink: "https://telegram.me/Navbharattimes",
  shortutm: "mx", // Using for micron
  icon: "https://navbharattimes.indiatimes.com/favicon.ico",
  breakingNewsFeedUrl: "https://langnetstorage.indiatimes.com/LANGBNews/nbtbnews.htm",
  fbsdkurl: "https://connect.facebook.net/hi_IN/sdk.js#xfbml=1&version=v3.0",
  fbpage: "https://www.facebook.com/navbharattimes",
  livebloghpfeed: "https://langnetstorage.indiatimes.com/Score/pwa_indiaLiveblog_hp.htm",
  livebloghostname: "nbt", // Using to getch liveblog callback feed
  navfeedurl: "https://langnetstorage.indiatimes.com/langappfeeds/pwa_navjson.htm",
  liveblogbnbewsurl: "https://navbharattimes.indiatimes.com/breaking-news-in-hindi/liveblog/58166012.cms",
  // logo_schema dimension should be 600*60
  logo_schema: "https://navbharattimes.indiatimes.com/photo/69514679/nbt-logo.jpg",
  logo_alt: "Navbharat Times - Hindi News",
  siteid: "696089404",
  fbpixelid: "530684973736330",
  fbappid: "154495568087154",
  googleClientId: "196250535198-r0370bk9l9hj7o6qajsok78ggd524dk8.apps.googleusercontent.com",
  astrowidgetId: "19127963",
  bennett: "https://timesofindia.indiatimes.com/bennettjul2020_form_nbt_mweb.cms",
  moreNews: "More News",
  moreNewsUrl: "https://navbharattimes.indiatimes.com/headlines.cms",
  glossaryLanding: "https://langnetstorage.indiatimes.com/langappfeeds/nbt_glossarylist_business.htm",
  marketindices: "https://m.economictimes.com/mcoverage_langwidget.cms?language=HIN&type=indices&nofollow=true",
  marketcommodities: "https://m.economictimes.com/mcoverage_langwidget.cms?language=HIN&type=commodities&nofollow=true",
  css:
    "$body-bgcolor:#fff;	$navbar-top-bgcolor:#fff;	$navbar-bg-color:#F5CC10;	$navbar-border-top:#c8cccb;	$navbar-border-shadow:#D8B40D;	$navbar-active-border-bottom-color:#000;	$navbar-link-color:#000;	$hamburger-bg-color:#747474;	$sidenav-bg-color:#fff;	$sidenav-color:#000;	$sidenav-border-bottom:#F5F5F5;	$sidenav-arrow-color:#D1D1D1;	$layer-bg:rgba(0,0,0,0.5);	$breadcrumb-home-color:#DA4848;	$card-border-bottom:#F5F5F5;	$card-bg-color:#8e8e93;	$card-text-color:#191919;	$card-date-color:#bababa;	$home-section-border-bottom:#f5f5f5;	$home-section-heading-border-bottom:#F5CC10;	$home-section-arrow-color:#000000;	$home-section-more-color:#858585;	$home-section-more-border:#CCCCCC;	$footer-background:#585858;	$footer-border-top:#333;	$footer-border-bottom:#7b7b7b;	$footer-heading-color:#e6e6e6;	$footer-text-color:#fff;	$footer-link-color:#d0d0d0;	$footer-trending-color:#95989a;	$footer-copyright-color:#d0d0d0;",
  fontContent:
    "@font-face {font-family: Noto Sans; src: url('https://static.nbt.indiatimes.com/fonts/NotoSansDevanagari-Regular.woff2') format('woff2'); font-weight: normal;font-style: normal;font-display: optional;}",
  fontUrl: "https://static.nbt.indiatimes.com/fonts/NotoSansDevanagari-Regular.woff2",
  cricket_SIAPI: {
    minischedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_liupre_hi.json",
    schedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_hi.json",
    points_table: "https://toicri.timesofindia.indiatimes.com/jsons/stats/Standings/standing_%seriesid%.json",
    scoreboard: "https://toicri.timesofindia.indiatimes.com/jsons/%matchid%_hi.json",
    topPlayer: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/feed_topplayer.cms?feedtype=sjson",
  },
  nativeclick: "https://click.nativclick.com/loading_iframe/?handle=6990&h=d7f426ccbc6db7e235c57958c21c5dfa",
  avdock_av_tagid: "63be5ed86bf78000fa0eec15",
  // gadgetMapping: {
  //   "mobile-phones": "mobile",
  //   laptops: "laptop",
  //   tablets: "tablet",
  //   cameras: "camera",
  //   television: "tv",
  //   ac: "ac",
  //   washingmachine: "washingmachine",
  //   refrigerator: "refrigerator",
  //   powerbank: "powerbank",
  //   smartwatch: "smartwatch",
  //   fitnessband: "fitnessband",
  // },

  // GN Config
  techsectionID: {
    latestGadgets: "66635263",
    trendingGadgets: "66635275",
    video: "20104392",
    photo: "19829828",
  },
  citymsid: "88295797",
  locale: {
    appIconText: "ऐप",
    live_blog: "लाइव ब्लॉग",
    photoshowrhsheading: "रिलेटेड फोटो",
    whatsapp_share: "Hey, you might find this interesting: ",
    commentary: "कमेंटरी",
    scorecard: "स्कोरकार्ड",
    photo_maza: "फोटो मज़ा",
    key_words: "इन टॉपिक्स पर और पढ़ें",
    more_from_topics: "इन टॉपिक्स पर और पढ़ें",
    brief: {
      tooltip: "इस फॉर्मैट में खबरें पसंद आईं तो और पढ़ने के लिए डाउनलोड करें ऐप",
      limitation_txt: "ब्रीफ की बाकी खबरें पढ़ने के लिए करें",
    },
    see_in_app: "ऐप पर देखें",
    see_in_app_details: "सभी फीचर्ड फोटो देखने के लिए ऐप पर जाए",
    recommendednews: "रेकमेंडेड खबरें",
    appLinkText:
      "देश-दुनिया की खबरें, आपके शहर का हाल, एजुकेशन और बिज़नेस अपडेट्स, फिल्म और खेल की दुनिया की हलचल, वायरल न्यूज़ और धर्म-कर्म... पाएँ हिंदी की ताज़ा खबरें",

    actors: "ऐक्टर",
    releaseDate: "रिलीज़ डेट",
    director: "डायरेक्टर ",
    genre: "श्रेणी",
    duration: "अवधि",
    most_read: "सबसे ज़्यादा पढ़े गए",
    latest_video: "लेटेस्ट विडियो",
    latest_photo: "लेटेस्ट फोटो",
    recipe: "रेसिपी",
    most_viewed_videos: "चर्चित विडियो",
    readmore: "और पढ़ें",
    watchmore: "और देखें",

    newsLetter: {
      LS: "2254",
      thankyou: "धन्यवाद",
      headerText: "देश-दुनिया की बड़ी खबरें मिस हो जाती हैं?",
      joinIn: "जॉइन करें",
      footerText: "ऊपर बॉक्स में अपना ईमेल आईडी लिखें. लेटेस्ट खबरें आपको अपने इनबॉक्स में मिलेंगी",
      verification: "आपके ईमेल पर वेरिफ़िकेशन मेल भेजा गया है",
      already: "आपने न्यूज़लेटर  पहले ही सब्सक्राइब किया हुआ है",
      Subscribed: "आपनेे सब्सक्राइब कर लिया है",
      errorNetwork: "नेटवर्क में कुछ समस्या है. कृपया फिर से कोशिश करें!",
      notverified: "आपके ईमेल पर वेरिफ़िकेशन मेल भेजा गया है. कृपया वेरिफाई करें!",
      verified: "आप अपना ईमेल आईडी पहले ही वेरिफाई कर चुके हैं",
      unchecked: "कृपया चेक बॉक्स का चयन करें",
      validemail: "कृृपया सही ईमेल आईडी लिखें (example@domain.com)",
      blankemail: "ईमेल एड्रेस की जगह खाली न छोड़ें",
      login: "सब्सक्राइब करने के लिए लॉग इन करें",
      error: "कोई समस्या है! सुनिश्चित करें कि आपने पुराने मेलर से अनसब्सक्राइब नहीं किया है",
    },

    social_download: {
      title: "रहें हर खबर से अपडेट नवभारत टाइम्स के साथ",
      fblike: "फेसबुक पेज लाइक करें।",
      appdownload: "ऐप डाउनलोड करें",
      extrasharetxt: "\n\nऐप में डाउनलोड और पढ़ने के लिए यहां क्लिक करें : ",
      fblikeURL:
        "https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fnavbharattimes&width=90&layout=button_count&action=like&size=small&show_faces=false&share=false&height=21&appId=874437342646992",
    },
    share_popup_header: "शेयर करे",
    read_more: "Read More...",
    read_less: "Read Less...",
    view_gallery_from_start: "शुरुआत से देखें",
    next_gallery: "अगली गैलरी",
    next_article: {
      moviereview: "अगला रिव्यू",
      movieshow: "अगली मूवी",
      articleshow: "अगला लेख",
      techreview: "अगला लेख",
      pdp: "अगला लेख",
      default: "अगला लेख",
    },
    next_topic: {
      more_all: "और",
      more_news: "और न्यूज़",
      more_photos: "और फोटो",
      more_videos: "और विडियो",
    },

    search_placeholder: "सर्च करे",
    highlight: "हाइलाइट्स",
    popularVideos: "चर्चित विडियो",

    search_gadgets: "Search Gadgets",
    search: "सर्च",

    orientation_heading: "कृपया, डिवाइस को रोटेट करें",
    orientation_text:
      "हम अभी लैंडस्केप मोड को सपोर्ट नहीं करते हैं। कृपया, बेहतर अनुभव के लिए पॉर्ट्रट मोड पर वापस जाएं।",
    videos: "वीडियो",
    photo: "फोटो",
    related_videos: "संबंधित विडियो",
    default_horizontal_tile_width: 133, // These widths are used for slider
    default_slideshow_tile_width: 120,
    related_articles_horizontal_tile_width: 230,
    relatedarticle: "संबंधित स्टोरीज़ ",
    read_more_listing: " और",
    critics_review: "क्रिटिक रिव्यू",
    photomasti: "फोटो धमाल",
    twitte_reaction: "ट्विटर पर चर्चा",
    critics_rating: "क्रिटिक रेटिंग",
    user_rating: "पाठकों की रेटिंग",
    movie_review: "मूवी रिव्यू",
    film_review: "मूवी रिव्यू",
    review_movie: "रिव्यू लिखें",
    review_device: "रिव्यू डिवाइस",
    rate_movie: "रेट करे",
    slide_to_rate_movie: "रेट करने के लिए स्लाइड",
    rate: "रेट डिवाइस",
    rate_recipe: "Rate Recipe",
    slide_to_rate: "Slide to Rate",
    reader_rating: "पाठको की रेटिंग",
    movie_review_tile_bg: "https://static.langimg.com/moviereview_list_bg/photo/65022261.cms",
    movie_review_detail_bg: "https://static.langimg.com/moviereview_list_bg/photo/65594589.cms",
    breaking_news: "ब्रेकिंग न्यूज़", // "ब्रेकिंग न्यूज़",
    trending: "ट्रेंडिंग",
    highlightText: "सारी खबरें हाइलाइट्स में पढ़ने के लिए ऐप डाउनलोड करें",
    live_video: "लाइव वीडियो", // Using for minitv widget
    view_text: "देखे",
    aur_jaane: "और जानें",
    oops: "ओह... ",
    offlineText: "लगता है आप ऑफलाइन हो चुके हैं।",
    onlineText: "अब आप ऑनलाइन हैं।",
    openinapp: "ऐप पर पढ़ें",
    superhit: " इन लोकप्रिय खबरों को भी पढ़ें",
    live_updates: "लाइव अपडेट",
    fblikecardtext: "एनबीटी फेसबुक पेज को <br/> लाइक करे", // Using in Service Drawer
    appdownloadcardtext: "हमेशा जुड़े रहें नवभारत टाइम्स <br /> की ऐप के साथ", // Using in Service Drawer
    installapp: "इंस्टॉल करें",
    login: "लॉग-इन",
    logout: "लॉग-आउट",
    amazonDeals: "टॉप डील्स",
    seemoreimages: "ऐसी और तस्वीरें देखें", // Using in Photomazzashow
    read_more_liveblog: "और पढ़े",
    footerheading: "Explore Navbharat Times",
    comment_text: "कॉमेंट लिखें",
    download_text: "डाउनलोड ऐप",
    write_comment: "कॉमेंट लिखें",
    view_comment: "कॉमेंट देखें",
    wp_broadcast: {
      description: "Read best news on WhatsApp",
      btnText: "Subscribe",
      url: "https://widget.whatsbroadcast.com/widget_more/8531f3a382edfe5c49a332a5fb08a2aa/?show=walink&text=",
    },
    crossbrand: "यह खबर पहले -hyperlink- में -dl- को पब्लिश हुई थी।",
    appexclusive: "ऐप एक्सक्लूसिव",
    votesuccessfully: "आपका वोट दर्ज हो गया है।",
    votealready: "आप पहले ही वोट दे चुके हैं।",
    thanks: "धन्यवाद",
    submit_vote: "वोट दें",
    photoshow_app_install: {
      read_more: "बाकी फोटो के लिए ऐप  इन्स्टॉल करें",
      download: "डाउनलोड ऐप",
    },
    disclaimer: "डिसक्लेमर",
    live_tv: "लाइव टीवी",
    data_hub: "डाटा हब",
    fantasy_game: "फॅंटेसी गेम",
    players: "प्लेयर्स",
    appDownload: "NBT App",
    tech: {
      inIndia: "भारत में",
      loadmore: "और लोड करे",
      rating: "रेटिंग",
      sortby: "शॉर्ट बाई:",
      clearall: "क्लियर ऑल",
      buyhere: "यहाँ से ख़रीदे",
      indiaLaunchDates: "भारत में लांच की तारीखें",
      indiaPrice: "भारत में कीमत",
      compCriteria: "कंपरीजन क्राइटेरिया",
      showDiff: "केवल अंतर देखें",
      alreadyAdded: "यह गैजेट आपने पहले से ही चुना हुआ है।",
      buyFrom: "ख़रीदे",
      addDevice: "डिवाइस एंटर करें",
      compare: "की तुलना करें",
      englishtype: "कृपया english में टाइप करें",
      change: "बदलें",
      suggestedDevice: "सुझाए गए",
      pe: "पर",
      gadgets: "गैजेटस",
      filtertxt: "फिल्टर्स",
      purchasehere: "स्पॉन्सर्ड: स्टोर में",
      popular: "पॉप्युलर",
      allbrands: "सभी ब्रैंड्स",
      brands: "ब्रैंड्स",
      othervariants: "और वेरिएंट",
      criticsrating: "क्रिटिक रेटिंग",
      launchdate: "संभावित लॉन्च",
      review: "रिव्यू",
      overview: "ओवरव्यू",
      userrating: "यूज़र रेटिंग",
      addtocompare: "तुलना करने के लिए जोड़ें",
      purchase: "खरीदें",
      suggested: "सुझाववित",
      comparetxt: "तुलना",
      latest: "लेटेस्ट",
      price: "कीमत",
      rumoured: "संभावित",
      upcoming: "आने वाले",
      ki: "की",
      relatedgadgets: "Related Gadgets",
      seemore: "इन्हें भी देखें",
      topfeature: "टॉप फीचर्स",
      fullspecification: "पूरे स्पेसिफिकेशन्स को देखें",
      selectatleast2: "Select minimum 2 items.",
      devicealreadyinlist: "Item already selected for comparison.",
      same_gadget: "इसी तरह के गैजेट्स",
      user_review: "यूज़र रिव्यू",
      read_fullreview: "रिव्यू पढ़ें",
      similar_gadget: "समान गैजेट",
      see_diff: "अंतर जानें",
      news_glance: "एक क्लिक से खबर देखें",
      latest_comparisons: "लेटेस्ट तुलना",
      popular_comparisons: "Popular Comparisons",

      techNewsH1: "टेक्नॉलजी न्यूज",
      comparedotxt: "तुलना करें",
      minimumComparisonError: "तुलना के लिए कम से कम दो गैजेट्स आवश्यक है।",
      // gadgets show
      buyAtAmazon: "Amazon से ख़रीदे",
      priceList: "कीमतों की लिस्ट",
      priceInIndia: "भारत में कीमत",

      criticReview: "क्रिटिक रिव्यू",
      userReview: "यूजर रिव्यू",
      specifications: "स्पेसिफिकेशन्स",

      moreLikeThis: "इस तरह के",
      criticRating: "क्रिटिक रेटिंग",
      userRating: "यूज़र रेटिंग",
      submitrating: "रेटिंग सबमिट करें",
      user: "यूजर",
      others: "अन्य",
      nextGadget: "अगली गैजेट",
      similarGadgets: "इस तरह के और गैजट्स",

      readCompleteReview: "पूरा रिव्यू पढ़ें",
      readLess: "कम पढ़ें",

      recentlyCompared: "हाल ही में की गई तुलना",
      weak: "कमजोर",
      belowAverage: "औसत रेटिंग",
      worthpurchase: "खरीदने लायक",
      good: "बढ़िया",
      excellent: "बेहतरीन",
      thanksforreview: "आपकी समीक्षा के लिए धन्यवाद",
      befirsttoreview: "सबसे पहले रिव्यू करें",
      userreviewandrating: "यूजर रिव्यू और रेटिंग",
      ratedevice: "रेट डिवाइस",

      postRating: "रेटिंग पोस्ट करें",
      readMoreReview: "और रिव्यू पढ़ें",
      varients: "और वेरिएंट्स",
      text_write_reviews: "रिव्यू डिवाइस",
      text_view_comment: "कॉमेंट्स देखें",
      text_write_comment: "अपना कॉमेंट लिखें",
      language: "Tech",

      category: [
        { keylabel: "मोबाइल", keyword: "mobile" },
        { keylabel: "लैपटॉप्स", keyword: "laptop" },
        { keylabel: "स्मार्टवॉच", keyword: "smartwatch" },
        { keylabel: "टेलीविजन", keyword: "tv" },
        { keylabel: "एयर कंडीशनर", keyword: "ac" },
        { keylabel: "टैबलेट", keyword: "tablet" },
        { keylabel: "कैमरे", keyword: "camera" },
        { keylabel: "फिटनेस बैंड", keyword: "fitnessband" },
        { keylabel: "वॉशिंग मशीन", keyword: "washingmachine" },
        { keylabel: "फ्रिज", keyword: "refrigerator" },
        { keylabel: "पावर बैंक", keyword: "powerbank" },
      ],
      gadgetSliderConfig: {
        mobile: "मोबाइल",
        laptop: "लैपटॉप्स",
        tablet: "टैबलेट",
        camera: "कैमरे",
        smartwatch: "स्मार्टवॉच",
        fitnessband: "फिटनेस बैंड",
        tv: "टेलीविजन",
        ac: "एयर कंडीशनर",
        washingmachine: "वॉशिंग मशीन",
        refrigerator: "फ्रिज",
        powerbank: "पावर बैंक",
        submitRating: "रेटिंग करें",
        critic: "क्रिटिक",
        user: "यूजर",
      },
      affiliateTags: {
        homePage: "nbt_wap_home_latesttrendingwidget",
        comparisonLandingPageTag: "hinbt_wap_comparisonlanding_suggestionwidget-21",
      },
    },
    top_headlines: "Top Headlines",
    utility: "उपयोगिता",
    choseStateCity: { dropDownText: "अपना शहर/राज्य चुनें", extraCityContent: "अपने शहर की खबरें पढ़ें" },
    cityPopUp: {
      selectStateCity: "राज्य & शहर चुनें",
      selectCity: "शहर चुनें",
      save: "सेव",
      state: "राज्य",
      city: "शहर",
      readersCount: "नवभारत टाइम्स की पाठक संख्या {{total}} लाख से ज्यादा है.",
    },
    cityHeading: "आसपास के शहरों की खबरें",
    cityHeadingVideo: "आसपास के शहरों के विडियो",
    user_review: "यूज़र रिव्यू",
    listenAlbum: "Listen to this album",
    castncrew: "कास्ट और क्रू",
    filmSongs: "फिल्म के गाने",
    read_movie_review: "का मूवी रिव्यू पढ़ें",
    news: "न्यूज़",
    photos: "फोटोज",
    market: "मार्केट",
    comment: {
      storyComment: "कॉमेंट्स इस स्टोरी के लिए",
      offLang: "अभद्र भाषा",
      defame: "झूठा/घिनौना आरोप",
      community: "किसी कम्युनिटी के खिलाफ घृणा भड़कानेवाला",
      offensive: "आपत्तिजनक",
      offensiveReason: "आपत्ति का कारण",
      offensiveSuccess: "आपकी आपत्ति संपादक तक पहुंचा दी गई है।",
      reply: "जवाब दें",
      objection: "आपत्ति दर्ज करें",
      close: "बंद करें",
    },
    openInApp: {
      stayHere: "यही रहें",
      openApp: "ऐप खोलें",
      mainText: "ऐप में आर्टिकल पढ़ना जारी रखें?",
      mainTextForVSnPS: "ऐप पर देखना जारी रखें?",
    },
    authoraritcle: "के आर्टिकल",
    authorwebstories: "के वेब स्टोरी",
    authorsharetext: "से ऑनलाइन कनेक्ट करें",
    authorabout: "के बारे में",
    articles: "आर्टिकल",
    webstories: "वेब स्टोरी",
    dailyNewsUpdate: "दैनिक न्यूज़ अपडेट के लिए लॉगिन करें",
    downloadAppForNews: "सीधे अपने मोबाइल पर न्यूज़ अपडेट पाने के लिए, डाउनलोड  करें  NBT न्यूज़ ऐप",
    notificationTopNewsAlert: "टॉप न्यूज़ अलर्ट पाने के लिए NBT नोटिफ़िकेशन सब्सक्राइब  करें। Allow बटन पर क्लिक करें।",
    notification: "नोटिफ़िकेशन",
    others: "अन्य",
    authoraritcle: "के आर्टिकल",
    authorwebstories: "के वेब स्टोरी",
    authorsharetext: "से ऑनलाइन कनेक्ट करे",
    authorabout: "के बारे में",
    articles: "आर्टिकल",
    webstories: "वेब स्टोरी",
  },
  imageconfig: {
    thumbid: "76874587",
    liveblogthumb: "58166012",
    techthumb: "76874587",
    defaultthumb: "76874587", // preserve default id if thubmid chnaged to differ
    imagedomain: "https://static.langimg.com/thumb/",
    webimagedomain: "https://navbharattimes.indiatimes.com/thumb/",
    bigimage: "width=540&resizemode=3", // Article Inline Images, will maintain aspect ratio of original image
    big2ximage: "width=1080&resizemode=3", // Article Inline Images, will maintain aspect ratio of spotlight/paid article image
    smallthumb: "width=135&height=102&resizemode=75", // Listing small thumbs, Aspect Ratio 4:3
    smallslideshowthumb: "width=320&height=240&resizemode=1", // Used for external photogallery strip on top news, Aspect Ratio 4:3
    midthumb: "width=320&height=240&resizemode=75", // Photo Listing widget thumb, etc Aspect Ratio 4:3
    largethumb: "width=380&height=285&resizemode=75", // Lead Images Aspect Ratio 4:3
    amplargethumb: "width=1600&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only videoshow
    amplargethumbarticle: "width=1200&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only for article
    smallwidethumb: "width=200&height=111&resizemode=75", // For video listing widgets Aspect Ratio 16:9
    largewidethumb: "width=380&height=214&resizemode=75", // For videowidget lead image and videoshow Aspect Ratio 16:9
    posterthumb: "width=210&height=281&resizemode=4", // Moview Posters
    squarethumb: "width=200&height=200&resizemode=75", // for two colum layout
    rectanglethumb: "width=160&height=103&resizemode=75", // for rectangle flags
    gnthumb: "width=200&resizemode=4", // for Gadget now
    gnthumbWithHeight: "height=150&resizemode=4", // for GN PDP, need height
    webstoriesthumb: "width=300&height=500&resizemode=4", // web stories Photo Listing widget thumb",
    webstoriesthumbLarge: "width=364&height=607&resizemode=4", // web stories Photo Listing widget thumb",
    widecardthumb: "width=600&height=315&resizemode=6", // End Article Card thumb 16: 9",
  },
  sso: {
    BASE_URL: "https://navbharattimes.indiatimes.com", // jsso
    SSO_CHANNEL: "nbt-wap",
    GADGET_CHANNEL: "hindi-gadgetsnow-wap",
    stg: {
      BASE_URL: "https://langdev.indiatimes.com",
      MYTIMES_URL_USER: "https://mytest.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
      MYTIMES_URL_SETTINGS: "https://jssostg.indiatimes.com/sso/identity/profile/edit?channel=tm",
      SSO_URL_LOGIN: "https://jssostg.indiatimes.com/sso/identity/login",
      SSO_URL_LOGOUT: "https://jssostg.indiatimes.com/sso/identity/profile/logout/external",
      SSO_URL_GETTICKET: "https://jssostg.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
      SOCIAL_API_INTEGRATOR: "https://testsocialappsintegrator.indiatimes.com/socialsite",
      SSO_BASE_URL: "https://jssostg.indiatimes.com/sso/crossdomain",
      SSO_CROSSWALK: "https://jssocdnstg.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
      SSO_WIDGET_URL: "https://jssocdnstg.indiatimes.com/crosswalk/133/widget/main.bundle.js",
    },

    SSO_BASE_URL: "https://jsso.indiatimes.com/sso/crossdomain",
    SSO_CROSSWALK: "https://jssocdn.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
    SSO_WIDGET_URL: "https://jssocdn.indiatimes.com/crosswalk/34/widget/main.bundle.min.js",
    MYTIMES_URL_USER: "https://myt.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
    MYTIMES_URL_SETTINGS: "https://jsso.indiatimes.com/sso/identity/profile/edit?channel=nbt",
    SSO_URL_LOGIN: "https://jsso.indiatimes.com/sso/identity/login",
    SSO_URL_LOGOUT: "https://jsso.indiatimes.com/sso/identity/profile/logout/external",
    SSO_URL_GETTICKET: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
    MYTIMES_ALREADY_RATED: "https://myt.indiatimes.com/mytimes/alreadyRated?appKey=",
    MYTIMES_ADD_ACTIVITY: "https://myt.indiatimes.com/mytimes/addActivity?appKey=",
    SSO_TRUECALLER_visibility: 4,
    PROFILE_URL: "https://mytimes.indiatimes.com/profile",
    SOCIAL_API_INTEGRATOR: "https://socialappsintegrator.indiatimes.com/socialsite",
    SSO_URL_NewsTicket: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1",
    SSO_URL_SubStatus: "https://webapi.sendpal.in/api/v1/get/user/nbt/status?dataformat=json",
    SSO_URL_unsubscribe: "https://webapi.sendpal.in/api/v1/multiple/unsubscribe/nbt?dataformat=json",
    SSO_URL_subscribe:
      "https://webapi.sendpal.in/api/v1/add/subscription/nbt?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=16",
    SSO_URL_Subscribe_ID: `https://webapi.sendpal.in/api/v1/add/subscription/nbt?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=`,
    SSO_URL_confirm: "https://webapi.sendpal.in/api/v1/confirm/subscription/nbt?dataformat=json",
    APP_KEY: "NBTO",
    APP_KEY_TECH: "NBTGTECH",
  },
  MYTIMES_PROFILE: "https://mytimes.indiatimes.com/?channel=nbt",
  TimesPoint: {
    jsDev: "https://test.timespoint.com/tpwidgets-test/static/dist/js/main.js",
    jsProd: "https://image.timespoints.iimg.in/tpwidgets/static/dist/js/main.js",
    channels: ["tml", "nbt", "eisamay", "tlg"],
    // status: true,
    pcode: "NBTO",
    scode: "NBTO",
    activities: {
      DAILY_CHECKINS: "act4027839",
      DAILY_CHECKINS_MOBILE: "act4045829",
      READ_ARTICLE: "act4770893",
      WATCH_VIDEOS: "act4844649",
      SH_FB: "act4928261",
      SH_TW: "act4952901",
      LOGIN: "act4244726",
      MOVIE_RATE: "act5013937",
      // Fired by MyProfile team
      MOVIE_REVIEW: "act5053085",
      VIEW_PHOTO: "act5083741",
      LIVE_BLOG: "act4327470",
      SUB_NL: "act4393050",
      REGISTER: "act5105942",
      // Fired by MyProfile team
      COMMENT: "act5325178",
      SUB_NOTIFICATION: "act4426590",
      // Not found for staging
      CHECKIN_BONUS_DESKTOP: "act4112300",
      // Not found for staging
      CHECKIN_BONUS_MOBILE: "act4135453",
      WHATSAPP_SHARE: "act4184299",
    },
    campaingHistoryName: {
      desktop: "campaign5485837",
      mobile: "campaign5575010",
    },
    campaignDays: 5,

    stg: {
      pcode: "NBTO",
      scode: "NBTO",
      campaingHistoryName: {
        desktop: "campaign2567007",
        mobile: "campaign2683205",
      },
      activities: {
        DAILY_CHECKINS: "act6038850",
        DAILY_CHECKINS_MOBILE: "act6086046",
        READ_ARTICLE: "act6446631",
        WATCH_VIDEOS: "watch_video",
        SH_FB: "sh_fb",
        SH_TW: "sh_tw",
        LOGIN: "act5444979",
        MOVIE_RATE: "act5493868",
        // Fired by MyProfile team
        MOVIE_REVIEW: "act5531742",
        VIEW_PHOTO: "view_photo",
        LIVE_BLOG: "act6658917",
        SUB_NL: "sub_nltr",
        REGISTER: "act6693566",
        // Fired by MyProfile team
        COMMENT: "cmnt",
        SUB_NOTIFICATION: "act752838",
        CHECKIN_BONUS_DESKTOP: "act6527944",
        CHECKIN_BONUS_MOBILE: "act6550840",
        WHATSAPP_SHARE: "act6730980",
      },
    },

    TP_FAQ_MSID: "79545247",
    NP_DOMAIN: {
      production: "https://npcoins.indiatimes.com",

      development: "https://nprelease.indiatimes.com",
      stg1: "https://nprelease.indiatimes.com",
      stg2: "https://nprelease.indiatimes.com",
    },

    TP_DOMAIN: {
      production: "https://tpapi.timespoints.com",

      development: "https://test.timespoints.com/tpapi",
      stg1: "https://test.timespoints.com/tpapi",
      stg2: "https://test.timespoints.com/tpapi",
    },

    SDK_DOMAIN: {
      production: "https://image.timespoints.iimg.in",

      development: "https://test-img.timespoints.com",
      stg1: "https://test-img.timespoints.com",
      stg2: "https://test-img.timespoints.com",
    },

    tpwidgetJS: {
      production: "/tpwidgets/dist/js/tpwidget.js",

      development: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg1: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg2: "/static/tpwidgets/static/dist/js/tpwidget.js",
    },

    //* * Moved to common config */
    tpPage: "/timespoints.cms",
    tpRedeemLink: "https://www.timespoints.com/products",
  },
  Comments: {
    appkey: "NBTO",
    topComments: {
      appkey: "NBTO",
      sortcriteria: "AgreeCount",
      order: "desc",
      size: "1",
      lastdeenid: "0",
      after: "true",
      withReward: "false",
      pagenum: "1",
    },
    allComments: {
      appkey: "NBTO",
      sortcriteria: "CreationDate",
      order: "asc",
      size: "6",
      lastdeenid: 0,
      after: true,
      withReward: false,
      pagenum: 1,
    },
  },
  pages: {
    astro: "17335279",
    sports: "2279790",
    jokes: "12545605",
    business: "2279786",
    mktwdt: "18572282",
    education: "2279784",
    citizenreporter: "54234500",
    automobile: "2355188",
    elections: "63828428",
    techreview: "77498664",
    tech: "19615041", // test id
    iplHomePage: "63286582",
    commonwealth: "63440665",
    fifa: "64401805",
    wcHomePage: "86773537",
    apanabazaar: "71186319",
    giftsection: "82049727",
    stateSection: "2279808",
    gadgethome: "83349039",
    gnreview: "83349331",
    gadgetsnow: {
      video: "83709144",
    },
    budget: "50994837",
    budget_you: "97254403",
    lifestyle: "2354729",
  },
  iplpages: {
    venues: "63297252",
    teams: "63297211",
    pointsTable: "63297178",
    miniSchedule: "63297281",
  },
  t20wcpages: {
    venues: "86773637",
    teams: "86773941",
    pointsTable: "86773614",
    miniSchedule: "86773566",
  },
  redis: {
    host: "127.0.0.1",
    port: "6379",
    db: "1",
    isRedisCachingSupported: true,
  },
  etIframes: {
    sensex: "https://navbharattimes.indiatimes.com/market_nbtbusiness.cms",
    stokes: "https://widget.economictimes.indiatimes.com/stock_nbtbusiness1.cms",
    rateOfTheDay: "https://widget.economictimes.indiatimes.com/qetquote_nbtbusiness1.cms",
  },
  // To print label in listing node at bottom right corner [templatename, label]
  listNodeLabels: {
    articlelist: ["articlelist"],
    news: ["articleshow"],
    photo: ["photoshow"],
    slideshow: ["photoshow"],
    video: ["videoshow"],
    videolist: ["videolist"],
    photolist: ["photoarticlelist"],
    lb: ["liveblog", "लाइव अपडेट"],
    moviereview: ["moviereview", "मूवी रिव्यू"],
    movieshow: ["movieshow", "मूवी"],
    poll: ["pollsurvey", "पोल"],
  },
  photoListView: "47882310",
  miniTvMoreVideos: "4901865",
  // Used In AnchorLinkCard
  routes: [
    "/newsbrief",
    "/exitpolls/",
    "/results/",
    "/result",
    "education.cms",
    "business.cms",
    "elections.cms",
    "/electionlist/",
    "/articlelist/",
    "/photoarticlelist/",
    "/photomazza/",
    "/photolist/",
    "/photoshow/",
    "/articleshow/",
    "/moviereview/",
    "/movieshow/",
    "/movieshow/",
    "/liveblog/",
    "/videolist/",
    "/videoshow/",
    "/topics/",
    "/teams/",
    "/venues/",
    "/pointstable/",
    "/iplt20.cms",
    "/schedule/",
    "/sportsresult/",
    "/elections/assembly-elections/results",
    "/reviews/",
    "/timespoints",
    "/newsbrief",
    "/gulf",
  ],

  staticPagesDir: "/var/www/html/testpages/",

  slike: {
    apikey: "nbtmwebtoi54",
    // apikey: "lng54web5a7fu96zzo",
    snapchatapikey: "lng54mweb5afm96lgz9",
    ampapikey: "lng54googleamp5a5nglz9l9",
    default_slikeid_minitv: "1x13qpaggu", // Times-Now
    nextvideo_domain: "https://mtpwafeeds.indiatimes.com",
    default_pl_videolist: "/feeds/videpostroll_v5_slike/4901865.cms?feedtype=json&callback=cached",
  },

  slikeAdCodes: {
    home: "home,4901865",
    auto: "2355188,28471009",
    bharat: "1564454",
    cricket: "3521869",
    duniya: "2279801",
    haryana: "21236773",
    "josh-jawani": "3041664",
    jokes: "12545518,5556078",
    lucknow: "21248218",
    "share-market": "2279786,11873677",
    "movie-masti": "2279793,4901881,11872954",
    mumbai: "5722181",
    "movie-review": "2325387",
    "other-cities": "21236618",
    other: "other",
    photo: "2339144",
    rajya: "33503484",
    rashifal: "17127056,48972527",
    "score-card": "999999",
    sahar: "33503484",
    "super-hit": "999999",
    tech: "19615041,20104392",
    "top-news": "696089404,4901886",
    "uttar-pradesh": "21236867",
    vichar: "2007740431",
  },

  gRecaptchaKey: "6LcxSGUUAAAAAPsGPKVpEkLKxnuluuqDKa1AivEN",

  ga: {
    gtm: "GTM-NS5K3GZ",
    gtm4: "G-DGH2MSM4NL",
    ampgtm: "GTM-NS5K3GZ",
    gverifyCode: "GdaeWTVPddYtkw-2hEyDpLYMw9SjsNr4dS5Z-9tfcT0",
    gatrackid: "UA-429254-3",
    ga4trackid: "G-DGH2MSM4NL",
    gaprofile: "['navbharattimes.com', 'superpacer.in', 'm.nbt.in']",
  },

  growthrx: {
    stg: {
      id: "ge3cad4f9",
    },
    prod: {
      id: "gd029f7bb",
    },
    gn: {
      stg: {
        id: "g26611efa",
      },
      prod: {
        id: "gcedac275",
      },
    },
  },

  appexclusive_ga: {
    category: "Wap to App install",
    action: "click",
    label: "articlelist_topsection",
  },
  poll_ga: {
    poll_submit: {
      category: "pollSurvey",
      action: "submit",
      label: "pollsubmit",
    },
    poll_result_loggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "loggedin",
    },
    poll_result_nonloggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "non-loggedin",
    },
  },

  photoshow_app_install: {
    ga_object: {
      category: "Wap to App install",
      action: "click",
      label: "photo show",
    },
  },
  // sso_ga: {
  //   truecaller_requestscreen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen Request",
  //   },
  //   truecaller_screen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen View",
  //   },
  //   truecaller_screencontinue: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Continue",
  //   },
  //   truecaller_skip: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Skip",
  //   },
  //   truecaller_loginsuccess: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Login Successful",
  //   },
  // },
  comscore: { c1: "2", c2: "6036484" },

  applinks: {
    android: {
      hrnav: "https://navbharattimes.onelink.me/cMxT/c14f8b60",
      asshow: "https://navbharattimes.onelink.me/cMxT/5cd132ca",
      photoshow: "https://navbharattimes.onelink.me/cMxT/acad793f",
      // openinapp: 'https://m.eisamay.com/nbt_appexclusive.cms?msid=',
      serviceDrawer: "https://navbharattimes.onelink.me/cMxT/dbb77f22",
      social: "https://navbharattimes.onelink.me/cMxT/ebb4e433",
      oip_appexclusive: "https://m.eisamay.com/nbt_openinapp.cms?msid=",

      // photoshow_new:'https://m.eisamay.com/nbt_appexclusive.cms?type=photo&msid=' //using for new photoshow app install where we are showing lesser number of slides

      // https://navbharattimes.onelink.me/cMxT/b256ac1
    },
  },
  appdeeplink: {
    domain: "https://navbharattimes.onelink.me",
    shortcode: "cMxT",
    c: "Internal_Campaign",
    pid: {
      hrnav: "WAP_HRNAV",
      serviceDrawer: "WAP_BOTTOM",
      news: "WAP_MWEB",
      article_end: "WAP_AS",
      photo: "WAP_PG",
      toparticle: "WAP_Top%20Articles",
      extphoto: "WAP_Home_Photostrip",
      photoshow: "WAP_Photoshow",
      campaign: "WAP_Election",
      campaignHome: "WAP_Election_Home",
      openinapp_as: "NBT_AS_Brandwire",
      openinapp_al: "NBT_AL_Brandwire",
      recommended: "WAP_Home_Photostrip_Reco",
      photofeature: "WAP_MWEB",
      photoFeature: "WAP_MWEB",
      recipe: "WAP_MWEB",
      videoshow: "WAP_VideoShow",
      topStrip: "WAP_Top_Strip",
      topStripAS: "New_Top",
      articlelist: "WAP_ArticleList",
      videolist: "WAP_VideoList",
      photolist: "WAP_PhotoList",
      continueInApp: "Continue_App",
      mwebHP: "WAP_MWEB_HOME",
      ampHP: "WAP_AMP_HOME",
      sharing: "WAP_Sitesharing",
    },
    listdefaultUrl: "https://navbharattimesfeeds.indiatimes.com/feeds/app_listing/<MSID>.cms?feedtype=json",
    openapp: "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times",
    opennews:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dnews-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openphoto:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openextphoto:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dp-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openhtmlview:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BURL%7D",
    opensection:
      "nbtreaderactivities://open-%24%7C%24-pub%3D2:Navbharat Times-%24%7C%24-type%3Dsection-%24%7C%24-sectionID%3D%7BsectionID%7D-%24%7C%24-sectionName%3D%7BsectionName%7D-%24%7C%24-id%3D%7BMSID%7D",
    openphotofeature:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3DphotoFeature-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openrecipe:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Drecipe-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openvideoshow:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dvideo-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openarticlelist:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dnews-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openphotolist:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dphoto-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openvideolist:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dvideo-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openContinueInApp:
      "nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D&deep_link_value=nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D&is_retargeting=true&af_web_dp=https%3A%2F%2Fnavbharattimes.indiatimes.com%2F",
  },
  pushNotification: {
    cookieName: "notifypopup",
    defaultThumb: "https://static.langimg.com/thumb/54585494/pic.jpg?width=100&height=100",
    heading: "लेटेस्ट ब्रेकिंग न्यूज के लिए नोटिफ़िकेशन सब्सक्राइब करें. 'Allow' पर क्लिक करें.",
  },

  weather: {
    geoLocationApi: "https://geoapi.indiatimes.com/?cb=1",
    defaultCity: "Delhi",
    citiesJson: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_geocities.cms",
    weatherFeed: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_weathertoday.cms?lat=",
    heading: "आज का तापमान",
    cityText: "पढ़ें अपने शहर की खबरें",
  },
  pollution: {
    heading: "प्रदूषण",
    headingV1: "आपके शहर में पलूशन का हाल",
    status: {
      good: "ठीक",
      moderate: "मीडियम",
      unhelathfSG: "सेंसटिव ग्रुप के लिए घातक",
      unhealthy: "खराब",
      veryUnhealthy: "बहुत खराब",
      hazardous: "खतरनाक",
    },
    url: "https://navbharattimes.indiatimes.com/state/pollution/tracker",
  },
  fuel: {
    heading: "फ्यूल",
    feedUrl: "https://toibnews.timesofindia.indiatimes.com/fuelprice/latestPrice",
  },

  oneTapSignIn: {
    smartlockurl: "https://smartlock.google.com/client",
    isViewGaTracked: false,
    eventGAObj: { overrideEvent: "tp_login_new", category: "Login", action: "One_Tap", label: "" },
    text: {
      oneTapSuccessMsg: "आपने सफलतापूर्वक लॉगइन कर लिया है",
      oneTapErrorMsg: "Oops! कुछ गड़बड़ है। कृपया दोबारा कोशिश करें।",
      oneTapBtnText: "दोबारा कोशिश करें",
    },
    constants: {
      onetapIgnoreDays: 15,
      onetapCookie: "oneTapNextShow",
      onetapIframeCheckTimer: 2000,
      smartlockJsLoadTimer: 10000,
      clientId: "196250535198-r0370bk9l9hj7o6qajsok78ggd524dk8.apps.googleusercontent.com",
      channel: "nbt-wap",
      jssoAPIGetURL: "https://jsso.indiatimes.com/sso/services/gponetaplogin/verify",
    },
  },
  ZodiacSigns: {
    url: "#",
    data: [
      { name: "aries", regName: "मेष", pos: 1 },
      { name: "taurus", regName: "वृषभ", pos: 2 },
      { name: "gemini", regName: "मिथुन", pos: 3 },
      { name: "cancer", regName: "कर्क", pos: 4 },
      { name: "leo", regName: "सिंह", pos: 5 },
      { name: "virgo", regName: "कन्या", pos: 6 },
      { name: "libra", regName: "तुला", pos: 7 },
      { name: "scorpio", regName: "वृृश्चिक", pos: 8 },
      { name: "sagittarius", regName: "धनु ", pos: 9 },
      { name: "capricorn", regName: "मकर ", pos: 10 },
      { name: "aquarius ", regName: "कुंभ ", pos: 11 },
      { name: "pisces", regName: "मीन", pos: 12 },
    ],
  },
  cricplay_widget: {
    schedulelink: "/sports/cricket/icc-world-cup/schedule/69160257.cms",
    deeplink:
      "https://navbharattimes.onelink.me/cMxT?pid=WAP_CricPlay&c=Internal_Campaign&af_dp=nbtreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D2%3ANavbharat%2520Times-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3Dhttps%3A%2F%2Fcrpl.app.link%2Fh2nR5IiRxW",
    wincashtxt1: "अपनी पसंदीदा क्रिकेट टीम बनाएं और",
    wincashtxt2: "जीतें कैश",
    appdwntxt: "NBT ऐप डाउनलोड करें",
  },
  ads: {
    ampInuxuAd:
      "https://adgebra.co.in/afpf/IBN_AMP.html?domain=amp-navbharattimes.indiatimes.com&pubid=3613&slotId=1&templateId=4652&accessMode=1&divId=div_407860734567731&cache=123",
    ampAdChannelId: "636b5a20946d483d8d22d8ff",
    ampAdAfter:
      "https://player.avplayer.com/amp/ampiframe.html?AV_TAGID=63515d5e94a33d18c85d6633&AV_PUBLISHERID=6215f6d82b93b72d275027d7",
    gptUrl: "",
    ctnAddress: "https://static.clmbtech.com/ad/commons/js/2310/colombia_v2.js",
    dmpUrl: "https://static.clmbtech.com/ase/2310/16/aa.js",
    isvPreRollUrl:
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/7176/NBT_MWeb/NBT_Mweb_Videoshow/NBT_Mweb_Videoshow_ISV&description_url=https%3A%2F%2Fnavbharattimes.indiatimes.com%2F&tfcd=0&npa=0&sz=300x230%7C300x400%7C320x25%7C300x415%7C360x480%7C359x200%7C400x315&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
    ADS_PRIORITY: "FAN",
    profileid: "2930",
    exchangeId: "692987",
    ctnads: {
      inline: {
        ctnId: "129186",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      ampinline: "326944",
      ampinlinehome: "326943",
      ampctnhometop: "330642", // For AMP Home Page

      ctnlist: {
        ctnId: "129186",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      ctnlistTop: "354481",
      ctnlist1: {
        ctnId: "129186",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      // "ctnlist": "320650",
      ctnpgl1: "341348",
      ctnpgl2: "341348",
      ctnvll1: "341346",
      ctnvll2: {
        ctnId: "341347",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_UPD_New_AL_INS2_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnbiglist: {
        ctnId: "320608",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_Direct_AL_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnsluglist: {
        ctnId: "355638",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_AL_INS_NEW_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listdefault: {
        ctnId: "129186",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      listhorizontalsmall: {
        ctnId: "129186",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      ctnmgid: "M769011ScriptRootC",
      ctnMmgid: "1258771",
      ctnBmgid: "1258772",
      ctnmgidurl: "https://jsc.mgid.com/t/i/til.navbharattimes.indiatimes.com",

      ctnshow: "323134",
      ctnmidart: "334310",
      ctnnative: "323133",
      ctnmidart_test: "336104", // for test page only requested by sales
      ctninlineshow: "208371",
      ctnrecommended: {
        ctnId: "129186",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      ctnrhsvideo: "341349",
      ctnshowvideo: "334310", // video ad on articleshow
      ctnvs: "341346", // Video Show
      mrec3CTN: "518053", // ctn ads in place of mrec3
      mrec2CTN: "518632", // /ctn ads in place of mrec2
      ampctnvs: {
        id: "337264",
        width: "320",
        height: "110",
        minHeights1: "188px",
        minHeights2: "188px",
        minHeights3: "188px",
        minHeights4: "188px",
      }, // Video Show AMP
      // "ctnhome" : "316371",  // caraousal ad code, just for test
      // "ctnhometop" : "206698",
      ctnhome: {
        ctnId: "129169",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_HP_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      homedefault: {
        ctnId: "129169",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_HP_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      homedefaultsmall: {
        ctnId: "129169",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_HP_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      homehorizontal: {
        ctnId: "129169",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_HP_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      homevertical: {
        ctnId: "129169",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_HP_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      homehorizontalsmall: {
        ctnId: "129169",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_HP_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      ctnhometop: "206698", // updated
      ctnhomevideo: "315058", // video ad , updated
      ctnbighome: {
        ctnId: "320607",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_Direct_HP_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      homeibeat: {
        ctnId: "129169",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_HP_Bid_Experiments_320",
        dfpSize: [320, 100],
      },

      ctnslider: "210645",
      ctnVideoURL: "https://navbharattimes.indiatimes.com/ads_native_video_dev.cms",

      adspositionsPhoto: "-3-,-5-,-9-,-14-,-20-,-27-,-36-,-45-,-55-",
      ctnbigphoto: {
        ctnId: "320609",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_Direct_PG_Bid_Experiment_300",
        dfpSize: [300, 250],
      },

      ctnint: "324441",
      ctnint_test: "337410",
      adspositionsLiveblog: "-5-,-10-,-15-,-20-,-25-,-30-,-35-,-40-",
      ctncookievalue: "ce_aemsp",
      ctnbccl: "340361",

      ctntopicsall: {
        ctnId: "129186",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      ctntopicsnews: {
        ctnId: "129186",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
        dfpSize: [320, 100],
      },
      ctntopicsphotos: "341348",
      ctntopicsvideos: {
        ctnId: "341347",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_UPD_New_AL_INS2_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnTechGL: "331475", // Gadget Config
      ctnTechPDP: {
        ctnId: "325713",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Gadget_Mweb_ROS_Inarticle_Bid_Experiment_300",
        dfpSize: [300, 250],
      }, // Gadget Config
      ctnTechCL: "356624", // Gadget Config
      ctnTechCDP: {
        ctnId: "325713",
        dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Gadget_Mweb_ROS_Inarticle_Bid_Experiment_300",
        dfpSize: [300, 250],
      }, // Gadget Config
      ctnTechTC: "356624", // Gadget Config
      tech: {
        ctntech: {
          ctnId: "129186",
          dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
          dfpSize: [320, 100],
        },
        ctntechTop: "354489",
        ctntechlist: {
          ctnId: "129186",
          dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
          dfpSize: [320, 100],
        },
        ctntechoth: {
          ctnId: "129186",
          dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Mweb_ROS_Bid_Experiments_320",
          dfpSize: [320, 100],
        },
        ctntechvideo: {
          ctnId: "348066",
          dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Tech_Mweb_HP_VDO_Bid_Experiment_320",
          dfpSize: [320, 100],
        },
        ctnbiglist: "331475",
        ctncomparevideo: {
          ctnId: "325713",
          dfpSlot: "/7176/NBT_MWeb/NBT_MWeb_Bid_Experiment/NBT_Gadget_Mweb_ROS_Inarticle_Bid_Experiment_300",
          dfpSize: [300, 250],
        }, // gadget list
        ampctncomparevideo: "356622",
        ampctnbiglist: "356621",
      },
      ctnEoaFeed: "505704",
      ctnInImage: "518951",
      ctnPreRoll: "518050",
      ctnNonVodPreRoll: "518432",
    },
    // For ESI Ads
    ctnslots: {
      atf: "327295",
      ctnshow: "323134",
      ctnbiglist: "",
      ctnbigphoto: "",
      midart: "327294",
      articleshow: "ctnshow,atf,midart",
      liveblog: "",
      photoshow: "",
      videoshow: "",
      videolist: "",
    },

    fanads: {
      home: {
        atf: {
          id: "515634995914437_515721679239102",
          size: "320x50",
        },
        fbn: {
          id: "515634995914437_515720492572554",
          size: "320x50",
        },
      },
      articlelist: {
        atf: {
          id: "515634995914437_515720639239206",
          size: "320x50",
        },
        fbn: {
          id: "515634995914437_515720735905863",
          size: "320x50",
        },
        mrec1: {
          id: "515634995914437_515721779239092",
          size: "300x250",
        },
      },
      articleshow: {
        atf: {
          id: "515634995914437_515720825905854",
          size: "320x50",
        },
        fbn: {
          id: "515634995914437_515720922572511",
          size: "320x50",
        },
        mrec1: {
          id: "515634995914437_515721165905820",
          size: "300x250",
        },
        mrec2: {
          id: "515634995914437_515721392572464",
          size: "300x250",
        },
      },
      others: {
        atf: {
          id: "515634995914437_515721575905779",
          size: "320x50",
        },
        fbn: {
          id: "515634995914437_515721679239102",
          size: "320x50",
        },
        mrec1: {
          id: "515634995914437_515721779239092",
          size: "300x250",
        },
      },
    },

    dfpads: {
      adSiteName: "NBT",
      adSiteShortName: "NBT",
      amp: {
        atf: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_ATF",
        fbn: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_FBN",
        mrec1: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_Mrec",
        mrec2: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_Mrec1",
        mrec3: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_Mrec3",
        mrec4: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_Mrec4",
        mreceoa: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_Mrec2",
        parallax: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_FC",
        perp_Atf: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_PERP_ATF",
        perp_Fbn: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_PERP_FBN",
        perp_Mrec1: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_PERP_Mrec",
        perp_Mrec2: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_PERP_Mrec1",
        bottomCTNamp: "215442",
        ampcarousalad: "215441",
      },
      topatf: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_OTH_Fixed",
      cubead1: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_MWEB_OTH_CUBE_195x85",
      cubead2: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_MWEB_OTH_CUBE2_195x85",
      cubeheadad1: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_MWEB_OTH_CUBE_195x30",
      cubeheadad2: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_MWEB_OTH_CUBE_195x30",
      cubeheadad3: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_MWEB_OTH_CUBE2_195x30",
      cubeheadad4: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_MWEB_OTH_CUBE2_195x30",
      gndineoutad: "/7176/NBT_MWeb/NBT_MWeb_ROS/NBT_MWEB_ROS_TextLink_320",
      andbeyond: "/7176/NBT_MWeb/NBT_MWeb_ROS/NBT_Mweb_ROS_Andbeyond_1x1",
      inimage: "/7176/NBT_MWeb/NBT_MWeb_ROS/NBT_Mweb_ROS_Inimage_1x1",
      multiplex: "/7176/NBT_MWeb/NBT_MWeb_ROS/NBT_MWEB_ROS_Bottomwidget",
      canvasAd: "/7176/NBT_MWeb/NBT_MWeb_ROS/NBT_MWeb_ROS_Mcanvas_1x1",
      networkPGT: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_OTH_OOP",
      interstitial: "ca-pub-1902173858658913",
      dfpint: "/7176/NBT_MWeb/NBT_MWeb_Home/NBT_Mweb_HP_INT",
      trk: "/7176/NBT_MWeb/NBT_MWeb_ROS/NBT_MWeb_ROS_Trk_1x1",
      osv: "/7176/NBT_MWeb/NBT_MOBILE_WEB_ROS/NBT_Mweb_Outstream_1x1",
      sitesync: "/7176/NBT_MWeb/NBT_MWeb_Home/NBT_MWeb_HP_SiteSync_1x1",
      nativead: "/7176/Languages/NBT_MWeb/NBT_Mweb_Native_300x250",
      nativeadamp: "/7176/Languages/NBT_AMP/NBT_AMP_Native_300x250",
      ampIntAd: "/7176/NBT_AMP/NBT_AMP_ROS/NBT_AMP_ROS_INT",
      budgetSlug: "/7176/Navbharattimes/NBT_Budget/NBT_BDGT_SLG",
      test1: {
        atf: {
          id: "div-gpt-ad-91355108653883-0",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_1_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-91355108653883-1",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_1_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-91355108653883-mrec1",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_1_ROS_Mrec1",
          size: [
            [300, 250],
            [320, 480],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-91355108653883-mrec2",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_1_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-91355108653883-mrec3",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_1_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-91355108653883-mrecInf",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_1_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      test2: {
        atf: {
          id: "div-gpt-ad-9135510865388-033",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_2_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-133",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_2_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-91355108653884-mrec1",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_2_ROS_Mrec1",
          size: [
            [300, 250],
            [320, 480],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-91355108653883-mrec2",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_2_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-91355108653883-mrec3",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_2_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-91355108653883-mrecInf",
          name: "/7176/NBT_MWeb/Test/NBT_MWeb_Test_2_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      others: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_ATF",
          size: [
            [300, 250],
            [320, 100],
            [320, 50],
            [336, 280],
            [250, 250],
            [300, 50],
          ],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-2",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_FBN",
          size: [
            [320, 50],
            [300, 50],
          ],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_MREC1",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_MREC2",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_MREC3",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec4: {
          id: "div-gpt-ad-9135510865388-mrec4",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_MREC4",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec5: {
          id: "div-gpt-ad-9135510865388-mrec5",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_MREC5",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec6: {
          id: "div-gpt-ad-9135510865388-mrec6",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_MREC6",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec7: {
          id: "div-gpt-ad-9135510865388-mrec7",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_MREC7",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_MrecINF",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        slug: {
          id: "div-gpt-ad-9135510865388-slug",
          name: "/7176/NBT_MWeb/NBT_MWeb_Others/NBT_Mweb_Others_Slug1",
          size: [
            [300, 100],
            [320, 100],
          ],
        },
        parallax: {
          id: "div-gpt-ad-9135510865388-parallax",
          name: "/7176/NBT_Mweb/NBT_Mweb_Others/NBT_Mweb_Others_FC",
          size: [[300, 600]],
        },
        refreshnews: "/7176/NBT_MWeb/NBT_Mweb_News/NBT_Mweb_News",
      },
    },
  },
  gold: {
    logoClass: "nbtgold",
    redirectUrl:
      "https://navbharattimes.indiatimes.com/navbharatgold?utm_source=gold_navigation&utm_medium=mobile&utm_campaign=nbtgold",
    goldNavigationApi: "https://navbharattimes.indiatimes.com/navbharatgold/nbtgoldsectiondata.cms?feedtype=sjson",
    homepagePodCastUrl: "https://navbharattimes.indiatimes.com/navbharatgold/podcastplayer.cms",
    goldTopNewsApi: "https://navbharattimes.indiatimes.com/navbharatgold/feeds/topnewslist.cms?feedtype=sjson",
  },
  plus: {
    disablePlus: false,
    logo: "https://static.langimg.com/thumb/85000253/navbharat-times.jpg?height=36&resizemode=4",
    home: "81964570",
    video: "81964592",
    shortName: "NBT Plus",
    articleReferrerCd: 23,
    articleTypeCd: 20,
    premiumText: "प्रीमियम खबरें",
    homeText: "होम",
  },
  // dailyMotion: { channel: "navbharattimes", playerId: "x54ti", syndication: "278256" },
  listingmsid: "88295605",
  lifestylePhotoshow: "3531342",
  plusWidgetObj: {
    logo: "https://static.langimg.com/thumb/85000253/navbharat-times.jpg?height=36&resizemode=4",
    altText: "navbharat-times",
    premiumText: "प्रीमियम खबरें",
    thumb: "https://static.langimg.com/thumb/76874587/navbharat-times.jpg?width=540&height=405&resizemode=4",
  },
  loginWall: {
    heading: "एनबीटी प्लस पढ़ना जारी रखने के लिए कृपया साइन-इन करें",
    subHeading: "एनबीटी प्लस की खासियत",
    label1: "विज्ञापनमुक्त कंटेंट",
    label2: "एक्सक्लूसिव खबरें और वीडियो",
    label3: "हर खबर और वीडियो पर टाइम्स पॉइंट कमाएं",
  },
  foryoupage: {
    navUrl: "/foryou?utm_source=personalisation&utm_medium=foryoupage&utm_campaign=more-link-super-hit-widget",
    navLabel: "आपके लिए",
    cid: "2310:49",
    agencyFilters: ["भाषा", "Brandwire", "SPOTLIGHT"],
  },
  authorDetails: {
    agencyName: "नवभारतटाइम्स.कॉम",
    authorName: "NBT NEWS DESK",
    editorLink: "https://navbharattimes.indiatimes.com/nbtreporter/author-NBT-479254397.cms",
    editorLabel: "Written By",
  },
  recipeArticlelistMsid: "59541333",
  cityLandingPage: "/state/articlelist/2279808.cms",
  timesXP: {
    hostName: "nbt_xp",
    xpUrl: "https://nbtfeed.timesxp.com/langapi",
    appUrl: "https://hindi.timesxp.com",
    wapCode: "hindiTxp",
  },
  vdoAI: {
    isEnabled: true,
    scriptUrl: "//a.vdo.ai/core/navbharattimes-indiatimes/vdo.ai.js",
    containerID: "vdo_ai_div",
  },
  orgAddress: {
    addressLocality: "Sector - 16A, Film City",
    addressRegion: "NOIDA, Uttar Pradesh",
    postalCode: "201301",
  },
  cleoPlayer: {
    apikey: "lang-n9GgmFF518E5Bknb",
  },
};
