module.exports = {
  hostid: "286", // GN Config
  channelid: "696089404",
  mediawireslot: "13",
  wapsitename: "Samayam Telugu",
  wapsiteregionalname: "సమయం తెలుగు",
  siteName: "telugu.samayam.com",
  staticSiteName: "static.tlg.indiatimes.com",
  fbIAcontentId: "515040411993267",
  languagemeta: "te",
  language: "Telugu",
  channelCode: "tlg",
  langnetstorageBasePath: "https://langnetstorage.indiatimes.com/langappfeeds",
  wapCode: "telugu",
  gdprID: "TELUGU",
  languagefullName: "Samayam Telugu",
  video: {
    rootId: "47330979",
    newsId: "97083637",
  },
  fbLive: "92082206",
  videoiconurl: "/video-gallery/videolist/47330979.cms",
  rss: "/rss.cms",
  editTrendingMSID: "74951530",
  coronaId: "74471428",
  iospackageid: "1469015977",
  androidpackage: "com.til.telugusamayam",
  deeplinkappid: "telugusamayamactivities",
  deeplinkpubid: "pub=9:Samayam Telugu",
  iosapp_name: "Samayam Telugu App",
  weburl: "https://telugu.samayam.com",
  mweburl: "https://telugu.samayam.com",
  gadgetdomain: "https://telugu.gadgetsnow.com",
  etdomain: "https://telugu.economictimes.com",
  ccaudId: "13540:220",
  ccaudAmp: "13540",
  ccaudIdAmp: "13540:1219",
  indexExchangeUrl: "//js-sec.indexww.com/ht/p/191952-74217596866254.js",
  pwtUrl: "//ads.pubmatic.com/AdServer/js/pwt/23105/3280",
  footerDesktopLink: "https://telugu.samayam.com?mobile=no",
  cookieLessDomain: "https://static.tlg.indiatimes.com",
  domain: "samayam.com",
  webdomain: "telugu.samayam.com",
  mwebdomain: "telugu.samayam.com",
  photogallerydomain: "photogallery.telugu.samayam.com",
  google_site_verification: "6j2LiIEnVIeQivS9Z22g50jOqP1AnqnW9qx247OwWwc",
  twitterHdandler: "@SamayamTelugu",
  logo: "nbt-logo.jpg",
  logo_id: "https://static.langimg.com/thumb/78038853/telugu-samayam.jpg?width=186&resizemode=4",
  logogn_id: "https://static.langimg.com/thumb/78038853/telugu-samayam.jpg?width=186&resizemode=4",
  logoPathGadget: "https://static.langimg.com/thumb/83978675/telugu-samayam.jpg?width=232&resizemode=4",
  googleNews: "https://news.google.com/search?q=telugu%20samayam&hl=te&gl=IN&ceid=IN%3Ate",
  fb: "https://www.facebook.com/samayam.telugu",
  twitter: "https://twitter.com/SAMAYAMTELUGU",
  gplus: "https://plus.google.com/u/0/111247391086283244184/about",
  youtubeUrl: "https://www.youtube.com/channel/UCE8KNq9oibK4AdPw_iWrS1Q",
  linkedInUrl: "",
  shoppingBag: "https://telugu.samayam.com/best-deals-online?category=clothes?utm_source=social_panel",
  izooto: "",
  fullutm: "&utm_campaign=telugumobile&utm_medium=referral",
  slikeshareutm: "utm_source=slikevideo&utm_medium=referral",
  telegramFollowLink: "https://telegram.me/SamayamTelugu_News",
  shortutm: "ma4", // Using for micron
  icon: "https://telugu.samayam.com/favicon.ico",
  breakingNewsFeedUrl: "https://langnetstorage.indiatimes.com/LANGBNews/telugubnews.htm",
  fbsdkurl: "https://connect.facebook.net/te_IN/sdk.js#xfbml=1&version=v3.0",
  fbpage: "https://www.facebook.com/samayam.telugu",
  livebloghpfeed: "",
  livebloghostname: "telugu", // Using to getch liveblog callback feed
  navfeedurl: "https://langnetstorage.indiatimes.com/langappfeeds/telugu_navjson.htm",
  // navfeedurl: "https://spmdev8391.indiatimes.com/off-url-forward/wdt_navjson_v2.cms",
  liveblogbnbewsurl: "",
  moreNews: "More News",
  moreNewsUrl: "https://telugu.samayam.com/headlines.cms",
  glossaryLanding: "https://langnetstorage.indiatimes.com/langappfeeds/tlg_glossarylist_business.htm",
  marketindices: "https://m.economictimes.com/mcoverage_langwidget.cms?language=TEL&type=indices&nofollow=true",
  marketcommodities: "https://m.economictimes.com/mcoverage_langwidget.cms?language=TEL&type=commodities&nofollow=true",
  // logo_schema dimension should be 600*60
  logo_schema: "https://static.langimg.com/thumb/66649598/telugu-samayam.jpg?width=600&resizemode=4",
  logo_alt: "Samayam Telugu - Telugu News",
  siteid: "2147478018",
  viralBrandingLink: "/viral-adda/articlelist/67088530.cms",
  fbpixelid: "",

  astrowidgetId: "57464974",

  fbappid: "417098625162615",
  googleClientId: "586641927846-bi1jtisviubr34u2bg13pc2cijulhjpq.apps.googleusercontent.com",
  bennett: "https://timesofindia.indiatimes.com/bennettjul2020_form_nbt_mweb.cms",

  css:
    "$body-bgcolor:#fff;	$navbar-top-bgcolor:#fff;	$navbar-bg-color:#F5CC10;	$navbar-border-top:#c8cccb;	$navbar-border-shadow:#D8B40D;	$navbar-active-border-bottom-color:#000;	$navbar-link-color:#000;	$hamburger-bg-color:#747474;	$sidenav-bg-color:#fff;	$sidenav-color:#000;	$sidenav-border-bottom:#F5F5F5;	$sidenav-arrow-color:#D1D1D1;	$layer-bg:rgba(0,0,0,0.5);	$breadcrumb-home-color:#DA4848;	$card-border-bottom:#F5F5F5;	$card-bg-color:#8e8e93;	$card-text-color:#191919;	$card-date-color:#bababa;	$home-section-border-bottom:#f5f5f5;	$home-section-heading-border-bottom:#F5CC10;	$home-section-arrow-color:#000000;	$home-section-more-color:#858585;	$home-section-more-border:#CCCCCC;	$footer-background:#585858;	$footer-border-top:#333;	$footer-border-bottom:#7b7b7b;	$footer-heading-color:#e6e6e6;	$footer-text-color:#fff;	$footer-link-color:#d0d0d0;	$footer-trending-color:#95989a;	$footer-copyright-color:#d0d0d0;",
  fontContent:
    "@font-face {font-family: Noto Sans;src: url('https://static.tlg.indiatimes.com/fonts/NotoSansTelugu-Regular.eot');src: url('https://static.tlg.indiatimes.com/fonts/NotoSansTelugu-Regular.eot?#iefix') format('embedded-opentype'),url('https://static.tlg.indiatimes.com/fonts/NotoSansTelugu-Regular.woff2') format('woff2'),url('https://static.tlg.indiatimes.com/fonts/NotoSansTelugu-Regular.ttf') format('truetype');font-weight: normal;font-style: normal;font-display: optional;}",
  fontUrl: "https://static.tlg.indiatimes.com/fonts/NotoSansTelugu-Regular.woff2",
  cricket_SIAPI: {
    minischedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_liupre_te.json",
    schedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_te.json",
    points_table: "https://toicri.timesofindia.indiatimes.com/jsons/stats/Standings/standing_%seriesid%.json",
    scoreboard: "https://toicri.timesofindia.indiatimes.com/jsons/%matchid%_te.json",
    topPlayer: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/feed_topplayer.cms?feedtype=sjson",
  },

  techsectionID: {
    // GN Config
    latestGadgets: "81473265",
    trendingGadgets: "81473404",
    video: "70538423",
    photo: "70538694",
  },

  locale: {
    comment: {}, // don't remove this
    appIconText: "యాప్",
    live_blog: "లైవ్ బ్లాగ్",
    recommendednews: "సూచించబడిన వార్తలు",
    whatsapp_share: "Hey, you might find this interesting: ",
    latest: "లేటెస్ట్",
    most_read: "ఎక్కువగా చదివినవి",
    latest_video: "లేటెస్ట్ వీడియోలు",
    latest_photo: "లేటెస్ట్ ఫోటోలు",
    see_in_app: "యాప్‌లో చూడండి",
    see_in_app_details: "మరిన్ని ఫీచర్ ఫొటోలు యాప్‌లో చూడండి",
    appLinkText:
      "ఏపీ, తెలంగాణకు సంబంధించిన లేటెస్ట్ అప్‌డేట్స్‌, జాతీయ, అంతర్జాతీయ, ఎడ్యుకేషన్, బిజినెస్, సినిమా, ఆధ్యాత్మికం, స్పోర్ట్స్, వైరల్ కథనాల కోసం తెలుగు సమయం యాప్‌ను డౌన్‌లోడ్ చేసుకోండి.",
    actors: "నటులు",
    releaseDate: "విడుదల తేదీ",
    director: "దర్శకుడు",
    genre: "సినిమా శైలి",
    duration: "వ్యవధి",
    readmore: "మరిన్ని చదవండి",
    watchmore: "మరిన్ని చూడండి",
    commentary: "కామెంటరీ",
    scorecard: "స్కోర్ కార్డు",
    photo_maza: "ఫోటో మజా",
    key_words: "మరింత సమాచారం తెలుసుకోండి",
    more_from_topics: "మరింత సమాచారం తెలుసుకోండి",
    brief: {
      tooltip: "ఈ సంక్షిప్త వార్తలు నచ్చినట్లయితే యాప్ డౌన్‌లోడ్ చేసుకోండి",
      limitation_txt: "మరిన్ని సంక్షిప్త వార్తలు చదివేందుకు",
    },
    newsLetter: {
      LS: "5231",
      thankyou: "ధన్యవాదాలు",
      headerText: "రోజువారీ ముఖ్యమైన వార్తల అప్ డేట్స్ కోరుకుంటున్నారా?..",
      joinIn: "చేరండి",
      footerText: "పైన ఉన్న బాక్స్‌లో ఈమెయిల్ ఐడీ నమోదు చేయండి. మీ ఇన్‌బాక్స్‌కు వార్తలు వస్తాయి.",
      verification: "వెరిఫికేషన్ ఈమెయిల్ మీ ఈమెయిల్ అడ్రస్‌కు పంపబడింది",
      already: "మీరు ఇదివరకే న్యూస్‌లెటర్‌కు సబ్‌స్క్రైబ్ చేసుకున్నారు ",
      Subscribed: "మీరు ఇప్పుడు సబ్‌స్క్రైబ్ చెయ్యబడ్డారు",
      errorNetwork: "నెట్‌వర్క్‌లో సమస్య ఉంది! దయచేసి మరల ప్రయత్నించండి!",
      notverified: "మీకు ఈమెయిల్ పంపబడింది! దయచేసి వెరిఫై చెయ్యండి!",
      verified: "మీరు ఇదివరకే వెరిఫై చేసారు",
      unchecked: "దయచేసి చెక్ బాక్స్‌ను చూడండి",
      validemail: "దయచేసి సరైన ఈమెయిల్‌ను ఎంటర్ చెయ్యండి(example@domain.com)",
      blankemail: "ఈమెయిల్ అడ్రస్‌ను ఖాళీగా ఉంచరాదు",
      login: "సబ్‌స్క్రైబ్ చేసుకోవడానికి దయచేసి లాగిన్ అవ్వండి",
      error: "సమస్య వచ్చింది! మీరు పాత మెయిలర్ నుండి అన్‌సబ్‌స్క్రైబ్ కాలేదని నిర్దారించుకోండి",
    },
    popup: {
      related_videos: "సంబంధిత వీడియోలు",
    },
    social_download: {
      title: "'సమయం వార్తలను ఎప్పటికప్పుడు తెలుసుకోండి",
      fblike: "ఫేస్‌బుక్ పేజ్‌ను లైక్ చేయండి",
      appdownload: "యాప్ డౌన్‌లోడ్ చేసుకోండి",
      extrasharetxt: "\n\nఆప్‌లో డౌన్‌లోడ్ చేసుకుని చదవడానికి ఇక్కడ క్లిక్ చెయ్యండి : ",
      fblikeURL:
        "https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FSamayamTelugu%2F%3Ffref%3Dts&width=90&layout=button_count&action=like&size=small&show_faces=false&share=false&height=21&appId=117787264903013",
    },
    share_popup_header: "దయచేసి షేర్ చెయ్యండి",
    read_more: "మరిన్ని చదవండి",
    read_less: "తక్కువ చదవండి",
    view_gallery_from_start: "ప్రారంభం నుండి గేలరీను చూడండి",
    next_gallery: "తరవాత గ్యాలరీ",
    next_article: {
      moviereview: "మూవీ రివ్యూ",
      topicslist: "అంశాల జాబితా",
      articleshow: "తరవాత కథనం",
      default: "డిఫాల్ట్",
      photoshow: "ఫోటో షో",
      movieshow: "Next Movie",
    },
    next_topic: {
      more_all: "మరిన్ని",
      more_news: "మరిన్ని వార్తలు",
      more_photos: "మరిన్ని ఫోటోలు",
      more_videos: "మరిన్ని వీడియోలు",
    },
    search_placeholder: "శోధించండి",
    highlight: "ప్రధానాంశాలు:",
    orientation_heading: "డివైజ్‌ను తిప్పండి",
    popularVideos: "ఎక్కువగా చూసిన వీడియోలు",
    orientation_text: "ల్యాండ్‌స్కేప్ మోడ్ సపోర్ట్ చేయదు. దయచేసి పోర్ట్‌రైట్ మోడ్‌లో చదవండి",
    videos: "వీడియోలు",
    photo: "ఫోటో",
    related_videos: "సంబంధిత వీడియోలు",
    most_viewed_videos: "ఎక్కువుగా చూసిన వీడియోలు",
    default_horizontal_tile_width: 133, // These widths are used for slider
    default_slideshow_tile_width: 120,
    related_articles_horizontal_tile_width: 230,
    relatedarticle: "సంబంధిత వార్తలు",
    cast: "తారాగణం:",
    read_more_listing: "మరిన్ని",
    photomasti: "ఫొటో మస్తీ",
    critics_review: "విమర్శకుల రివ్యూ",
    twitte_reaction: "ట్విట్టర్ చర్చ",
    critics_rating: "విమర్శకుల రేటింగ్",
    user_rating: "యూజర్ రేటింగ్",
    movie_review: "మూవీ రివ్యూ",
    film_review: "సినిమా రివ్యూ",
    review_movie: "రివ్యూ రాయండి",
    review_device: "డివైజ్‌ను రివ్యూ చెయ్యండి",
    rate_movie: "మూవీకి రేటింగ్ ఇవ్వండి",
    rate: "రేట్",
    rate_recipe: "రెసిపీకు రేటింగ్ ఇవ్వండి",
    slide_to_rate: "రేటింగ్ ఇవ్వడానికి స్లైడ్ చెయ్యండి",
    slide_to_rate_movie: "మూవీకు రేటింగ్ ఇవ్వడానికి స్లైడ్ చెయ్యండి",
    reader_rating: "రీడర్ రేటింగ్",
    movie_review_tile_bg: "https://static.langimg.com/moviereview_list_bg/photo/65022261.cms",
    movie_review_detail_bg: "https://static.langimg.com/moviereview_list_bg/photo/65594589.cms",
    breaking_news: "బ్రేకింగ్ న్యూస్",
    trending: "ట్రెండింగ్",
    highlightText: "హైలైట్స్ చదవాలంటే యాప్‌ను డౌన్‌లోడ్ చేసుకోండి",
    live_video: "లైవ్ వీడియో", // Using for minitv widget
    view_text: "చూడండి",
    aur_jaane: "మరింత సమాచారం",
    oops: "అయ్యో...",
    thanks: "ధన్యవాదాలు.. ",
    offlineText: "మీరు ఆఫ్‌లైన్‌లో ఉన్నారు",
    onlineText: "మీరిప్పుడు ఆన్‌లైన్‌లో ఉన్నారు",
    openinapp: "Open App",
    superhit: "  ఎక్కువ మంది చదివిన కథనాలు",
    live_updates: "లైవ్ అప్‌డేట్స్",
    fblikecardtext: "సమయం తెలుగు ఫేస్‌బుక్ <br/> పేజ్ లైక్", // Using in Service Drawer
    appdownloadcardtext: "తెలుగు సమయంతో కనెక్ట్ అయి <br /> ఉండండి యాప్", // Using in Service Drawer
    installapp: "ఇన్‌స్టాల్",
    login: "లాగిన్",
    logout: "లాగౌట్",
    amazonDeals: "నేటి ఒప్పందాలు",
    seemoreimages: "ఇలాంటి ఫొటోలు మరిన్ని చూడండి", // Using in Photomazzashow
    read_more_liveblog: "మరింత సమాచారం",
    footerheading: "వెతకండి",
    comment_text: "కామెంట్ రాయండి",
    download_text: "డౌన్‌లోడ్ యాప్‌",
    write_comment: "కామెంట్ రాయండి",
    view_comment: "కామెంట్ చూడండి",
    text_topcomment: "టాప్ కామెంట్",
    text_latestcomment: "లేటెస్ట్ కామెంట్",
    text_author_comment: "రచయిత కామెంట్",

    wp_broadcast: {
      description: "తప్పక చదవాల్సిన కథనాలను వాట్సప్‌లో పొందండి",
      btnText: "సబ్‌స్క్రైబ్",
      url: "https://widget.whatsbroadcast.com/widget_more/8531f3a382edfe5c49a332a5fb08a2aa/?show=walink&text=",
    },
    crossbrand: "{site name} లో ఈ ఆర్టికల్ మొదటగా ప్రచురించబడింది",
    appexclusive: "App Exclusive",
    votesuccessfully: "మీరు ఓటును విజయవంతంగా వేశారు",
    votealready: "మీరు ఇదివరకే ఓటు వేశారు",
    submit_vote: "ఓటు",
    photoshow_app_install: {
      read_more: "మిగిలిన ఫోటోలను చూడటానికి",
      download: "డౌన్‌లోడ్ యాప్",
    },
    disclaimer: "గమనిక",
    live_tv: "LIVE TV",
    data_hub: "బడ్జెట్ డేటా హబ్",
    fantasy_game: "బడ్జెట్ ఫ్యాంటసీ గేమ్",
    topics_no_result: "సంబంధిత ఫలితాలు లేవు",
    players: "ప్లేయర్లు",
    utility: "ప్రయోజనం",
    appDownload: "Telugu Samayam App",
    tech: {
      inIndia: "భారతదేశంలో ధర",
      loadmore: "మరిన్ని లోడ్ చెయ్యండి",
      rating: "రేటింగ్",
      sortby: "తదనుగుణంగా అమర్చండి",
      clearall: "అన్నీ క్లియర్ చెయ్యండి",
      buyhere: "ఇక్కడ కొనండి",
      indiaLaunchDates: "భారతదేశంలో విడుదల తేదీ",
      indiaPrice: "భారతదేశంలో ధర",
      compCriteria: "పోలిక ప్రమాణం",
      showDiff: "తేడాను మాత్రమే చూపించండి",
      alreadyAdded: "ఈ గాడ్జెట్‌ను ఇదివరకే సెలక్ట్ చేసుకున్నారు",
      buyFrom: "లో కొనండి",
      addDevice: "డివైస్‌ జోడించండి",
      compare: "ను పోల్చండి",
      englishtype: "ఇంగ్లీష్‌లో టైపు చెయ్యండి",
      change: "మార్చండి",
      suggestedDevice: "సూచించబడిన డివైస్‌లు",
      pe: "पर",
      gadgets: "గాడ్జెట్లు",
      filtertxt: "ఫిల్టర్లు",
      purchasehere: "స్పాన్సర్ చేసినవారు: స్టోర్‌లో",
      popular: "ఎక్కువగా చూసినవి",
      allbrands: "అన్ని బ్రాండ్లు",
      brands: "బ్రాండ్",
      othervariants: "ఇతర వేరియంట్లు",
      criticsrating: "విమర్శకుల రేటింగ్",
      launchdate: "చెప్పబడుతున్న విడుదల తేదీ",
      review: "రివ్యూ",
      overview: "ఓవర్ వ్యూ",
      userrating: "యూజర్ రేటింగ్",
      comparedotxt: "పోల్చండి",
      submitrating: "రేటింగ్‌ సబ్మిట్ చెయ్యండి",
      addtocompare: "పోల్చడానికి జోడించండి",
      purchase: "కొనండి",
      suggested: "సూచించబడినవి",
      comparetxt: "పోల్చండి",
      latest: "లేటెస్ట్",
      price: "ధర",
      rumoured: "పుకార్లు",
      upcoming: "త్వరలో",
      ki: "యొక్క",
      relatedgadgets: "సంబంధిత గాడ్జెట్లు",
      seemore: "మరిన్ని చూడండి",
      topfeature: "ముఖ్య ఫీచర్లు",
      fullspecification: "పూర్తి స్పెసిఫికేషన్లు చూడండి",
      selectatleast2: "కనీసం 2 ఐటమ్స్‌ ఎంచుకోండి",
      devicealreadyinlist: "ఐటమ్ ఇదివరకే పోల్చడానికి ఎంచుకోబడింది",
      same_gadget: "ఈ తరహా గాడ్జెట్లు",
      user_review: "యూజర్ రివ్యూ",
      read_fullreview: "పూర్తి రివ్యూను చదవండి",
      similar_gadget: "ఈ తరహా గాడ్జెట్లు",
      see_diff: "తేడాలు చూడండి",
      latest_comparisons: "లేటెస్ట్‌గా పోల్చినవి",
      popular_comparisons: "ఎక్కువగా పోల్చినవి",
      techNewsH1: "టెక్నాలజీ వార్తలు",
      minimumComparisonError: "పోల్చడానికి కనీసం 2 గాడ్జెట్లు అవసరం",
      review_device: "డివైస్‌కు రేటింగ్ ఇవ్వండి",
      // gadgets show
      buyAtAmazon: "అమెజాన్‌లో కొనండి",
      priceList: "ధరల జాబితా",
      priceInIndia: "భారతదేశంలో ధర",
      criticReview: "విమర్శకుల రివ్యూ",
      userReview: "యూజర్ రివ్యూ",
      specifications: "స్పెసిఫికేషన్లు",
      moreLikeThis: "ఇలాంటివి మరిన్ని",
      criticRating: "విమర్శకుల రేటింగ్",
      userRating: "యూజర్ రేటింగ్",
      user: "యూజర్",
      others: "ఇతరములు",
      nextGadget: "తరువాత గాడ్జెట్",
      similarGadgets: "ఈ తరహా గాడ్జెట్లు",
      readCompleteReview: "పూర్తి రివ్యూ చదవండి",
      readLess: "తక్కువ చదవండి",
      recentlyCompared: "ఇటీవల పోల్చినవి",
      weak: "బాగోలేదు",
      belowAverage: "యావరేజ్ కంటే తక్కువ",
      worthpurchase: "కొనడానికి తగినది",
      good: "బాగుంది",
      excellent: "చాలా బాగుంది",
      thanksforreview: "రివ్యూ ఇచ్చినందుకు మీకు ధన్యవాదములు",
      befirsttoreview: "రివ్యూ ఇవ్వండి",
      userreviewandrating: "యూజర్ రివ్యూలు మరియు రేటింగ్లు",
      ratedevice: "డివైస్‌కు రేటింగ్ ఇవ్వండి",
      postRating: "మీ రేటింగ్ పోస్ట్ చెయ్యండి",
      readMoreReview: "మరిన్ని రివ్యూలు చదవండి",
      varients: "ఇతర వేరియంట్లు",
      text_write_reviews: "డివైస్ ను రివ్యూ చేయండి",
      text_view_comment: "కామెంట్లు చూడండి",
      text_write_comment: "కామెంట్లు చేయండి",
      critic: "క్రిటిక్ రివ్యూ",
      averagerating: "సరాసరి రేటింగ్",
      ratingbased: "రేటింగ్స్ ఆధారంగా",
      language: "Tech",
      category: [
        { keylabel: "మొబైల్", keyword: "mobile" },
        { keylabel: "లాప్‌టాప్", keyword: "laptop" },
        { keylabel: "స్మార్ట్‌వాచ్", keyword: "smartwatch", keylabelEng: "smart watch" },
        { keylabel: "టెలీవిజన్", keyword: "tv" },
        { keylabel: "ఎయిర్ కండీషనర్", keyword: "ac" },
        { keylabel: "టాబ్లెట్", keyword: "tablet" },
        { keylabel: "కెమెరా", keyword: "camera" },
        { keylabel: "ఫిట్‌నెస్ బ్యాండ్", keyword: "fitnessband", keylabelEng: "fitness band" },
        { keylabel: "వాషింగ్ మెషిన్", keyword: "washingmachine", keylabelEng: "washing machine" },
        { keylabel: "రిఫ్రిజిరేటర్", keyword: "refrigerator", keylabelEng: "fridge" },
        { keylabel: "పవర్ బ్యాంకు", keyword: "powerbank", keylabelEng: "power bank" },
      ],
      gadgetSliderConfig: {
        mobile: "మొబైల్",
        laptop: "లాప్‌టాప్",
        tablet: "టాబ్లెట్",
        camera: "కెమెరా",
        smartwatch: "స్మార్ట్‌వాచీలు",
        fitnessband: "ఫిట్‌నెస్ బ్యాండ్",
        tv: "టెలీవిజన్",
        ac: "ఎయిర్ కండీషనర్",
        washingmachine: "వాషింగ్ మెషిన్‌",
        refrigerator: "రిఫ్రిజిరేటర్",
        powerbank: "పవర్ బ్యాంకు",
      },
      affiliateTags: {
        homePage: "tlg_wap_home_latesttrendingwidget",
      },
    },
    user_review: "User Review",
    listenAlbum: "Listen to this album",
    castncrew: "Cast & Crew",
    filmSongs: "Film Songs",
    read_movie_review: "read movie review",
    news: "వార్తలు",
    photos: "Photos",
    market: "మార్కెట్",
    choseStateCity: { dropDownText: "నగరాన్ని ఎంచుకోండి", extraCityContent: " మీ నగరం వార్తలు చదవండి " },
    cityPopUp: {
      selectStateCity: "రాష్ట్రం మరియు నగరం",
      selectCity: "నగరాన్ని ఎంచుకోండి",
      save: "సేవ్",
      state: "రాష్ట్రం",
      city: "నగరం",
      readersCount: "సమయం తెలుగు పాఠకుల సంఖ్య 15 Lac+",
    },
    cityHeading: "సమీప నగరాల వార్తలు",
    cityHeadingVideo: "మీ సమీప నగరాల వీడియోలు",
    openInApp: {
      stayHere: "కొనసాగించండి",
      openApp: "యాప్ ఓపెన్ చెయ్యండి",
      mainText: "యాప్‌లో ఆర్టికల్ చదవడాన్ని కొనసాగిస్తారా?",
      mainTextForVSnPS: "యాప్‌లో చూడలనుకుంటున్నారా?",
    },
    authoraritcle: "ఆర్టికల్స్",
    authorwebstories: " యొక్క వెబ్ స్టోరీలు",
    authorsharetext: "తో ఆన్‌లైన్‌లో కనెక్ట్ అవ్వండి",
    authorabout: "గురించి",
    articles: "కథనాలు",
    webstories: "వెబ్ స్టోరీలు",
    dailyNewsUpdate: "ప్రతీరోజు అప్‌డేట్స్ కోసం లాగిన్ అవ్వండి",
    downloadAppForNews: "ప్రతీరోజు వార్తల అప్‌డేట్స్ కోసం మా యాప్‌ను డౌన్‌లోడ్ చేసుకోండి",
    notificationTopNewsAlert: "ప్రతీ వార్తను తెలుసుకోండి. Allow మీద క్లిక్ చేసి నోటిఫికేషన్లను సబ్‌స్క్రైబ్ చేసుకోండి",
    notification: "నోటిఫికేషన్",
    others: "ఇతరములు",
    authoraritcle: "ఆర్టికల్స్",
    authorwebstories: " యొక్క వెబ్ స్టోరీలు",
    authorsharetext: "తో ఆన్‌లైన్‌లో కనెక్ట్ అవ్వండి",
    authorabout: "గురించి",
    articles: "కథనాలు",
    webstories: "వెబ్ స్టోరీలు",
  },

  imageconfig: {
    thumbid: "67415780",
    defaultthumb: "67415780",
    liveblogthumb: "56295200",
    imagedomain: "https://static.langimg.com/thumb/",
    webimagedomain: "https://telugu.samayam.com/thumb/",
    bigimage: "width=540&resizemode=3", // Article Inline Images, will maintain aspect ratio of original image
    big2ximage: "width=1080&resizemode=3", // Article Inline Images, will maintain aspect ratio of spotlight/paid article image
    smallthumb: "width=280&height=210&resizemode=75", // Listing small thumbs, Aspect Ratio 4:3
    smallslideshowthumb: "width=320&height=240&resizemode=1", // Used for external photogallery strip on top news, Aspect Ratio 4:3
    midthumb: "width=320&height=240&resizemode=75", // Photo Listing widget thumb, etc Aspect Ratio 4:3
    largethumb: "width=380&height=285&resizemode=75", // Lead Images Aspect Ratio 4:3
    amplargethumb: "width=1600&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only videoshow
    amplargethumbarticle: "width=1200&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only for article
    smallwidethumb: "width=200&height=111&resizemode=75", // For video listing widgets Aspect Ratio 16:9
    largewidethumb: "width=380&height=214&resizemode=75", // For videowidget lead image and videoshow Aspect Ratio 16:9
    posterthumb: "width=210&height=281&resizemode=4", // Moview Posters
    squarethumb: "width=200&height=200&resizemode=75", // for two colum layout
    rectanglethumb: "width=160&height=103&resizemode=75", // for rectangle flags
    gnthumb: "width=200&resizemode=4", // for Gadget now
    gnthumbWithHeight: "height=150&resizemode=4", // for GN PDP, need height
    webstoriesthumb: "width=300&height=500&resizemode=4", // web stories Photo Listing widget thumb
    webstoriesthumbLarge: "width=364&height=607&resizemode=4", // web stories Photo Listing widget thumb
    widecardthumb: "width=600&height=315&resizemode=6", // End Article Card thumb 16: 9",
  },
  sso: {
    BASE_URL: "https://telugu.samayam.com",
    SSO_CHANNEL: "tl-wap",
    GADGET_CHANNEL: "telugu-gadgetsnow-wap",
    stg: {
      BASE_URL: "https://jstgtelugu.samayam.com",
      MYTIMES_URL_USER: "https://mytest.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
      MYTIMES_URL_SETTINGS: "https://jssostg.indiatimes.com/sso/identity/profile/edit?channel=tm",
      SSO_URL_LOGIN: "https://jssostg.indiatimes.com/sso/identity/login",
      SSO_URL_LOGOUT: "https://jssostg.indiatimes.com/sso/identity/profile/logout/external",
      SSO_URL_GETTICKET: "https://jssostg.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
      SOCIAL_API_INTEGRATOR: "https://testsocialappsintegrator.indiatimes.com/socialsite",
      SSO_BASE_URL: "https://jssostg.indiatimes.com/sso/crossdomain",
      SSO_CROSSWALK: "https://jssocdnstg.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
      SSO_WIDGET_URL: "https://jssocdnstg.indiatimes.com/crosswalk/133/widget/main.bundle.js",
    },

    SSO_BASE_URL: "https://jsso.indiatimes.com/sso/crossdomain",
    SSO_CROSSWALK: "https://jssocdn.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
    SSO_WIDGET_URL: "https://jssocdn.indiatimes.com/crosswalk/34/widget/main.bundle.min.js",
    MYTIMES_URL_USER: "https://myt.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
    MYTIMES_URL_SETTINGS: "https://jsso.indiatimes.com/sso/identity/profile/edit?channel=tl",
    SSO_URL_LOGIN: "https://jsso.indiatimes.com/sso/identity/login",
    SSO_URL_LOGOUT: "https://jsso.indiatimes.com/sso/identity/profile/logout/external",
    SSO_URL_GETTICKET: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
    MYTIMES_ALREADY_RATED: "https://myt.indiatimes.com/mytimes/alreadyRated?appKey=TELUGU&",
    MYTIMES_ADD_ACTIVITY: "https://myt.indiatimes.com/mytimes/addActivity?appKey=TELUGU&",
    SOCIAL_API_INTEGRATOR: "https://socialappsintegrator.indiatimes.com/socialsite",
    SSO_TRUECALLER_visibility: 4,
    PROFILE_URL: "https://mytimes.indiatimes.com/profile",

    SSO_URL_NewsTicket: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1",
    SSO_URL_SubStatus: "https://webapi.sendpal.in/api/v1/get/user/tl/status?dataformat=json",
    SSO_URL_unsubscribe: "https://webapi.sendpal.in/api/v1/multiple/unsubscribe/tl?dataformat=json",
    SSO_URL_subscribe:
      "https://webapi.sendpal.in/api/v1/add/subscription/tl?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=42",
    SSO_URL_confirm: "https://webapi.sendpal.in/api/v1/confirm/subscription/tl?dataformat=json",
  },
  MYTIMES_PROFILE: "https://mytimes.indiatimes.com/?channel=tlg",
  TimesPoint: {
    jsDev: "https://test.timespoint.com/tpwidgets-test/static/dist/js/main.js",
    jsProd: "https://image.timespoints.iimg.in/tpwidgets/static/dist/js/main.js",
    channels: ["tml", "nbt", "eisamay", "tlg"],
    // status: true,
    pcode: "channel97218",
    scode: "channel97218",
    activities: {
      DAILY_CHECKINS: "act6012496",
      DAILY_CHECKINS_MOBILE: "act6030506",
      READ_ARTICLE: "act8316645",
      WATCH_VIDEOS: "watch_video",
      SH_FB: "sh_fb",
      SH_TW: "sh_tw",
      LOGIN: "login",
      MOVIE_RATE: "act3375455",
      // Fired by MyProfile team
      MOVIE_REVIEW: "act3297358",
      VIEW_PHOTO: "view_photo",
      LIVE_BLOG: "act6238982",
      SUB_NL: "sub_nltr",
      REGISTER: "act8838785",
      // Fired by MyProfile team
      COMMENT: "cmnt",
      SUB_NOTIFICATION: "act264224",
      // Not found for staging
      CHECKIN_BONUS_DESKTOP: "act6332795",
      // Not found for staging
      CHECKIN_BONUS_MOBILE: "act6352539",
      WHATSAPP_SHARE: "act6313063",
    },
    campaingHistoryName: {
      desktop: "campaign7551210",
      mobile: "campaign7662887",
    },
    campaignDays: 5,

    stg: {
      pcode: "channel3148168",
      scode: "channel3148168",
      campaingHistoryName: {
        desktop: "campaign1396315",
        mobile: "campaign1522056",
      },
      activities: {
        DAILY_CHECKINS: "act2110205",
        DAILY_CHECKINS_MOBILE: "act2135027",
        READ_ARTICLE: "read",
        WATCH_VIDEOS: "watch_video",
        SH_FB: "sh_fb",
        SH_TW: "sh_tw",
        LOGIN: "act2313032",
        MOVIE_RATE: "act2346857",
        // Fired by MyProfile team
        MOVIE_REVIEW: "rv",
        VIEW_PHOTO: "view_photo",
        LIVE_BLOG: "act2666870",
        SUB_NL: "sub_nltr",
        REGISTER: "register",
        // Fired by MyProfile team
        COMMENT: "cmnt",
        SUB_NOTIFICATION: "act2807986",
        CHECKIN_BONUS_DESKTOP: "act2890495",
        CHECKIN_BONUS_MOBILE: "act2920867",
        WHATSAPP_SHARE: "act2839582",
      },
    },

    TP_FAQ_MSID: "79547916",
    NP_DOMAIN: {
      production: "https://npcoins.indiatimes.com",

      development: "https://nprelease.indiatimes.com",
      stg1: "https://nprelease.indiatimes.com",
      stg2: "https://nprelease.indiatimes.com",
    },

    TP_DOMAIN: {
      production: "https://tpapi.timespoints.com",

      development: "https://test.timespoints.com/tpapi",
      stg1: "https://test.timespoints.com/tpapi",
      stg2: "https://test.timespoints.com/tpapi",
    },

    SDK_DOMAIN: {
      production: "https://image.timespoints.iimg.in",

      development: "https://test-img.timespoints.com",
      stg1: "https://test-img.timespoints.com",
      stg2: "https://test-img.timespoints.com",
    },

    tpwidgetJS: {
      production: "/tpwidgets/dist/js/tpwidget.js",

      development: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg1: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg2: "/static/tpwidgets/static/dist/js/tpwidget.js",
    },

    //* * Moved to common config */
    tpPage: "/timespoints.cms",
    tpRedeemLink: "https://www.timespoints.com/products",
  },
  Comments: {
    appkey: "TELUGU",
    topComments: {
      appkey: "TELUGU",
      sortcriteria: "AgreeCount",
      order: "desc",
      size: "1",
      lastdeenid: "0",
      after: "true",
      withReward: "false",
      pagenum: "1",
    },
    allComments: {
      appkey: "TELUGU",
      sortcriteria: "CreationDate",
      order: "asc",
      size: "6",
      lastdeenid: 0,
      after: true,
      withReward: false,
      pagenum: 1,
    },
  },
  pages: {
    elections: "56662194",
    mktwdt: "87983477",
    business: "56181272",
    iplHomePage: "63301741",
    commonwealth: "63479906",
    fifa: "64448117",
    wcHomePage: "86753875",
    stateSection: "70465844,70465878",
    tech: "65719422",
    gadgethome: "83551579",
    budget: "56596600",
    budget_you: "97255597",
    apanabazaar: "83403678",
  },
  iplpages: {
    venues: "63301781",
    teams: "63301809",
    pointsTable: "63301873",
    miniSchedule: "63301831",
  },
  t20wcpages: {
    venues: "86756559",
    teams: "86754685",
    pointsTable: "86754645",
    miniSchedule: "86754577",
  },
  redis: {
    host: "192.168.24.51",
    port: "6379",
    db: "1",
  },
  // To print label in listing node at bottom right corner [templatename, label]
  listNodeLabels: {
    articlelist: ["articlelist"],
    news: ["articleshow"],
    photo: ["photoshow"],
    slideshow: ["photoshow"],
    video: ["videoshow"],
    videolist: ["videolist"],
    photolist: ["photolist"],
    lb: ["liveblog", "Live Update"],
    moviereview: ["moviereview", "Movie Review"],
    movieshow: ["movieshow", "Movie"],
    poll: ["pollsurvey", "Poll"],
  },
  photoListView: "47882310",
  miniTvMoreVideos: "47330979",
  // Used In AnchorLinkCard
  routes: [
    "/exitpolls/",
    "/results/",
    "/electionlist/",
    "/articlelist/",
    "/photoarticlelist/",
    "/photomazza/",
    "/photolist/",
    "/photoshow/",
    "/photogallery/",
    "/articleshow/",
    "/moviereview/",
    "/movieshow/",
    "/liveblog/",
    "/videolist/",
    "/videoshow/",
    "/topics/",
    "/teams/",
    "/venues/",
    "/pointstable/",
    "/iplt20.cms",
    "/schedule/",
    "/sportsresult/",
    "elections.cms",
    "/timespoints",
  ],

  staticPagesDir: "/var/www/html/testpages/",

  slike: {
    apikey: "telugumweb210lang",
    snapchatapikey: "",
    ampapikey: "teluguampweb210lang",
    default_slikeid_minitv: "1x13qpaggu", // Times-Now
    nextvideo_domain: "https://mtpwafeeds.indiatimes.com",
    default_pl_videolist: "/feeds/videpostroll_v5_slike/51022274.cms?feedtype=json&callback=cached",
  },

  slikeAdCodes: {
    astro: "1564454",
    others: "ros",
  },

  gRecaptchaKey: "6LcxSGUUAAAAAPsGPKVpEkLKxnuluuqDKa1AivEN",

  ga: {
    gtm: "GTM-PRW9X35",
    gtm4: "G-PVF836X6ZX",
    ampgtm: "GTM-K64M6BM",
    gverifyCode: "zU5qA2HPdN2PFPyZd70q25_5NHXI8AE8AbqWNwXsoFA",
    gatrackid: "UA-29031733-9",
    ga4trackid: "G-PVF836X6ZX",
    gaprofile: "[]",
  },

  growthrx: {
    stg: {
      id: "g046f1d6f",
    },
    prod: {
      id: "g91cc83e8",
    },
    gn: {
      stg: {
        id: "gc16bbe63",
      },
      prod: {
        id: "g534464f0",
      },
    },
  },

  appexclusive_ga: {
    category: "Wap to App install",
    action: "click",
    label: "articlelist_topsection",
  },

  poll: {
    link: "pollslist.cms",
  },

  poll_ga: {
    poll_submit: {
      category: "pollSurvey",
      action: "submit",
      label: "pollsubmit",
    },
    poll_result_loggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "loggedin",
    },
    poll_result_nonloggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "non-loggedin",
    },
  },

  photoshow_app_install: {
    ga_object: {
      category: "Wap to App install",
      action: "click",
      label: "photo show",
    },
  },
  // sso_ga: {
  //   truecaller_requestscreen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen Request",
  //   },
  //   truecaller_screen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen View",
  //   },
  //   truecaller_screencontinue: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Continue",
  //   },
  //   truecaller_skip: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Skip",
  //   },
  //   truecaller_loginsuccess: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Login Successful",
  //   },
  // },
  comscore: { c1: "2", c2: "6036484" },

  applinks: {
    android: {
      hrnav: "https://telugusamayam.onelink.me/Inpe/472737b0",
      asshow: "https://telugusamayam.onelink.me/Inpe/890c826f",
      photoshow: "https://telugusamayam.onelink.me/Inpe/4a95265b",
      serviceDrawer: "https://telugusamayam.onelink.me/Inpe/ac39bf39",
      social: "https://telugusamayam.onelink.me/Inpe/f4a40caa",
      oip_appexclusive: "https://navbharattimes.indiatimes.com/off-url-forward/tl_openinapp.cms?msid=",
      // https://telugusamayam.onelink.me/cMxT/b256ac1
    },
  },
  appdeeplink: {
    domain: "https://telugusamayam.onelink.me",
    // shortcode: "com.til.telugusamayam",
    shortcode: "Inpe",
    c: "Internal_Campaign",
    pid: {
      hrnav: "WAP_HRNAV_New",
      serviceDrawer: "WAP_BOTTOM_New",
      news: "WAP_MWEB_New",
      article_end: "WAP_AS_New",
      photo: "WAP_PG_New",
      toparticle: "WAP_Top%20Articles_New",
      extphoto: "WAP_Home_Photostrip_New",
      photoshow: "WAP_Photoshow_New",
      campaign: "WAP_Election_New",
      campaignHome: "WAP_Election_Home_New",
      openinapp_as: "TLG_AS_Brandwire",
      openinapp_al: "TLG_AL_Brandwire",
      photofeature: "WAP_MWEB_New",
      photoFeature: "WAP_MWEB_New",
      recipe: "WAP_MWEB_New",
      videoshow: "WAP_VideoShow",
      topStrip: "WAP_Top_Strip",
      articlelist: "WAP_ArticleList",
      topStripAS: "New_Top",
      videolist: "WAP_VideoList",
      photolist: "WAP_PhotoList",
      continueInApp: "Continue_App",
      sharing: "WAP_Sitesharing_New",
    },
    listdefaultUrl: "https://tlgpwafeeds.indiatimes.com/feeds/app_listing/<MSID>.cms?feedtype=json",
    openapp: "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu",
    opennews:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Dnews-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openphoto:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openextphoto:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dp-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openhtmlview:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BURL%7D",
    opensection:
      "telugusamayamactivities://open-%24%7C%24-pub%3D9:Samayam Telugu-%24%7C%24-type%3Dsection-%24%7C%24-sectionID%3D%7BsectionID%7D-%24%7C%24-sectionName%3D%7BsectionName%7D-%24%7C%24-id%3D%7BMSID%7D",
    openphotofeature:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3DphotoFeature-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openrecipe:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Drecipe-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openvideoshow:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Dvideo-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openarticlelist:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dnews-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openphotolist:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dphoto-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openvideolist:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dvideo-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openContinueInApp:
      "telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D&af_web_dp=https%3A%2F%2Ftelugu.samayam.com%2F&is_retargeting=true&deep_link_value=telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D9%3ASamayam%2520Telugu-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
  },
  pushNotification: {
    cookieName: "notifypopup_tlg",
    defaultThumb: "https://static.langimg.com/thumb/59455619/pic.jpg?width=100&height=100",
    heading: " లేటెస్ట్ మరియు బ్రేకింగ్ న్యూస్ కోసం నోటిఫికేషన్లు సబ్‌స్క్రైబ్ చేసుకోండి. అనుమతించు పై క్లిక్ చెయ్యండి",
  },

  weather: {
    geoLocationApi: "https://geoapi.indiatimes.com/?cb=1",
    defaultCity: "Hyderabad",
    citiesJson: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_geocities.cms",
    weatherFeed: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_weathertoday.cms?lat=",
    heading: "Today's Temperature",
    cityText: "మీ నగరం వార్తలు చదవండి",
  },
  pollution: {
    heading: "प्रदूषण",
    headingV1: "మీ నగరంలోని గాలి నాణ్యత ఎలా ఉంది",
    status: {
      good: "బాగుంది",
      moderate: "పర్వాలేదు",
      unhelathfSG: "సెన్సిటివిటీ గ్రూపులకు ప్రమాదకరం",
      unhealthy: "ప్రమాదకరం",
      veryUnhealthy: "అత్యంత ప్రమాదకరం",
      hazardous: "విషమం",
    },
    url: "https://telugu.samayam.com/pollution/87502530.cms",
  },
  fuel: {
    heading: "फ्यूल",
    feedUrl: "https://toibnews.timesofindia.indiatimes.com/fuelprice/latestPrice",
  },

  oneTapSignIn: {
    smartlockurl: "https://smartlock.google.com/client",
    isViewGaTracked: false,
    eventGAObj: {
      hitType: "event",
      category: "Login",
      action: "One_Tap",
      label: "",
    },
    text: {
      oneTapSuccessMsg: "మీరు విజయవంతంగా లాగిన్ అయ్యారు",
      oneTapErrorMsg: "అయ్యో! ఏదో తప్పు జరిగింది । దయచేసి మళ్లీ ప్రయత్నించండి।",
      oneTapBtnText: "మరొకసారి ప్రయత్నించండి",
    },
    constants: {
      onetapIgnoreDays: 15,
      onetapCookie: "oneTapNextShow",
      onetapIframeCheckTimer: 2000,
      smartlockJsLoadTimer: 10000,
      clientId: "586641927846-bi1jtisviubr34u2bg13pc2cijulhjpq.apps.googleusercontent.com",
      channel: "tl-wap",
      jssoAPIGetURL: "https://jsso.indiatimes.com/sso/services/gponetaplogin/verify",
    },
  },

  cricplay_widget: {
    schedulelink: "/sports/cricket/icc-world-cup/schedule/69161420.cms",
    deeplink:
      "https://telugusamayam.onelink.me/V28U?pid=WAP_CricPlay&c=Internal_Campaign&af_dp=telugusamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D8%3ASamayam%2520Tamil-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3Dhttps%3A%2F%2Fcrpl.app.link%2FZnAyOSBSxW",
    wincashtxt1: "உங்களுக்கு பிடித்த கிரிக்கெட் அணியை உருவாக்குங்கள் மற்றும் ",
    wincashtxt2: "பணம் வென்றிடுங்கள்!",
    appdwntxt: "சமயம் தமிழ் ஆப் டவுண்லோடு செய்க",
  },

  ZodiacSigns: {
    url: "#",
    data: [
      {
        name: "aries",
        regName: "మేష రాశి",
        pos: 1,
      },
      {
        name: "taurus",
        regName: "వృషభ రాశి",
        pos: 2,
      },
      {
        name: "gemini",
        regName: "మిథున రాశి",
        pos: 3,
      },
      {
        name: "cancer",
        regName: "కర్కాటక రాశి",
        pos: 4,
      },
      {
        name: "leo",
        regName: "సింహ రాశి",
        pos: 5,
      },
      {
        name: "virgo",
        regName: "కన్య రాశి",
        pos: 6,
      },
      {
        name: "libra",
        regName: "తుల రాశి",
        pos: 7,
      },
      {
        name: "scorpio",
        regName: "వృశ్చిక రాశి",
        pos: 8,
      },
      {
        name: "sagittarius",
        regName: "ధనస్సు రాశి",
        pos: 9,
      },
      {
        name: "capricorn",
        regName: "మకర రాశి",
        pos: 10,
      },
      {
        name: "aquarius ",
        regName: "కుంభ రాశి",
        pos: 11,
      },
      {
        name: "pisces",
        regName: "మీన రాశి",
        pos: 12,
      },
    ],
  },

  ads: {
    ampInuxuAd:
      "https://adgebra.co.in/afpf/IBN_AMP.html?domain=amp-telugu.samayam.com&pubid=3613&slotId=1&templateId=4655&accessMode=1&divId=div_407860734567731&cache=123",
    ampAdAfter: "",
    gptUrl: "https://www.googletagservices.com/tag/js/gpt.js",
    ctnAddress: "https://static.clmbtech.com/ad/commons/js/13540/colombia_v2.js",
    dmpUrl: "https://static.clmbtech.com/ase/13540/220/aa.js",
    isvPreRollUrl:
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/7176/TLG_MWEB/TLG_MWEB_Videoshow/TLG_MWEB_Videoshow_ISV&description_url=[placeholder]&tfcd=0&npa=0&sz=300x230%7C300x250%7C300x415%7C304x350%7C256x144&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
    ADS_PRIORITY: "FAN",
    profileid: "2924",
    exchangeId: "692988",
    ctnads: {
      inline: "259404",

      homedefault: {
        ctnId: "206009",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefaultsmall: {
        ctnId: "206009",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontal: {
        ctnId: "206009",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homevertical: {
        ctnId: "206009",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontalsmall: {
        ctnId: "206009",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },

      ctnlist: "259404",
      ctnlistTop: "354486",
      ctnlist1: "259404",
      // "ctnlist": "320650",
      ctnpgl1: "337831",
      ctnpgl2: "337831",
      ctnvll1: "337829",
      ctnvll2: "337830",
      ctnbiglist: "324209",
      ctnsluglist: {
        ctnId: "355641",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_AL_INS_NEW_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listdefault: "259404",
      listhorizontalsmall: "259404",
      ctnmgid: "M787960ScriptRootC",
      ctnMmgid: "1277579",
      ctnBmgid: "1277580",
      ctnmgidurl: "https://jsc.mgid.com/t/i/til.telugu.samayam.com",

      ctnshow: "323124",
      ctnmidart: "334314",
      ctnnative: "323123",
      ctnmidart_test: "", // for test page only requested by sales
      ctnrecommended: {
        ctnId: "206010",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnrhsvideo: "337835",
      ctnshowvideo: "334314", // video ad on articleshow
      ctnvs: "337829", // Video Show
      // "ctnhome" : "316371",  // caraousal ad code, just for test
      // "ctnhometop" : "206698",
      ctnhome: {
        ctnId: "206009",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnhometop: "207571", // updated
      ctnhomevideo: "324709", // video ad , updated
      ctninlineshow: "208368",
      ctnslider: "210641",
      ctnVideoURL: "https://telugu.samayam.com/ads_native_video_dev.cms",
      ctnbighome: {
        ctnId: "324205",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_Mweb_Direct_HP_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnbigphoto: {
        ctnId: "324207",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_Mweb_Direct_PG_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      homeibeat: {
        ctnId: "206009",
        dfpSlot: "/7176/TLG_MWEB/TLG_MWEB_Bid_Experiment/TLG_MWEB_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnint: "324740", // actual ad code for CTN INT TLG

      ctnphotoshowrhs: "",
      ctnshowphoto: "338799",

      ctntopicsall: "259404",
      ctntopicsnews: "259404",
      ctntopicsphotos: "337831",
      ctntopicsvideos: "337830",

      ctnint_test: "",
      adspositionsPhoto: "-3-,-5-,-9-,-14-,-20-,-27-,-36-,-45-,-55-",
      adspositionsLiveblog: "-5-,-10-,-15-,-20-,-25-,-30-,-35-,-40-",
      ctncookievalue: "ce_tgapm",
      ctnbccl: "340363",
      ctntechlist: "335478", // Gadget Config
      ctnTechGL: "335478", // Gadget Config
      ctnTechPDP: "335482", // Gadget Config
      ctnTechCL: "357063", // Gadget Config
      ctnTechCDP: "335482", // Gadget Config
      ctnTechTC: "357063", // Gadget Config
      ctntechTop: "335484", // GN Config
      ctntechvideo: "335483", // GN Config
      ctntechoth: "357688", // GN Config
      ctnInImage: "518963",
      ctnPreRoll: "518891",
    },
    ctnslots: {
      atf: "327958",
      ctnshow: "323124",
      ctnbiglist: "",
      ctnbigphoto: "",
      midart: "327957",
      articleshow: "ctnshow,atf,midart",
      liveblog: "",
      photoshow: "",
      videoshow: "",
      videolist: "",
    },
    dfpads: {
      adSiteName: "TLG",
      adSiteShortName: "TLG",
      topatf: "/7176/TLG_Mweb/TLG_Mweb_Others/TLG_MWEB_OTH_Fixed",
      cubead1: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_OTH_CUBE_195x85",
      cubead2: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_OTH_CUBE2_195x85",
      cubeheadad1: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_OTH_CUBE_195x30",
      cubeheadad2: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_OTH_CUBE_195x30",
      cubeheadad3: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_OTH_CUBE2_195x30",
      cubeheadad4: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_OTH_CUBE2_195x30",
      andbeyond: "/7176/TLG_MWEB/TLG_MWEB_ROS/TLG_Mweb_ROS_Andbeyond_1x1",
      inimage: "/7176/TLG_MWEB/TLG_MWEB_ROS/TLG_Mweb_ROS_Inimage_1x1",
      multiplex: "/7176/TLG_MWEB/TLG_MWEB_ROS/TLG_MWEB_ROS_Bottomwidget",
      canvasAd: "/7176/TLG_MWEB/TLG_MWEB_ROS/TLG_Mweb_ROS_Mcanvas_1x1",
      interstitial: "ca-pub-1902173858658913",
      inuxu: "/7176/Telgu/TLG_ROS/TLG_ROS_Inuxu_1x1",
      dfpint: "/7176/TLG_MWEB/TLG_MWEB_Home/TLG_MWEB_HP_INT",
      trk: "/7176/TLG_MWEB/TLG_MWEB_Home/TLG_MWEB_HP_trl_1x1",
      osv: "/7176/TLG_MWEB/TLG_MWEB_ROS/TLG_MWEB_ROS_OUTSTREAM_1x1",
      sitesync: "/7176/TLG_MWEB/TLG_MWEB_Home/TLG_Mweb_HP_SiteSync_1x1",
      nativead: "/7176/Languages/TLG_Mweb/TLG_Mweb_Native_300x250",
      nativeadamp: "/7176/Languages/TLG_AMP/TLG_AMP_Native_300x250",
      ampIntAd: "/7176/AMP_TLG_Mweb/AMP_TLG_Mweb_ROS/AMP_TLG_Mweb_ROS_INT",
      budgetSlug: "/7176/Telgu/Budget/TLG_BDGT_SLG",
      test1: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_1_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_1_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_1_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_1_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_1_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_1_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      test2: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_2_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_2_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_2_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_2_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_2_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/TLG_MWEB/TLG_Mweb_Test/TLG_MWeb_Test_2_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      others: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_ATF",
          size: [
            [300, 250],
            [320, 100],
            [320, 50],
            [336, 280],
            [250, 250],
            [300, 50],
          ],
        },
        btf: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_BTF",
          size: [
            [300, 250],
            [320, 50],
            [300, 50],
            [300, 75],
            [234, 60],
          ],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-2-fbn",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_FBN",
          size: [
            [320, 50],
            [300, 50],
          ],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-4",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_Mrec1",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-2",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_Mrec2",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecinf",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_MrecINF",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        slug: {
          id: "div-gpt-ad-9135510865388-slug",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_Slug1",
          size: [
            [320, 100],
            [300, 100],
          ],
        },
        parallax: {
          id: "div-gpt-ad-9135510865388-parallax",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_FC",
          size: [[300, 600]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-3",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_Mrec3",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec4: {
          id: "div-gpt-ad-9135510865388-4",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_Mrec4",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec5: {
          id: "div-gpt-ad-9135510865388-5",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_Mrec5",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec6: {
          id: "div-gpt-ad-9135510865388-6",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_Mrec6",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec7: {
          id: "div-gpt-ad-9135510865388-7",
          name: "/7176/TLG_MWEB/TLG_MWEB_Others/TLG_MWEB_Others_Mrec7",
          size: [
            [336, 280],
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        refreshnews: "/7176/TLG_MWEB/TLG_MWEB_News/TLG_MWEB_News",
      },
    },
  },
  plus: {
    disablePlus: true,
    logo: "https://static.langimg.com/thumb/85000251/tamil-samayam.jpg?height=36&resizemode=4",
    home: "84195947",
    video: "84195995",
    shortName: "TML Plus",
    articleReferrerCd: 8,
    articleTypeCd: 6,
    homeText: "Home",
  },
  // dailyMotion: { channel: "samayamtelugu", playerId: "x6k8x", meta: "dm4c1r6s6xg3zasvo", syndication: "278260" },
  foryoupage: {
    cid: "13540:220",
    agencyFilters: ["భాష", "Brandwire", "SPOTLIGHT"],
  },
  authorDetails: {
    agencyName: "Samayam Telugu",
    authorName: "",
    editorLink: "",
    editorLabel: "",
  },
  cityLandingPage: "/andhra-pradesh/articlelist/70465844.cms",
  timesXP: {
    hostName: "tlg_xp",
    xpUrl: "https://tlgfeed.timesxp.com/langapi",
    appUrl: "https://telugu.timesxp.com",
    wapCode: "teluguTxp",
  },
  vdoAI: {
    isEnabled: true,
    scriptUrl: "//a.vdo.ai/core/v-telugu-samayam-v0/vdo.ai.js",
    containerID: "v-telugu-samayam-v0",
  },
  orgAddress: {
    addressLocality:
      "Times House H.No 8-2-351, Beside Rangoli Road No 3, Banjara Hills Near Nagarjuna Circle, TV 9 Road",
    addressRegion: "Hyderabad",
    postalCode: "500034",
  },
  cleoPlayer: {
    apikey: "lang-n9GgmFF518E5Bknb",
  },
};
