module.exports = {
  hostid: "245", // Gadget Config
  channelid: "696089404",
  mediawireslot: "13",
  wapsitename: "Vijay Karnataka",
  wapsiteregionalname: "Vijay Karnataka",
  siteName: "vijaykarnataka.com",
  staticSiteName: "static.vk.indiatimes.com",
  fbIAcontentId: "143961472330928",
  languagemeta: "kn",
  language: "Kannada",
  channelCode: "vk",
  wapCode: "vk",
  gdprID: "VK",
  languagefullName: "Vijay Karnataka",
  languagefullNameGN: "ಟೆಕ್ನಾಲಜಿ",
  langnetstorageBasePath: "https://langnetstorage.indiatimes.com/langappfeeds",
  video: { rootId: "49909262", newsId: "97642874" },
  fbLive: "92082060",
  videoiconurl: "/video/videolist/49909262.cms",
  editTrendingMSID: "75718278",
  applist: "/appslist.cms",
  rss: "/rss.cms",
  coronaId: "74483525",
  iospackageid: "848154881",
  androidpackage: "com.vk.reader",
  deeplinkappid: "vkreaderactivities",
  deeplinkpubid: "pub=5:Vijay Karnataka",
  iosapp_name: "Vijaykarnataka App",
  weburl: "https://vijaykarnataka.com",

  mweburl: "https://vijaykarnataka.com",
  gadgetdomain: "https://kannada.gadgetsnow.com",
  etdomain: "https://kannada.economictimes.com",
  ccaudId: "8359:136",
  ccaudAmp: "8359",
  ccaudIdAmp: "8359:1215",
  indexExchangeUrl: "//js-sec.indexww.com/ht/p/191952-96221565249861.js",
  pwtUrl: "//ads.pubmatic.com/AdServer/js/pwt/23105/3676",
  footerDesktopLink: "https://vijaykarnataka.com?mobile=no",
  cookieLessDomain: "https://static.vk.indiatimes.com",
  domain: "indiatimes.com",
  webdomain: "vijaykarnataka.com",
  mwebdomain: "vijaykarnataka.com",
  photogallerydomain: "photogallery.vijaykarnataka.indiatimes.com",
  google_site_verification: "tX6zCoCuYqu6JY5VZ1ZQ7Cj5n6zcR9NzfuaFvWlolqA",
  twitterHdandler: "@Vijaykarnataka",
  logo: "nbt-logo.jpg",
  logo_id: "https://static.langimg.com/thumb/76438688/vijaykarnataka.jpg?width=218&resizemode=4",
  logogn_id: "https://static.langimg.com/thumb/76438688/vijaykarnataka.jpg?width=218&resizemode=4",
  logoPathGadget: "https://static.langimg.com/thumb/83990295/vijaykarnataka.jpg?width=232&resizemode=4",
  googleNews: "https://news.google.com/publications/CAAqBwgKMJDq7wowr8PUAQ?hl=en-IN&gl=IN&ceid=IN%3Aen",
  fb: "https://www.facebook.com/vijayKarnataka",
  twitter: "https://twitter.com/Vijaykarnataka",
  gplus: "https://plus.google.com/+VijayKarnataka/posts",
  youtubeUrl: "https://www.youtube.com/channel/UCClDtg3ns0xa_d7Q5sK1yOQ",
  kooUrl: "https://www.kooapp.com/profile/vijaykarnataka",
  // Production izooto for vk - Uncomment after done
  linkedInUrl: "",
  shoppingBag: "https://vijaykarnataka.com/best-deals-online?category=clothes?utm_source=social_panel",
  izooto: "",
  // TODO:Staging izooto for vk - Comment after done
  // izooto: "https://cdn.izooto.com/scripts/3225ef3f4b6c206015c295db5fa34106bae2a1fa.js",
  fullutm: "&utm_campaign=vkmobile&utm_medium=referral",
  slikeshareutm: "utm_source=slikevideo&utm_medium=referral",
  telegramFollowLink: "https://telegram.me/Vijaykarnataka_News",
  shortutm: "ma", // Using for micron
  icon: "https://vijaykarnataka.com/favicon.ico",
  breakingNewsFeedUrl: "https://langnetstorage.indiatimes.com/LANGBNews/vkbnews.htm",
  fbsdkurl: "https://connect.facebook.net/kn_IN/sdk.js#xfbml=1&version=v3.0",
  fbpage: "https://www.facebook.com/vijayKarnataka",
  livebloghpfeed: "",
  livebloghostname: "vk", // Using to getch liveblog callback feed
  navfeedurl: "https://langnetstorage.indiatimes.com/langappfeeds/vk_navjson.htm",
  liveblogbnbewsurl: "",
  moreNews: "More News",
  moreNewsUrl: "https://vijaykarnataka.com/headlines.cms",
  glossaryLanding: "https://langnetstorage.indiatimes.com/langappfeeds/vk_glossarylist_business.htm",
  marketindices: "https://m.economictimes.com/mcoverage_langwidget.cms?language=KAN&type=indices&nofollow=true",
  marketcommodities: "https://m.economictimes.com/mcoverage_langwidget.cms?language=KAN&type=commodities&nofollow=true",

  // logo_schema dimension should be 600*60
  logo_schema: "https://static.langimg.com/thumb/60408761/Vijay-Karnataka.jpg?width=600&resizemode=4",
  logo_alt: "Vijaya Karnataka - Kannada News",
  gnschemalogo: "https://navbharattimes.indiatimes.com/thumb/73125079/nbt-gadget-now-logo.jpg?width=600&resizemode=4",
  siteid: "2147477979",
  fbpixelid: "",
  fbappid: "683939958300651",
  googleClientId: "820635333666-ks46aedtelfqud1pf80ood2slnlt0l2q.apps.googleusercontent.com",
  astrowidgetId: "19127963",
  viralBrandingLink: "/viral-adda/articlelist/71395137.cms",
  bennett: "https://timesofindia.indiatimes.com/bennettjul2020_form_nbt_mweb.cms",

  css:
    "$body-bgcolor:#fff;	$navbar-top-bgcolor:#fff;	$navbar-bg-color:#F5CC10;	$navbar-border-top:#c8cccb;	$navbar-border-shadow:#D8B40D;	$navbar-active-border-bottom-color:#000;	$navbar-link-color:#000;	$hamburger-bg-color:#747474;	$sidenav-bg-color:#fff;	$sidenav-color:#000;	$sidenav-border-bottom:#F5F5F5;	$sidenav-arrow-color:#D1D1D1;	$layer-bg:rgba(0,0,0,0.5);	$breadcrumb-home-color:#DA4848;	$card-border-bottom:#F5F5F5;	$card-bg-color:#8e8e93;	$card-text-color:#191919;	$card-date-color:#bababa;	$home-section-border-bottom:#f5f5f5;	$home-section-heading-border-bottom:#F5CC10;	$home-section-arrow-color:#000000;	$home-section-more-color:#858585;	$home-section-more-border:#CCCCCC;	$footer-background:#585858;	$footer-border-top:#333;	$footer-border-bottom:#7b7b7b;	$footer-heading-color:#e6e6e6;	$footer-text-color:#fff;	$footer-link-color:#d0d0d0;	$footer-trending-color:#95989a;	$footer-copyright-color:#d0d0d0;",
  fontContent:
    "@font-face {font-family: Noto Sans;src: url('https://static.vk.indiatimes.com/fonts/NotoSansKannada-Regular.eot');src: url('https://static.vk.indiatimes.com/fonts/NotoSansKannada-Regular.eot?#iefix') format('embedded-opentype'),url('https://static.vk.indiatimes.com/fonts/NotoSansKannada-Regular.woff2') format('woff2'),url('https://static.vk.indiatimes.com/fonts/NotoSansKannada-Regular.ttf') format('truetype');font-weight: normal;font-style: normal;font-display: optional;}",
  fontUrl: "https://static.vk.indiatimes.com/fonts/NotoSansKannada-Regular.woff2",
  cricket_SIAPI: {
    minischedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_liupre_kn.json",
    schedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_kn.json",
    points_table: "https://toicri.timesofindia.indiatimes.com/jsons/stats/Standings/standing_%seriesid%.json",
    scoreboard: "https://toicri.timesofindia.indiatimes.com/jsons/%matchid%_kn.json",
    topPlayer: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/feed_topplayer.cms?feedtype=sjson",
  },
  instant_article: {
    fbia_recirculation_placement_id: "472457120063475_472496230059564",
    fbia_ad_placement_id: "472457120063475_472457133396807",
  },
  techsectionID: {
    // GN Config
    latestGadgets: "74433894",
    trendingGadgets: "74433915", // or popular
    video: "60309764",
    photo: "70479074",
  },
  citymsid: "71478549",
  locale: {
    comment: {}, // don't remove this
    appIconText: "ಆ್ಯಪ್",
    live_blog: "ಲೈವ್‌ಬ್ಲಾಗ್‌",
    commentary: "Commentary",
    whatsapp_share: "Hey, you might find this interesting: ",
    latest: "ಲೇಟೆಸ್ಟ್‌ ",
    most_read: "ಹೆಚ್ಚು ಓದಿದ",
    latest_video: "ಲೇಟೆಸ್ಟ್‌ ವಿಡಿಯೋ",
    latest_photo: "ಲೇಟೆಸ್ಟ್‌ ಫೋಟೋ",
    see_in_app: "ಆ್ಯಪ್‌ನಲ್ಲಿ ನೋಡಿ",
    see_in_app_details: "ಎಲ್ಲಾ ವೈವಿಧ್ಯಮಯ ಫೋಟೋಗಳನ್ನ ವೀಕ್ಷಿಸಲು ಆ್ಯಪ್‌ ತೆರೆದು ನೋಡಿ",
    scorecard: "Scorecard",
    photo_maza: "ಫೋಟೋ ಮಾಜಾ",
    key_words: "ಕೀವರ್ಡ್ಸ್‌",
    more_from_topics: "ಇನ್ನಷ್ಟು ವಿಷಯಗಳು’",
    brief: {
      tooltip: "ಸುದ್ದಿಗಳನ್ನು ಈ ರೀತಿ ಪಡೆಯುವುದು ನಿಮಗೆ ಇಷ್ಟವಾಗುತ್ತಿದ್ದಲ್ಲಿ ಇನ್ನಷ್ಟು ಓದಲು  ಆ್ಯಪ್‌ ಡೌನ್‌ಲೋಡ್‌ ಮಾಡಿ",
      limitation_txt: "ಇನ್ನುಳಿದ ಸಂಕ್ಷಿಪ್ತ ಸುದ್ದಿಗಳನ್ನು ನೋಡಲು",
    },
    recommendednews: "ಓದಲೇ ಬೇಕಾದ ಸುದ್ದಿ",
    appLinkText:
      "ನಿಮ್ಮ ಸುತ್ತಮುತ್ತಲು ನಡೆಯುವ ವಿದ್ಯಮಾನಗಳನ್ನುಹಂಚಿಕೊಳ್ಳಲು ಬಯಸುತ್ತೀರಾ? ಹಾಗಿದ್ದಲ್ಲಿ ವಿಜಯ ಕರ್ನಾಟಕ ಆ್ಯಪ್‌ಡೌನ್‌ಲೋಡ್‌ ಮಾಡಿಕೊಳ್ಳಿ ಹಾಗೂ ರಿಪೋರ್ಟ್‌ ಕಳಿಸಿ",

    actors: "ನಟ",
    releaseDate: "ಬಿಡುಗಡೆ ದಿನಾಂಕ",
    director: "ನಿರ್ದೇಶಕ ",
    genre: "ಚಿತ್ರದ ವಿಧ",
    duration: "ಅವಧಿ",
    readmore: "ಇನ್ನಷ್ಟು ಓದಿ",
    watchmore: "ಇನ್ನಷ್ಟು ವೀಕ್ಷಿಸಿ",

    newsLetter: {
      LS: "545687",
      thankyou: "ಧನ್ಯವಾದ",
      headerText: "ನಿಮ್ಮ ಸುತ್ತಮುತ್ತ ನಡೆಯುವ ಪ್ರಮುಖ ವಿಚಾರಗಳ ಬಗ್ಗೆ ಅಪ್‌ಡೇಟೆಡ್‌ ಆಗಿರಬೇಕೇ?",
      joinIn: "ಜಾಯಿನ್‌ ಆಗಿರಿ",
      footerText: "ನಿಮ್ಮ ಇಮೇಲ್‌ ವಿಳಾಸವನ್ನು ಮೇಲಿನ ಬಾಕ್ಸ್‌ ನಲ್ಲಿ ಟೈಪ್‌ ಮಾಡಿ. ನಿಮಗೆ ನ್ಯೂಸ್‌ ಅಪ್‌ಡೇಟ್‌ಗಳು ಸಿಕ್ಕಲಿದೆ. ",
      verification: "Verification Email Sent to your Email Address",
      already: "ನೀವು ಈಗಾಗಲೇ ಸಬ್‌ಸ್ಕ್ರೈಬ್‌ ಆಗಿದ್ದೀರಿ",
      Subscribed: "You are subscribed now",
      errorNetwork: "There is some network error ! Please try again !",
      notverified: "Already an email has been sent to you ! Please verify !",
      verified: "Your are already Verified",
      unchecked: "Please check the check box",
      validemail: "Please enter a valid email address (example@domain.com)",
      blankemail: "Email Address cannot be left blank",
      login: "Please login to subscribe",
      error: "Error occured!! kindly make sure that you are not unsubscrbing from any older mailer",
    },

    social_download: {
      title: "ವಿಜಯ ಕರ್ನಾಟಕದಿಂದ ಕ್ಷಣ ಕ್ಷಣದ ಸುದ್ದಿಗಳನ್ನು ತಿಳಿಯಿರಿ",
      fblike: "ಫೇಸ್‌ಬುಕ್‌ ಪೇಜ್‌ ಲೈಕ್‌ ಮಾಡಿರಿ।",
      appdownload: "ಆ್ಯಪ್ ಬಳಸಿ",
      extrasharetxt: "\n\nಆ್ಯಪ್‌ನಲ್ಲಿ ಓದಲು ಹಾಗೂ ಡೌನ್‌ಲೋಡ್‌ ಇಲ್ಲಿ ಕ್ಲಿಕ್‌ ಮಾಡಿ : ",
      fblikeURL:
        "https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FVijayKarnataka&width=79&layout=button_count&action=like&size=small&show_faces=false&share=false&height=21&appId=505830642956378",
    },
    share_popup_header: "ಶೇರ್‌ ಮಾಡಿ",
    read_more: "ಇನ್ನಷ್ಟು ಓದಿ...",
    read_less: "ಕಡಿಮೆಗೊಳಿಸಿ...",
    view_gallery_from_start: "ಆರಂಭದಿಂದ ಗ್ಯಾಲರಿ ನೋಡಿ",
    next_gallery: "ಮುಂದಿನ ಗ್ಯಾಲರಿ",
    next_article: {
      moviereview: "ಸಿನಿಮಾ ವಿಮರ್ಶೆ",
      articleshow: "ಮುಂದಿನ ಲೇಖನ",
      default: "ಡಿಫಾಲ್ಟ್",
      movieshow: "Next Movie",
    },
    next_topic: {
      more_all: "ಇನ್ನಷ್ಟು",
      more_news: "ಮತ್ತಷ್ಟು ಸುದ್ದಿ",
      more_photos: "ಇನ್ನಷ್ಟು ಫೋಟೋ",
      more_videos: "ಇನ್ನಷ್ಟು ವಿಡಿಯೋ",
    },
    // gadgetSliderConfig: {
    //   mobile: "ಮೊಬೈಲ್‌",
    //   laptop: "ಲ್ಯಾಪ್‌ಟಾಪ್‌ಗಳು",
    //   tablet: "ಟ್ಯಾಬ್ಲೆಟ್‌",
    //   camera: "ಕ್ಯಾಮರಾ",
    //   smartwatch: "ಸ್ಮಾರ್ಟ್‌ವಾಚ್‌",
    //   fitnessband: "ಫಿಟ್‌ನೆಸ್‌ ಬ್ಯಾಂಡ್‌",
    //   latest: "ಲೇಟೆಸ್ಟ್‌",
    //   popular: "ಟ್ರೆಂಡಿಂಗ್‌",
    //   submitRating: "ರೇಟಿಂಗ್‌ ಸಬ್ಮಿಟ್‌ ಮಾಡಿ",
    //   critic: "ಕ್ರಿಟಿಕ್‌",
    //   user: "ಯೂಸರ್‌",
    //   buyAtAmazon: "ಅಮೆಜಾನ್‌ನಲ್ಲಿ ಖರೀದಿಸಿ",
    //   rumoured: "ಅಂದಾಜು ಬಿಡುಗಡೆ ದಿನಾಂಕ",
    //   upcoming: "ಬಿಡುಗಡೆಗೊಳ್ಳಲಿರುವ",
    //   estimatedReleaseDate: "ಅಂದಾಜು ಬಿಡುಗಡೆ ದಿನಾಂಕ",
    // },
    search_placeholder: "ಹುಡುಕಿ",
    highlight: "ಹೈಲೈಟ್ಸ್‌:",
    popularVideos: "ಜನಪ್ರಿಯ ವಿಡಿಯೋ",
    orientation_heading: "ನಿಮ್ಮ ಡಿವೈಸ್‌ನನ್ನು ರೊಟೇಟ್‌ ಮಾಡಿ",
    orientation_text: "ದಯವಿಟ್ಟು ಪೋಟ್ರೇಟ್‌ ಮೋಡ್‌ ಅನ್ನೇ ಉಪಯೋಗಿಸಿ",
    videos: "ವೀಡಿಯೋ",
    photo: "ಗ್ಯಾಲರಿ",
    cast: "ತಾರಾಗಣ",
    related_videos: "ಸಂಬಂಧಿತ ವೀಡಿಯೋ",
    most_viewed_videos: "ಜನಪ್ರಿಯ ವಿಡಿಯೋ",
    photomasti: "ಫೋಟೊ ಗ್ಯಾಲರಿ",
    user_rating: "ನಿಮ್ಮ ರೇಟಿಂಗ್‌",
    default_horizontal_tile_width: 133, // These widths are used for slider
    default_slideshow_tile_width: 120,
    related_articles_horizontal_tile_width: 230,
    relatedarticle: "ಸಂಬಂಧಿತ ಸುದ್ದಿ",
    read_more_listing: " ಮತ್ತಷ್ಟು",
    critics_review: "ವಿಮರ್ಶೆ",
    twitte_reaction: "ಟ್ವಿಟರ್ ಪ್ರತಿಕ್ರಿಯೆ",
    critics_rating: "ಕ್ರಿಟಿಕ್‌ ರೇಟಿಂಗ್",
    movie_review: "ಸಿನಿಮಾ ವಿಮರ್ಶೆ",
    review_device: "ಡಿವೈಸ್‌ ರಿವ್ಯೂ ಮಾಡಿ",
    film_review: "ಸಿನಿಮಾ ವಿಮರ್ಶೆ",
    review_movie: "ವಿಮರ್ಶೆ",
    rate_movie: "ಸಿನಿಮಾಗೆ ಅಂಕ ನೀಡಿ",
    rate: "ರೇಟಿಂಗ್‌ ನೀಡಿ",
    rate_recipe: "Rate Recipe",
    slide_to_rate: "Slide to Rate",
    slide_to_rate_movie: "ಚಿತ್ರಕ್ಕೆ ರೇಟಿಂಗ್ ನೀಡಲು ಸ್ಲೈಡ್ ಮಾಡಿ",
    reader_rating: "ಓದುಗರ ರೇಟಿಂಗ್",
    movie_review_tile_bg: "https://static.langimg.com/moviereview_list_bg/photo/65022261.cms",
    movie_review_detail_bg: "https://static.langimg.com/moviereview_list_bg/photo/65594589.cms",
    breaking_news: "ಬ್ರೇಕಿಂಗ್‌ ನ್ಯೂಸ್",
    trending: "ಟ್ರೆಂಡಿಂಗ್‌",
    highlightText: "ಹೈಲೈಟ್ಸ್‌ ಮಾತ್ರವೇ ಓದಲು ಆ್ಯಪ್‌ ಡೌನ್‌ಲೋಡ್‌ ಮಾಡಿ",
    live_video: "ಲೈವ್‌ ವೀಡಿಯೋ", // Using for minitv widget
    view_text: "ನೋಡಿ",
    aur_jaane: "ಮತ್ತಷ್ಟು ತಿಳಿಯಿರಿ",
    oops: "ಅಯ್ಯೋ... ",
    thanks: "ಧನ್ಯವಾದ... ",
    offlineText: "ನೀವು ಆಫ್‌ಲೈನ್‌ ಹೋಗಿದ್ದೀರಿ ಎಂದೆನಿಸುತ್ತದೆ",
    onlineText: "ಈಗ ನೀವು ಆನ್‌ಲೈನ್‌ ಇದ್ದೀರಿ",
    openinapp: "ಆ್ಯಪ್‌ನಲ್ಲಿ ನೋಡಿ",
    superhit: " ಇನ್ನಷ್ಟು ಸುದ್ದಿಗಳು",
    live_updates: "ಲೈವ್‌ ಅಪ್‌ಡೇಟ್‌",
    fblikecardtext: "ವಿಕ ಫೇಸ್‌ಬುಕ್‌ ಪೇಜ್‌ ಅನ್ನು <br/> ಲೈಕ್‌ ಮಾಡಿ", // Using in Service Drawer
    appdownloadcardtext: "ತಾಜಾ ಸುದ್ದಿಗಳನ್ನು ವಿಕ <br /> ಆ್ಯಪ್‌ನಲ್ಲಿ ಪಡೆಯಿರಿ", // Using in Service Drawer
    installapp: "ಇನ್‌ಸ್ಟಾಲ್‌ ಮಾಡಿ",
    login: "ಲಾಗ್‌ಇನ್‌",
    logout: "ಲಾಗ್‌ಔಟ್‌",
    amazonDeals: "ಈ ದಿನದ ಕೊಡುಗೆಗಳು",
    seemoreimages: "ಇನ್ನಷ್ಟು ಚಿತ್ರಗಳು", // Using in Photomazzashow
    read_more_liveblog: "ಮತ್ತಷ್ಟು ಓದಿ",
    footerheading: "ವಿಜಯ ಕರ್ನಾಟಕವನ್ನು ನೋಡಿ",
    comment_text: "ಕಾಮೆಂಟ್‌ ಮಾಡಿ",
    download_text: "ಡೌನ್‌ಲೋಡ್‌",
    write_comment: "'ಕಾಮೆಂಟ್‌ ಮಾಡಿ",
    view_comment: "ಕಾಮೆಂಟ್‌ ನೋಡಿ",
    text_topcomment: "ಟಾಪ್‌ ಕಾಮೆಂಟ್‌",
    text_latestcomment: "ಇತ್ತೀಚಿನ ಕಾಮೆಂಟ್‌",
    text_author_comment: "ಲೇಖಕರ ಕಾಮೆಂಟ್‌",

    wp_broadcast: {
      description: "ವಾಟ್ಸ್‌ಆ್ಯಪ್‌ನಲ್ಲೇ ಸುದ್ದಿಗಳನ್ನು ಪಡೆಯಿರಿ",
      btnText: "ಸಬ್‌ಸ್ಕ್ರೈಬ್‌",
      url: "https://widget.whatsbroadcast.com/widget_more/6f6d34241a811f155f117e19ff23de74/?show=walink&text=",
    },
    crossbrand: "ಈ ಸುದ್ದಿ -hyperlink- ಲ್ಲಿ -dl- ಪ್ರಕಟವಾಗಿತ್ತು",
    appexclusive: "ಆ್ಯಪ್‌ ಎಕ್ಸ್‌ಕ್ಲೂಸಿವ್‌",
    votesuccessfully: "ನಿಮ್ಮ ವೋಟ್‌ ನೋಂದಣಿಯಾಗಿದೆ",
    votealready: "ನೀವು ಈಗಾಗಲೇ ವೋಟ್‌ ಮಾಡಿದ್ದೀರಿ",
    submit_vote: "ಸಲ್ಲಿಸಿ",
    photoshow_app_install: {
      read_more: "ಇನ್ನಷ್ಟು ಫೋಟೋಗಳಿಗೆ ಆ್ಯಪ್‌ ಡೌನ್‌ಲೋಡ್‌ ಮಾಡಿ",
      download: "ಡೌನ್‌ಲೋಡ್‌ ಆ್ಯಪ್‌",
    },
    disclaimer: "ಅಬಾಧ್ಯತೆ",
    live_tv: "LIVE TV",
    data_hub: "ಬಜೆಟ್ ಮಾಹಿತಿ ಗುಚ್ಛ",
    fantasy_game: "ಬಜೆಟ್ ಫ್ಯಾಂಟಸಿ ಗೇಮ್",
    topics_no_result: "ಈ ವಿಷಯದಲ್ಲಿ ಯಾವುದೇ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ",
    players: "ಆಟಗಾರರು",
    appDownload: "Vijay Karnataka App",
    tech: {
      inIndia: "ಭಾರತದಲ್ಲಿ",
      loadmore: "ಇನ್ನಷ್ಟು",
      rating: "ರೇಟಿಂಗ್‌",
      sortby: "ವಿಂಗಡಿಸಿ",
      clearall: "ಎಲ್ಲವನ್ನೂ ಕ್ಲೀಯರ್ ಮಾಡಿ",
      buyhere: "ಖರೀದಿಸಿ",
      indiaLaunchDates: "ಭಾರತದಲ್ಲಿ ಬಿಡುಗಡೆ ದಿನಾಂಕ",
      indiaPrice: "ಭಾರತದಲ್ಲಿ ಬೆಲೆ",
      compCriteria: "ಹೋಲಿಕೆ ಕ್ರೈಟೀರಿಯಾ",
      showDiff: "ವ್ಯತ್ಯಾಸವನ್ನಷ್ಟೇ ತೋರಿಸಿ",
      alreadyAdded: "ಈ ಗ್ಯಾಜೆಟ್‌ ನ್ನು ನೀವು ಈಗಾಗಲೇ ಆಯ್ಕೆ ಮಾಡಿದ್ದೀರಿ",
      buyFrom: "ಅಮೆಜಾನ್‌ನಿಂದ ಖರೀದಿಸಿ",
      addDevice: "ಡಿವೈಸ್‌ ಸೇರಿಸಿ",
      compare: "ಹೋಲಿಸಿ",
      englishtype: "ದಯವಿಟ್ಟು english ನಲ್ಲಿ ಟೈಪ್‌ ಮಾಡಿರಿ",
      change: "ಬದಲಿಸಿ",
      suggestedDevice: "ಡಿವೈಸ್ ಸಲಹೆ",
      pe: "पर",
      gadgets: "ಗ್ಯಾಜೆಟ್ಸ್‌",
      filtertxt: "ಫಿಲ್ಟರ್ಸ್‌",
      purchasehere: "ಜಾಹೀರಾತು: ಸ್ಟೋರ್‌ನಲ್ಲಿ",
      popular: "ಪ್ರಸಿದ್ದ",
      allbrands: "ಎಲ್ಲ ಬ್ರ್ಯಾಂಡ್‌ಗಳು",
      brands: "ಬ್ರ್ಯಾಂಡ್‌",
      othervariants: "ಇನ್ನಷ್ಟು ಮಾದರಿ",
      criticsrating: "ಕ್ರಿಟಿಕ್‌ ರೇಟಿಂಗ್‌",
      launchdate: "ಸಂಭಾವ್ಯ ಬಿಡುಗಡೆ ದಿನಾಂಕ",
      review: "ವಿಮರ್ಶೆ",
      overview: "ಓವರ್‌ ವ್ಯೂ",
      userrating: "ಬಳಕೆದಾರರ ರೇಟಿಂಗ್‌",
      submitrating: "ರೇಟಿಂಗ್‌ ಸಬ್ಮಿಟ್‌ ಮಾಡಿರಿ",
      addtocompare: "ಹೋಲಿಕೆಗೆ ಸೇರಿಸಿ",
      purchase: "ಖರೀದಿಸಿ",
      suggested: "ಸೂಚಿಸಲಾದುದು",
      comparetxt: " ಹೋಲಿಕೆ",
      latest: "ಲೇಟೆಸ್ಟ್‌",
      price: "ಬೆಲೆ",
      rumoured: "ಸಂಭಾವ್ಯ",
      upcoming: "ಮುಂಬರುವ",
      ki: "ಇಂದ",
      relatedgadgets: "ಸಂಬಂಧಿತ ಗ್ಯಾಜೆಟ್ಸ್‌",
      seemore: "ಇನ್ನಷ್ಟು",
      topfeature: "ಟಾಪ್‌ ಫೀಚರ್ಸ್‌",
      fullspecification: "ಸಂಪೂರ್ಣ ಸ್ಪೆಸಿಫಿಕೇಶನ್ಸ್‌",
      selectatleast2: "ಕನಿಷ್ಠ 2 ವಸ್ತುಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿರಿ",
      devicealreadyinlist: "ಈ ವಸ್ತು ಹೋಲಿಕೆಗೆ ಅದಾಗಲೇ ಆಯ್ಕೆ ಮಾಡಿಕೊಳ್ಳಲಾಗಿದೆ.",
      same_gadget: "ಇದೇ ರೀತಿಯ ಗ್ಯಾಜೆಟ್ಸ್‌ಗಳು",
      user_review: "ಬಳಕೆೆದಾರರ ರಿವ್ಯೂ",
      read_fullreview: " ಪೂರ್ಣ ರಿವ್ಯೂ ಓದಿರಿ",
      similar_gadget: "ಇದೇ ರೀತಿಯ ಗ್ಯಾಜೆಟ್ಸ್‌ಗಳು",
      see_diff: "ವ್ಯತ್ಯಾಸ ತಿಳಿಯಿರಿ",
      latest_comparisons: "ಇತ್ತೀಚಿನ ಹೋಲಿಕೆಗಳು",
      popular_comparisons: "ಪ್ರಸಿದ್ದ ಹೋಲಿಕೆಗಳು",

      techNewsH1: "ಟೆಕ್‌ ನ್ಯೂಸ್‌",

      minimumComparisonError: "ಹೋಲಿಕೆೆಗೆ 2 ಗ್ಯಾಜೆಟ್ಸ್‌ಗಳು ಅಗತ್ಯ",
      // gadgets show
      buyAtAmazon: "ಖರೀದಿಸಿ",
      priceList: "ಬೆಲೆೆ ವಿವರ",
      priceInIndia: "ಭಾರತದಲ್ಲಿ ಬೆಲೆ",

      criticReview: "ಕ್ರಿಟಿಕ್‌ ರಿವ್ಯೂ",
      userReview: "ಬಳಕೆದಾಾರರ ರಿವ್ಯೂ",
      specifications: "ಸ್ಪೆಸಿಫಿಕೇಶನ್ಸ್‌",
      comparedotxt: "ಹೋಲಿಸಿ",
      moreLikeThis: "ಇದೇ ರೀತಿಯ",
      criticRating: "ಕ್ರಿಟಿಕ್‌ ರೇಟಿಂಗ್‌",
      userRating: "ಯೂಸರ್ ರೇಟಿಂಗ್‌",

      user: "ಯೂಸರ್",
      others: "ಇತರ",
      nextGadget: "ಮುಂದಿನ ಗ್ಯಾಜೆಟ್‌",
      similarGadgets: "ಇದೇ ರೀತಿಯ ಇನ್ನಷ್ಟು ಗ್ಯಾಜೆಟ್ಸ್‌",

      readCompleteReview: "ಸಂಪೂರ್ಣ ರಿವ್ಯೂ ಓದಿ",
      readLess: "read less",

      recentlyCompared: "ಇತ್ತೀಚಿಗಿನ ಹೋಲಿಕೆ",
      weak: "ದುರ್ಬಲ",
      belowAverage: "ಸಮಾನ್ಯಕ್ಕಿಂತ ಕಡಿಮೆ",
      worthpurchase: "ಖರೀದಿಗೆ ಯೋಗ್ಯ",
      good: "ಉತ್ತಮ",
      excellent: "ಅತ್ಯುತ್ತಮ",
      thanksforreview: "ನಿಮ್ಮ ವಿಮರ್ಶೆಗೆ ಧನ್ಯವಾದ",
      befirsttoreview: "ಮೊದಲ ರಿವ್ಯೂ ನೀವೇ ಬರೆಯಿರಿ",
      userreviewandrating: "ಯೂಸರ್‌ ರಿವ್ಯೂ ಹಾಗೂ ರೇಟಿಂಗ್‌",
      ratedevice: "ಡಿವೈಸ್‌ಗೆ ರೇಟಿಂಗ್‌ ನೀಡಿ",
      postRating: "ನಿಮ್ಮ ರೇಟಿಂಗ್‌ ನೀಡಿ",
      readMoreReview: "ಇನ್ನಷ್ಟು ವಿಮರ್ಶೆ ಓದಿ",
      varients: "ಇನ್ನಷ್ಟು ವೇರಿಯಂಟ್ಸ್‌",
      text_write_reviews: "ವಿಮರ್ಶೆ",
      text_view_comment: "View Comments",
      text_write_comment: "Write Comments",
      critic: "Critic",
      language: "Tech",
      category: [
        { keylabel: "ಮೊಬೈಲ್‌", keyword: "mobile" },
        { keylabel: "ಲ್ಯಾಪ್‌ಟಾಪ್‌", keyword: "laptop" },
        { keylabel: "ಸ್ಮಾರ್ಟ್‌ವಾಚ್‌", keyword: "smartwatch", keylabelEng: "smart watch" },
        { keylabel: "ಟೆಲಿವಿಷನ್‌", keyword: "tv" },
        { keylabel: "ಏರ್‌ ಕಂಡಿಷನರ್‌", keyword: "ac" },
        { keylabel: "ಟ್ಯಾಬ್ಲೆಟ್‌", keyword: "tablet" },
        { keylabel: "ಕ್ಯಾಮೆರಾ", keyword: "camera" },
        { keylabel: "ಫಿಟ್‌ನೆಸ್‌ ಬ್ಯಾಂಡ್‌", keyword: "fitnessband", keylabelEng: "fitness band" },
        { keylabel: "ವಾಷಿಂಗ್‌ ಮಷೀನ್‌", keyword: "washingmachine", keylabelEng: "washing machine" },
        { keylabel: "ರೆಫ್ರಿಜಿರೇಟರ್‌", keyword: "refrigerator", keylabelEng: "fridge" },
        { keylabel: "ಪವರ್‌ ಬ್ಯಾಂಕ್", keyword: "powerbank", keylabelEng: "power bank" },
      ],
      gadgetSliderConfig: {
        mobile: "ಮೊಬೈಲ್‌",
        laptop: "ಲ್ಯಾಪ್‌ಟಾಪ್‌",
        tablet: "ಟ್ಯಾಬ್ಲೆಟ್‌",
        camera: "ಕ್ಯಾಮೆರಾ",
        smartwatch: "ಸ್ಮಾರ್ಟ್‌ವಾಚ್‌",
        fitnessband: "ಫಿಟ್‌ನೆಸ್‌ ಬ್ಯಾಂಡ್",
        tv: "ಟೆಲಿವಿಷನ್‌",
        ac: "ಏರ್‌ ಕಂಡಿಷನರ್",
        washingmachine: "ವಾಷಿಂಗ್‌ ಮಷೀನ್",
        refrigerator: "ರೆಫ್ರಿಜಿರೇಟರ್‌",
        powerbank: "ಪವರ್‌ ಬ್ಯಾಂಕ್",
      },
      affiliateTags: {
        homePage: "vk_wap_home_latesttrendingwidget",
      },
    },
    utility: "ಉಪಯುಕ್ತತೆ",
    user_review: "User Review",
    listenAlbum: "Listen to this album",
    castncrew: "Cast & Crew",
    filmSongs: "Film Songs",
    read_movie_review: "read movie review",
    news: "ಸುದ್ದಿ",
    photos: "Photos",
    market: "ಮಾರುಕಟ್ಟೆ",
    choseStateCity: { dropDownText: "ನಗರ ಆಯ್ಕೆ ಮಾಡಿ", extraCityContent: "ನಿಮ್ಮ ನಗರದ ಸುದ್ದಿಗಳು" },
    cityPopUp: {
      selectStateCity: "ರಾಜ್ಯ ಮತ್ತು ನಗರ",
      selectCity: "ನಗರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
      save: "ಉಳಿಸಿ",
      state: "ರಾಜ್ಯ",
      city: "ನಗರ",
      readersCount: "ವಿಜಯ ಕರ್ನಾಟಕ ದ ಓದುಗರ ಸಂಖ್ಯೆ {{total}} Lac ಆಗಿರುತ್ತದೆ.",
    },
    cityHeading: "ಸಮೀಪದ ನಗರಗಳ ಸುದ್ದಿ",
    cityHeadingVideo: "ಸಮೀಪದ ನಗರಗಳ ವಿಡಿಯೋಗಳು",
    openInApp: {
      stayHere: "ಇಲ್ಲೇ ಓದಿ",
      openApp: "ಆ್ಯಪ್‌ನಲ್ಲಿ ಓದಿ",
      mainText: "ಲೇಖನವನ್ನು ಆ್ಯಪ್‌ನಲ್ಲಿ ಓದುವುದನ್ನು ಮುಂದುವರಿಸುವಿರೇ?",
      mainTextForVSnPS: "ಆ್ಯಪ್‌ನಲ್ಲೇ ನೋಡಲು ಬಯಸುವಿರೇ?",
    },
    authoraritcle: "ಅವರ ಲೇಖನಗಳು",
    authorsharetext: "ಆನ್‌ಲೈನ್‌ ಕನೆಕ್ಟ್‌ ಆಗಿರಿ",
    authorwebstories: " ಅವರ ವೆಬ್‌ಸ್ಟೋರಿಗಳು",
    authorabout: "ಅವರ ಬಗ್ಗೆ",
    articles: "ಆರ್ಟಿಕಲ್‌ಗಳು",
    webstories: "ವೆಬ್‌ಸ್ಟೋರೀಸ್‌",
    dailyNewsUpdate: "ಡೈಲಿ ಅಪ್‌ಡೇಟ್ಸ್‌ಗಾಗಿ ಲಾಗ್‌ಇನ್‌ ಆಗಿರಿ",
    downloadAppForNews: "ಪ್ರತಿನಿತ್ಯದ ನ್ಯೂಸ್‌ ಅಪ್‌ಡೇಟ್ಸ್‌ಗಾಗಿ ಆ್ಯಪ್‌ ಡೌನ್‌ಲೋಡ್‌ ಮಾಡಿರಿ",
    notificationTopNewsAlert: "ಯಾವುದೇ ನ್ಯೂಸ್‌ ಮಿಸ್‌ ಮಾಡದಿರಿ. ನೋಟಿಫಿಕೇಶನ್‌ಗಾಗಿ ಸಬ್‌ಸ್ಕ್ರೈಬ್‌ ಮಾಡಿರಿ",
    notification: "ನೋಟಿಫಿಕೇಶನ್‌",
    others: "ಇತರ",
  },
  imageconfig: {
    thumbid: "67175291",
    liveblogthumb: "58166012",
    techthumb: "67175291",
    defaultthumb: "67175291", // preserve default id if thubmid chnaged to differ
    imagedomain: "https://static.langimg.com/thumb/",
    webimagedomain: "https://vijaykarnataka.com/thumb/",
    bigimage: "width=540&resizemode=3", // Article Inline Images, will maintain aspect ratio of original image
    big2ximage: "width=1080&resizemode=3", // Article Inline Images, will maintain aspect ratio of spotlight/paid article image
    smallthumb: "width=280&height=210&resizemode=75", // Listing small thumbs, Aspect Ratio 4:3
    smallslideshowthumb: "width=320&height=240&resizemode=1", // Used for external photogallery strip on top news, Aspect Ratio 4:3
    midthumb: "width=320&height=240&resizemode=75", // Photo Listing widget thumb, etc Aspect Ratio 4:3
    largethumb: "width=380&height=285&resizemode=75", // Lead Images Aspect Ratio 4:3
    amplargethumb: "width=1600&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only videoshow
    amplargethumbarticle: "width=1200&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only for article
    smallwidethumb: "width=200&height=111&resizemode=75", // For video listing widgets Aspect Ratio 16:9
    largewidethumb: "width=380&height=214&resizemode=75", //  For videowidget lead image and videoshow Aspect Ratio 16:9
    posterthumb: "width=210&height=281&resizemode=4", // Moview Posters
    squarethumb: "width=200&height=200&resizemode=75", // for two colum layout
    rectanglethumb: "width=160&height=103&resizemode=75", // for rectangle flags
    gnthumb: "width=200&resizemode=4", // for Gadget now
    gnthumbWithHeight: "height=150&resizemode=4", // for GN PDP, need height
    webstoriesthumb: "width=300&height=500&resizemode=4", // web stories Photo Listing widget thumb",
    webstoriesthumbLarge: "width=364&height=607&resizemode=4", // web stories Photo Listing widget thumb",
    widecardthumb: "width=600&height=315&resizemode=6", // End Article Card thumb 16: 9",
  },
  sso: {
    BASE_URL: "https://vijaykarnataka.com",
    SSO_CHANNEL: "vk-wap",
    GADGET_CHANNEL: "kannada-gadgetsnow-wap",
    stg: {
      BASE_URL: "https://langdev8352.indiatimes.com",
      MYTIMES_URL_USER: "https://mytest.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
      MYTIMES_URL_SETTINGS: "https://jssostg.indiatimes.com/sso/identity/profile/edit?channel=tm",
      SSO_URL_LOGIN: "https://jssostg.indiatimes.com/sso/identity/login",
      SSO_URL_LOGOUT: "https://jssostg.indiatimes.com/sso/identity/profile/logout/external",
      SSO_URL_GETTICKET: "https://jssostg.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
      SOCIAL_API_INTEGRATOR: "https://testsocialappsintegrator.indiatimes.com/socialsite",
      SSO_BASE_URL: "https://jssostg.indiatimes.com/sso/crossdomain",
      SSO_CROSSWALK: "https://jssocdnstg.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
      SSO_WIDGET_URL: "https://jssocdnstg.indiatimes.com/crosswalk/133/widget/main.bundle.js",
    },

    SSO_BASE_URL: "https://jsso.indiatimes.com/sso/crossdomain",
    SSO_CROSSWALK: "https://jssocdn.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
    SSO_WIDGET_URL: "https://jssocdn.indiatimes.com/crosswalk/34/widget/main.bundle.min.js",
    MYTIMES_URL_USER: "https://myt.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
    SSO_URL_LOGIN: "https://jsso.indiatimes.com/sso/identity/login",
    SSO_URL_LOGOUT: "https://jsso.indiatimes.com/sso/identity/profile/logout/external",
    SSO_URL_GETTICKET: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
    MYTIMES_ALREADY_RATED: "https://myt.indiatimes.com/mytimes/alreadyRated?appKey=IV&",
    MYTIMES_ADD_ACTIVITY: "https://myt.indiatimes.com/mytimes/addActivity?appKey=IV&",
    SSO_TRUECALLER_visibility: 4,
    MYTIMES_URL_SETTINGS: "https://jsso.indiatimes.com/sso/identity/profile/edit?channel=vk",
    PROFILE_URL: "https://mytimes.indiatimes.com/profile",
    SSO_URL_NewsTicket: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1",
    SSO_URL_SubStatus: "https://webapi.sendpal.in/api/v1/get/user/vk/status?dataformat=json",
    SSO_URL_unsubscribe: "https://webapi.sendpal.in/api/v1/multiple/unsubscribe/vk?dataformat=json",
    SSO_URL_subscribe:
      "https://webapi.sendpal.in/api/v1/add/subscription/vk?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=43",
    SSO_URL_confirm: "https://webapi.sendpal.in/api/v1/confirm/subscription/vk?dataformat=json",
    SOCIAL_API_INTEGRATOR: "https://socialappsintegrator.indiatimes.com/socialsite",
  },
  MYTIMES_PROFILE: "https://mytimes.indiatimes.com/?channel=vk",
  TimesPoint: {
    jsDev: "https://test.timespoint.com/tpwidgets-test/static/dist/js/main.js",
    jsProd: "https://image.timespoints.iimg.in/tpwidgets/static/dist/js/main.js",
    channels: ["tml", "nbt", "eisamay", "tlg", "mly", "mt", "vk"],
    // status: true,
    pcode: "channel9817715",
    scode: "channel9817715",
    activities: {
      DAILY_CHECKINS: "act4709720",
      DAILY_CHECKINS_MOBILE: "act4837418",
      READ_ARTICLE: "act7123641",
      WATCH_VIDEOS: "watch_video",
      SH_FB: "sh_fb",
      SH_TW: "sh_tw",
      LOGIN: "login",
      MOVIE_RATE: "act887226",
      // Fired by MyProfile team
      MOVIE_REVIEW: "act8983865",
      VIEW_PHOTO: "view_photo",
      LIVE_BLOG: "act4938882",
      SUB_NL: "sub_nltr",
      REGISTER: "act3472334",
      // Fired by MyProfile team
      COMMENT: "cmnt",
      SUB_NOTIFICATION: "act5001108",
      // Not found for staging
      CHECKIN_BONUS_DESKTOP: "act4856706",
      // Not found for staging
      CHECKIN_BONUS_MOBILE: "act4878553",
      WHATSAPP_SHARE: "act5021627",
    },
    campaingHistoryName: {
      desktop: "campaign7924060",
      mobile: "campaign8021672",
    },
    campaignDays: 5,

    stg: {
      pcode: "channel4365687",
      scode: "channel4365687",
      campaingHistoryName: {
        desktop: "campaign2053450",
        mobile: "campaign2190994",
      },
      activities: {
        DAILY_CHECKINS: "act1337680",
        DAILY_CHECKINS_MOBILE: "act1359277",
        READ_ARTICLE: "act8793733",
        WATCH_VIDEOS: "watch_video",
        SH_FB: "sh_fb",
        SH_TW: "sh_tw",
        LOGIN: "login",
        MOVIE_RATE: "act1439693",
        // Fired by MyProfile team
        MOVIE_REVIEW: "rv",
        VIEW_PHOTO: "view_photo",
        LIVE_BLOG: "act1474368",
        SUB_NL: "sub_nltr",
        REGISTER: "register",
        // Fired by MyProfile team
        COMMENT: "cmnt",
        SUB_NOTIFICATION: "act1519134",
        CHECKIN_BONUS_DESKTOP: "act1850581",
        CHECKIN_BONUS_MOBILE: "act1872964",
        WHATSAPP_SHARE: "act1542784",
      },
    },

    TP_FAQ_MSID: "79550983",
    NP_DOMAIN: {
      production: "https://npcoins.indiatimes.com",

      development: "https://nprelease.indiatimes.com",
      stg1: "https://nprelease.indiatimes.com",
      stg2: "https://nprelease.indiatimes.com",
    },

    TP_DOMAIN: {
      production: "https://tpapi.timespoints.com",

      development: "https://test.timespoints.com/tpapi",
      stg1: "https://test.timespoints.com/tpapi",
      stg2: "https://test.timespoints.com/tpapi",
    },

    SDK_DOMAIN: {
      production: "https://image.timespoints.iimg.in",

      development: "https://test-img.timespoints.com",
      stg1: "https://test-img.timespoints.com",
      stg2: "https://test-img.timespoints.com",
    },

    tpwidgetJS: {
      production: "/tpwidgets/dist/js/tpwidget.js",

      development: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg1: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg2: "/static/tpwidgets/static/dist/js/tpwidget.js",
    },

    //* * Moved to common config */
    tpPage: "/timespoints.cms",
    tpRedeemLink: "https://www.timespoints.com/products",
  },
  Comments: {
    appkey: "IV",
    topComments: {
      appkey: "IV",
      sortcriteria: "AgreeCount",
      order: "desc",
      size: "1",
      lastdeenid: "0",
      after: "true",
      withReward: "false",
      pagenum: "1",
    },
    allComments: {
      appkey: "IV",
      sortcriteria: "CreationDate",
      order: "asc",
      size: "6",
      lastdeenid: 0,
      after: true,
      withReward: false,
      pagenum: 1,
    },
  },
  pages: {
    elections: "63427237",
    mktwdt: "87731283",
    business: "10738503",
    tech: "60023487",
    techreview: "70396691",
    technav: "60023487",
    iplHomePage: "63300283",
    commonwealth: "63514281",
    fifa: "64494258",
    wcHomePage: "86780091",
    stateSection: "71478549,10753874",
    gadgethome: "83548350",
    budget: "67585877",
    budget_you: "97254559",
    apanabazaar: "86556272",
  },
  iplpages: {
    venues: "63300526",
    teams: "63300502",
    pointsTable: "63300474",
    miniSchedule: "63300493",
  },
  t20wcpages: {
    venues: "86780401",
    teams: "86780321",
    pointsTable: "86780224",
    miniSchedule: "86780271",
  },
  redis: {
    host: "127.0.0.1",
    port: "6379",
    db: "1",
    isRedisCachingSupported: true,
  },
  // To print label in listing node at bottom right corner [templatename, label]
  listNodeLabels: {
    articlelist: ["articlelist"],
    news: ["articleshow"],
    photo: ["photoshow"],
    slideshow: ["photoshow"],
    video: ["videoshow"],
    videolist: ["videolist"],
    photolist: ["photolist"],
    lb: ["liveblog", "ಲೈವ್‌ ಬ್ಲಾಗ್‌"],
    moviereview: ["moviereview", "ಸಿನಿ ವಿಮರ್ಶೆ"],
    movieshow: ["movieshow", "ಸಿನಿ"],
    poll: ["pollsurvey", "ಮತದಾನ"],
  },
  photoListView: "47882310",
  miniTvMoreVideos: "49909262",
  // Used In AnchorLinkCard
  routes: [
    "/exitpolls/",
    "/results/",
    "/electionlist/",
    "/articlelist/",
    "/photoarticlelist/",
    "/photomazza/",
    "/photolist/",
    "/photogallery/",
    "/photoshow/",
    "/articleshow/",
    "/moviereview/",
    "/movieshow/",
    "/liveblog/",
    "/videolist/",
    "/videoshow/",
    "/topics/",
    "/teams/",
    "/venues/",
    "/pointstable/",
    "/iplt20.cms",
    "/schedule/",
    "/sportsresult/",
    "/elections/assembly-elections/results",
    "elections.cms",
    "/reviews.cms",
    "/timespoints",
  ],

  staticPagesDir: "/var/www/html/testpages/",

  slike: {
    apikey: "vijaykamweb78lang",
    snapchatapikey: "lng54mweb5afm96lgz9",
    ampapikey: "vijaykaampweb78lang",
    default_slikeid_minitv: "1x13qpaggu", // Times-Now
    nextvideo_domain: "https://mtpwafeeds.indiatimes.com",
    default_pl_videolist: "/feeds/videpostroll_v5_slike/4901865.cms?feedtype=json&callback=cached",
  },

  slikeAdCodes: {
    home: "home,4901865",
    auto: "2355188,28471009",
    bharat: "1564454",
    cricket: "3521869",
    duniya: "2279801",
    haryana: "21236773",
    "josh-jawani": "3041664",
    jokes: "12545518,5556078",
    lucknow: "21248218",
    "share-market": "2279786,11873677",
    "movie-masti": "2279793,4901881,11872954",
    mumbai: "5722181",
    "movie-review": "2325387",
    "other-cities": "21236618",
    other: "other",
    photo: "2339144",
    rajya: "33503484",
    rashifal: "17127056,48972527",
    "score-card": "999999",
    sahar: "33503484",
    "super-hit": "999999",
    tech: "19615041,20104392",
    "top-news": "696089404,4901886",
    "uttar-pradesh": "21236867",
    vichar: "2007740431",
  },
  gRecaptchaKey: "6LcxSGUUAAAAAPsGPKVpEkLKxnuluuqDKa1AivEN",

  ga: {
    gtm: "GTM-5WVQ988",
    gtm4: "G-P6RWT403VS",
    ampgtm: "GTM-5WVQ988",
    gverifyCode: "tX6zCoCuYqu6JY5VZ1ZQ7Cj5n6zcR9NzfuaFvWlolqA",
    gatrackid: "UA-29031733-2",
    ga4trackid: "G-P6RWT403VS",
    gaprofile: "['superpacer.in', 'vijayanextepaper.com', 'vijaykarnatakaepaper.com', 'mobilevk.com']",
  },

  growthrx: {
    stg: {
      id: "g3dd26d07",
    },
    prod: {
      id: "g8c6d3876",
    },
    gn: {
      stg: {
        id: "g6038def9",
      },
      prod: {
        id: "g2bdedac1",
      },
    },
  },

  appexclusive_ga: {
    category: "Wap to App install",
    action: "click",
    label: "articlelist_topsection",
  },
  poll: {
    link: "pollslist.cms",
  },
  poll_ga: {
    poll_submit: {
      category: "pollSurvey",
      action: "submit",
      label: "pollsubmit",
    },
    poll_result_loggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "loggedin",
    },
    poll_result_nonloggedIn: {
      category: "pollSurvey",
      action: "viewresult",
      label: "non-loggedin",
    },
  },

  photoshow_app_install: {
    ga_object: {
      category: "Wap to App install",
      action: "click",
      label: "photo show",
    },
  },
  // sso_ga: {
  //   truecaller_requestscreen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen Request",
  //   },
  //   truecaller_screen: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Screen View",
  //   },
  //   truecaller_screencontinue: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Continue",
  //   },
  //   truecaller_skip: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Skip",
  //   },
  //   truecaller_loginsuccess: {
  //     category: "True Caller",
  //     action: "Click",
  //     label: "Login Successful",
  //   },
  // },
  comscore: { c1: "2", c2: "6036484" },

  applinks: {
    android: {
      hrnav: "https://vijaykarnataka.onelink.me/mi10/286092c9",
      asshow: "https://vijaykarnataka.onelink.me/mi10/446b3fa1",
      photoshow: "https://vijaykarnataka.onelink.me/mi10/dd002b19",
      serviceDrawer: "https://vijaykarnataka.onelink.me/mi10/509a8e5b",
      social: "https://vijaykarnataka.onelink.me/mi10/9890a4c1",
      oip_appexclusive: "https://navbharattimes.indiatimes.com/off-url-forward/vk_openinapp.cms?msid=",
      // https://vijaykarnataka.onelink.me/cMxT/b256ac1
    },
  },
  appdeeplink: {
    domain: "https://vijaykarnataka.onelink.me",
    shortcode: "mi10",
    c: "Internal_Campaign",
    pid: {
      hrnav: "WAP_HRNAV",
      serviceDrawer: "WAP_BOTTOM",
      news: "WAP_MWEB",
      article_end: "WAP_AS",
      photo: "WAP_PG",
      toparticle: "WAP_Top%20Articles",
      extphoto: "WAP_Home_Photostrip",
      photoshow: "WAP_Photoshow",
      campaign: "WAP_Election",
      campaignHome: "WAP_Election_Home",
      openinapp_as: "VK_AS_Brandwire",
      openinapp_al: "VK_AL_Brandwire",
      photofeature: "WAP_MWEB",
      photoFeature: "WAP_MWEB",
      recipe: "WAP_MWEB",
      videoshow: "WAP_VideoShow",
      topStrip: "WAP_Top_Strip",
      articlelist: "WAP_ArticleList",
      topStripAS: "New_Top",
      videolist: "WAP_VideoList",
      photolist: "WAP_PhotoList",
      continueInApp: "Continue_App",
      sharing: "WAP_Sitesharing",
    },
    listdefaultUrl: "http://vijaykarnataka.com/feeds/app_listing/<MSID>.cms?feedtype=json",
    openapp: "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka",
    opennews:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Dnews-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openphoto:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openextphoto:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dp-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openhtmlview:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BURL%7D",
    opensection:
      "vkreaderactivities://open-%24%7C%24-pub%3D5:Vijay Karnataka-%24%7C%24-type%3Dsection-%24%7C%24-sectionID%3D%7BsectionID%7D-%24%7C%24-sectionName%3D%7BsectionName%7D-%24%7C%24-id%3D%7BMSID%7D",
    openphotofeature:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3DphotoFeature-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openrecipe:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Drecipe-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openvideoshow:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Dvideo-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
    openarticlelist:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dnews-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openphotolist:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dphoto-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openvideolist:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3Dsection-%2524%257C%2524-sectionType%3Dvideo-%2524%257C%2524-sectionID%3D%7BMSID%7D-%2524%257C%2524-sectionName%3D%7BSECTION_NAME%7D-%2524%257C%2524-defaultUrl%3D%7BFeed_Path%7D",
    openContinueInApp:
      "vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D&af_web_dp=https%3A%2F%2Fvijaykarnataka.com%2F&is_retargeting=true&deep_link_value=vkreaderactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D5%3AVijay%2520Karnataka-%2524%257C%2524-type%3D%7BTYPE%7D-%2524%257C%2524-domain%3Dt-%2524%257C%2524%7BDYNAMIC_DATA%7D-id%3D%7BMSID%7D",
  },
  pushNotification: {
    cookieName: "notifypopup_vk",
    defaultThumb: "https://static.langimg.com/thumb/56082868/pic.jpg?width=100&height=100",
    heading: "ಲೇಟೆಸ್ಟ್‌ ಹಾಗೂ ಬ್ರೇಕಿಂಗ್‌ ನ್ಯೂಸ್‌ಗಾಗಿ ನೋಟಿಫಿಕೇಶನ್‌ ಸಬ್‌ಸ್ಕ್ರೈಬ್‌ ಮಾಡಿಕೊಳ್ಳಿ. ಅನುಮೋದಿಸಿ - ಕ್ಲಿಕ್‌ ಮಾಡಿ.",
  },

  weather: {
    geoLocationApi: "https://geoapi.indiatimes.com/?cb=1",
    defaultCity: "Bangalore",
    citiesJson: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_geocities.cms",
    weatherFeed: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_weathertoday.cms?lat=",
    heading: "ಇಂದಿನ ತಾಪಮಾನ",
    cityText: "ನಿಮ್ಮ ನಗರದ ಸುದ್ದಿ ಓದಿ",
  },
  pollution: {
    heading: "प्रदूषण",
    headingV1: "ನಿಮ್ಮ ನಗರದ ವಾತಾವರಣ ಹೇಗಿದೆ?",
    status: {
      good: "ಉತ್ತಮ",
      moderate: "ಮಧ್ಯಮ",
      unhelathfSG: "ಸೂಕ್ಷ್ಮ ಆರೋಗ್ಯದವರಿಗೆ ಹಿತಕರವಲ್ಲ",
      unhealthy: "ಅನಾರೋಗ್ಯಕರ",
      veryUnhealthy: "ಅಪಾಯಕಾರಿ",
      hazardous: "ಹಾನಿಕಾರಕ",
    },
    url: "https://vijaykarnataka.com/state/pollution-tracker",
  },
  fuel: {
    heading: "फ्यूल",
    feedUrl: "https://toibnews.timesofindia.indiatimes.com/fuelprice/latestPrice",
  },

  oneTapSignIn: {
    smartlockurl: "https://smartlock.google.com/client",
    isViewGaTracked: false,
    eventGAObj: {
      hitType: "event",
      eventCategory: "Login",
      eventAction: "One_Tap",
      eventLabel: "",
    },
    text: {
      oneTapSuccessMsg: "ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಲಾಗ್‌ಇನ್‌ ಆಗಿದ್ದೀರಿ",
      oneTapErrorMsg: "Oops! ತಾಂತ್ರಿಕ ದೋಷಗಳಿವೆ.ಸ್ವಲ್ಪ ಸಮಯದ ಬಳಿಕ ಪ್ರಯತ್ನಿಸಿ",
      oneTapBtnText: "ಮತ್ತೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ",
    },
    constants: {
      onetapIgnoreDays: 15,
      onetapCookie: "oneTapNextShow",
      onetapIframeCheckTimer: 2000,
      smartlockJsLoadTimer: 10000,
      clientId: "820635333666-ks46aedtelfqud1pf80ood2slnlt0l2q.apps.googleusercontent.com",
      channel: "vk-wap",
      jssoAPIGetURL: "https://jsso.indiatimes.com/sso/services/gponetaplogin/verify",
    },
  },
  ZodiacSigns: {
    url: "#",
    data: [
      { name: "aries", regName: "ಮೇಷ", pos: 1 },
      { name: "taurus", regName: "ವೃಷಭ ರಾಶಿ", pos: 2 },
      { name: "gemini", regName: "ಮಿಥುನ", pos: 3 },
      { name: "cancer", regName: "ಕರ್ಕಾಟಕ", pos: 4 },
      { name: "leo", regName: "ಸಿಂಹ", pos: 5 },
      { name: "virgo", regName: "ಕನ್ಯಾ", pos: 6 },
      { name: "libra", regName: "ತುಲಾ", pos: 7 },
      { name: "scorpio", regName: "ವೃಶ್ಚಿಕ", pos: 8 },
      { name: "sagittarius", regName: "ಧನು ", pos: 9 },
      { name: "capricorn", regName: "ಮಕರ ", pos: 10 },
      { name: "aquarius ", regName: "ಕುಂಭ ", pos: 11 },
      { name: "pisces", regName: "ಮೀನ", pos: 12 },
    ],
  },

  ads: {
    ampInuxuAd:
      "https://adgebra.co.in/afpf/IBN_AMP.html?domain=amp-vijaykarnataka.com&pubid=3613&slotId=1&templateId=4657&accessMode=1&divId=div_407860734567731&cache=123",
    ampAdAfter: "",
    gptUrl: "",
    ctnAddress: "https://static.clmbtech.com/ad/commons/js/8359/colombia_v2.js",
    dmpUrl: "https://static.clmbtech.com/ase/8359/19/aa.js",
    isvPreRollUrl:
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/7176/VijayKarnataka_Mweb/VK_Mweb_Videoshow/VK_Mweb_Videoshow_ISV&description_url=https%3A%2F%2Fvijaykarnataka.com%2F&tfcd=0&npa=0&sz=300x230%7C300x250%7C300x400%7C300x415%7C320x400%7C359x200%7C320x3480%7C320x180&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
    ADS_PRIORITY: "FAN",
    profileid: "2930", // used NBT as of now
    exchangeId: "692991",
    ctnads: {
      inline: {
        ctnId: "206000",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefault: {
        ctnId: "206002",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homedefaultsmall: {
        ctnId: "206002",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontal: {
        ctnId: "206002",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homevertical: {
        ctnId: "206002",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      homehorizontalsmall: {
        ctnId: "206002",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },

      ctnlist: {
        ctnId: "206000",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnlistTop: "354488",
      ctnlist1: {
        ctnId: "206000",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      // "ctnlist": "320650",
      ctnpgl1: "341004",
      ctnpgl2: "341004",
      ctnvll1: "341002",
      ctnvll2: "341003",
      ctnbiglist: {
        ctnId: "324203",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_Direct_AL_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnbigphoto: {
        ctnId: "324204",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_Direct_PG_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      ctnsluglist: "355642",
      listdefault: {
        ctnId: "206000",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      listhorizontalsmall: {
        ctnId: "206000",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnmgid: "M787962ScriptRootC",
      ctnMmgid: "1277592",
      ctnBmgid: "1277593",
      ctnmgidurl: "https://jsc.mgid.com/t/i/til.vijaykarnataka.com",

      ctnshow: "323132",
      ctnmidart: "334312",
      ctnnative: "323131",
      ctnmidart_test: "", // for test page only requested by sales
      ctnrecommended: {
        ctnId: "206000",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnrhsvideo: "341005",
      ctnshowvideo: "334312", // video ad on articleshow
      ctnvs: "341002", // Video Show
      // "ctnhome" : "316371",  // caraousal ad code, just for test
      // "ctnhometop" : "206698",
      ctnhome: {
        ctnId: "206002",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnhometop: "206701", // updated
      ctnhomevideo: "318092",
      ctninlineshow: "259033",
      ctnslider: "210646",
      ctnVideoURL: "https://vijaykarnataka.com/ads_native_video_dev.cms",
      ctnbighome: {
        ctnId: "324202",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_Direct_HP_Bid_Experiment_300",
        dfpSize: [300, 250],
      },
      homeibeat: {
        ctnId: "206002",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_HP_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctnint: "324738", // actual ad code for CTN INT TLG

      ctnshowphoto: "341029",

      ctntopicsall: {
        ctnId: "206000",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctntopicsnews: {
        ctnId: "206000",
        dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
        dfpSize: [320, 100],
      },
      ctntopicsphotos: "341004",
      ctntopicsvideos: "341003",

      ctnint_test: "",
      adspositionsPhoto: "-3-,-5-,-9-,-14-,-20-,-27-,-36-,-45-,-55-",
      adspositionsLiveblog: "-5-,-10-,-15-,-20-,-25-,-30-,-35-,-40-",
      ctncookievalue: "ce_mapvk",
      ctnbccl: "340364",
      ctnTechGL: "334798", // Gadget Config
      ctnTechPDP: {
        ctnId: "334802",
        dfpSlot:
          "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Gadget_Mweb_ROS_Inarticle_Bid_Experiment_300",
        dfpSize: [300, 250],
      }, // Gadget Config
      ctnTechCL: "357047", // Gadget Config
      ctnTechCDP: {
        ctnId: "334802",
        dfpSlot:
          "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Gadget_Mweb_ROS_Inarticle_Bid_Experiment_300",
        dfpSize: [300, 250],
      }, // Gadget Config
      ctnTechTC: "357047", // Gadget Config
      tech: {
        ctntech: {
          ctnId: "206000",
          dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
          dfpSize: [320, 100],
        },
        ctntechTop: "334804",
        ctntechlist: {
          ctnId: "206000",
          dfpSlot: "/7176/VijayKarnataka_Mweb/VijayKarnataka_Mweb_Bid_Experiment/VK_Mweb_ROS_Bid_Experiment_320",
          dfpSize: [320, 100],
        },
        ctntechoth: "357686",
        ctntechvideo: "334803",
      },
      ctnInImage: "518965",
      ctnPreRoll: "518893",
    },
    ctnslots: {
      atf: "",
      ctnshow: "",
      ctnbiglist: "",
      ctnbigphoto: "",
      midart: "",
      articleshow: "",
      liveblog: "",
      photoshow: "",
      videoshow: "",
      videolist: "",
    },

    fanads: {
      home: {
        atf: {
          id: "2692813710728993_2718700638140300",
          size: "320x50",
        },
        fbn: {
          id: "2692813710728993_2718700574806973",
          size: "320x50",
        },
      },
      articlelist: {
        atf: {
          id: "2692813710728993_2718702468140117",
          size: "320x50",
        },
        fbn: {
          id: "2692813710728993_2718702414806789",
          size: "320x50",
        },
        mrec: {
          id: "2692813710728993_2718702514806779",
          size: "300x250",
        },
      },
      articleshow: {
        atf: {
          id: "2692813710728993_2718700618140302",
          size: "320x50",
        },
        fbn: {
          id: "2692813710728993_2718700548140309",
          size: "320x50",
        },
        mrec: {
          id: "2692813710728993_2718700674806963",
          size: "300x250",
        },
        mrec2: {
          id: "2692813710728993_2718718488138515",
          size: "300x250",
        },
      },
      others: {
        atf: {
          id: "2692813710728993_2718702504806780",
          size: "320x50",
        },
        fbn: {
          id: "2692813710728993_2718702438140120",
          size: "320x50",
        },
        mrec: {
          id: "2692813710728993_2718702514806779",
          size: "300x250",
        },
      },
    },

    dfpads: {
      adSiteName: "VijayKarnataka",
      adSiteShortName: "VK",
      topatf: "/7176/VijayKarnataka_Mweb/VK_Mweb_Other/VK_Mweb_ROS_OTH_Fixed",
      cubead1: "/7176/VijayKarnataka_Mweb/VK_Mweb_Other/VK_MWEB_OTH_CUBE_195x85",
      cubead2: "/7176/VijayKarnataka_Mweb/VK_Mweb_Other/VK_MWEB_OTH_CUBE2_195x85",
      cubeheadad1: "/7176/VijayKarnataka_Mweb/VK_Mweb_Other/VK_MWEB_OTH_CUBE_195x30",
      cubeheadad2: "/7176/VijayKarnataka_Mweb/VK_Mweb_Other/VK_MWEB_OTH_CUBE_195x30",
      cubeheadad3: "/7176/VijayKarnataka_Mweb/VK_Mweb_Other/VK_MWEB_OTH_CUBE2_195x30",
      cubeheadad4: "/7176/VijayKarnataka_Mweb/VK_Mweb_Other/VK_MWEB_OTH_CUBE2_195x30",
      andbeyond: "/7176/VijayKarnataka_Mweb/VK_Mweb_ROS/VK_Mweb_ROS_Andbeyond_1x1",
      inimage: "/7176/VijayKarnataka_Mweb/VK_Mweb_ROS/VK_Mweb_ROS_Inimage_1x1",
      multiplex: "/7176/VijayKarnataka_Mweb/VK_Mweb_ROS/VK_MWEB_ROS_Bottomwidget",
      canvasAd: "/7176/VijayKarnataka_Mweb/VK_Mweb_ROS/VK_Mweb_ROS_Mcanvas_1x1",
      interstitial: "ca-pub-1902173858658913",
      dfpint: "/7176/VijayKarnataka_Mweb/VK_Mweb_Home/VK_Mweb_HP_INT",
      trk: "/7176/VijayKarnataka_Mweb/VK_Mweb_ROS/VK_Mweb_ROS_trk_1x1",
      osv: "/7176/VijayKarnataka_Mweb/VK_Mweb_ROS/VK_Mweb_ROS_OUTSTREAM_1x1",
      sitesync: "/7176/VijayKarnataka_Mweb/VK_Mweb_Home/VK_Mweb_HP_SiteSync_1x1",
      nativead: "/7176/Languages/VK_Mweb/VK_Mweb_Native_300x250",
      nativeadamp: "/7176/Languages/VK_AMP/VK_AMP_Native_300x250",
      ampIntAd: "/7176/AMP_VK_Mweb/AMP_VK_Mweb_ROS/AMP_VK_Mweb_ROS_INT",
      budgetSlug: "/7176/VijayKarnataka/budget/VK_BDGT_SLG",
      test1: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_1_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_1_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_1_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_1_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_1_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_1_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      test2: {
        atf: {
          id: "div-gpt-ad-9135510865388-0",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_2_ROS_ATF",
          size: [[320, 50]],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-1",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_2_ROS_FBN",
          size: [[320, 50]],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_2_ROS_Mrec1",
          size: [[300, 250]],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_2_ROS_Mrec2",
          size: [[300, 250]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_2_ROS_Mrec3",
          size: [[300, 250]],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecInf",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Test/VK_MWeb_Test_2_ROS_MrecINF",
          size: [[300, 250]],
        },
      },
      others: {
        atf: {
          id: "div-gpt-ad-9135510865388-atf",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_ATF",
          size: [
            [300, 250],
            [320, 100],
            [320, 50],
            [336, 280],
            [250, 250],
            [300, 50],
          ],
        },
        btf: {
          id: "div-gpt-ad-9135510865388-btf",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Other/VK_Mweb_Others_BTF",
          size: [
            [300, 250],
            [320, 50],
            [300, 50],
            [300, 75],
            [234, 60],
          ],
        },
        fbn: {
          id: "div-gpt-ad-9135510865388-fbn",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_FBN",
          size: [
            [320, 50],
            [300, 50],
          ],
        },
        mrec1: {
          id: "div-gpt-ad-9135510865388-mrec1",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_MREC1",
          size: [
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-9135510865388-mrec2",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_MREC2",
          size: [
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrecinf: {
          id: "div-gpt-ad-9135510865388-mrecinf",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_MRECINF",
          size: [
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        slug: {
          id: "div-gpt-ad-9135510865388-slug",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_Slug1",
          size: [
            [300, 100],
            [250, 100],
          ],
        },
        parallax: {
          id: "div-gpt-ad-9135510865388-parallax",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_FC",
          size: [[300, 600]],
        },
        mrec3: {
          id: "div-gpt-ad-9135510865388-mrec3",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_MREC3",
          size: [
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec4: {
          id: "div-gpt-ad-9135510865388-mrec4",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_MREC4",
          size: [
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec5: {
          id: "div-gpt-ad-9135510865388-mrec5",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_MREC5",
          size: [
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec6: {
          id: "div-gpt-ad-9135510865388-mrec6",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_MREC6",
          size: [
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        mrec7: {
          id: "div-gpt-ad-9135510865388-mrec7",
          name: "/7176/VijayKarnataka_Mweb/VK_Mweb_Others/VK_Mweb_Others_MREC7",
          size: [
            [320, 250],
            [300, 250],
            [250, 250],
            [200, 200],
            [180, 150],
          ],
        },
        refreshnews: "/7176/VijayKarnataka_Mweb/VK_Mweb_News/VK_Mweb_News",
      },
    },
  },
  plus: {
    disablePlus: true,
    logo: "https://static.langimg.com/thumb/85000251/tamil-samayam.jpg?height=36&resizemode=4",
    home: "84195947",
    video: "84195995",
    shortName: "VK Plus",
    articleReferrerCd: 5,
    articleTypeCd: 3,
    homeText: "Home",
  },
  // dailyMotion: { channel: "vijaykarnataka", playerId: "x6k9o", meta: "dmdg2dibl6r0f6xd6", syndication: "278258" },
  foryoupage: {
    cid: "8359:136",
    agencyFilters: ["ಭಾಷೆ", "Brandwire", "SPOTLIGHT"],
  },
  authorDetails: {
    agencyName: "Vijaya Karnataka Web",
    authorName: "",
    editorLink: "",
    editorLabel: "",
  },
  cityLandingPage: "/city/articlelist/71478549.cms",
  timesXP: {
    hostName: "vk_xp",
    xpUrl: "https://vkfeed.timesxp.com/langapi",
    appUrl: "https://kannada.timesxp.com",
    wapCode: "kannadaTxp",
  },
  vdoAI: {
    isEnabled: true,
    scriptUrl: "//a.vdo.ai/core/v-vijaykarnataka-v0/vdo.ai.js",
    containerID: "v-vijaykarnataka-v0",
  },
  orgAddress: {
    addressLocality: "Times Internet, No 1/2, Hayat Chambers, 2nd floor, Primrose Road, Off M G Road",
    addressRegion: "Bangalore",
    postalCode: "560025",
  },
  cleoPlayer: {
    apikey: "lang-n9GgmFF518E5Bknb",
  },
};
