module.exports = {
  hostid: "287", // GN Config
  channelid: "696089404",
  mediawireslot: "17",
  wapsitename: "Samayam Malayalam",
  wapsiteregionalname: "സമയം മലയാളം",
  siteName: "malayalam.samayam.com",
  staticSiteName: "static.mly.indiatimes.com",
  fbIAcontentId: "1618522865080130",
  languagemeta: "ml",
  language: "Malayalam",
  channelCode: "ml",
  wapCode: "malayalam",
  gdprID: "MALAY",
  appPlayStoreLink: "https://play.google.com/store/apps/details?id=com.til.malayalamsamayam",
  langnetstorageBasePath: "https://langnetstorage.indiatimes.com/langappfeeds",
  newsApp: "Malayalam News App",
  searchIframeLink: "/topsearchbox.cms",
  languagefullName: "Samayam Malayalam",
  video: { rootId: "47329248", newsId: "97082584" },
  videoiconurl: "/video/videolist/47329248.cms",

  editTrendingMSID: "75174893",
  rss: "/rss.cms",
  coronaId: "74459526",
  applist: "/appslist.cms",
  iospackageid: "1437610958",
  androidpackage: "com.til.malayalamsamayam",
  deeplinkappid: "malayalamsamayamactivities",
  deeplinkpubid: "pub=7:Samayam Malayalam",
  iosapp_name: "Samayam Malayalam App",
  weburl: "https://malayalam.samayam.com",
  mweburl: "https://malayalam.samayam.com",
  gadgetdomain: "https://malayalam.gadgetsnow.com",
  etdomain: "https://malayalam.economictimes.com",
  mweburlgulf: "https://malayalam.samayam.com/gulf",
  ccaudId: "13542:203",
  indexExchangeUrl: "//js-sec.indexww.com/ht/p/191952-217163869956181.js",
  pwtUrl: "//ads.pubmatic.com/AdServer/js/pwt/23105/3786",
  footerDesktopLink: "https://malayalam.samayam.com?mobile=no",
  cookieLessDomain: "https://static.mly.indiatimes.com",
  domain: "samayam.com",
  webdomain: "malayalam.samayam.com",
  mwebdomain: "malayalam.samayam.com",
  photogallerydomain: "photogallery.malayalam.samayam.com",
  google_site_verification: "zU5qA2HPdN2PFPyZd70q25_5NHXI8AE8AbqWNwXsoFA",
  twitterHdandler: "@SamayamM",
  logo: "mly-logo.jpg",
  logo_id: "https://static.langimg.com/thumb/78040133/malayalam-samayam.jpg?width=268&resizemode=4",
  logogn_id: "https://static.langimg.com/thumb/78040133/malayalam-samayam.jpg?width=268&resizemode=4",
  logoPathGadget: "https://static.langimg.com/thumb/83978679/malayalam-samayam.jpg?width=302&resizemode=4",
  googleNews: "https://news.google.com/search?for=malayalam+samayam&hl=ml&gl=IN&ceid=IN%3Aml",
  fb: "https://www.facebook.com/samayammalayalam",
  twitter: "https://twitter.com/SamayamM",
  gplus: "https://plus.google.com/112202535427426413527/about",
  youtubeUrl: "https://www.youtube.com/channel/UCozaoypPySB4MKUi19p2HDA",
  linkedInUrl: "",
  shoppingBag: "https://malayalam.samayam.com/best-deals-online?category=clothes?utm_source=social_panel",
  izooto: "",
  fullutm: "&utm_campaign=malayalam&utm_medium=referral",
  slikeshareutm: "utm_source=slikevideo&utm_medium=referral",
  telegramFollowLink: "https://telegram.me/samayammalayalam",
  shortutm: "ma2",
  icon: "https://malayalam.samayam.com/icons/malyalam.ico?v=1",
  breakingNewsFeedUrl: "https://langnetstorage.indiatimes.com/LANGBNews/malayalambnews.htm",
  fbsdkurl: "https://connect.facebook.net/ml_IN/sdk.js#xfbml=1&version=v3.0",
  fbpage: "https://www.facebook.com/samayammalayalam",
  livebloghpfeed: "",
  moreNews: "More News",
  moreNewsUrl: "https://malayalam.samayam.com/headlines.cms",
  glossaryLanding: "https://langnetstorage.indiatimes.com/langappfeeds/mly_glossarylist_business.htm",
  livebloghostname: "malayalam",
  navfeedurl: "https://langnetstorage.indiatimes.com/langappfeeds/malayalam_navjson.htm",
  liveblogbnbewsurl: "",
  marketIframe: "https://economictimes.indiatimes.com/widget_market.cms?type=1&language=MAL&ref=MLY_Web",
  marketindices:
    "https://economictimes.indiatimes.com/mcoverage_langwidget.cms?language=MAL&type=indices&nofollow=true",
  marketcommodities:
    "https://economictimes.indiatimes.com/mcoverage_langwidget.cms?language=MAL&type=commodities&nofollow=true",
  logo_schema: "https://static.langimg.com/thumb/66648013/malayalam-samayam.jpg?width=600&resizemode=4",
  logo_alt: "Samayam Malayalam - Malayalam News",
  siteid: "2147478019",
  viralBrandingLink: "/viral-adda/articlelist/67088530.cms",
  fbpixelid: "",

  astrowidgetId: "61035114",
  fbappid: "1452558595050529",
  googleClientId: "961161019499-83ecofrdm4eg9btinnq5hnkkqj1kvqea.apps.googleusercontent.com",
  bennett: "https://timesofindia.indiatimes.com/bennettjul2020_form_nbt.cms",

  css:
    "$body-bgcolor:#fff; $navbar-top-bgcolor:#fff; $navbar-bg-color:#F5CC10; $navbar-border-top:#c8cccb; $navbar-border-shadow:#D8B40D; $navbar-active-border-bottom-color:#000; $navbar-link-color:#000; $hamburger-bg-color:#747474; $sidenav-bg-color:#fff; $sidenav-color:#000; $sidenav-border-bottom:#F5F5F5; $sidenav-arrow-color:#D1D1D1; $layer-bg:rgba(0,0,0,0.5); $breadcrumb-home-color:#DA4848; $card-border-bottom:#F5F5F5; $card-bg-color:#8e8e93; $card-text-color:#191919; $card-date-color:#bababa; $home-section-border-bottom:#f5f5f5; $home-section-heading-border-bottom:#F5CC10; $home-section-arrow-color:#000000; $home-section-more-color:#858585; $home-section-more-border:#CCCCCC; $footer-background:#585858; $footer-border-top:#333; $footer-border-bottom:#7b7b7b; $footer-heading-color:#e6e6e6; $footer-text-color:#fff; $footer-link-color:#d0d0d0; $footer-trending-color:#95989a; $footer-copyright-color:#d0d0d0;",
  fontContent:
    "@font-face {font-family: Noto Sans;src: url('https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.eot');src: url('https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.eot?#iefix') format('embedded-opentype'),url('https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.woff2') format('woff2'),url('https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.ttf') format('truetype');font-weight: normal;font-style: normal;font-display: optional;}",
  fontUrl: "https://static.mly.indiatimes.com/fonts/NotoSansMalayalam-Regular.woff2",
  cricket_SIAPI: {
    minischedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_liupre_ml.json",
    schedule: "https://toicri.timesofindia.indiatimes.com/jsons/calendar_new_ml.json",
    points_table: "https://toicri.timesofindia.indiatimes.com/jsons/stats/Standings/standing_%seriesid%.json",
    scoreboard: "https://toicri.timesofindia.indiatimes.com/jsons/%matchid%_ml.json",
    topPlayer: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/feed_topplayer.cms?feedtype=sjson",
  },
  Thumb: {
    userImage: "/photo/11834507.cms",
  },

  techsectionID: {
    // GN Config
    latestGadgets: "81814336",
    trendingGadgets: "81814275",
    video: "70499318",
    photo: "",
  },

  locale: {
    missedNews: "ഈ വാര്‍ത്തകള്‍ നിങ്ങള്‍ വായിച്ചിരുന്നോ?",
    live_blog: "ലൈവ് ബ്ലോഗ്‌",
    latest: "ഏറ്റവും പുതിയ ",
    most_read: "Most Read",
    latest_video: "Latest Videos",
    latest_photo: "Latest Photos",
    whatsapp_share: "Hey, you might find this interesting: ",
    see_in_app: "App-ൽ നോക്കൂ",
    read_more_tml: "మరింత చదవండి",
    recommendednews: "Recommended News",
    appLinkText: "ഏറ്റവും പുതിയ മലയാളം വാര്‍ത്തകള്‍ അറിയാന്‍ ആപ്പ് ഡൗണ്‍ലോഡ് ചെയ്യുക",
    actors: "താരനിര",
    releaseDate: "റിലീസ് തീയതി",
    director: "സംവിധാനം",
    genre: "സിനിമ വിഭാഗം",
    duration: "ദൈര്‍ഘ്യം",
    readmore: "കൂടുതൽ വായിക്കൂ",
    watchmore: "കൂടുതൽ കാണുക",
    commentary: "Commentary",
    scorecard: "Scorecard",
    photo_maza: "ഫോട്ടോ മസ",
    key_words: "കൂടുതൽ വാർത്തകൾ",
    more_from_topics: "ടോപിക്കുകളില്‍ നിന്നും കൂടുതല്‍’",
    brief: {
      tooltip: "കൂടുതല്‍ വാര്‍ത്തകള്‍ ചുരുക്കത്തില്‍ വായിക്കാന്‍ ആപ്പ്  ഡൗണ്‍ലോഡ് ചെയ്യൂ! ",
      limitation_txt: "വാര്‍ത്തകള്‍ ചുരുക്കത്തില്‍ വായിക്കാന്‍",
    },
    fblikeTxt: {
      txt1: "ഏറ്റവും പുതിയ വാർത്തകൾ അതിവേഗം അറിയാൻ ",
      siteName: "Samayam Malayalam ഫേസ്ബുക്ക്",
      txt2: "പേജ് ലൈക്ക് ചെയ്യൂ ",
    },
    newsLetter: {
      LS: "5236",
      thankyou: "നന്ദി",
      headerText: "പ്രധാനപ്പെട്ട ന്യൂസ് അപ്ഡേറ്റുകള്‍ ദിവസവും അറിയണോ?",
      joinIn: "ജോയിൻ ചെയ്യൂ",
      footerText: "മുകളിലുള്ള ബോക്സിൽ ഇമെയിൽ ഐഡി നൽകൂ, വാര്‍ത്തകള്‍ നിങ്ങളുടെ ഇൻബോക്സിലെത്തും",
      verification: "നിങ്ങളുടെ ഇമെയിൽ അഡ്രസിലേക്ക് വേരിഫിക്കേഷന്‍ മെയിൽ അയച്ചിട്ടുണ്ട്.",
      already: "നിങ്ങള്‍ നേരത്തെ തന്നെ ന്യൂസ് ലെറ്റര്‍ സബ്സ്ക്രൈബ് ചെയ്തിട്ടുണ്ട് ",
      Subscribed: "നിങ്ങള്‍ സബ്സ്ക്രൈബ് ചെയ്തിരിക്കുന്നു",
      errorNetwork: "നെറ്റ്‌വർക്കിൽ എന്തോ പ്രശ്നമുണ്ട്! വീണ്ടും ശ്രമിക്കുക!",
      notverified: "നിങ്ങള്‍ ഇമെയിൽ അയച്ചിട്ടുണ്ട്. വേരിഫൈ ചെയ്യൂ!",
      verified: "നിങ്ങള്‍ നേരത്തെ തന്നെ വേരിഫൈ ചെയ്തിട്ടുണ്ട്.",
      unchecked: "ചെക്ക് ബോക്സ് തെരഞ്ഞെടുക്കൂ",
      validemail: "ശരിയായ ഇമെയിൽ അഡ്രസ് നൽകൂ (example@domain.com)",
      blankemail: "ഇമെയിൽ അഡ്രസ് നൽകേണ്ട കോളം ഒഴിവാക്കിയിടാൻ കഴിയുകയില്ല.",
      login: "സബ്സ്ക്രൈബ് ചെയ്യാൻ ലോഗിൻ ചെയ്യൂ",
      error: "പ്രശ്നം കണ്ടെത്തി! പഴയ മെയിലറിൽ നിന്ന് നിങ്ങള്‍ അണ്‍ സബ്സ്ക്രൈബ് ചെയ്തിട്ടില്ലെന്ന് ഉറപ്പാക്കൂ!",
    },
    social_download: {
      title: "വാര്‍ത്തകള്‍ ഉടനറിയൂ, സമയം മലയാളത്തിനൊപ്പം",
      fblike: "ഫേസ്ബുക്ക് പേജ് ലൈക്ക് ചെയ്യുക",
      appdownload: "ആപ്പ് ഡൌണ്‍ലോഡ് ചെയ്യൂ",
      extrasharetxt: "\n\nഡൗണ്‍ലോഡ് ചെയ്യാനും ആപ്പില്‍ വായിക്കാനുമായി ക്ലിക്ക് ചെയ്യൂ:",
      fblikeURL:
        "https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fsamayammalayalam%2F&width=79&layout=button_count&action=like&size=small&show_faces=false&share=false&height=21&appId=505830642956378",
    },
    share_popup_header: "ഷെയര്‍ ചെയ്യൂ",
    read_more: "കൂടുതല്‍ വായിക്കൂ",
    read_less: "കുറച്ചു വായിക്കൂ",
    view_gallery_from_start: "ഗ്യാലറി തുടക്കം മുതൽ കാണുക",
    next_gallery: "അടുത്ത ഗാലറി",
    next_article: {
      moviereview: "മൂവി റിവ്യൂ",
      articleshow: "ആര്‍ട്ടിക്കിള്‍ ഷോ",
      default: "ഡിഫോള്‍ട്ട്",
      movieshow: "Next Movie",
    },
    next_topic: {
      more_all: "കൂടുതൽ",
      more_news: "കൂടുതൽ വാര്‍ത്തകള്‍",
      more_photos: "കൂടുതൽ ഫോട്ടോസ്",
      more_videos: "കൂടുതൽ വീഡിയോസ്",
    },
    search_placeholder: "തെരയൂ",
    highlight: "ഹൈലൈറ്റ്:",
    orientation_heading: "ഡിവൈസ് തിരിച്ചു പിടിക്കൂ",
    orientation_text: "ലാന്‍ഡ്‌സ്കേപ്പ് മോഡ് സപ്പോര്‍ട്ട് ചെയ്യുന്നില്ല, ദയവായി പോര്‍ട്രയിറ്റ് മോഡില്‍ ഉപയോഗിക്കൂ",
    videos: "വീഡിയോസ്",
    photo: "ഫോട്ടോസ്",
    related_videos: "അനുബന്ധ വീഡിയോകള്‍",
    most_viewed_videos: "കൂടുതൽ പേര്‍ കണ്ട വീഡിയോസ്",
    default_horizontal_tile_width: 133,
    default_slideshow_tile_width: 120,
    related_articles_horizontal_tile_width: 230,
    relatedarticle: "അനുബന്ധ ലേഖനങ്ങള്‍",
    cast: "താരനിര: ",
    read_more_listing: " കൂടുതല്‍",
    critics_review: "ക്രിട്ടിക്സ് റിവ്യൂ",
    photomasti: "PHOTO GALLERY",
    twitte_reaction: "ട്വിറ്റര്‍ റിയാക്ഷന്‍",
    critics_rating: "ക്രിട്ടിക്സ് റേറ്റിങ്",
    user_rating: "വായനക്കാരുടെ റേറ്റിങ്",
    movie_review: "മൂവി റിവ്യൂ",
    film_review: "ഫിലിം റിവ്യൂ",
    review_movie: "മൂവി റിവ്യൂ ചെയ്യുക",
    review_device: "ഡിവൈസ് റിവ്യൂ ചെയ്യുക",
    rate_movie: "നിങ്ങളുടെ റേറ്റിങ്ങ്",
    rate: "Rate",
    rate_recipe: "Rate Recipe",
    slide_to_rate: "Slide to Rate",
    slide_to_rate_movie: "സിനിമ റേറ്റ് ചെയ്യാനായി സ്ലൈഡ് ചെയ്യൂ",
    reader_rating: "User's rating",
    movie_review_tile_bg: "https://static.langimg.com/moviereview_list_bg/photo/65022261.cms",
    movie_review_detail_bg: "https://static.langimg.com/moviereview_list_bg/photo/65594589.cms",
    breaking_news: "ബ്രേക്കിങ് ന്യൂസ്",
    trending: "ട്രെൻഡിങ്",
    highlightText: "ഹൈലൈറ്റ്സിനായി ആപ്പ് ഡൗൺലോഡ് ചെയ്യൂ!",
    live_video: "ലൈവ് വീഡിയോ",
    view_text: "കാണൂ!",
    aur_jaane: "കൂടുതല്‍ അറിയാന്‍",
    oops: "oops…!!!",
    thanks: "നന്ദി",
    offlineText: "നിങ്ങള്‍ ഓഫ്ലൈന്‍",
    onlineText: "നിങ്ങള്‍ ഓണ്‍ലൈന്‍ ആയിരിക്കുന്നു",
    openinapp: "ആപ്പില്‍ തുറക്കുക",
    superhit: " ഏറ്റവും കൂടുതല്‍ പേര്‍ വായിച്ചവ",
    live_updates: "ലൈവ് അപ്ഡേറ്റ്",
    fblikecardtext: "സമയം മലയാളം ഫേസ്ബുക്ക് <br/> പേജ് ലൈക്ക് ചെയ്യുക",
    appdownloadcardtext: "അപ്ഡേറ്റഡായിരിക്കൂ, സമയം <br /> മലയാളത്തിനൊപ്പം!",
    installapp: "ഇന്‍സ്റ്റാള്‍ ചെയ്യുക",
    login: "ലോഗിന്‍",
    logout: "ലോഗൗട്ട്",
    amazonDeals: "ഡീൽസ് ഓഫ് ദി ഡേ",
    seemoreimages: "കൂടുതല്‍ ചിത്രങ്ങള്‍",
    read_more_liveblog: "കൂടുതല്‍ വായിക്കൂ",
    footerheading: "സമയം മലയാളം",
    comment_text: "കമന്റ് ചെയ്യൂ",
    download_text: "Download App",
    write_comment: "കമന്റ് ചെയ്യൂ",
    view_comment: "പ്രതികരണങ്ങള്‍",
    text_topcomment: "മികച്ച പ്രതികരണം",
    text_latestcomment: "ഏറ്റവും പുതിയ പ്രതികരണം",
    text_author_comment: "എഴുത്തുകാരന്‍റെ കമന്‍റ്",
    wp_broadcast: {
      description: "ഇന്നത്തെ പ്രധാന വാര്‍ത്ത വാട്സാപ്പില്‍ അറിയൂ",
      btnText: "സബ്സ്ക്രൈബ്",
      url: "https://widget.whatsbroadcast.com/widget_more/b1600181418ab41ffc6e0275e17c7d5f/?show=walink&text=",
    },
    crossbrand: "ഈ വാര്‍ത്ത ആദ്യം -hyperlink- ല്‍ -dl- പ്രസിദ്ധീകരിക്കപ്പെട്ടിരിക്കുന്നു",
    appexclusive: "App Exclusive",
    votesuccessfully: "നിങ്ങള്‍ വോട്ടു ചെയ്തിരിക്കുന്നു",
    votealready: "മുന്‍പേ തന്നെ വോട്ടു രേഖപ്പെടുത്തിയിട്ടുണ്ട്",
    submit_vote: "വോട്ട്",
    photoshow_app_install: { read_more: "കൂടുതല്‍ വായിക്കൂ", download: "Download App" },
    disclaimer: "നിരാകരണവ്യവസ്ഥ",
    live_tv: "LIVE TV",
    data_hub: "Budget Data Hub",
    fantasy_game: "Budget Fantasy Game",
    topics_no_result: "ബന്ധപ്പെട്ട വിവരങ്ങളൊന്നും ലഭ്യമല്ല",
    popularVideos: "Popular Videos",
    ieText:
      "ഹായ്, നിങ്ങള്‍ സമയം മലയാളം വെബ്സൈറ്റ് IE11 പതിപ്പിലാണ് കാണുന്നതെന്ന് തോന്നുന്നു. എഡ്ജ് , ക്രോം ബ്രൗസറുകളിലാണ് സമയം വെബ്സൈറ്റ് മികച്ച രീതിയില്‍ പ്രവര്‍ത്തിക്കുന്നത്. ദയവായി നിങ്ങളുടെ ബ്രൗസര്‍ അപ്ഡേറ്റ് ചെയ്യൂ! ",
    closeText: "ക്ലോസ് ചെയ്യുക",
    photoshowrhsheading: "Related Photos",
    utility: "Utility",
    tech: {
      inIndia: "ഇന്ത്യയിലെ വില",
      loadmore: "കൂടൂതൽ ലോഡ് ചെയ്യൂ",
      rating: "റേറ്റിങ്",
      sortby: "ഇപ്രകാരം തരംതിരിക്കൂ",
      clearall: "നീക്കുക",
      buyhere: "ഇവിടെ വാങ്ങാം",
      indiaLaunchDates: "ഇന്ത്യയിലെ ലോഞ്ച് തിയ്യതി",
      indiaPrice: "ഇന്ത്യയിലെ വില",
      compCriteria: "താരതമ്യം ചെയ്യുന്ന മാനദണ്ഡം",
      showDiff: "വ്യത്യാസം മാത്രം കാണിക്കുക",
      alreadyAdded: "ഈ ഗാഡ്ജറ്റ് നേരത്തെ തന്നെ തെരഞ്ഞെടുത്തു",
      buyFrom: "വാങ്ങുക",
      addDevice: "ഉപകരണം ആഡ് ചെയ്യുക",
      compare: "താരതമ്യം ചെയ്യുക",
      englishtype: "ഇംഗ്ലീഷിൽ ടൈപ്പ് ചെയ്യുക",
      change: "മാറ്റുക",
      suggestedDevice: "നിര്‍ദ്ദേശിക്കപ്പെട്ട ഉപകരണങ്ങള്‍",
      pe: "पर",
      gadgets: "ഗാഡ്ജറ്റുകള്‍",
      filtertxt: "ഫിൽറ്ററുകള്‍",
      purchasehere: "സ്പോണ്‍സര്‍ ചെയ്തത് : ഇൻ സ്റ്റോര്‍",
      popular: "പോപ്പുലര്‍",
      allbrands: "എല്ലാ ബ്രാൻഡുകളും",
      brands: "ബ്രാൻഡ്",
      othervariants: "മറ്റു വേരിയന്‍റുകള്‍",
      criticsrating: "ക്രിട്ടിക് റേറ്റിങ്",
      launchdate: "ലോഞ്ച് ഡേറ്റ് അഭ്യൂഹം",
      review: "റിവ്യൂ",
      overview: "ഓവര്‍വ്യൂ",
      userrating: "യൂസര്‍ റേറ്റിങ്",
      comparedotxt: "താരതമ്യം ചെയ്യുക",
      submitrating: "റേറ്റിങ് സമര്‍പ്പിക്കുക",
      addtocompare: "താരതമ്യം ചെയ്യാൻ ചേര്‍ക്കുക",
      purchase: "വാങ്ങുക",
      suggested: "നിര്‍ദ്ദേശിക്കപ്പെട്ടത്",
      comparetxt: "താരതമ്യം",
      latest: "ലേറ്റസ്റ്റ്",
      price: "വില",
      rumoured: "അഭ്യൂഹം",
      upcoming: "ഉടന്‍ വരുന്നത്",
      ki: "ന്‍റെ",
      relatedgadgets: "ബന്ധപ്പെട്ട മറ്റു ഗാ‍ഡ്ജറ്റുകള്‍",
      seemore: "കൂടുതൽ കാണുക",
      topfeature: "ടോപ് ഫീച്ചറുകള്‍",
      fullspecification: "മുഴുവന്‍ സ്പെസിഫിക്കേഷനുകളും കാണുക",
      selectatleast2: "കുറഞ്ഞത് 2 എണ്ണം തെരഞ്ഞെടുക്കുക",
      devicealreadyinlist: "ഇത് നേരത്തെ തന്നെ താരതമ്യം ചെയ്യാനായി തെരഞ്ഞെടുത്തിട്ടുണ്ട്",
      same_gadget: "സമാനമായ ഗാ‍‍ഡ്ജറ്റുകള്‍",
      user_review: "യൂസര്‍ റിവ്യൂ",
      read_fullreview: "മുഴുവന്‍ റിവ്യൂ വായിക്കുക",
      similar_gadget: "സമാനമായ ഗാഡ്ജറ്റുകള്‍",
      see_diff: "വ്യത്യാസം കാണുക",
      latest_comparisons: "അടുത്തിടെ താരതമ്യം ചെയ്തത്",
      popular_comparisons: "പോപുലര്‍ താരതമ്യം",
      techNewsH1: "ടെക്നോളജി വാര്‍ത്ത",
      minimumComparisonError: "താരതമ്യം ചെയ്യാൻ കുറഞ്ഞത് 2 ഗാഡ്ജറ്റുകളെങ്കിലും തെരഞ്ഞെടുക്കുക",
      // gadgets show
      buyAtAmazon: "ആമസോണിൽ നിന്ന് വാങ്ങൂ",
      priceList: "വിലപ്പട്ടിക",
      priceInIndia: "ഇന്ത്യയിലെ വില",
      criticReview: "ക്രിട്ടിക്ക് റിവ്യൂ",
      userReview: "യൂസര്‍ റിവ്യൂ",
      specifications: "സ്പെസിഫിക്കേഷനുകള്‍",
      moreLikeThis: "സമാനമായവ",
      criticRating: "ക്രിട്ടിക്ക് റേറ്റിങ്",
      userRating: "യൂസര്‍ റേറ്റിങ്",
      user: "യൂസര്‍",
      others: "മറ്റുള്ളവ",
      nextGadget: "അടുത്ത ഗാഡ്ജറ്റ്",
      similarGadgets: "സമാനമായ ഗാഡ്ജറ്റുകള്‍",

      readCompleteReview: "മുഴുവന്‍ റിവ്യൂ വായിക്കുക",
      readLess: "കുറച്ച് വായിക്കുക",

      recentlyCompared: "അടുത്തിടെ താരതമ്യം ചെയ്തത്",
      weak: "മോശം",
      belowAverage: "ശരാശരിയിലും താഴെ",
      worthpurchase: "വാങ്ങാവുന്നത്",
      good: "നല്ലത്",
      excellent: "വളരെ മികച്ചത്",
      thanksforreview: "റിവ്യൂ ചെയ്തതിന് നിങ്ങള്‍ക്ക് നന്ദി",
      befirsttoreview: "റിവ്യൂ ചെയ്യുന്ന ആദ്യത്തെ ആളാകം",
      userreviewandrating: "യൂസര്‍ റിവ്യൂകളും റേറ്റിങും",
      ratedevice: "ഡിവൈസിനെ റേറ്റ് ചെയ്യാം",
      postRating: "നിങ്ങളുടെ റേറ്റിങ് പോസ്റ്റ് ചെയ്യുക",
      readMoreReview: "കൂടുതൽ റിവ്യൂ വായിക്കാം",
      varients: "മറ്റു വേരിയന്‍റുകള്‍",
      text_write_reviews: "റിവ്യൂ എഴുതാം",
      text_view_comment: "View Comments",
      text_write_comment: "Write Comments",
      critic: "Critic",
      language: "Tech",
      category: [
        { keylabel: "മൊബൈൽ", keyword: "mobile" },
        { keylabel: "ലാപ്ടോപ്", keyword: "laptop" },
        { keylabel: "സ്മാര്‍ട്ട് വാച്ച്", keyword: "smartwatch", keylabelEng: "smart watch" },
        { keylabel: "ടെലിവിഷന്‍", keyword: "tv" },
        { keylabel: "എയര്‍ കണ്ടീഷണര്‍", keyword: "ac" },
        { keylabel: "ടാബ്ലറ്റ്", keyword: "tablet" },
        { keylabel: "ക്യാമറ", keyword: "camera" },
        { keylabel: "ഫിറ്റ്നസ് ബാന്‍ഡ്", keyword: "fitnessband", keylabelEng: "fitness band" },
        { keylabel: "വാഷിങ് മെഷീന്‍", keyword: "washingmachine", keylabelEng: "washing machine" },
        { keylabel: "റഫ്രിജറേറ്റര്‍", keyword: "refrigerator", keylabelEng: "fridge" },
        { keylabel: "പവര്‍ ബാങ്ക്", keyword: "powerbank", keylabelEng: "power bank" },
      ],
      gadgetSliderConfig: {
        mobile: "മൊബൈൽ",
        laptop: "ലാപ്ടോപ്",
        tablet: "ടാബ്ലറ്റ്",
        camera: "ക്യാമറ",
        smartwatch: "സ്മാര്‍ട്ട് വാച്ച്",
        fitnessband: "ഫിറ്റ്നസ് ബാന്‍ഡ്",
        tv: "ടെലിവിഷന്‍",
        ac: "എയര്‍ കണ്ടീഷണര്‍",
        washingmachine: "വാഷിങ് മെഷീന്‍",
        refrigerator: "റഫ്രിജറേറ്റര്‍",
        powerbank: "പവര്‍ ബാങ്ക്",
      },
      affiliateTags: {
        homePage: "mly_web_home_latesttrendingwidget",
      },
    },
    top_headlines: "Top Headlines",
    user_review: "User Review",
    listenAlbum: "Listen to this album",
    castncrew: "Cast & Crew",
    filmSongs: "Film Songs",
    news: "വാർത്ത",
    photos: "Photos",
    market: "വിപണി",
    choseStateCity: {
      dropDownText: "ജില്ല തെരഞ്ഞെടുക്കുക",
      extraCityContent: "നിങ്ങളുടെ ജില്ലയിലെ വാര്‍ത്തകള്‍ വായിക്കൂ",
    },
    cityPopUp: {
      selectStateCity: "സംസ്ഥാനവും നഗരവും",
      selectCity: "നഗരം തിരഞ്ഞെടുക്കുക",
      save: "സേവ് ചെയ്യുക",
      state: "സംസ്ഥാനം",
      city: "നഗരം",
      readersCount: "സമയം മലയാളത്തിന് {{total}} ലക്ഷം + വായനക്കാരുണ്ട്",
    },
    cityHeading: "സമീപ നഗരങ്ങളിലെ വാര്‍ത്ത",
    cityHeadingVideo: "സമീപ നഗരങ്ങളിലെ വീഡിയോ",
    players: "താരങ്ങള്‍",
    authoraritcle: "ലേഖനങ്ങൾ",
    authorwebstories: " നെ കുറിച്ച് ",
    authorsharetext: "ഓൺലൈനിൽ ബന്ധപ്പെടുക",
    authorabout: "നെ കുറിച്ച് ",
    articles: "ആർട്ടിക്കിൾ",
    webstories: "വെബ് സ്റ്റോറി",
  },
  imageconfig: {
    thumbid: "67415762",
    liveblogthumb: "56295200",
    defaultthumb: "67415762",
    imagedomain: "https://static.langimg.com/thumb/",
    webimagedomain: "https://malayalam.samayam.com/thumb/",
    bigimage: "width=680&resizemode=3", // Article Inline Images, will maintain aspect ratio of original image
    big2ximage: "width=1020&resizemode=3", // Article Inline Images, will maintain aspect ratio of spotlight/paid article image
    gallerythumb: "width=700&height=525&resizemode=75", // photp Listing large gallery thumbs and articleshow lead image, Aspect Ratio 4:3
    smallthumb: "width=400&height=300&resizemode=75", // Listing small thumbs, Aspect Ratio 4:3
    smallslideshowthumb: "width=135&height=102&resizemode=1", // Used for external photogallery strip on top news, Aspect Ratio 4:3
    midthumb: "width=540&height=405&resizemode=75", // Photo Listing widget thumb, etc Aspect Ratio 4:3
    largethumb: "width=540&height=405&resizemode=75", // Lead Images Aspect Ratio 4:3
    amplargethumb: "width=1600&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only videoshow
    amplargethumbarticle: "width=1200&height=900&resizemode=75", // Lead Images Aspect Ratio 16:9 for AMP only for article
    smallwidethumb: "width=320&height=180&resizemode=75", // For video listing widgets Aspect Ratio 16:9
    largewidethumb: "width=680&height=380&resizemode=75", // For videowidget lead image and videoshow Aspect Ratio 16:9
    posterthumb: "width=392&height=514&resizemode=4", // Moview Posters
    squarethumb: "width=400&height=400&resizemode=75", // for two colum layout
    rectanglethumb: "width=160&height=103&resizemode=75", // for rectangle flags
    smallsquarethumb: "width=150&height=150&resizemode=3", // for resize mode three
    gnthumb: "width=200&resizemode=4", // for Gadget now
    gnthumbWithHeight: "height=150&resizemode=75", // for GN PDP, need height
    webstoriesthumb: "width=300&height=500&resizemode=4", // web stories Photo Listing widget thumb
    webstoriesthumbLarge: "width=364&height=607&resizemode=4", // web stories Photo Listing widget thumb
    widecardthumb: "width=600&height=315&resizemode=6", // End Article Card thumb 16: 9",
  },
  sso: {
    BASE_URL: "https://malayalam.samayam.com",
    SSO_CHANNEL: "ml",
    GADGET_CHANNEL: "malayalam-gadgetsnow",
    stg: {
      BASE_URL: "https://jstgmalayalam.samayam.com",
      MYTIMES_URL_USER: "https://mytest.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
      MYTIMES_URL_SETTINGS: "https://jssostg.indiatimes.com/sso/identity/profile/edit?channel=tm",
      SSO_URL_LOGIN: "https://jssostg.indiatimes.com/sso/identity/login",
      SSO_URL_LOGOUT: "https://jssostg.indiatimes.com/sso/identity/profile/logout/external",
      SSO_URL_GETTICKET: "https://jssostg.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
      SOCIAL_API_INTEGRATOR: "https://testsocialappsintegrator.indiatimes.com/socialsite",
      SSO_BASE_URL: "https://jssostg.indiatimes.com/sso/crossdomain",
      SSO_CROSSWALK: "https://jssocdnstg.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
      SSO_WIDGET_URL: "https://jssocdnstg.indiatimes.com/crosswalk/133/widget/main.bundle.js",
    },

    SSO_BASE_URL: "https://jsso.indiatimes.com/sso/crossdomain",
    SSO_CROSSWALK: "https://jssocdn.indiatimes.com/crosswalk/jsso_crosswalk_legacy_0.6.8.min.js",
    SSO_WIDGET_URL: "https://jssocdn.indiatimes.com/crosswalk/34/widget/main.bundle.min.js",
    MYTIMES_URL_USER: "https://myt.indiatimes.com/mytimes/profile/info/v1/?ssoid=",
    MYTIMES_URL_SETTINGS: "https://jsso.indiatimes.com/sso/identity/profile/edit?channel=ml",
    SSO_URL_LOGIN: "https://jsso.indiatimes.com/sso/identity/login",
    SSO_URL_LOGOUT: "https://jsso.indiatimes.com/sso/identity/profile/logout/external",
    SSO_URL_GETTICKET: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1&platform=wap&channel=",
    MYTIMES_ALREADY_RATED: "https://myt.indiatimes.com/mytimes/alreadyRated?appKey=Malayalam&",
    MYTIMES_ADD_ACTIVITY: "https://myt.indiatimes.com/mytimes/addActivity?appKey=Malayalam&",
    SOCIAL_API_INTEGRATOR: "https://socialappsintegrator.indiatimes.com/socialsite",
    SSO_TRUECALLER_visibility: 4,
    SSO_URL_NewsTicket: "https://jsso.indiatimes.com/sso/crossdomain/getTicket?version=v1",
    SSO_URL_SubStatus: "https://webapi.sendpal.in/api/v1/get/user/ml/status?dataformat=json",
    SSO_URL_unsubscribe: "https://webapi.sendpal.in/api/v1/multiple/unsubscribe/ml?dataformat=json",
    SSO_URL_subscribe:
      "https://webapi.sendpal.in/api/v1/add/subscription/ml?frequency=1&scheduletime=1&status=1&dataformat=json&nlid=40",
    SSO_URL_confirm: "https://webapi.sendpal.in/api/v1/confirm/subscription/ml?dataformat=json",
  },
  MYTIMES_PROFILE: "https://mytimes.indiatimes.com/?channel=mly",
  TimesPoint: {
    jsDev: "https://test.timespoint.com/tpwidgets-test/static/dist/js/main.js",
    jsProd: "https://image.timespoints.iimg.in/tpwidgets/static/dist/js/main.js",
    channels: ["tml", "nbt", "eisamay", "tlg", "mly", "mt"],
    // status: true,
    pcode: "channel184095",
    scode: "channel184095",
    activities: {
      DAILY_CHECKINS: "act5545856",
      DAILY_CHECKINS_MOBILE: "act5565223",
      READ_ARTICLE: "act3578224",
      WATCH_VIDEOS: "watch_video",
      SH_FB: "sh_fb",
      SH_TW: "sh_tw",
      LOGIN: "login",
      MOVIE_RATE: "act1286216",
      // Fired by MyProfile team
      MOVIE_REVIEW: "act1223982",
      VIEW_PHOTO: "view_photo",
      LIVE_BLOG: "act5636041",
      SUB_NL: "sub_nltr",
      REGISTER: "register",
      // Fired by MyProfile team
      COMMENT: "cmnt",
      SUB_NOTIFICATION: "act3928586",
      // Not found for staging
      CHECKIN_BONUS_DESKTOP: "act5692078",
      // Not found for staging
      CHECKIN_BONUS_MOBILE: "act5712467",
      WHATSAPP_SHARE: "act5666035",
    },
    campaingHistoryName: {
      desktop: "campaign7224262",
      mobile: "campaign7456140",
    },
    campaignDays: 5,

    stg: {
      pcode: "channel9859549",
      scode: "channel9859549",
      campaingHistoryName: {
        desktop: "campaign3944423",
        mobile: "campaign4051778",
      },
      activities: {
        DAILY_CHECKINS: "act3259327",
        DAILY_CHECKINS_MOBILE: "act3281536",
        READ_ARTICLE: "read",
        WATCH_VIDEOS: "watch_video",
        SH_FB: "sh_fb",
        SH_TW: "sh_tw",
        LOGIN: "login",
        MOVIE_RATE: "act3522728",
        // Fired by MyProfile team
        MOVIE_REVIEW: "rv",
        VIEW_PHOTO: "view_photo",
        LIVE_BLOG: "act3548991",
        SUB_NL: "sub_nltr",
        REGISTER: "register",
        // Fired by MyProfile team
        COMMENT: "cmnt",
        SUB_NOTIFICATION: "act3498524",
        CHECKIN_BONUS_DESKTOP: "act3368572",
        CHECKIN_BONUS_MOBILE: "act3327063",
        WHATSAPP_SHARE: "act3394327",
      },
    },

    TP_FAQ_MSID: "79547313",
    NP_DOMAIN: {
      production: "https://npcoins.indiatimes.com",

      development: "https://nprelease.indiatimes.com",
      stg1: "https://nprelease.indiatimes.com",
      stg2: "https://nprelease.indiatimes.com",
    },

    TP_DOMAIN: {
      production: "https://tpapi.timespoints.com",

      development: "https://test.timespoints.com/tpapi",
      stg1: "https://test.timespoints.com/tpapi",
      stg2: "https://test.timespoints.com/tpapi",
    },

    SDK_DOMAIN: {
      production: "https://image.timespoints.iimg.in",

      development: "https://test-img.timespoints.com",
      stg1: "https://test-img.timespoints.com",
      stg2: "https://test-img.timespoints.com",
    },

    tpwidgetJS: {
      production: "/tpwidgets/dist/js/tpwidget.js",

      development: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg1: "/static/tpwidgets/static/dist/js/tpwidget.js",
      stg2: "/static/tpwidgets/static/dist/js/tpwidget.js",
    },

    //* * Moved to common config */
    tpPage: "/timespoints.cms",
    tpRedeemLink: "https://www.timespoints.com/products",
  },
  Comments: {
    topComments: {
      appkey: "MALAY",
      sortcriteria: "AgreeCount",
      order: "desc",
      size: "1",
      lastdeenid: "0",
      after: "true",
      withReward: "false",
      pagenum: "1",
    },
    allComments: {
      appkey: "MALAY",
      sortcriteria: "CreationDate",
      order: "asc",
      size: "6",
      lastdeenid: 0,
      after: true,
      withReward: false,
      pagenum: 1,
    },
  },
  pages: {
    elections: "56661604",
    business: "56197560",
    mktwdt: "85295318",
    iplHomePage: "63301790",
    commonwealth: "63477139",
    fifa: "64383342",
    wcHomePage: "86750324",
    tech: "70499011",
    techreview: "70499194",
    stateSection: "74606583",
    gadgethome: "83552323",
    budget: "67585858",
    budget_you: "97254356",
  },
  iplpages: {
    venues: "63301836",
    teams: "63301827",
    pointsTable: "63301823",
    miniSchedule: "63301824",
  },
  t20wcpages: {
    venues: "86750971",
    teams: "86750490",
    pointsTable: "86750469",
    miniSchedule: "86750410",
  },
  redis: { host: "192.168.24.51", port: "6379", db: "1" },
  listNodeLabels: {
    articlelist: ["articlelist"],
    news: ["articleshow"],
    photo: ["photoshow"],
    slideshow: ["photoshow"],
    video: ["videoshow"],
    videolist: ["videolist"],
    photolist: ["photolist"],
    lb: ["liveblog", "ലൈവ് ബ്ലോഗ്‌"],
    moviereview: ["moviereview", "मूवी रिव्यू"],
    movieshow: ["movieshow", "मूवी"],
    poll: ["pollsurvey", "പോള്‍"],
  },
  photoListView: "47882310",
  routes: [
    "/exitpolls/",
    "/results/",
    "/electionlist/",
    "/articlelist/",
    "/photoarticlelist/",
    "/photomazza/",
    "/photolist/",
    "/photoshow/",
    "/photogallery/",
    "/articleshow/",
    "/moviereview/",
    "/movieshow/",
    "/liveblog/",
    "/videolist/",
    "/videoshow/",
    "/topics/",
    "/teams/",
    "/venues/",
    "/pointstable/",
    "/iplt20.cms",
    "/schedule/",
    "/sportsresult/",
    "elections.cms",
    "/gulf",
  ],
  staticPagesDir: "/var/www/html/testpages/",
  slike: {
    apikey: "malaweba5ec97054033e061",
    snapchatapikey: "",
    ampapikey: "malaampweb215lang",
    default_slikeid_minitv: "1x13qpaggu",
    nextvideo_domain: "https://mtpwafeeds.indiatimes.com",
    default_pl_videolist: "/feeds/videpostroll_v5_slike/47329248.cms?feedtype=json&callback=cached",
  },
  slikeAdCodes: { others: "ros" },
  gRecaptchaKey: "6LcxSGUUAAAAAPsGPKVpEkLKxnuluuqDKa1AivEN",
  ga: {
    gtm: "GTM-KQW3BK6",
    gtm4: "G-6HH2HEJHZT",
    gverifyCode: "zU5qA2HPdN2PFPyZd70q25_5NHXI8AE8AbqWNwXsoFA",
    gatrackid: "UA-29031733-10",
    ga4trackid: "G-6HH2HEJHZT",
    gaprofile: "[]",
  },

  growthrx: {
    stg: {
      id: "ga387f7ef",
    },
    prod: {
      id: "gb5c941ce",
    },
    gn: {
      stg: {
        id: "gf4078923",
      },
      prod: {
        id: "gcf0e7e75",
      },
    },
  },
  appexclusive_ga: { category: "Wap to App install", action: "click", label: "articlelist_topsection" },
  poll: {
    link: "pollslist.cms",
  },
  poll_ga: {
    poll_submit: { category: "pollSurvey", action: "submit", label: "pollsubmit" },
    poll_result_loggedIn: { category: "pollSurvey", action: "viewresult", label: "loggedin" },
    poll_result_nonloggedIn: { category: "pollSurvey", action: "viewresult", label: "non-loggedin" },
  },
  photoshow_app_install: { ga_object: { category: "Wap to App install", action: "click", label: "photo show" } },
  // sso_ga: {
  //   truecaller_requestscreen: { category: "True Caller", action: "Click", label: "Screen Request" },
  //   truecaller_screen: { category: "True Caller", action: "Click", label: "Screen View" },
  //   truecaller_screencontinue: { category: "True Caller", action: "Click", label: "Continue" },
  //   truecaller_skip: { category: "True Caller", action: "Click", label: "Skip" },
  //   truecaller_loginsuccess: { category: "True Caller", action: "Click", label: "Login Successful" },
  // },
  comscore: { c1: "2", c2: "6036484" },
  applinks: {
    android: {
      hrnav: "https://malayalamsamayam.onelink.me/9pRO/c08370a7",
      asshow: "https://malayalamsamayam.onelink.me/9pRO/e19888c3",
      photoshow: "https://malayalamsamayam.onelink.me/9pRO/850cc0d6",
      serviceDrawer: "https://malayalamsamayam.onelink.me/9pRO/7e8cbe8",
      social: "https://malayalamsamayam.onelink.me/9pRO/70b4c17b",
      oip_appexclusive: "https://navbharattimes.indiatimes.com/off-url-forward/ml_openinapp.cms?msid=",
      // https://malayalamsamayam.onelink.me/cMxT/b256ac1
    },
  },
  appdeeplink: {
    domain: "https://malayalamsamayam.onelink.me",
    shortcode: "9pRO",
    c: "Internal_Campaign",
    pid: {
      hrnav: "WAP_HRNAV_New",
      serviceDrawer: "WAP_BOTTOM_New",
      news: "WAP_MWEB_New",
      article_end: "WAP_AS_New",
      photo: "WAP_PG_New",
      toparticle: "WAP_Top%20Articles_New",
      extphoto: "WAP_Home_Photostrip_New",
      photoshow: "WAP_Photoshow_New",
      campaign: "WAP_Election",
      campaignHome: "WAP_Election_Home",
      openinapp_as: "MLY_AS_Brandwire",
      openinapp_al: "MLY_AL_Brandwire",
      photofeature: "WAP_MWEB_New",
      recipe: "WAP_MWEB_New",
    },
    openapp: "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam",
    opennews:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dnews-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openphoto:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D&af_web_dp=https%3A%2F%2Fmalayalam.samayam.com%2F",
    openextphoto:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dphoto-%2524%257C%2524-domain%3Dp-%2524%257C%2524-id%3D%7BMSID%7D&af_web_dp=https%3A%2F%2Fmalayalam.samayam.com%2F",
    openhtmlview:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Dhtml-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BURL%7D",
    opensection:
      "malayalamsamayamactivities://open-%24%7C%24-pub%3D7:Samayam Malayalam-%24%7C%24-type%3Dsection-%24%7C%24-sectionID%3D%7BsectionID%7D-%24%7C%24-sectionName%3D%7BsectionName%7D-%24%7C%24-id%3D%7BMSID%7D",
    openphotofeature:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3DphotoFeature-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
    openrecipe:
      "malayalamsamayamactivities%3A%2F%2Fopen-%2524%257C%2524-pub%3D7%3ASamayam%2520Malayalam-%2524%257C%2524-type%3Drecipe-%2524%257C%2524-domain%3Dt-%2524%257C%2524-id%3D%7BMSID%7D",
  },
  pushNotification: {
    cookieName: "notifypopup_mly",
    defaultThumb: "https://static.langimg.com/thumb/58896467/pic.jpg?width=100&height=100",
    heading:
      "വാര്‍ത്തകള്‍ അതിവേഗം അറിയാൻ നോട്ടിഫിക്കേഷന്‍ സബ്സ്ക്രൈബ് ചെയ്യൂ, അനുവദിക്കുക എന്ന ഓപ്ഷനിൽ ക്ലിക്ക് ചെയ്യൂ",
  },
  weather: {
    geoLocationApi: "https://geoapi.indiatimes.com/?cb=1",
    defaultCity: "Thiruvananthapuram",
    citiesJson: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_geocities.cms",
    weatherFeed: "https://navbharattimesfeeds.indiatimes.com/pwafeeds/pwa_weathertoday.cms?lat=",
    heading: "ഇന്നത്തെ താപനില",
    defultGulfCountry: "യുണൈറ്റഡ് അറബ് എമിറേറ്റ്സ്",
    cityText: "ജില്ലാ വാർത്ത വായിക്കൂ",
  },
  uaeJson: {
    city: "UAE",
    country: "United Arab Emirates",
    lang: "Malayalam",
    lat: "23.42",
    long: "53.84",
    mly: "United arab emirates",
  },

  pollution: {
    heading: "प्रदूषण",
    headingV1: "അന്തരീക്ഷ വായു നിലവാര സൂചിക",
    status: {
      good: "മികച്ചത്",
      moderate: "മിതമായത്",
      unhelathfSG: "സെന്‍സിറ്റീവ് ഗ്രൂപ്പുകാര്‍ക്ക് അനാരോഗ്യകരം",
      unhealthy: "അനാരോഗ്യകരം",
      veryUnhealthy: "വളരെ അനാരോഗ്യകരം",
      hazardous: "അപകടകരം",
    },
    url: "https://malayalam.samayam.com/pollution.cms",
  },
  fuel: {
    heading: "फ्यूल",
    feedUrl: "https://toibnews.timesofindia.indiatimes.com/fuelprice/latestPrice",
  },
  oneTapSignIn: {
    smartlockurl: "https://smartlock.google.com/client",
    isViewGaTracked: false,
    eventGAObj: { hitType: "event", category: "Login", action: "One_Tap", label: "" },
    text: {
      oneTapSuccessMsg: "നിങ്ങള്‍ വിജയകരമായി ലോഗിന്‍ ചെയ്തിരിക്കുന്നു",
      oneTapErrorMsg: "Oops! രണ്ടാമതും ശ്രമിക്കൂ",
      oneTapBtnText: "വീണ്ടും ശ്രമിക്കൂ",
    },
    constants: {
      onetapIgnoreDays: 15,
      onetapCookie: "oneTapNextShow",
      onetapIframeCheckTimer: 2000,
      smartlockJsLoadTimer: 10000,
      clientId: "961161019499-83ecofrdm4eg9btinnq5hnkkqj1kvqea.apps.googleusercontent.com",
      channel: "ml",
      jssoAPIGetURL: "https://jsso.indiatimes.com/sso/services/gponetaplogin/verify",
    },
  },
  ZodiacSigns: {
    url: "#",
    data: [
      { name: "aries", regName: "മേടം", pos: 1 },
      { name: "taurus", regName: "ഇടവം", pos: 2 },
      { name: "gemini", regName: "മിഥുനം", pos: 3 },
      { name: "cancer", regName: "കർക്കിടകം", pos: 4 },
      { name: "leo", regName: "ചിങ്ങം", pos: 5 },
      { name: "virgo", regName: "കന്നി", pos: 6 },
      { name: "libra", regName: "തുലാം", pos: 7 },
      { name: "scorpio", regName: "വൃശ്ചികം", pos: 8 },
      { name: "sagittarius", regName: "ധനു", pos: 9 },
      { name: "capricorn", regName: "മകരം", pos: 10 },
      { name: "aquarius ", regName: "കുംഭം", pos: 11 },
      { name: "pisces", regName: "മീനം", pos: 12 },
    ],
  },
  ads: {
    gptUrl: "",
    ctnAddress: "https://static.clmbtech.com/ad/commons/js/13542/colombia_v2.js",
    dmpUrl: "https://static.clmbtech.com/ase/13542/203/aa.js",
    isvPreRollUrl:
      "https://pubads.g.doubleclick.net/gampad/ads?iu=/7176/Malyalam/Malayalam_Videoshow/Malayalam_Videoshow_ATF_ISV&description_url=https%3A%2F%2Fmalayalam.samayam.com%2F&tfcd=0&npa=0&sz=300x230%7C300x250%7C300x400%7C1280x720%7C1024x768%7C960x540%7C640x360%7C300x415%7C320x450%7C320x3480%7C400x300%7C320x195&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
    ADS_PRIORITY: "FAN",
    ctnads: {
      inline: "206007",
      ampinline: "328050",
      ampinlinehome: "328049",
      ampctnhometop: "330647",
      ctnlist1: "206007",
      // ctnlistshow: "207483", Not used anywhere
      ctnvs: "338623",
      ctnlist: "338626",
      ctnlistTop: "338626",
      ctnpgl1: "338621",
      ctnpgl2: "338622",
      ctnvll1: "338627",
      ctnvll2: "338623",
      ampctnpgl1: "338632",
      ampctnpgl2: "338632",
      ampctnvll1: "338634",
      ampctnvll2: "338635",
      ctntrendvl: "338624",
      ctnshow: "323104",
      ctnshow1: "323104",
      ctnmidart: "338628",
      ctnnative: "323103",
      ctnrhsend: "264096",
      ctnrhsvideo: "338620",
      ctnrecommended: "351353",
      ctnmidart_test: "",
      ctnbiglist: "324212",
      ctnsluglist: "355616",
      listdefault: "355776",
      listhorizontalsmall: "355784",
      ctnmgid: "M787956ScriptRootC",
      ctnMmgid: "1277549",
      ctnBmgid: "1277551",
      ctnmgidurl: "https://jsc.mgid.com/t/i/til.malayalam.samayam.com",

      ctninlineshow: "208369",
      // ctnppdad: "319655",//Not in use LAN-14265
      ctnshowvideo: "338628",
      ctnhmvideoslider: "338629",
      ctnhmphotoslider: "338630",
      ctnhome: "338615",
      ctnhometop: "338615",
      ctnhomevideo: "338615",
      homedefault: "338614",
      homedefaultsmall: "338616",
      homehorizontalsmall: "338617",
      homevertical: "338618",
      homehorizontal: "338619",
      homeibeat: "207531",
      ctnbighome: "324211",
      ctnslider: "210642",
      ctnVideoURL: "https://malayalam.samayam.com/ads_native_video_dev.cms",
      ctnphotoshowrhs: "324690",
      ctnbigphoto: "338802",
      ctnshowphoto: "338803",
      ampctnbigphoto: "338633",
      adspositionsPhoto: "-3-,-5-,-9-,-14-,-20-,-27-,-36-,-45-,-55-",
      ctnint: "324742",
      ctnint_test: "",
      adspositionsLiveblog: "-7-,-14-,-21-,-28-,-35-,-42-,-49-,-56-,-63-,-70-,-77-,-84-,-91-,-98-,",
      ctncookievalue: "ce_mlmap",
      ctntopicsall: "338626",
      ctntopicsnews: "338626",
      ctntopicsphotos: "338626",
      ctntopicsvideos: "338625",
      ampctntopicsphotos: "338632",
      ampctntopicsvideos: "338635",
      ctnbccl: "340374",
      ctnshow1gadgets: "335427", // Gadget Config
      ctntechTop: "357477", // GN Config
      ctntechvideo: "357478", // GN Config
      ctntechoth: "357479", // GN Config
      ctnTechTC: "357067", // GN Config
      ctnInImage: "518958",
      ctnPreRoll: "518886",
    },
    ctnslots: {
      atf: "327958",
      ctnshow: "323124",
      ctnbiglist: "",
      ctnbigphoto: "",
      midart: "327957",
      articleshow: "ctnshow,atf,midart",
      liveblog: "",
      photoshow: "",
      videoshow: "",
      videolist: "",
    },
    fanads: {
      home: {
        atf: { id: "417098625162615_1112478895624581", size: "320x50" },
        fbn: { id: "417098625162615_1112478965624574", size: "320x50" },
      },
      articlelist: {
        atf: { id: "417098625162615_1112479042291233", size: "320x50" },
        fbn: { id: "417098625162615_1112479085624562", size: "320x50" },
        mrec: { id: "417098625162615_1112480022291135", size: "300x250" },
      },
      articleshow: {
        atf: { id: "417098625162615_1112479222291215", size: "320x50" },
        fbn: { id: "417098625162615_1112479358957868", size: "320x50" },
        mrec: { id: "417098625162615_1112479445624526", size: "300x250" },
        mrec2: { id: "417098625162615_1112479502291187", size: "300x250" },
      },
      others: {
        atf: { id: "417098625162615_1112479795624491", size: "320x50" },
        fbn: { id: "417098625162615_1112479915624479", size: "320x50" },
        mrec: { id: "417098625162615_1112480022291135", size: "300x250" },
      },
    },
    dfpads: {
      adSiteName: "MLY",
      adSiteShortName: "MLY",
      amp: { bottomCTNamp: {}, mrec: {}, atf: {}, fbn: {} },
      topatf: "/7176/Malyalam/MLM_Home/MLM_Home_Home/MAL_HP_Band_1000x80",
      cubead1: "/7176/Malyalam/MLM_ROS/MLM_ROS_CUBE_195x85",
      cubead2: "/7176/Malyalam/MLM_ROS/MLM_ROS_CUBE2_195x85",
      cubeheadad1: "/7176/Malyalam/MLM_ROS/MLM_ROS_CUBE_195x30",
      cubeheadad2: "/7176/Malyalam/MLM_ROS/MLM_ROS_CUBE_195x30",
      cubeheadad3: "/7176/Malyalam/MLM_ROS/MLM_ROS_CUBE2_195x30",
      cubeheadad4: "/7176/Malyalam/MLM_ROS/MLM_ROS_CUBE2_195x30",
      andbeyond: "/7176/Malyalam/MLM_ROS/MLM_ROS_Andbeyond_1x1",
      inimage: "/7176/Malyalam/MLM_ROS/Malayalam_ROS_Inimage_1x1",
      multiplex: "/7176/Malyalam/MLM_ROS/MLM_ROS_Multiplex",
      canvasAd: "/7176/MS_Mweb/MS_Mweb_ROS/MLM_Mweb_ROS_Mcanvas_1x1",
      inuxu: "/7176/Malyalam/MLM_ROS/MLM_ROS_Inuxu_1x1",
      trk: "/7176/Malyalam/MLM_ROS/MLM_ROS_trk_1x1",
      osv: "/7176/Malyalam/MLM_ROS/MLM_ROS_OUTSTREAM_1x1",
      skinrhs: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_SkinRHS",
      ppdad: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_ATF_PPD_980x40",
      budgetSlug: "/7176/Malyalam/Budget/MLM_BDGT_SLG",
      others: {
        atf: {
          id: "div-gpt-ad-21897448184-atf",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_ATF",
          size: [
            [970, 250],
            [728, 90],
            [980, 200],
            [980, 120],
            [950, 90],
            [930, 180],
            [750, 300],
            [750, 200],
            [750, 100],
            [970, 90],
          ],
        },
        mrec1: {
          id: "div-gpt-ad-21897448184-mrec1",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Mrec1",
          size: [
            [300, 250],
            [250, 250],
            [200, 200],
          ],
        },
        mrec2: {
          id: "div-gpt-ad-21897448184-mrec2",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Mrec2",
          size: [
            [300, 250],
            [250, 250],
            [200, 200],
          ],
        },
        mrec3: {
          id: "div-gpt-ad-21897448184-mrec3",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Mrec3",
          size: [
            [300, 250],
            [250, 250],
            [200, 200],
          ],
        },
        mrec4: {
          id: "div-gpt-ad-21897448184-mrec4",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Mrec4",
          size: [
            [300, 250],
            [250, 250],
            [200, 200],
          ],
        },
        mrec5: {
          id: "div-gpt-ad-21897448184-mrec5",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Mrec5",
          size: [
            [300, 250],
            [250, 250],
            [200, 200],
          ],
        },
        mrec6: {
          id: "div-gpt-ad-21897448184-mrec6",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Mrec6",
          size: [
            [300, 250],
            [250, 250],
            [200, 200],
          ],
        },
        mrec7: {
          id: "div-gpt-ad-21897448184-mrec7",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Mrec7",
          size: [
            [300, 250],
            [250, 250],
            [200, 200],
          ],
        },
        mrecinf: {
          id: "div-gpt-ad-21897448184-mrecinf",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_MrecINF",
          size: [
            [300, 250],
            [250, 250],
            [200, 200],
          ],
        },
        btf: {
          id: "div-gpt-ad-21897448184-btf",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_BTF",
          size: [
            [970, 250],
            [728, 90],
            [980, 200],
            [980, 120],
            [950, 90],
            [930, 180],
            [750, 300],
            [750, 200],
            [750, 100],
            [970, 90],
          ],
        },
        innove: {
          id: "div-gpt-ad-21897448184-innove",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Innov1",
          size: [[1, 1]],
        },
        slug: {
          id: "div-gpt-ad-1572861422851-slug",
          name: "/7176/Malyalam/Malayalam_Others/Malayalam_Others_Slug1",
          size: [
            [300, 100],
            [320, 100],
          ],
        },
        refreshnews: "/7176/Malyalam/Malayalam_News/Malayalam_News",
      },
    },
  },
  plus: {
    disablePlus: false,
    logo: "https://static.langimg.com/thumb/85000255/malayalam-samayam.jpg?height=36&resizemode=4",
    home: "84165781",
    video: "84169892",
    shortName: "MLY Plus",
    articleReferrerCd: 8,
    articleTypeCd: 6,
    premiumText: "പ്രീമിയം",
    homeText: "Home",
  },
  // dailyMotion: { channel: "samayammalayalam", playerId: "x6k8v", meta: "dmnlfxhgtn60p8lmt", syndication: "278261" },
  loginWall: {
    heading: "Malayalam Plus തുടർന്നു വായിക്കുന്നത്തിനായി, ദയവായി സൈൻ ഇൻ ചെയ്യുക",
    subHeading: "Malayalam Plus ന്റെ മെച്ചങ്ങള്‍",
    label1: "പരസ്യങ്ങളുണ്ടാകില്ല",
    label2: "എക്‌സ്‌ക്ലുസീവ് ലേഖനങ്ങളും വീഡിയോകളും",
    label3: "ലേഖനങ്ങളിലൂടെയും വീഡിയോകളിലൂടെയും ടൈംസ് പോയിന്റ് നേടാം",
  },
  foryoupage: {
    cid: "13542:203",
    agencyFilters: ["ഭാഷ", "Brandwire", "SPOTLIGHT"],
  },
  authorDetails: {
    agencyName: "Samayam Malayalam",
    authorName: "",
    editorLabel: "",
    editorLink: "",
  },
  timesXP: {
    hostName: "mly_xp",
    xpUrl: "https://mlyfeed.timesxp.com/langapi",
    appUrl: "https://malayalam.timesxp.com",
    wapCode: "malayalamTxp",
  },
  adblockerDetails: {
    title: "സമയം മലയാളം സൈറ്റ് സന്ദര്‍ശിച്ചതിന് നന്ദി",
    body:
      "നിങ്ങളുടെ ഡിവൈസിൽ ഒരു ആഡ് ബ്ലോക്കര്‍ ഓണ്‍ ആയിരിക്കുകയാണെന്ന് തോന്നുന്നു. തുടരുന്നതിനായി അത് ഓഫ് ചെയ്യൂ, അല്ലെങ്കിൽ സമയം മലയാളം  സൈറ്റിനെ വൈറ്റ്ലിസ്റ്റ് ചെയ്യൂ",
    turnoff: "എങ്ങനെ ആഡ് ബ്ലോക്കര്‍ ഓഫ് ചെയ്യാം",
    refresh: "നിങ്ങള്‍ ഇതിനകം ആഡ് ബ്ലോക്കര്‍ ഓഫ് ആക്കിയിട്ടുണ്ടെങ്കിൽ റിഫ്രഷ് ചെയ്യൂ",
    linkurl: "https://malayalam.samayam.com/blocked.cms",
  },
  vdoAI: {
    isEnabled: true,
    scriptUrl: "//a.vdo.ai/core/v-malayalam-samayam-v0/vdo.ai.js",
    containerID: "v-malayalam-samayam-v0",
  },
  orgAddress: {
    addressLocality:
      "Times Internet Limited,3rd Floor,Monlash Business Centre,Crescens Tower,Changampuzha Nagar PO, South Kalamassery",
    addressRegion: "Kochi, Kerala ",
    postalCode: "682033",
  },
  cleoPlayer: {
    apikey: "lang-n9GgmFF518E5Bknb",
  },
};
